### ISSUE TITLE
Training A-B potential with different datasets(A, B, and AB)  

### ISSUE THREAD

**Issue by LiuGaoyong** [deepmodeling/deepmd-kit#1015]
**Summary**

If I want to train a potential of A-B, could I ***use different datasets* with the varied elements(for example, *A, B, AB*)**?

**Deepmd-kit Version, Python Version, Tensorflow Version, GCC Version and Cuda Version.**

- deepmd-kit (2.0.0b4.dev10+g1f01650d)
- python  (3.7.3)
- tensorflow (2.3.0)
- gcc (Debian 8.3.0-6) 
- cuda (none)     

**Details**

For this case, A-dataset only includes A element while AB-dataset includes both A and B elements.
After running `dp train input.json`, I got an error:
```
DEEPMD INFO    ---Summary of DataSystem: training     -----------------------------------------------
DEEPMD INFO    found 12 system(s):
DEEPMD INFO              system               natoms  bch_sz   n_bch   prob  pbc
DEEPMD INFO    -- AB/system/dataset      32       1             193      0.114    T
DEEPMD INFO    --  A/system/dataset      32       1             190      0.110    T
DEEPMD INFO    --------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/lgy/.local/bin/dp", line 8, in <module>
    sys.exit(main())
  File "/home/lgy/.local/lib/python3.7/site-packages/deepmd/entrypoints/main.py", line 419, in main
    train_dp(**dict_args)
  File "/home/lgy/.local/lib/python3.7/site-packages/deepmd/entrypoints/train.py", line 216, in train
    _do_work(jdata, run_opt)
  File "/home/lgy/.local/lib/python3.7/site-packages/deepmd/entrypoints/train.py", line 266, in _do_work
    model.build(train_data, stop_batch)
  File "/home/lgy/.local/lib/python3.7/site-packages/deepmd/train/trainer.py", line 290, in build
    assert (self.ntypes >= data.get_ntypes()), "ntypes should match that found in data"
AssertionError: ntypes should match that found in data
```

In my input.json, I only modified a little things on [***hackathon2021 Cu example***](https://github.com/deepmodelinghackathon/hackathon2021/blob/master/A1/input.json)
```
model/type_map  : ["A", "B"]

training/training_data/systems: [
    "path/to/A-dataset",
    "path/to/AB-dataset" ]
training/training_data/batch_size: "auto"
```

Can deepmd-kit train a A-B potential in this way? if can, how to fix my `input.json`?

Thanks for any help.

**Comment by LiuGaoyong** [comment]
I solved this by the issues [261](https://github.com/deepmodeling/deepmd-kit/issues/261)

The reason of this error is the `model/descriptor/sel` must have same length with `model/type_map`.

![](https://res.cngoldres.com/upload/2017/1122/703e75a3237e0f76ca77e2b44b7dee5f.jpg)

**Comment by njzjz** [comment]
Maybe we can modify this message (line 290) to give a more clear information about what to do.

**Comment by Likejade** [comment]
I am wondering whether this issue had been fixed, as this is quite common:

If I want to train a potential of A-B, could I use different datasets with the varied elements(for example, A, B, AB)?
