### ISSUE TITLE
[BUG] Training fails when `type_embedding` is enbaled and `type_one_side` is disabled.

### ISSUE THREAD

**Issue by shishaochen** [deepmodeling/deepmd-kit#1073]
**Summary**

When `type_embedding` is enbaled and `type_one_side` is disabled, training always fails when `batch_size` is larger than 1.

**Deepmd-kit version, installation way, input file, running commands, error log, etc.**

- DeePMD-kit version: [v2.0.0](https://github.com/deepmodeling/deepmd-kit/releases/tag/v2.0.0)
- Installation way: building from source.
- Running command: `dp train input.json`
- Input file is edited from `deepmd-kit/examples/water/se_e2_a_tebd/input.json` while `type_one_side` is disabled and `batch_size` is set to 2.
```json
{
    "model": {
        "type_map":     ["O", "H"],
        "type_embedding":{
            "neuron":           [2, 4, 8],
            "resnet_dt":        false,
            "seed":             1
        },
        "descriptor" :{
            "type":             "se_e2_a",
            "sel":              [46, 92],
            "rcut_smth":        0.50,
            "rcut":             6.00,
            "neuron":           [25, 50, 100],
            "resnet_dt":        false,
            "axis_neuron":      16,
            "type_one_side":    false,
            "seed":             1
        },
        "fitting_net" : {
            "neuron":           [240, 240, 240],
            "resnet_dt":        true,
            "seed":             1
        }
    },
    "learning_rate" :{
        "type":         "exp",
        "decay_steps":  5000,
        "start_lr":     0.001,
        "stop_lr":      3.51e-8
    },
    "loss" :{
        "type":         "ener",
        "start_pref_e": 0.02,
        "limit_pref_e": 1,
        "start_pref_f": 1000,
        "limit_pref_f": 1,
        "start_pref_v": 0,
        "limit_pref_v": 0
    },
    "training" : {
        "training_data": {
            "systems":          ["../data/data_0/", "../data/data_1/", "../data/data_2/"],
            "batch_size":       2
        },
        "validation_data":{
            "systems":          ["../data/data_3"],
            "batch_size":       1,
            "numb_btch":        3
        },
        "numb_steps":   1000000,
        "seed":         10,
        "disp_file":    "lcurve.out",
        "disp_freq":    100,
        "save_freq":    1000
    }
}
```
- Error log:
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape[0] = [52992,9] vs.
 shape[1] = [26496,8]
         [[node filter_type_all/concat_2 (defined at /lib/python3.7/dist-packages/deepmd_kit-2.0.0b5.dev60+g37af1d1-py3.7-linux-x86_
64.egg/deepmd/descriptor/se_a.py:684) ]]
```

**Steps to Reproduce**

Execute commands as the followings.
```
cd /deepmd-kit/examples/water/se_e2_a_tebd/

# Apply the above changes to `input.json`.

dp train input.json
```

**Comment by njzjz** [comment]
Maybe #1058 is the same error?

**Comment by shishaochen** [comment]
> Maybe #1058 is the same error?

Aha, exactly the same.

**Comment by J-You** [comment]
I also found that if you set `type_one_side` as false, and set `bath_size` as 1, although training could run, testing will have a similar error about the matrix shape mismatch.

**Comment by shishaochen** [comment]
> I also found that if you set `type_one_side` as false, and set `bath_size` as 1, although training could run, testing will have a similar error about the matrix shape mismatch.

Thanks for feedback. I will try to reproduce and fix it.

**Comment by shishaochen** [comment]
> I also found that if you set `type_one_side` as false, and set `bath_size` as 1, although training could run, testing will have a similar error about the matrix shape mismatch.

@J-You Sorry, with #1074 applied, no error happens when executing `dp test`.
```
root@n136-080-018:~/deepmd-kit/examples/water/se_e2_a_tebd# dp test -m graph.pb -s ../data/data_3 -n 30
WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
DEEPMD INFO    # ---------------output of dp test---------------
DEEPMD INFO    # testing system : ../data/data_3
embedding_input: [794880 9]     atm_embed: [192 8]
DEEPMD INFO    # number of test data : 30
DEEPMD INFO    Energy RMSE        : 5.005369e+00 eV
DEEPMD INFO    Energy RMSE/Natoms : 2.606963e-02 eV
DEEPMD INFO    Force  RMSE        : 5.522614e-02 eV/A
DEEPMD INFO    Virial RMSE        : 5.648692e+00 eV
DEEPMD INFO    Virial RMSE/Natoms : 2.942027e-02 eV
DEEPMD INFO    # -----------------------------------------------
```

**Comment by J-You** [comment]
> > I also found that if you set `type_one_side` as false, and set `bath_size` as 1, although training could run, testing will have a similar error about the matrix shape mismatch.
> 
> @J-You Sorry, with #1074 applied, no error happens when executing `dp test`.
> 
> ```
> root@n136-080-018:~/deepmd-kit/examples/water/se_e2_a_tebd# dp test -m graph.pb -s ../data/data_3 -n 30
> WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
> Instructions for updating:
> non-resource variables are not supported in the long term
> DEEPMD INFO    # ---------------output of dp test---------------
> DEEPMD INFO    # testing system : ../data/data_3
> embedding_input: [794880 9]     atm_embed: [192 8]
> DEEPMD INFO    # number of test data : 30
> DEEPMD INFO    Energy RMSE        : 5.005369e+00 eV
> DEEPMD INFO    Energy RMSE/Natoms : 2.606963e-02 eV
> DEEPMD INFO    Force  RMSE        : 5.522614e-02 eV/A
> DEEPMD INFO    Virial RMSE        : 5.648692e+00 eV
> DEEPMD INFO    Virial RMSE/Natoms : 2.942027e-02 eV
> DEEPMD INFO    # -----------------------------------------------
> ```

Thanks for your maintenance. I will try it right away.

**Comment by J-You** [comment]
Hi, @shishaochen, does this fix have been applied in the off-line package? I installed dp-kit through off-line package, but same error occurs.
