### ISSUE TITLE
Lammps： Warnning ：Radial neighbor list length of type 0 is not enough

### ISSUE THREAD

**Issue by tiandijunhao** [deepmodeling/deepmd-kit#108]
When I use freeze.dp model in lammps, it always has a warning which is " Warnning ：Radial neighbor list length of type 0 is not enough" .  

What's the reason, please

**Comment by njzjz** [comment]
﻿se_a in your model is not enough.

————————
Jinzhe Zeng
PhD student in Chemistry
Rutgers University

jinzhe.zeng@rutgers.edu
CV: https://njzjz.win/cv



————————
Jinzhe Zeng
PhD student in Chemistry
Rutgers University

jinzhe.zeng@rutgers.edu
CV: https://njzjz.win/cv
On Oct 22, 2019, at 07:15, tiandijunhao <notifications@github.com> wrote:

﻿

When I use freeze.dp model in lammps, it always has a warning which is " Warnning ：Radial neighbor list length of type 0 is not enough" .

What's the reason, please

**Comment by tiandijunhao** [comment]
> ﻿sel in your model, which gives the maximum possible number of neighbors in the cut-off radius, is not enough.

Thank you very much. Does this mean that I only need to modify the value of sel, keep the rcut at 6A, and then retrain the model? In addition, if I want this model to be able to simulate a large cell in lammps (for example, 10 * 10 * 10, 2000 atoms in total, fcc structure). Is the higher the sel value, the better?

**Comment by tiandijunhao** [comment]
Thank you very much. Does this mean that I only need to modify the value of sel, keep the rcut at 6A, and then retrain the model? In addition, if I want this model to be able to simulate a large cell in lammps (for example, 10 * 10 * 10, 2000 atoms in total, fcc structure). Is the higher the sel value, the better?

发送自 Windows 10 版邮件应用

发件人: Jinzhe Zeng
发送时间: 2019年10月23日 0:47
主题: Re: [deepmodeling/deepmd-kit] Lammps： Warnning ：Radial neighbor list length of type 0 is not enough (#108)

se_a in your model is not enough. 

———————— 
Jinzhe Zeng 
PhD student in Chemistry 
Rutgers University 

jinzhe.zeng@rutgers.edu 
CV: https://njzjz.win/cv 



———————— 
Jinzhe Zeng 
PhD student in Chemistry 
Rutgers University 

jinzhe.zeng@rutgers.edu 
CV: https://njzjz.win/cv 
On Oct 22, 2019, at 07:15, tiandijunhao <notifications@github.com> wrote: 

﻿ 

When I use freeze.dp model in lammps, it always has a warning which is " Warnning ：Radial neighbor list length of type 0 is not enough" . 

What's the reason, please

**Comment by njzjz** [comment]
> > sel in your model, which gives the maximum possible number of neighbors in the cut-off radius, is not enough.
> 
> Thank you very much. Does this mean that I only need to modify the value of sel, keep the rcut at 6A, and then retrain the model? In addition, if I want this model to be able to simulate a large cell in lammps (for example, 10 * 10 * 10, 2000 atoms in total, fcc structure). Is the higher the sel value, the better?

No, the model will become slower if you set it too high. It’s recommended to estimate the maximum atom number in the cutoff radius (in your model is 6 angstroms).

**Comment by tiandijunhao** [comment]
thank you very much



---Original---
