### ISSUE TITLE
[BUG] _Unreasonable water structure when the lammps run time is over 1 ns

### ISSUE THREAD

**Issue by wangzhe86** [deepmodeling/deepmd-kit#1099]
**Unreasonable water structure when the lammps run time is over 1 ns**

**Deepmd-kit 2.0, .sh files, input file**

**I trained the example (/example/water/se_e2_a), and got the graph.pb**
**Then, I copied the graph.pd to the lmp files (/water/lmp) to test the potential parameter.**
**The lammps script can be run (NVT ensemble). I got a water.dump file, but the structure is unreasonable when the run time is over 1 ns.**
**I found that the temperature suddenly rose from 330K to 4000K. The O and H are aggregated.**
**Why does this problem occur?**

<img width="831" alt="image" src="https://user-images.githubusercontent.com/45929029/132146536-e11e0f21-36ea-46f5-8fdb-e1b4e767f04a.png">
<img width="859" alt="image" src="https://user-images.githubusercontent.com/45929029/132146546-776cde10-79f5-4753-9d5e-ba95fa14c73b.png">

**Comment by njzjz** [comment]
The size of training data in `examples` directory is very small, so it's not surprised to find that the model is not food,
