### ISSUE TITLE
[BUG] Error with "rcut" using hybrid descriptor

### ISSUE THREAD

**Issue by negf** [deepmodeling/deepmd-kit#1105]
I tried to run the water example with hybrid model as descriptor using the 2.0 release of deepmd:
DEEPMD INFO    installed to:         /tmp/pip-req-build-m0vk2rxi/_skbuild/linux-x86_64-3.9/cmake-install
DEEPMD INFO    source :              v2.0.0
DEEPMD INFO    source brach:         HEAD
DEEPMD INFO    source commit:        1a25414
DEEPMD INFO    source commit at:     2021-08-28 08:15:38 +0800

but I end up with the following error:

DEEPMD INFO    ---Summary of DataSystem: training     -----------------------------------------------
DEEPMD INFO    found 3 system(s):
DEEPMD INFO                                        system  natoms  bch_sz   n_bch   prob  pbc
DEEPMD INFO                               ../data/data_0/     192       1      80  0.250    T
DEEPMD INFO                               ../data/data_1/     192       1     160  0.500    T
DEEPMD INFO                               ../data/data_2/     192       1      80  0.250    T
DEEPMD INFO    --------------------------------------------------------------------------------------
DEEPMD INFO    ---Summary of DataSystem: validation   -----------------------------------------------
DEEPMD INFO    found 1 system(s):
DEEPMD INFO                                        system  natoms  bch_sz   n_bch   prob  pbc
DEEPMD INFO                                ../data/data_3     192       1      80  1.000    T
DEEPMD INFO    --------------------------------------------------------------------------------------
DEEPMD INFO    training without frame parameter
OMP: Info #254: KMP_AFFINITY: pid 23042 tid 23042 thread 1 bound to OS proc set 1
Traceback (most recent call last):
  File "/home/deepmd-kit/bin/dp", line 10, in <module>
    sys.exit(main())
  File "/home/deepmd-kit/lib/python3.9/site-packages/deepmd/entrypoints/main.py", line 437, in main
    train_dp(**dict_args)
  File "/home/deepmd-kit/lib/python3.9/site-packages/deepmd/entrypoints/train.py", line 102, in train
    _do_work(jdata, run_opt, is_compress)
  File "/home/deepmd-kit/lib/python3.9/site-packages/deepmd/entrypoints/train.py", line 158, in _do_work
    model.build(train_data, stop_batch)
  File "/home/deepmd-kit/lib/python3.9/site-packages/deepmd/train/trainer.py", line 318, in build:
    = NeighborStat(self.ntypes, self.descrpt_param['rcut'])
KeyError: 'rcut'

**Comment by amcadmus** [comment]
duplicated to  #1051.
