### ISSUE TITLE
[BUG] Compress model command covers the original checkpoint.

### ISSUE THREAD

**Issue by tuoping** [deepmodeling/deepmd-kit#1146]
**Summary**

Compress model command covers the original checkpoint. 

**Deepmd-kit version, installation way, input file, running commands, error log, etc.**

**Steps to Reproduce**

**Further Information, Files, and Links**

**Comment by tuoping** [comment]
#350  #586  #610  #921  #948  #956  #1000  #1008  #1020  #1043

**Comment by denghuilu** [comment]
Which version of deepmd-kit are you using? This problem should be fixed by PR #1076 . Please use the latest release [deepmd-kit-v2.0.1](https://github.com/deepmodeling/deepmd-kit/releases/tag/v2.0.1) to check if this problem still exists.

**Comment by tuoping** [comment]
Got it. Thank you.
