### ISSUE TITLE
[BUG] build problem - about /pppm_dplr.cpp

### ISSUE THREAD

**Issue by pee8379** [deepmodeling/deepmd-kit#1150]
Recent version of lammps changes gridcomm.h , (looks like version newer than Jun 10, 2021) remove forward_comm_kspace from file.
Same with reverse_comm_kspace .

Therefore, during installing deepmd-kit c++ interface from source code, /source/lmp/pppm_dplr.cpp make error and crash building process.

**Comment by njzjz** [comment]
Already fixed in #1129

**Comment by njzjz** [comment]
Note that this change is in lammps/lammps#2902 which was merged just 15 days ago.
