### ISSUE TITLE
Error when adding `load_ckpt` in the training script

### ISSUE THREAD

**Issue by nisargjoshi10** [deepmodeling/deepmd-kit#1157]
Hello all,

I am using deepmd-kit and just recently installed v2.0.1 on my new system. I've been using the `se_e2_a` training script for training the model and when I add the parameters `load_ckpt` and `save_ckpt` in the script, it crashes with the error:

***dargs.dargs.ArgumentKeyError: [at location `training`] undefined key `load_ckpt` is not allowed in strict mode***

These parameters seemed to work fine in the previous versions and I'm not sure if I'm missing something here or need to make any changes in my input script.

Thank you for your time!

Best,
Nisarg

**Comment by njzjz** [comment]
`load_ckpt` has been removed in v1.0 and it has no effect from v1.0 to v1.3. In v2.0, we add an error to make sure you know this parameter has no effect.
Duplicated of #919.
