### ISSUE TITLE
[BUG] Error in training on Colab using deepmd-kit 2.0.2

### ISSUE THREAD

**Issue by PeterGPH** [deepmodeling/deepmd-kit#1178]
**Summary**

**Deepmd-kit version, installation way, input file, running commands, error log, etc.**
Deepmd-kit 2.0.2, input file was the example file available on the GitHub 

error log:
Traceback (most recent call last):
  File "/usr/local/bin/dp", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/deepmd/entrypoints/main.py", line 437, in main
    train_dp(**dict_args)
  File "/usr/local/lib/python3.7/dist-packages/deepmd/entrypoints/train.py", line 103, in train
    _do_work(jdata, run_opt, is_compress)
  File "/usr/local/lib/python3.7/dist-packages/deepmd/entrypoints/train.py", line 164, in _do_work
    model.train(train_data, valid_data)
  File "/usr/local/lib/python3.7/dist-packages/deepmd/train/trainer.py", line 517, in train
    os.symlink(ori_ff, new_ff)
OSError: [Errno 95] Operation not supported: '/content/drive/My Drive/Trail/se_e3/model.ckpt-10000.data-00000-of-00001' -> 'model.ckpt.data-00000-of-00001'

Hi there! I am trying to train a model (https://github.com/deepmodeling/deepmd-kit/tree/master/examples/water/se_e2_a) on Colab following the jinzhe's tutorial (https://njzjz.win/2020/03/08/colab/). But I failed with the above error message, I tried to edit the os.symlink(ori_ff, new_ff) into os.replace(ori_ff, new_ff) and it worked!!! I am not sure whether my edition is correct. I hope it will be helpful!
Thanks for your help in advance!

**Comment by PeterGPH** [comment]
In addition, even though I trained the model around 800000 steps, the results I can find in the lcurvev.out is just 1000 steps. It seems that the solution I provided is not correct:(

**Comment by njzjz** [comment]
It may be a network issue when operating files on the mounted Google Drive. You may consider training in the local directory instead.

**Comment by PeterGPH** [comment]
OK, I see! Thanks for your help!
