### ISSUE TITLE
deepmd-kit 2.0.2, error of init-frz-model command

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/deepmd-kit#1194]
### Discussed in https://github.com/deepmodeling/deepmd-kit/discussions/1185

<div type='discussions-op-text'>

<sup>Originally posted by **zjd11** October  4, 2021</sup>
I use init-frz-model command to train a frozen model generated by this command, and i find the newly trained model is the same as the old one, because i use the two models to perform a MD calculation, the result is same. I have tested different "auto_prob_style":  "prob_sys_size; when i train the new model. How can i fix the error.</div>

**Comment by njzjz** [comment]
This only happens when the model has been compressed.

**Comment by denghuilu** [comment]
@iProzd Have you got any idea about this problem?
