### ISSUE TITLE
Unrecognized pair_style 'deepmd' after 'clear' command in Lammps(dp)

### ISSUE THREAD

**Issue by zs-ustc** [deepmodeling/deepmd-kit#1224]
### **Description**

####I got the "Unrecognized pair_style 'deepmd'" when i use LAMMPS(dp) with command ''pair_style deepmd  graph.pb'' after the clear command.

### **Basic Infos**

####CPU: Intel i7-10700
####Operating system: CentOS7
####Deepmd-kit version: 2.0.2(CPU)
####LAMMPS version: 29 Sep 2021
####Installation way:  Offline installation package.

### **Input File**

####It can be reproduced by only three or the first two commands listed below: 
"
clear
pair_style deepmd graph.pb
pair_coeff * *
"

### **Error Display**

####Full log information is listed below: 
"
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:98)
  using 1 OpenMP thread(s) per MPI task
plugin load libdeepmd_lmp.so
Loading plugin: deepmd pair style v2.0 by Han Wang
Loading plugin: compute deeptensor/atom v2.0 by Han Wang
Loading plugin: fix dplr v2.0 by Han Wang
clear
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:98)
  using 1 OpenMP thread(s) per MPI task
plugin load libdeepmd_lmp.so
Ignoring load of pair style deepmd: must unload existing deepmd plugin first
Ignoring load of compute style deepmd: must unload existing deepmd plugin first
Ignoring load of fix style deepmd: must unload existing deepmd plugin first
pair_style deepmd graph.pb
ERROR: Unrecognized pair style 'deepmd' (src/force.cpp:278)
Last command: pair_style deepmd graph.pb
"

**Comment by njzjz** [comment]
It's a bug of LAMMPS and is going to be fixed in https://github.com/lammps/lammps/pull/2998/commits/f9e99f1f4cd8bc1a76d44c8ac560ef3ca306efe8. See also lammps/lammps#3000.

**Comment by njzjz** [comment]
A new package has been uploaded, which bumps LAMMPS to a newer version.
