### ISSUE TITLE
[FEATURE_REQUEST] "dp compress" supports only the compression of energy model?

### ISSUE THREAD

**Issue by salinelake** [deepmodeling/deepmd-kit#1226]
**Summary**

For the recent release (deepmd-kit-2.0.3-cuda11.3_gpu-Linux-x86_64.sh), "dp compress" will call the "init_variables" method of the fitting neural network, through  https://github.com/deepmodeling/deepmd-kit/blob/159e45d248b0429844fb6a8cb3b3a201987c8d79/deepmd/train/trainer.py#L286. 

But this method is only implemented in deepmd/fit/ener.py, not in deepmd/fit/dipole.py.
 
The compression of dipole used to be supported in an earlier devel version of DP2.0. So I suppose this is a bug due to the recent introduction of "init_variables"?

**Comment by denghuilu** [comment]
Could you please provide a training data sets as well as the training script for the `dipole` type fitting net, so that I can test it in my local environment.
