### ISSUE TITLE
[BUG] _Multi-GPU version is much slower than the single GPU

### ISSUE THREAD

**Issue by Manyi-Yang** [deepmodeling/deepmd-kit#1284]
**Summary**
I am confused that the Multi-GPU version is much slower than the single GPU.

**Deepmd-kit version, installation way, input file, running commands, error log, etc.**
How to install： conda install deepmd-kit=2.0.3=*cpu libdeepmd=2.0.3=*cpu lammps-dp=2.0.0 horovod -c https://conda.deepmodeling.org
GPU: NVIDIA Tesla V100 16Gb
In my system, one core has four GPU

### Test results
In both cases, the same input file was used:
If with one GPU:
`dp train --mpi-log=master input.json   1>> train.log 2>> train.log`
the run speed is like this:
![image](https://user-images.githubusercontent.com/50021753/141460838-b930af0a-5959-4f89-9449-c83889878d19.png)

horovodrun -np 2  dp train --mpi-log=master input.json   1>> train.log 2>> train.log
the run speed is like this:
![image](https://user-images.githubusercontent.com/50021753/141461241-343c3c63-3071-49c6-8c60-37df76d2f543.png)

### Another problem
when training the model with version 2.0.2/3, It took me more than 1 hour to load the data, but it only took me a few mins if with version 2.0.0.b2.  why?

**Comment by wanghan-iapcm** [comment]
@shishaochen could you plz take a look? thanks

**Comment by njzjz** [comment]
> I am confused that the Multi-GPU version is much slower than the single GPU.
> 
> How to install： conda install deepmd-kit=2.0.3=*cpu libdeepmd=2.0.3=*cpu lammps-dp=2.0.0 horovod -c https://conda.deepmodeling.org

Why did you install the CPU version?

**Comment by Manyi-Yang** [comment]
> > I am confused that the Multi-GPU version is much slower than the single GPU.
> > How to install： conda install deepmd-kit=2.0.3=*cpu libdeepmd=2.0.3=*cpu lammps-dp=2.0.0 horovod -c https://conda.deepmodeling.org
> 
> Why did you install the CPU version?
Sorry, Actually I installed like this:
conda install deepmd-kit=2.0.3=*gpu libdeepmd=2.0.3=*gpu lammps-dp=2.0.0 horovod -c https://conda.deepmodeling.org

**Comment by njzjz** [comment]
As was discussed, the behavior was caused by a improper `OMP_NUM_THREADS`. We may add some documents to encourage some one to adjust it.

The second problem should be tracked in #1088.
