### ISSUE TITLE
Datasets with differing amounts of atoms

### ISSUE THREAD

**Issue by rschireman** [deepmodeling/deepmd-kit#1298]
Hi all,

I apologize if this is already a feature, but today I attempted to build a dataset of similar molecules with varying atom counts and I obtained a numpy error when reading in my type.raw file saying that the number of columns was not consistent. I am assuming this error is because the frames must have the same number of atoms. Is there any interest in developing a feature that allows frames to have differing atom counts? I am willing to contribute if need be! Thank you!

**Comment by njzjz** [comment]
Please do not put them into a same file but create multiple directories. See https://github.com/deepmodeling/deepmd-kit/tree/v2.0.3/examples/nopbc/data for an example.

**Comment by rschireman** [comment]
awesome, thank you!

**Comment by yufengwhy** [comment]
What if the [QM9](http://quantum-machine.org/datasets/) datasets, that  is, 133,885 species with up to nine heavy atoms (CONF) ?
So I should create 133,885 folds?

**Comment by njzjz** [comment]
> What if the [QM9](http://quantum-machine.org/datasets/) datasets, that is, 133,885 species with up to nine heavy atoms (CONF) ? differing both types and amounts of atoms So I should create 133,885 folds?

According to [its paper](https://doi.org/10.1038/sdata.2014.22):
> Among the 134k molecules, there are 621 stoichiometries, among ...

This means you only need to create 621 folders as there are only 621 stoichiometries.
