### ISSUE TITLE
run dp with multiple node

### ISSUE THREAD

**Issue by jingganglan** [deepmodeling/deepmd-kit#131]
Hi,

I am trying to run dp with multiple nodes, each node has 1 gpu.
I am wondering if this is possible?

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
export CRAY_CUDA_MPS=1
export CUDA_VISIBLE_DEVICES=0

srun -N dp train water_se_a.json > log

this run script doesn't work. dp will only use one GPU

**Comment by jameswind** [comment]
Hi, right now the DeePMD-kit code does not support multi-GPU training. It
only supports multi-GPU MD.

**Comment by jingganglan** [comment]
thanks
