### ISSUE TITLE
[Feature Request] _model-devi_to_distinguish inner/outer steps of lammps_

### ISSUE THREAD

**Issue by Vibsteamer** [deepmodeling/deepmd-kit#1311]
**Summary**

demands:
the inner/outer steps of lammps can be correctly distinguished when recording the model_devi, if the exploration scheme involves simulation schemes requesting 【"M steps of A (inner steps) every N steps of B (outer steps)"】.  

where to enhance:
interface with lammps 【USER-DEEPMD】

**Detailed Description**
current behavior :
All M inner-step configurations would be checked if the (n*N+1) outer step is checked, but the "step" recorded in model_devi.out is always the outer step, 
consequently, there could be more than M repeated  “(n*N+1)” step in model_devi.out, each could correspond to an A-operation-changed configuration that gives distinct model_devi values.
Then, masses pile up that, only the outer-step configuration with the unique outer-step number would be dumped by lammps, thus may lead to the mismatch between the model_devi value and the configuration.

e.g. 1 MC every 1 MD with the check frequency of 20: 
```
#       step         max_devi_v         min_devi_v         avg_devi_v         max_devi_f         min_devi_f         avg_devi_f
           0       4.855339e-03       3.620449e-04       2.155005e-03       5.544143e-02       3.397749e-03       1.350702e-02
          20       4.863981e-03       3.443043e-04       2.159035e-03       5.969543e-02       2.550778e-03       1.346281e-02
          20       4.856934e-03       3.430119e-04       2.157541e-03       5.969543e-02       2.893945e-03       1.346905e-02
          20       4.863981e-03       3.443043e-04       2.159035e-03       5.969543e-02       2.550778e-03       1.346281e-02
          20       4.863981e-03       3.443043e-04       2.159035e-03       5.969543e-02       2.550778e-03       1.346281e-02
          40       4.807203e-03       2.885032e-04       2.140186e-03       6.285083e-02       2.974297e-03       1.346278e-02
          40       4.787086e-03       2.796485e-04       2.129975e-03       6.285313e-02       2.985939e-03       1.345673e-02
          40       4.807203e-03       2.885032e-04       2.140186e-03       6.285083e-02       2.974297e-03       1.346278e-02
          40       4.807203e-03       2.885032e-04       2.140186e-03       6.285083e-02       2.974297e-03       1.346278e-02
          60       4.674819e-03       2.312313e-04       2.083987e-03       6.086843e-02       3.015907e-03       1.345834e-02
          60       4.644291e-03       2.393396e-04       2.062258e-03       6.096299e-02       3.059302e-03       1.345712e-02
          60       4.674819e-03       2.312313e-04       2.083987e-03       6.086843e-02       3.015907e-03       1.345834e-02
          60       4.674819e-03       2.312313e-04       2.083987e-03       6.086843e-02       3.015907e-03       1.345834e-02
          80       4.598876e-03       1.901227e-04       2.033878e-03       5.906127e-02       3.173004e-03       1.343717e-02
          80       4.591424e-03       1.816086e-04       2.021215e-03       5.932063e-02       3.146032e-03       1.343876e-02
          80       4.598876e-03       1.901227e-04       2.033878e-03       5.906127e-02       3.173004e-03       1.343717e-02
          80       4.598876e-03       1.901227e-04       2.033878e-03       5.906127e-02       3.173004e-03       1.343717e-02
```
 

**Further Information, Files, and Links**

**Comment by njzjz** [comment]
After discussion, we decided to reject this request.

There is no "outer-step" in LAMMPS. For the same step, LAMMPS only dumps the first configuration. However, only processing the first one conflicts with `reset_timestep` when one repeatedly performs `reset_timestep 0`. LAMMPS throws errors when there is any active `dump` but does nothing with `pair_style`.
