### ISSUE TITLE
[BUG] _Different MD results of DP models from Shuguang DCU _

### ISSUE THREAD

**Issue by Carrotkingdom** [deepmodeling/deepmd-kit#1321]
The Shuguang DCU predicted wrong MD min results. The energy per atom is overestimated and the structure collapsed for dislocation system. Both compressed and uncompressed models have this mistake. Test results on a smaller system and the lammps input script are attached.  

[P100.zip](https://github.com/deepmodeling/deepmd-kit/files/7624651/P100.zip)
[DCU.zip](https://github.com/deepmodeling/deepmd-kit/files/7624653/DCU.zip)
[in.lammps.txt](https://github.com/deepmodeling/deepmd-kit/files/7624668/in.lammps.txt)

The results from P100 are correct as comparision.

**Comment by Carrotkingdom** [comment]
The bug raises from the different edition of lammps... There is something wrong between the Lammps-20210702 and DP. Lammps-20201029 on Shuguang DCU and CPU gives right results.

**Comment by Carrotkingdom** [comment]
@amcadmus @denghuilu

**Comment by denghuilu** [comment]
@njzjz Do we need to modify the lammps script for different version of lammps?

**Comment by njzjz** [comment]
Is it the same as #1109?

**Comment by njzjz** [comment]
Hi @Carrotkingdom, Do you use v2.0.0? If so, please upgrade to apply #1128.

**Comment by Carrotkingdom** [comment]
OK, @denghuilu fixed the bug. Case closed :)

**Comment by denghuilu** [comment]
> Hi @Carrotkingdom, Do you use v2.0.0? If so, please upgrade to apply #1128.

The same problem as #1109 , fixed manually.
