### ISSUE TITLE
[BUG] In the release 2.0.3 version, the defult lammps versions can't be used after training the initial model

### ISSUE THREAD

**Issue by wct4715** [deepmodeling/deepmd-kit#1322]
**Summary**
The deepkit2.0.3 was installed by "***.sh" file. I use dpgen to invoke the dp in deepmd-kit-2.0.3 to train a model, and the model can be trained successfully. When I use the defult lammps in deepmd-kit-2.0.3 to perform the DPMD simulation, there is something wrong of lammps. The output information is shown as below:

**lammps result**
LAMMPS (29 Oct 2020)
  using 1 OpenMP thread(s) per MPI task
Reading data file ...
  triclinic box = (0.0000000 0.0000000 0.0000000) to (8.0990000 8.0990000 8.0990000) with tilt (0.0000000 0.0000000 0.0000000)
  1 by 1 by 1 MPI processor grid
  reading atoms ...
  32 atoms
  read_data CPU = 0.002 seconds
Changing box ...
  triclinic box = (0.0000000 0.0000000 0.0000000) to (8.0990000 8.0990000 8.0990000) with tilt (0.0000000 0.0000000 0.0000000)
Summary of lammps deepmd module ...
  >>> Info of deepmd-kit:
  installed to:       /public3/home/sc71405/bin/software/miniconda3
  source:             v1.3.3
  source brach:       HEAD
  source commit:      3a59596
  source commit at:   2021-03-20 00:53:44 +0800
  build float prec:   double
  build with tf inc:  /public3/home/sc71405/bin/software/miniconda3/include;/public3/home/sc71405/bin/software/miniconda3/include
  build with tf lib:  /public3/home/sc71405/bin/software/miniconda3/lib/libtensorflow_cc.so;/public3/home/sc71405/bin/software/miniconda3/lib/libtensorflow_framework.so
  set tf intra_op_parallelism_threads: 0
  set tf inter_op_parallelism_threads: 0
  >>> Info of lammps module:
  use deepmd-kit at:  /public3/home/sc71405/bin/software/miniconda3
  source:             v1.3.3
  source branch:      HEAD
  source commit:      3a59596
  source commit at:   2021-03-20 00:53:44 +0800
  build float prec:   double
  build with tf inc:  /public3/home/sc71405/bin/software/miniconda3/include;/public3/home/sc71405/bin/software/miniconda3/include
  build with tf lib:  /public3/home/sc71405/bin/software/miniconda3/lib/libtensorflow_cc.so;/public3/home/sc71405/bin/software/miniconda3/lib/libtensorflow_framework.so
2021-11-30 23:17:34.165142: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-11-30 23:17:34.200732: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2345580000 Hz
2021-11-30 23:17:34.208523: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x267d660 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-11-30 23:17:34.208612: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Not found: Op type not registered 'ProdEnvMatA' in binary running on x2212.para.bscc. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

The detailed  machine.json ,record.dpgen information are:

**

**machine.json**

**
{
   "_comment":         "training on localhost ",
  "train" :[
    {
      "command": "/public3/home/sc71405/deepmd-kit/bin/dp",
      "machine": {
        "batch": "slurm",
        "hostname": "",
        "port": 22,
        "username": "USERNAME",
        "work_path": "./",
        "_comment": "that's all"
      },
      "resources": {
        "numb_node": 1,
        "numb_gpu": 0,
        "task_per_node": 64,
        "partition": "amd_256",
        "mem_limit": 24,
        "exclude_list": [ ],
        "_comment" : "Environment to be activated. This will generate source PATH/train_new.env . ",
        "module_list": [" mpi/intel/17.0.5-cjj-public3" ],
        "source_list": [ ],
        "time_limit": "23:0:0",
        "_comment": "that's all"
      }
    }
  ],

  "model_devi": [
    {
      "machine": {
        "batch": "slurm",
        "hostname": "",
        "port": 22,
        "username": "USERNAME",
        "work_path": "./",
        "_comment": "that's all"
      },
      "resources": {
        "numb_node": 1,
        "numb_gpu": 0,
        "task_per_node":64,
        "partition": "amd_256",
        "mem_limit": 24,
        "exclude_list": [ ],
        "source_list": [ ],
        "module_list": ["mpi/intel/17.0.5-cjj-public3"],
        "time_limit": "23:0:0",
        "_comment": "that's all"
      },
      "command": "/public3/home/sc71405/bin/software/miniconda3/bin/lmp", # the part I have changed different versions. 
      "_comment" : "DP-GEN will put 5 tasks together in one submitting script.",  
      "group_size": 100
    }
  ],

  "fp":
  [
    {
      "machine": {
        "batch":"slurm",
        "hostname": "",
        "port": 22,
        "username": "USERNAMR",
        "work_path": "./"
      },
      "resources": {
        "task_per_node":64,
        "numb_gpu": 0,
        "exclude_list": ["x2116" ],
        "_comment" : "If you set with_mpi to true, the defaulted parallelling command of Slurm, srun, will be appended as prefix.",
        "_comment" : "If you do not want this, you can set with_mpi to false, and specify parallelling command yourself. ",
        "_comment" : "Notice that in json format, the upper/lower case is strict. You should write true instead of True and false instead of False", 
        "with_mpi": true,
        "source_list": [  ],
        "module_list": [" mpi/intel/17.0.5-cjj-public3" ],
        "time_limit": "120:0:0",
        "partition": "amd_256",
        "_comment": "that's all"
      },
      "command": " /public3/home/sc71405/bin/software/vasp.5.4.4_vtst/bin/vasp_std",
      "group_size": 20
    }
  ]
}

**record.dpgen**
0 0
0 1
0 2
0 3

**Comment by njzjz** [comment]
The output you provided shows it is v1.3.3 but not v2.0.3.

**Comment by wct4715** [comment]
> The output you provided shows it is v1.3.3 but not v2.0.3.
> […](#)
> On Nov 30, 2021, at 10:45, wct4715 ***@***.***> wrote: ﻿ Summary The deepkit2.0.3 was installed by "***.sh" file. I use dpgen to invoke the dp in deepmd-kit-2.0.3 to train a model, and the model can be trained successfully. When I use the defult lammps in deepmd-kit-2.0.3 to perform the DPMD simulation, there is something wrong of lammps. The output information is shown as below: lammps result LAMMPS (29 Oct 2020) using 1 OpenMP thread(s) per MPI task Reading data file ... triclinic box = (0.0000000 0.0000000 0.0000000) to (8.0990000 8.0990000 8.0990000) with tilt (0.0000000 0.0000000 0.0000000) 1 by 1 by 1 MPI processor grid reading atoms ... 32 atoms read_data CPU = 0.002 seconds Changing box ... triclinic box = (0.0000000 0.0000000 0.0000000) to (8.0990000 8.0990000 8.0990000) with tilt (0.0000000 0.0000000 0.0000000) Summary of lammps deepmd module ... Info of deepmd-kit: installed to: /public3/home/sc71405/bin/software/miniconda3 source: v1.3.3 source brach: HEAD source commit: [3a59596](https://github.com/deepmodeling/deepmd-kit/commit/3a59596dbd3b9a40a65649b31c794c7f7144f886) source commit at: 2021-03-20 00:53:44 +0800 build float prec: double build with tf inc: /public3/home/sc71405/bin/software/miniconda3/include;/public3/home/sc71405/bin/software/miniconda3/include build with tf lib: /public3/home/sc71405/bin/software/miniconda3/lib/libtensorflow_cc.so;/public3/home/sc71405/bin/software/miniconda3/lib/libtensorflow_framework.so set tf intra_op_parallelism_threads: 0 set tf inter_op_parallelism_threads: 0 Info of lammps module: use deepmd-kit at: /public3/home/sc71405/bin/software/miniconda3 source: v1.3.3 source branch: HEAD source commit: [3a59596](https://github.com/deepmodeling/deepmd-kit/commit/3a59596dbd3b9a40a65649b31c794c7f7144f886) source commit at: 2021-03-20 00:53:44 +0800 build float prec: double build with tf inc: /public3/home/sc71405/bin/software/miniconda3/include;/public3/home/sc71405/bin/software/miniconda3/include build with tf lib: /public3/home/sc71405/bin/software/miniconda3/lib/libtensorflow_cc.so;/public3/home/sc71405/bin/software/miniconda3/lib/libtensorflow_framework.so 2021-11-30 23:17:34.165142: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations: SSE4.1 SSE4.2 AVX AVX2 FMA To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags. 2021-11-30 23:17:34.200732: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2345580000 Hz 2021-11-30 23:17:34.208523: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x267d660 initialized for platform Host (this does not guarantee that XLA will be used). Devices: 2021-11-30 23:17:34.208612: I tensorflow/compiler/xla/service/service.cc:176] StreamExecutor device (0): Host, Default Version Not found: Op type not registered 'ProdEnvMatA' in binary running on x2212.para.bscc. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) tf.contrib.resampler should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed. The detailed machine.json ,record.dpgen information are: ** machine.json ** { "_comment": "training on localhost ", "train" :[ { "command": "/public3/home/sc71405/deepmd-kit/bin/dp", "machine": { "batch": "slurm", "hostname": "", "port": 22, "username": "USERNAME", "work_path": "./", "_comment": "that's all" }, "resources": { "numb_node": 1, "numb_gpu": 0, "task_per_node": 64, "partition": "amd_256", "mem_limit": 24, "exclude_list": [ ], "_comment" : "Environment to be activated. This will generate source PATH/train_new.env . ", "module_list": [" mpi/intel/17.0.5-cjj-public3" ], "source_list": [ ], "time_limit": "23:0:0", "_comment": "that's all" } } ], "model_devi": [ { "machine": { "batch": "slurm", "hostname": "", "port": 22, "username": "USERNAME", "work_path": "./", "_comment": "that's all" }, "resources": { "numb_node": 1, "numb_gpu": 0, "task_per_node":64, "partition": "amd_256", "mem_limit": 24, "exclude_list": [ ], "source_list": [ ], "module_list": ["mpi/intel/17.0.5-cjj-public3"], "time_limit": "23:0:0", "_comment": "that's all" }, "command": "/public3/home/sc71405/bin/software/miniconda3/bin/lmp", # the part I have changed different versions. "_comment" : "DP-GEN will put 5 tasks together in one submitting script.", "group_size": 100 } ], "fp": [ { "machine": { "batch":"slurm", "hostname": "", "port": 22, "username": "USERNAMR", "work_path": "./" }, "resources": { "task_per_node":64, "numb_gpu": 0, "exclude_list": ["x2116" ], "_comment" : "If you set with_mpi to true, the defaulted parallelling command of Slurm, srun, will be appended as prefix.", "_comment" : "If you do not want this, you can set with_mpi to false, and specify parallelling command yourself. ", "_comment" : "Notice that in json format, the upper/lower case is strict. You should write true instead of True and false instead of False", "with_mpi": true, "source_list": [ ], "module_list": [" mpi/intel/17.0.5-cjj-public3" ], "time_limit": "120:0:0", "partition": "amd_256", "_comment": "that's all" }, "command": " /public3/home/sc71405/bin/software/vasp.5.4.4_vtst/bin/vasp_std", "group_size": 20 } ] } record.dpgen 0 0 0 1 0 2 0 3 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Thanks for your reply, I have used conda to reinstall the deepmd-kit-2.0.3 , and solved my problem!

**Comment by njzjz** [comment]
@Zhang-pchao Please execute `pair_coeff * *` instead.
