### ISSUE TITLE
[BUG] ABIs

### ISSUE THREAD

**Issue by xhjj** [deepmodeling/deepmd-kit#1329]
RuntimeError: This deepmd-kit package was compiled with CXX11_ABI_FLAG=1, but TensorFlow runtime was compiled with CXX11_ABI_FLAG=0. These two library ABIs are incompatible and thus an error is raised when loading libop_abi.You need to rebuild deepmd-kit against this TensorFlow runtime.

**Comment by njzjz** [comment]
As the error suggests,

> You need to rebuild deepmd-kit against this TensorFlow runtime.
