### ISSUE TITLE
KeyError: "Registering two gradient with name 'Gelu'!

### ISSUE THREAD

**Issue by wanghan-iapcm** [deepmodeling/deepmd-kit#1380]
### Discussed in https://github.com/deepmodeling/deepmd-kit/discussions/1371

<div type='discussions-op-text'>

<sup>Originally posted by **wankiwi** December 22, 2021</sup>
Hi, everyone.
I installed Deepmd-kit 2.0.3 successfully from the source code without any error message. But when I tried to train a model, I got the following error message.

`**KeyError: "Registering two gradient with name 'Gelu'! (Previous registration was in register /public/software/apps/DeepLearning/Tensorflow/tensorflow_2.3.3-rocm_3.9.1/lib/python3.6/site-packages/tensorflow/python/framework/registry.py:66)"**`

How to solve it? Thanks in advance.
PS: my Tensorflow version is tensorflow_rocm-2.3.3 on a machine with dcu 
[slurm-236155.zip](https://github.com/deepmodeling/deepmd-kit/files/7760756/slurm-236155.zip)

</div>

**Comment by foxbrucecui** [comment]
Hello,Sincerely expect get your help.I also run Deepmd-kit in dcu.But I can only use 1 DCU when training models.
I found Horovod in the [install from source code.md](https://github.com/horovod/horovod/blob/master/docs/gpus.rst) to support multiple GPU acceleration,
I also found ROCM's compatibility for NCCL https://github.com/ROCmSoftwarePlatform/rccl
I follow it step by step,but it didn't work.
Do you have experience in using multiple DCU training?
Heartfelt thanks.

**Comment by njzjz** [comment]
Fixed in #1406.

**Comment by njzjz** [comment]
> Hello,Sincerely expect get your help.I also run Deepmd-kit in dcu.But I can only use 1 DCU when training models. I found Horovod in the [install from source code.md](https://github.com/horovod/horovod/blob/master/docs/gpus.rst) to support multiple GPU acceleration, I also found ROCM's compatibility for NCCL https://github.com/ROCmSoftwarePlatform/rccl I follow it step by step,but it didn't work. Do you have experience in using multiple DCU training? Heartfelt thanks.

@foxbrucecui The horovod should be built against MPI and NCCL.

**Comment by Jack9959** [comment]
> Hello,Sincerely expect get your help.I also run Deepmd-kit in dcu.But I can only use 1 DCU when training models. I found Horovod in the [install from source code.md](https://github.com/horovod/horovod/blob/master/docs/gpus.rst) to support multiple GPU acceleration, I also found ROCM's compatibility for NCCL https://github.com/ROCmSoftwarePlatform/rccl I follow it step by step,but it didn't work. Do you have experience in using multiple DCU training? Heartfelt thanks.

@foxbrucecui Hello, there are some errors emerged when i try to install deepmd-kit in dcu. Can you tell me some details of installing and the version of deepmd-kit and tensorflow?The current available version of tensorflow-rocm on my machine is 2.3.3 ,2.5.0, 2.7.0. Thanks for your help sincerely.

**Comment by Jack9959** [comment]
> Hello,Sincerely expect get your help.I also run Deepmd-kit in dcu.But I can only use 1 DCU when training models. I found Horovod in the [install from source code.md](https://github.com/horovod/horovod/blob/master/docs/gpus.rst) to support multiple GPU acceleration, I also found ROCM's compatibility for NCCL https://github.com/ROCmSoftwarePlatform/rccl I follow it step by step,but it didn't work. Do you have experience in using multiple DCU training? Heartfelt thanks.

@foxbrucecui  Hello, I am trying to run deepmdkit on DCU, but I met some problems. The versions of deepmd-kit and tensorflow installed are 2.0.3 and 2.5.0, separately. It does work only with cpu, but when using DCU, it doesn't work normally, not even 1 DCU, it always shows like this error:segmentation fault. So could you tell me how you install tensorflow and deepmdkit on device with DCU.thanks for your help sincerely.
