### ISSUE TITLE
[BUG] Incorrect dipole prediction with LAMMPS of new version

### ISSUE THREAD

**Issue by Yi-FanLi** [deepmodeling/deepmd-kit#1381]
**Summary**

The following tasks give inconsistent results:
Task1: Compute dipole with DeePMD-kit python interface;
Task2: Compute dipole with DeePMD-kit C++ interface + LAMMPS (Oct29, 2020);
Task3: Compute dipole with DeePMD-kit C++ interface + LAMMPS (Sep20, 2021).

Task1 and Task2 give consistent predictions, but the result of Task3 is different from the others.

**Deepmd-kit version, installation way, input file, running commands, error log, etc.**

DeePMD-kit: v2.0.3 (commit 2223ff3), built from source.
LAMMPS versions:
Task2: commit 31f9f17
Task3: commit 584943f
The input scripts and the model are given in the attachment. 
[dipole_bug_reproduce.tar.gz](https://github.com/deepmodeling/deepmd-kit/files/7772521/dipole_bug_reproduce.tar.gz)

Task1 and Task2 predict the dipole of the first atom to be -0.0582886 0.0159309 -0.0381824, while Task3 predict the dipole of the first atom to be -0.0637354 0.0123003 -0.0416543. 

**Steps to Reproduce**
For Task1, simply run the python script with 
```python run.py```

The predicted dipole is in dipole.raw.

For Task2 and Task3, run the lammps task with
```lmp_mpi -echo screen -in in.lammps >> output```
The predicted dipole is in water.dump.

**Comment by njzjz** [comment]
I am wondering it is the same bug as #1109... Could you try to uncomment `source/lmp/compute_deeptensor_atom.cpp#L73`?
https://github.com/deepmodeling/deepmd-kit/blob/159e45d248b0429844fb6a8cb3b3a201987c8d79/source/lmp/compute_deeptensor_atom.cpp#L73

**Comment by Yi-FanLi** [comment]
> #1109

I commented Line 73 and recompiled DeePMD-kit and LAMMPS. Now it gives the consistent results with the other test cases.

**Comment by Yi-FanLi** [comment]
I commented Line 73 and recompiled DeePMD-kit and LAMMPS. Now it gives the consistent results with the other test cases.
