### ISSUE TITLE
Not found lib/'hip_hcc' when compile the DeePMD-kit's C++ interface using ROCm4.0.1 

### ISSUE THREAD

**Issue by wankiwi** [deepmodeling/deepmd-kit#1400]
When I installed the DeePMD-kit's C++ interface using the ROCm4.0.1 with the command `cmake -DTENSORFLOW_ROOT=$tensorflow_root -DCMAKE_INSTALL_PREFIX=$deepmd_root -DUSE_ROCM_TOOLKIT=TRUE -DROCM_ROOT=xxxxx/rocm-4.0.1 ..`, I got the following error message:
`CMake Error at cmake/FindROCM.cmake:43 (message):
  Not found lib/'hip_hcc' in
  '/public/software/compiler/rocm/rocm-4.0.1;/opt/rocm/' You can manually set
  the ROCM install path by -DROCM_ROOT
Call Stack (most recent call first):
  CMakeLists.txt:72 (find_package)`
However, the libhip_hcc is deprecated until ROCm3.3, https://github.com/RadeonOpenCompute/ROCm/issues/1200, it is necessary to modify the corresponding part in the makefile to adapt to the new version of ROCm (>3.3).
![屏幕截图 2022-01-05 112923](https://user-images.githubusercontent.com/46419582/148156976-9c015d37-4489-4b5f-b351-c56b59bb7550.png)
.

**Comment by njzjz** [comment]
Fixed in #2012.
