### ISSUE TITLE
cannot install deepmd-kit

### ISSUE THREAD

**Issue by neojie** [deepmodeling/deepmd-kit#144]
I failed installing deepmd-kit on my mac . The system of my mac is macOS Catalina, version 10.15.1
I followed the instructions step by step but got an error message when running "pip install ." as "Building wheel for deepmd-kit (PEP 517) ... error". 
I attach the whole error report as well. Please help.
Thank you.
Jie

[report.txt](https://github.com/deepmodeling/deepmd-kit/files/4008759/report.txt)

**Comment by wsyxbcl** [comment]
Please check your gcc.
XCode may be a good option for MacOS.

**Comment by nisargjoshi10** [comment]
Hey! I am getting the same error while installing deepmd-kit. My system is macOS Mojave. Is there any other solution than XCode? I plan to install and run the deepmd-kit on SSH.

Thanks!

**Comment by neojie** [comment]
I have tried to updated my 
```
gcc (Homebrew GCC 9.3.0_1) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
However, I still cannot install. See the attached report2.

I also tried use

**Comment by njzjz** [comment]
We didn't build conda packages on macOS. Please try Linux.
