### ISSUE TITLE
[BUG] compressed model produces NaN forces

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/deepmd-kit#1444]
**Summary**

Here I have a system. Predicted forces by an uncompressed model:
![image](https://user-images.githubusercontent.com/9496702/150708543-7324c54b-e880-410f-b685-17d9457969ff.png)

Forces predicted by the compressed model:
![image](https://user-images.githubusercontent.com/9496702/150708636-66171bf0-63fb-4da3-aafd-963e59560d0c.png)

We can see most of atoms have the same forces, but some of forces are NaN. (Python interface)

**Deepmd-kit version, installation way, input file, running commands, error log, etc.**

devel, f5b0abb7acc63aec7bd144ee914f0290bc690f05

**Steps to Reproduce**
I upload the model and data here: [1.zip](https://github.com/deepmodeling/deepmd-kit/files/7922038/1.zip).
The compress model is too big to upload, but it should be able to compress by `dp compress`.

dpdata's [`predict` method](https://github.com/deepmodeling/dpdata/blob/306172d51f08a63c7214efbbf40b2f25ba8c0484/dpdata/system.py#L1198) can be used here.

**Further Information, Files, and Links**

**Comment by njzjz** [comment]
UPDATE: I have no issue with CPUs. It should be a problem of GPU ops.

**Comment by denghuilu** [comment]
> UPDATE: I have no issue with CPUs. It should be a problem of GPU ops.

#1575
