### ISSUE TITLE
[BUG] makefile compiled lammps cannot find shared libraries.

### ISSUE THREAD

**Issue by amcadmus** [deepmodeling/deepmd-kit#1455]
**Summary**

makefile compiled lammps cannot find shared libraries.

**Deepmd-kit version, installation way, input file, running commands, error log, etc.**

Deepmd-kit: devel branch. commit bcfb127
Lammps: stable_29Oct2020
Tensorflow: 2.5.2

**Steps to Reproduce**

Can compile lammps using make file. At runtime:

```bash
lmp_serial -h
lmp_serial: error while loading shared libraries: libdeepmd_op.so: cannot open shared object file: No such file or directory
```

One has to manually export LD_LIBRARY_PATH to deepmd and tensorflow libs to solve the issue. It was not the case in previous deepmd-kit versions.

**Comment by njzjz** [comment]
I guess `libdeepmd_op.so` (by `-llibdeepmd_op`) is linked when compiling. There may be old flags in the `Makefile.package`. Also check `ldd lmp_serial`.

**Comment by amcadmus** [comment]
The bug is caused by a wrong setting of PATH environment, not relevant to the linking of shared libs.
