### ISSUE TITLE
[web page] broken link to HEA data

### ISSUE THREAD

**Issue by bernstei** [deepmodeling/deepmd-kit#1459]
Not exactly an issue with this repo, but the "contact us " link on the web page doesn't work either.  The [link to the HEA data](http://www.deepmd.org/wp-content/uploads/2018/10/HEA.zip) from the page [here](http://www.deepmd.org/database/deeppot-se-data/) gives a 404 page not found error.

**Comment by amcadmus** [comment]
Thank you very much reporting the issues.  The website you were mentioning is http://www.deepmd.org/.  We will fix it asap.

**Comment by njzjz** [comment]
The old website has been redirected.
