### ISSUE TITLE
Inspecting descriptor values?

### ISSUE THREAD

**Issue by rschireman** [deepmodeling/deepmd-kit#1464]
I apologize if this is already a feature, but I can't seem to find a way to "print" or view the values of the descriptor for a given frame. Is there any interest in implementing this feature?

**Comment by njzjz** [comment]
See #1393; contributing is welcome.

**Comment by rschireman** [comment]
The solution in #1393 works and I can see the descriptor in the inference process, but is there a way to inspect the descriptor going into the neural network, i.e. _{D_ij}_  in [https://doi.org/10.1103/physrevlett.120.143001](https://doi.org/10.1103/physrevlett.120.143001)? I'm more than happy to implement the function(s) and submit a pull request but I'm having trouble on where to start based on the python API documentation. I'm sorry that my original question was unclear.

**Comment by rschireman** [comment]
Is there not a way to see the descriptor without having a frozen model? I want to see the local coordinate information that is generated for each frame before training.

**Comment by njzjz** [comment]
Most of descriptors in the deepmd-kit are trainable, so there is no such way in the framework. However, as `loc_frame` is not trainable, you can refer the following lines
https://github.com/deepmodeling/deepmd-kit/blob/159e45d248b0429844fb6a8cb3b3a201987c8d79/deepmd/descriptor/loc_frame.py#L330-L346
`dd_all` is what you want.

**Comment by rschireman** [comment]
awesome, thank you!
