### ISSUE TITLE
CMAKE flags when compiling from source

### ISSUE THREAD

**Issue by CompRhys** [deepmodeling/deepmd-kit#1500]
I am attempting to build deepmd-kit from source and was wondering about the roles of a few of the following compile flags when trying to install LAMMPS to use deepmd-kit in plugin mode (https://docs.deepmodeling.org/projects/deepmd/en/master/install/install-lammps.html):

```bash
cmake -D PKG_PLUGIN=ON -D PKG_KSPACE=ON -D LAMMPS_INSTALL_RPATH=ON -D BUILD_SHARED_LIBS=yes -D CMAKE_INSTALL_PREFIX=${deepmd_root} -D CMAKE_INSTALL_LIBDIR=lib -D CMAKE_INSTALL_FULL_LIBDIR=${deepmd_root}/lib ../cmake
make -j4
make install
```

The documentation isn't clear about whether `LAMMPS_INSTALL_RPATH=ON` and `CMAKE_INSTALL_PREFIX=${deepmd_root} -D CMAKE_INSTALL_LIBDIR=lib -D CMAKE_INSTALL_FULL_LIBDIR=${deepmd_root}/lib` are actually needed.  Can I remove them and just set `LD_LIBRARY_PATH`  to wherever the shared objects are built? It would seem like having to hard code paths to where `deepmd-kit` is found defeats the purpose of using plugin mode?

**Comment by njzjz** [comment]
You can, and you can actually load plugins from an absolute path
```sh
plugin load /path/to/libdeepmd_lmp.so
```
