### ISSUE TITLE
Issues with installing DeepMD kit at ppc64le architecture using conda

### ISSUE THREAD

**Issue by ramic-k** [deepmodeling/deepmd-kit#1502]
Hello, as the title says I am having issues installing the code using conda on ppc64le architecture, more specifically at https://secure.cci.rpi.edu/wiki/clusters/DCS_Supercomputer/.

The command I use is: conda create -n deepmd deepmd-kit=*=*gpu libdeepmd=*=*gpu lammps-dp cudatoolkit=11.3 horovod -c https://conda.deepmodeling.org

But I get the following error:

```
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - horovod
  - cudatoolkit=11.3

Current channels:

  - https://conda.deepmodeling.org/linux-ppc64le
  - https://conda.deepmodeling.org/noarch
  - https://repo.anaconda.com/pkgs/main/linux-ppc64le
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-ppc64le
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

If I try without those two packages I get the following error:
```
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package libgcc-ng conflicts for:
libdeepmd[build=*gpu] -> libgcc-ng[version='>=7.3.0']
libdeepmd[build=*gpu] -> libtensorflow_cc==2.5[build=gpu*] -> libgcc-ng[version='>=8.2.0']

Package libdeepmd conflicts for:
lammps-dp -> libdeepmd[version='>=2.0.0|>=2.0.1|>=2.0.2']
libdeepmd[build=*gpu]

Package cudatoolkit conflicts for:
deepmd-kit[build=*gpu] -> cudatoolkit[version='>=10.2.89,<10.3.0a0*']
deepmd-kit[build=*gpu] -> tensorflow-base=2.5.0[build=gpu*] -> cudatoolkit=10.2
lammps-dp -> libdeepmd[version='>=2.0.2'] -> cudatoolkit[version='>=10.2.89,<10.3.0a0']
libdeepmd[build=*gpu] -> cudatoolkit[version='>=10.2.89,<10.3.0a0']

Package libstdcxx-ng conflicts for:
libdeepmd[build=*gpu] -> libstdcxx-ng[version='>=7.3.0']
libdeepmd[build=*gpu] -> libtensorflow_cc==2.5[build=gpu*] -> libstdcxx-ng[version='>=8.2.0']

Package pip conflicts for:
lammps-dp -> python[version='>=3.8,<3.9.0a0'] -> pip
deepmd-kit[build=*gpu] -> python[version='>=3.8,<3.9.0a0'] -> pip
```

I would like to try to install it using Conda if possible, because I am having some issues compiling from the source as well.

Thank you for your help.

**Comment by njzjz** [comment]
Support for ppc64le is not fully supported. For now, you need to (1) add conda-forge channel; (2) use CUDA 10.2; (3) use Python 3.8; (4) hovorod is not supported.
There is also an offline package here: https://github.com/deepmodeling/deepmd-kit/releases/tag/v2.0.0

**Comment by ramic-k** [comment]
Hi Jinzhe,

Thank you for your answer!

Theoretically is it possible to example run deepmd and dpgen on one machine (i.e. linux64) but then have it submit VASP jobs to the said ppc64le cluster and take those files, analyze the result on the linux machine and repeat the process? Or am I completely misunderstanding what dpgen does here also?

**Comment by njzjz** [comment]
DP-GEN supports SSH. You can run DP-GEN on one machine and submit jobs to another cluster.
