### ISSUE TITLE
[BUG] _!!!The newest dpdata can not read vasp6.3.0 machine learning molecular dynamic OUTCAR to make a train set!!!_

### ISSUE THREAD

**Issue by woyolo990422** [deepmodeling/deepmd-kit#1510]
**Summary**

The use of the vasp6.3.0 machine learning module leads to the change of the output file of the OUTCAR file. The outcar.py of dpdata cannot read the OUTCAR, and can only read some data in vasprun.xml that is not calculated by the machine learning module.
**(We tried to use vasp6 3.0 is because it greatly improves the speed of our calculation and generation of training set from a few days to a few hours. Combined with deepmd, we can quickly get the dynamic results of large-scale system)**

Deepmd-kit version=2.0.3
dpdata version =0.25

Installation via pip，Very common NVT ensemble room temperature dynamics. I think the output file format is not adapted

Code:
(dpdatanew) [js_wangyl@login1 dpdata]$ python OUTCAR1.py 
/fs08/home/js_wangyl/.conda/envs/dpdatanew/lib/python3.9/site-packages/dpdata/vasp/outcar.py:87: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  return atom_names, atom_numbs, atom_types, np.array(all_cells), np.array(all_coords), np.array(all_energies), np.array(all_forces), all_virials
OUTCAR
Traceback (most recent call last):
  File "/fs08/home/js_wangyl/work/test/dpdata/OUTCAR1.py", line 14, in <module>
    if len(ls)>0:
NameError: name 'ls' is not defined
(dpdatanew) [js_wangyl@login1 dpdata]$ 

platform ：
CENTOS 7

we attached a OUTCAR and vasprun.xml， it was formed by vasp6.3.0 (Using machine learning)
[OUTCAR and vasprunxml.zip](https://github.com/deepmodeling/deepmd-kit/files/8142561/OUTCAR.and.vasprunxml.zip)

**Comment by woyolo990422** [comment]
**OUTCAR1.py:**


from dpdata import LabeledSystem,MultiSystems
from glob import glob
"""
process multi systems
"""
fs=glob('OUTCAR')  # remeber to change here !!!
ms=MultiSystems()
for f in fs:
    try:
        ls=LabeledSystem(f)
    except:
        print(f)
    if len(ls)>0:
        ms.append(ls)

ms.to_deepmd_raw('deepmd1')
ms.to_deepmd_npy('deepmd1',set_size=1)

**Comment by wanghan-iapcm** [comment]
will be fixed by https://github.com/deepmodeling/dpdata/pull/251
