### ISSUE TITLE
Can I only use box.npy  and coord.npy to predcit energy and force?

### ISSUE THREAD

**Issue by ywwang0** [deepmodeling/deepmd-kit#1546]
### Summary

can deepmd-kit only use box.npy  and coord.npy to predcit energy and force?

### DeePMD-kit Version

2.1.0

### TensorFlow Version

2.7.0

### Details

I am a beginner of deepmd-kit, after training the model with the water data, I froze the model and got graph.pb file. Then I test the model by `dp test -m graph.pb -s deepmd-kit/examples/water/data/data_3/ -n 80`.  I got something like below.
```
DEEPMD INFO    # number of test data : 80
DEEPMD INFO    Energy RMSE        : 9.043685e+00 eV
DEEPMD INFO    Energy RMSE/Natoms : 4.710252e-02 eV
DEEPMD INFO    Force  RMSE        : 1.385164e-01 eV/A
DEEPMD INFO    Virial RMSE        : 1.002691e+01 eV
DEEPMD INFO    Virial RMSE/Natoms : 5.222349e-02 eV
```
I don't understand the meaning here. when I test the model, the input of the model should be four data file(box.npy ,coord.npy ,energy.npy ,force.npy) or only structural data? Are there any methods to use only box.npy  and coord.npy to predcit energy and force? If so, How can I achieve them?

**Comment by AnguseZhang** [comment]
See https://docs.deepmodeling.org/projects/deepmd/en/master/inference/python.html

**Comment by ywwang0** [comment]
@AnguseZhang Thanks！ this would be a great help! I put the script here for more new learners.
```
from deepmd.infer import DeepPot
import numpy as np
dp = DeepPot('graph.pb')
coord = np.array([[1,0,0], [0,0,1.5], [1,0,3]]).reshape([1, -1])
cell = np.diag(10 * np.ones(3)).reshape([1, -1])
atype = [1,0,1]
e, f, v = dp.eval(coord, cell, atype)
```
Two more small questions:
1）I think the `coord.npy` input file are experienced mathematically transformed. Should I input the same coordinates   with the POSCAR file of vasp in `coord = np.array([[1,0,0], [0,0,1.5], [1,0,3]]).reshape([1, -1])`and the `DeepPot('graph.pb')` will automatically do the exchange?

2）`atype` in script should be same with the elemental symbol in `type_map.raw` and  `type.raw`?

Thanks!

**Comment by njzjz** [comment]
We have provided a [`predict`](https://github.com/deepmodeling/dpdata/blob/81c656cc92cf37cca17249e506dc81bb6dfe5549/dpdata/system.py#L645-L701) method in dpdata:
```py
import dpdata
system = dpdata.System("deepmd-kit/examples/water/data/data_3/", fmt="deepmd/npy").predict(“graph.pb”)
```
`system` can be printed or dumped.
