### ISSUE TITLE
[BUG] Unrecognized compute style 'deeptensor/atom' 

### ISSUE THREAD

**Issue by ChunyiZh** [deepmodeling/deepmd-kit#1547]
### Bug summary

I'm running DPMD with 
"compute dipole all deeptensor/atom xxx.pb" 
There is an error
"ERROR: Unrecognized compute style 'deeptensor/atom' (src/modify.cpp:1265)"

However, at the top of the log file it shows "Loading plugin: compute deeptensor/atom v2.0 by Han Wang"

### DeePMD-kit Version

2.1.0

### TensorFlow Version

2.8.0

### How did you download the software?

docker

### Input Files, Running Commands, Error Log, etc.

Please find the input files and the Error log attached
[test.zip](https://github.com/deepmodeling/deepmd-kit/files/8201319/test.zip)
.

### Steps to Reproduce

submit the "job.sh" file 

### Further Information, Files, and Links

The software was installed using the shifter container on NERSC machine "shifterimg -v pull deepmodeling/deepmd-kit:2.1.0_cuda11.3_gpu". I pulled 2.1.0, 2.0.0 and 2.0.1 versions, they all have the same problem.

**Comment by njzjz** [comment]
#1548 will fix the error.

At present it's called "deepmd" instead of "deeptensor/atom".

**Comment by njzjz** [comment]
I found another bug may exist there...

**Comment by njzjz** [comment]
> I found another bug may exist there...

Maybe not a bug - but I fixed it in #1602.
