### ISSUE TITLE
Problem with _get_package_constants() when running python model inference

### ISSUE THREAD

**Issue by AhmedBourouis** [deepmodeling/deepmd-kit#1559]
### Summary

problem with _get_package_constants() when running python model inference to get the predicted energy, force and virial of the system

### DeePMD-kit Version

DeePMD-kit v2.0.4.dev1+g96e623d5

### TensorFlow Version

2.7.0

### Python Version, CUDA Version, GCC Version, LAMMPS Version, etc

![image](https://user-images.githubusercontent.com/25748425/157646965-aebc23d2-b1ac-44aa-ac59-0e82a3134e86.png)

### Details

i have a problem with _get_package_constants() when running python model inference to get the predicted energy, force and virial of the system
![image](https://user-images.githubusercontent.com/25748425/157645242-62de8b3d-b83d-45d4-8746-3ed97e6d9867.png)

and indeed when i checked config.items() that are read from config_file i got this: 
![image](https://user-images.githubusercontent.com/25748425/157645654-1d12d3af-7940-47bc-a37a-47dab89c396f.png)

No 'CONFIG' section!

**Comment by njzjz** [comment]
Please follow the doc to install the package.

**Comment by AhmedBourouis** [comment]
i reinstalled the package on a different machine and i still have the same problem 
i followed the easy install method, should i install it from scratch ?

**Comment by njzjz** [comment]
It looks like you run the program in the root directory of the source code? As a result, when you import the package, it will import the source code instead of what you installed.

**Comment by AhmedBourouis** [comment]
yes exactly, i didn't know that they weren't the same thing.
thank you for your answer, now its working.
