### ISSUE TITLE
[BUG] Unrecognized kspace style 'pppm/dplr'

### ISSUE THREAD

**Issue by ChunyiZh** [deepmodeling/deepmd-kit#1567]
### Bug summary

DPLR simulation has this error "ERROR: Unrecognized kspace style 'pppm/dplr' (src/force.cpp:697)"

I used the plugin mode of LAMMPS. The "deeptensor" and "dplr" are recognized successfully. However, "pppm/dplr" is unrecognized.

### DeePMD-kit Version

2.1.0

### TensorFlow Version

2.8.0

### How did you download the software?

Built from source

### Input Files, Running Commands, Error Log, etc.

Please find the files attached.
[test.zip](https://github.com/deepmodeling/deepmd-kit/files/8238705/test.zip)

### Steps to Reproduce

Submit the job.sh file.

**Comment by wanghan-iapcm** [comment]
@njzjz Could you please take a look? Is it also related to #1548?

**Comment by njzjz** [comment]
Sadly, LAMMPS does not support plugins for `kspace` style.
https://github.com/lammps/lammps/blob/7586adbb6a61254125992709ef2fda9134cfca6c/src/PLUGIN/plugin.cpp#L306-L407

We may consider contributing to LAMMPS to make it possible firstly.

**Comment by njzjz** [comment]
Both lammps/lammps#3188 and #1603 should fix this issue.

**Comment by ChunyiZh** [comment]
Thanks a lot!
