### ISSUE TITLE
[BUG] _Replace With Suitable Title_

### ISSUE THREAD

**Issue by chtchelkatchev** [deepmodeling/deepmd-kit#1572]
### Bug summary

I got incompatibility error from deepmd-2.1.0-gpu during conda installation on two different supercomputers running on CentOS Linux release 7.9.2009. But everything is fine with conda deepmd-2.0.3-gpu. Please, extend conda package for support of operating systems (like this Centos OS) running on glibc_2.17 like it was done for deepmd-2.0.3.

### DeePMD-kit Version

2.1.0

### TensorFlow Version

2.7

### How did you download the software?

conda

### Input Files, Running Commands, Error Log, etc.

I ran the comand:
conda create -n deepmd_2_gpu deepmd-kit=2.1.0=*gpu libdeepmd=2.1.0=*gpu lammps-dp cudatoolkit=10.1 horovod -c https://conda.deepmodeling.org

and got:

Solving environment: |
Found conflicts! Looking for incompatible packages.                           failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

Package mpich conflicts for:
lammps-dp -> fftw[version='>=3.3.9,<4.0a0'] -> mpich[version='>=3.2.1,<3.3.0a0|>=3.3.1,<5.0.0a0|>=3.3.2,<5.0.0a0|>=3.4,<5.0.0a0|>=3.4.1,<5.0a0|>=3.4.2,<5.0a0']
lammps-dp -> mpich[version='>=3.2,<3.3.0a0|>=3.3.2,<3.4.0a0|>=3.3.2,<4.0a0|>=3.2.1,<4.0a0']

Package libgfortran5 conflicts for:
deepmd-kit==2.1.0[build=*gpu] -> scipy -> libgfortran5[version='>=9.3.0|>=9.4.0']
horovod -> mpich[version='>=3.3.2,<3.4.0a0'] -> libgfortran5[version='>=9.3.0|>=9.4.0']
libdeepmd==2.1.0[build=*gpu] -> mpich[version='>=3.3.2,<3.4.0a0'] -> libgfortran5[version='>=9.3.0']
lammps-dp -> fftw[version='>=3.3.9,<4.0a0'] -> libgfortran5[version='>=9.3.0|>=9.4.0']

Package tensorflow-base conflicts for:
horovod -> tensorflow=2.7[build=cuda*] -> tensorflow-base[version='2.6.0|2.6.0|2.6.0|2.6.0|2.6.0|2.6.0|2.6.0|2.6.0|2.6.0|2.6.0|2.6.0|2.6.0|2.6.0|2.6.0|2.6.0|2.6.0|2.6.0|2.6.0|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.6.2|2.7.0|2.7.0|2.7.0|2.7.0|2.7.0|>=2.4.1,<2.5.0a0|>=2.3.0,<2.4.0a0|>=2.2.0,<2.3.0a0|>=2.1.0,<2.2.0a0|>=2.0.0,<2.1.0a0|>=1.15.0,<1.16.0a0|>=1.14.0,<1.15.0a0',build='cuda102py39h747ea68_2|cuda110py37hb8f09f9_2|cuda110py38h937a041_2|cpu_py37hc5ef7b8_2|cpu_py39h7e79a0b_2|cuda112py38heae9c4c_2|cuda112py37hd5a5b6b_2|cuda111py38h152c24c_2|cuda111py37h95189bc_2|cuda102py37hd5ceeda_0|cuda102py39h32831d4_0|cuda110py39hd0eac33_0|cuda111py37h8b10f06_0|cuda111py38hcc0b86b_0|cuda112py37h8584d8f_0|cuda112py38h30560fc_0|cpu_py39hbcb9a37_0|cuda111py38h806d141_1|cuda112py37h151f92d_1|cuda112py38h8955826_1|cuda112py39he9472f8_1|cuda102py37h9af999e_1|cuda110py37h0ebe739_1|cuda102py38h8c73509_2|cuda112py38h1eec131_2|cuda110py38h7f44352_2|cuda112py39hc7f77e4_2|cpu_py37hf9aebbf_2|cpu_py38he70b6e8_2|cuda111py37ha84a828_2|cpu_py38h48ebf30_0|cpu_py310h8d3bea7_0|cuda112py38hd3dc81e_0|cuda111py39h2b78b69_0|cuda111py310h8463a45_0|cuda111py37hf266e69_0|cuda110py37h3fa1966_0|cuda110py39h0c9afd6_0|cuda110py38h76162fe_0|cuda102py37h44d275c_0|cuda102py38h021f141_0|cuda102py310hf4be40b_0|cuda102py39h15c874f_0|cuda110py310hae929b1_0|cuda111py38hca068ee_0|cuda112py37had06f64_0|cuda112py310h2bd284a_0|cuda112py39hd98b2dd_0|cpu_py39hf4995fd_0|cpu_py37h8697747_0|cpu_py39h6349a3b_2|cuda110py39h1b3dc91_2|cuda110py37h341a48a_2|cuda112py37h8d33417_2|cuda102py39h42c91ab_2|cuda111py39h26679cf_2|cuda102py37h55054dc_2|cuda111py38hf41bb10_2|cuda110py39h405f49e_1|cuda110py38h0c0c5d7_1|cuda102py39hcf1dd7e_1|cpu_py39h73312ee_1|cuda102py38h62eeb6a_1|cpu_py38h8e8016f_1|cpu_py37hfc86a07_1|cuda111py39h763576d_1|cuda111py37h85699b6_1|cpu_py38h113505c_0|cpu_py37h2c79ba4_0|cuda112py39h7de589b_0|cuda111py39h0d021e8_0|cuda110py38hca4bd6d_0|cuda110py37he67c9a8_0|cuda102py38h11de4e7_0|cuda111py39he6e9a3f_2|cpu_py38h4611ba2_2|cuda110py39hd7afca0_2|cuda102py37hbd7ce69_2|cuda102py38h3f41ba3_2|cuda112py39h0b4cdfd_2|py39he745eb5_1|py37h4c77830_1|py38he1e5d52_1']
horovod -> tensorflow-base=2.5.0[build='gpu*|mkl*']

Package deepmd-kit conflicts for:
deepmd-kit==2.1.0[build=*gpu]
lammps-dp -> deepmd-kit==0.12.8[build='*cpu|*gpu']

Package cudatoolkit conflicts for:
libdeepmd==2.1.0[build=*gpu] -> libtensorflow_cc=2.7[build=cuda*] -> cudatoolkit[version='10.0|10.0.*|10.2|10.2.*|11.0|11.0.*|11.1|11.1.*|>=11.2,<12|>=11.2,<12.0a0']
horovod -> cudatoolkit[version='*|10.1|10.1.*|>=11.3,<12|>=11.3.1,<11.4.0a0*|>=10.1.243,<10.2.0a0*']
lammps-dp -> libdeepmd[version='>=2.0.2'] -> cudatoolkit[version='10.1|10.1.*|>=11.3,<12|>=11.3.1,<11.4.0a0|>=11.1.74,<11.2.0a0|>=11.0.221,<11.1.0a0']
lammps-dp -> cudatoolkit[version='>=10.0.130,<10.1.0a0|>=10.1.243,<10.2.0a0|>=9.2,<9.3.0a0']
deepmd-kit==2.1.0[build=*gpu] -> cudatoolkit[version='10.1|10.1.*|>=11.3,<12']
horovod -> nccl[version='>=2.11.4.1,<3.0a0'] -> cudatoolkit[version='10.0|10.0.*|10.2|10.2.*|11.0|11.0.*|11.1|11.1.*|>=11.2,<12|>=11.2,<12.0a0|10.1.*|11.3.*|9.2|9.2.*']
cudatoolkit=10.1
libdeepmd==2.1.0[build=*gpu] -> cudatoolkit[version='10.1|10.1.*|>=11.3,<12']

Package numpy conflicts for:
horovod -> tensorflow=2.7[build=cuda*] -> numpy[version='>=1.13.3|>=1.16.1|>=1.20.3,<2.0a0|>=1.19|>=1.20']
deepmd-kit==2.1.0[build=*gpu] -> numpy
lammps-dp -> deepmd-kit==0.12.8[build=*cpu] -> numpy[version='>=1.13.3,<2.0a0']
deepmd-kit==2.1.0[build=*gpu] -> h5py -> numpy[version='1.10.*|1.11.*|1.12.*|1.13.*|>=1.11.3,<2.0a0|>=1.14.6,<2.0a0|>=1.16.6,<2.0a0|>=1.21.2,<2.0a0|>=1.21.4,<2.0a0|>=1.18.5,<2.0a0|>=1.19.5,<2.0a0|>=1.17.5,<2.0a0|>=1.19.4,<2.0a0|>=1.16.5,<2.0a0|>=1.19.2,<2.0a0|>=1.9.3,<2.0a0|>=1.8|>=1.8,<1.14|>=1.15.1,<2.0a0|>=1.21.5,<2.0a0|>=1.18.1,<2.0a0|>=1.9|>=1.11|>=1.20.3,<2.0a0']

Package sqlite conflicts for:
deepmd-kit==2.1.0[build=*gpu] -> python[version='>=3.8,<3.9.0a0'] -> sqlite[version='>=3.24.0,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.27.2,<4.0a0|>=3.29.0,<4.0a0|>=3.30.0,<4.0a0|>=3.30.1,<4.0a0|>=3.31.1,<4.0a0|>=3.32.3,<4.0a0|>=3.33.0,<4.0a0|>=3.35.4,<4.0a0|>=3.36.0,<4.0a0|>=3.37.0,<4.0a0|>=3.35.5,<4.0a0|>=3.34.0,<4.0a0|>=3.28.0,<4.0a0|>=3.25.1,<4.0a0']
libdeepmd==2.1.0[build=*gpu] -> libtensorflow_cc=2.7[build=cuda*] -> sqlite[version='>=3.36.0,<4.0a0|>=3.37.0,<4.0a0']
horovod -> python[version='>=3.9,<3.10.0a0'] -> sqlite[version='>=3.24.0,<4.0a0|>=3.25.2,<4.0a0|>=3.25.3,<4.0a0|>=3.26.0,<4.0a0|>=3.27.2,<4.0a0|>=3.29.0,<4.0a0|>=3.30.0,<4.0a0|>=3.30.1,<4.0a0|>=3.31.1,<4.0a0|>=3.32.3,<4.0a0|>=3.33.0,<4.0a0|>=3.35.4,<4.0a0|>=3.36.0,<4.0a0|>=3.37.0,<4.0a0|>=3.35.5,<4.0a0|>=3.34.0,<4.0a0|>=3.28.0,<4.0a0|>=3.25.1,<4.0a0']

Package libdeepmd conflicts for:
lammps-dp -> liblammps-dp==1.3.3=1_cuda9.2_gpu -> libdeepmd[version='1.2.2|1.2.2|1.2.2|1.2.2|1.2.2|1.2.2|1.2.2|1.2.2|1.2.2|1.2.2|1.2.2|1.2.2|1.2.2|1.2.2|1.2.2|1.2.2|1.2.3|1.2.3|1.2.3|1.2.3|1.2.3|1.2.3|1.2.3|1.2.3|1.2.4|1.2.4|1.2.4|1.2.4|1.2.4|1.2.4|1.2.4|1.2.4|1.3.0|1.3.0|1.3.0|1.3.0|1.3.0|1.3.0|1.3.0|1.3.0|1.3.1|1.3.1|1.3.1|1.3.1|1.3.1|1.3.1|1.3.1|1.3.1|1.3.2|1.3.2|1.3.2|1.3.2|1.3.2|1.3.2|1.3.2|1.3.2|1.3.2|1.3.2|1.3.2|1.3.2|1.3.3',build='0_cudaNone_cpu_low|0_cuda9.2_gpu_low|0_cuda9.2_gpu|0_cuda10.0_gpu_low|0_cuda10.0_gpu|0_cuda10.1_gpu_low|1_cudaNone_cpu_low|1_cudaNone_cpu|1_cuda10.1_gpu|1_cuda9.2_gpu_low|1_cuda9.2_gpu|1_cuda10.0_gpu|0_cudaNone_cpu_low|0_cuda9.2_gpu_low|0_cuda10.1_gpu_low|0_cuda9.2_gpu|0_cuda10.0_gpu_low|0_cuda10.0_gpu|0_cuda10.1_gpu_low|0_cuda10.0_gpu|0_cuda10.0_gpu_low|0_cudaNone_cpu_low|0_cuda9.2_gpu|0_cudaNone_cpu_low|0_cuda10.1_gpu_low|0_cuda9.2_gpu|0_cuda9.2_gpu_low|0_cuda10.0_gpu_low|0_cuda10.0_gpu|0_cudaNone_cpu_low|0_cuda9.2_gpu_low|0_cuda9.2_gpu|0_cuda10.0_gpu|0_cuda10.1_gpu_low|0_cuda10.0_gpu_low|0_cuda10.1_gpu_low|0_cuda9.2_gpu|0_cuda10.0_gpu|0_cuda9.2_gpu_low|0_cuda10.0_gpu_low|0_cuda11.0_gpu_low|0_cuda10.0_gpu_low|0_cuda9.2_gpu_low|0_cuda10.0_gpu|0_cuda10.1_gpu_low|0_cuda11.0_gpu|0_cudaNone_cpu_low|0_cuda9.2_gpu|0_cuda11.1_gpu|0_cuda11.1_gpu_low|0_cuda11.0_gpu_low|0_cudaNone_cpu|0_cuda10.1_gpu|0_cuda11.0_gpu|0_cuda11.1_gpu_low|0_cuda11.1_gpu|0_cuda10.1_gpu|0_cudaNone_cpu|0_cudaNone_cpu_low|0_cuda10.1_gpu|0_cudaNone_cpu|0_cuda10.1_gpu|0_cudaNone_cpu|0_cuda9.2_gpu_low|0_cudaNone_cpu|0_cuda10.1_gpu|0_cuda10.1_gpu|0_cudaNone_cpu|1_cuda10.0_gpu_low|1_cuda10.1_gpu_low|0_cuda10.1_gpu|0_cudaNone_cpu']
libdeepmd==2.1.0[build=*gpu]
lammps-dp -> libdeepmd[version='1.0.1|1.0.1|1.0.1|1.0.1|1.1.0|1.1.0|1.1.0|1.1.0|1.1.1|1.1.1|1.1.1|1.1.1|1.1.2|1.1.2|1.1.2|1.1.2|1.1.3|1.1.3|1.1.3|1.1.3|1.1.3|1.1.3|1.1.3|1.1.3|1.1.3|1.1.3|1.1.3|1.1.3|1.1.4|1.1.4|1.1.4|1.1.4|1.1.4|1.1.4|1.1.4|1.1.4|1.1.5|1.1.5|1.1.5|1.1.5|1.1.5|1.1.5|1.1.5|1.1.5|1.2.0|1.2.0|1.2.0|1.2.0|1.2.0|1.2.0|1.2.0|1.2.0|>=2.0.0|>=2.0.1|>=2.0.2',build='*cpu|*gpu|*cpu_low|*cpu|*cpu|*gpu|*cpu_low|*gpu|*cpu_low|*cpu|*gpu|1_cudaNone_cpu_low|1_cuda10.0_gpu_low|1_cuda9.2_gpu|0_cudaNone_cpu_low|0_cuda9.2_gpu_low|0_cuda10.0_gpu_low|0_cuda9.2_gpu|0_cuda10.1_gpu_low|0_cuda10.0_gpu|0_cudaNone_cpu_low|0_cuda10.0_gpu|0_cuda9.2_gpu|0_cuda10.0_gpu_low|0_cuda10.1_gpu_low|0_cuda10.0_gpu|0_cuda10.1_gpu_low|0_cuda9.2_gpu|0_cuda9.2_gpu_low|0_cuda10.0_gpu_low|0_cuda10.1_gpu|0_cudaNone_cpu|0_cudaNone_cpu_low|0_cuda10.1_gpu|0_cuda9.2_gpu_low|0_cudaNone_cpu|0_cuda10.1_gpu|0_cudaNone_cpu|1_cuda10.1_gpu_low|1_cuda10.1_gpu|1_cuda10.0_gpu|1_cuda9.2_gpu_low|1_cudaNone_cpu|*gpu_low|*gpu_low|*cpu|*gpu_low|*cpu_low|*gpu|*gpu_low|*cpu_low|*gpu_low']

Package mpi conflicts for:
lammps-dp -> mpich[version='>=3.3.2,<3.4.0a0'] -> mpi==1.0=mpich
horovod -> mpich[version='>=3.3.2,<3.4.0a0'] -> mpi==1.0=mpich
libdeepmd==2.1.0[build=*gpu] -> mpich[version='>=3.3.2,<3.4.0a0'] -> mpi==1.0=mpich

Package libuuid conflicts for:
deepmd-kit==2.1.0[build=*gpu] -> python[version='>=3.9,<3.10.0a0'] -> libuuid[version='>=2.32.1,<3.0a0']
horovod -> python[version='>=3.9,<3.10.0a0'] -> libuuid[version='>=2.32.1,<3.0a0']

Package tensorflow-estimator conflicts for:
horovod -> tensorflow-estimator
horovod -> tensorflow=2.7[build=cuda*] -> tensorflow-estimator[version='2.7.0|>=2.5.0,<2.6',build='cpu_py37h6f16af5_0|cuda112py39h23446aa_0|cuda111py38h6ed5851_0|cuda110py37h41dd380_0|cuda110py39ha53fd0e_0|cuda102py37h80be449_0|cuda102py38h4357c17_0|cuda102py310hac962ef_0|cuda102py39h87695c4_0|cuda110py310h4e8d1b5_0|cuda110py38h09c20b0_0|cuda111py37hf54207c_0|cuda111py310h33dc607_0|cuda111py39h594ad97_0|cuda112py37h474db6c_0|cuda112py310h922d117_0|cuda112py38hab8ae04_0|cpu_py310hb7a2f4b_0|cpu_py39ha241409_0|cpu_py38h7d34d82_0']The following specifications were found to be incompatible with your system:

  - feature:/linux-64::__glibc==2.17=0
  - cudatoolkit=10.1 -> libgcc-ng[version='>=9.3.0'] -> __glibc[version='>=2.17']
  - deepmd-kit==2.1.0[build=*gpu] -> __glibc[version='>=2.17']
  - deepmd-kit==2.1.0[build=*gpu] -> cudatoolkit[version='>=11.3,<12'] -> __glibc[version='>=2.17,<3.0.a0']
  - horovod -> __cuda
  - horovod -> __glibc[version='>=2.17']
  - horovod -> cudatoolkit[version='>=11.3,<12'] -> __glibc[version='>=2.17,<3.0.a0']
  - lammps-dp -> libdeepmd[version='>=2.0.2'] -> __glibc[version='>=2.17']
  - libdeepmd==2.1.0[build=*gpu] -> __glibc[version='>=2.17']
  - libdeepmd==2.1.0[build=*gpu] -> cudatoolkit[version='>=11.3,<12'] -> __glibc[version='>=2.17,<3.0.a0']

Your installed version is: 2.17

### Steps to Reproduce

I also tried

conda create -n deepmd_2_gpu deepmd-kit=*=*gpu libdeepmd=*=*gpu lammps-dp cudatoolkit=10.1 horovod -c https://conda.deepmodeling.org

Then 2.0.3 deepmd version was installed instead of 2.1.0 one. Change cudatoolkit=10.1 to cudatoolkit=11.3 also did not help.

### Further Information, Files, and Links

On ubuntu server I managed to install deepmd=2.3.0 using conda and command
conda create -n deepmd_2_gpu deepmd-kit=*=*gpu libdeepmd=*=*gpu lammps-dp cudatoolkit=11.3 horovod -c https://conda.deepmodeling.org

Unfortunately this server is not sutable for simulations other than tutorial.

**Comment by njzjz** [comment]
See my comments in #1362.

**Comment by chtchelkatchev** [comment]
Thank You for assistance! After executing the following commands:
export CONDA_OVERRIDE_CUDA="10.1"
export CONDA_OVERRIDE_GLIBC=""
export CONDA_OVERRIDE_OSX=""
I installed conda environment with deepmd=2.1.0 by typing:
conda create -n deepmd_210_gpu deepmd-kit=2.1.0=*gpu libdeepmd=2.1.0=*gpu lammps-dp cudatoolkit=10.1 horovod -c https://conda.deepmodeling.org
A test showed that dp train works well.
