### ISSUE TITLE
build lammps_7Aug_2019 with deepmd-kit 1.3.3

### ISSUE THREAD

**Issue by YJYfudo** [deepmodeling/deepmd-kit#1586]
### Summary

error occurs when use 1.3.3 but doesn't when use 1.1.4

### DeePMD-kit Version

dp --1.3.3

### TensorFlow Version

2.4.0

### Details

For some reason, I want to to compile lammps_7Aug_2019 with deepmdkit-1.3.3.
In the past, I successfully bulid this lammps version with deepmdkit-1.1.4 with no error.
However, I can't do this using 1.3.3.
It seems that something is wrong with pppm.dplr.cpp or "protobuf".
I have searched this problem in "Issues" but can't solve this problem.
So I am wondering whether it is a version conflict ( 1.3.3 essentially can't be builded with lammps_7Aug_2019)
or it is because of my setting error (for example, tensorflow version)?
Hope for your reply, thanks !

**Comment by njzjz** [comment]
Yes, we dropped the support for old LAMMPS in #302.

The protobuf issue can be referred to #944.
