### ISSUE TITLE
[BUG] _"compute stress/atom" not working in Lammps_

### ISSUE THREAD

**Issue by DingChangjie** [deepmodeling/deepmd-kit#1589]
### Bug summary

======= Description ===========
"compute stress/atom" command gives all-zero components, however "thermo" command still works and gives correct total stress of the system. 
======= Supporting information ==========
The Lammps binary file in this issue is distributed together with deepmd-kit, located in /bin/lmp.
To confirm this issue, an EAM empirical potential is also tested (see "Input Files, Running Commands, Error Log, etc.") as a comparison.

### DeePMD-kit Version

v2.0.3-1-g96e623d5

### TensorFlow Version

2.7.0

### How did you download the software?

Offline packages

### Input Files, Running Commands, Error Log, etc.

# Related files
All the related files and test results are in the Bugreport.zip file.
calc_stress.in : Lammps input file.
DP_test.pb : A DP potential for tungsten.
2013_Marinica_EAM2 : a well-known EAM potential.
relaxed.lmp : a configuration containing two interstitial loops, which should give non-zero atomic stress.
[Bugreport.zip](https://github.com/deepmodeling/deepmd-kit/files/8330170/Bugreport.zip)

### Steps to Reproduce

Simply modify and run calc_stress.in

**Comment by wanghan-iapcm** [comment]
Please read the [link](https://github.com/deepmodeling/deepmd-kit/blob/master/doc/third-party/lammps-command.md#use-of-the-centroidstressatom-to-get-the-full-3x3-atomic-virial) to see if the `centroid/stress/atom` compute solves the issue.

**Comment by DingChangjie** [comment]
> Please read the [link](https://github.com/deepmodeling/deepmd-kit/blob/master/doc/third-party/lammps-command.md#use-of-the-centroidstressatom-to-get-the-full-3x3-atomic-virial) to see if the `centroid/stress/atom` compute solves the issue.

It seems that the default Lammps binary in version 2.0.3 is not compiled with centroid/stress/atom support ... Here is the error message :

CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE

WARNING: No fixes defined, atoms won't move (../verlet.cpp:55)
ERROR: Pair style does not support compute centroid/stress/atom (../compute_centroid_stress_atom.cpp:131)
Last command: run 1

**Comment by DingChangjie** [comment]
> Please read the [link](https://github.com/deepmodeling/deepmd-kit/blob/master/doc/third-party/lammps-command.md#use-of-the-centroidstressatom-to-get-the-full-3x3-atomic-virial) to see if the `centroid/stress/atom` compute solves the issue.

I've tested the default lammps binary in version 2.0.3 and a manually compiled Lammps by bazel, neither of them seems to work... Here is the error message : 

CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE

WARNING: No fixes defined, atoms won't move (src/verlet.cpp:55)
ERROR: Pair style does not support compute centroid/stress/atom (src/compute_centroid_stress_atom.cpp:131)
Last command: run 1

**Comment by njzjz** [comment]
> ERROR: Pair style does not support compute centroid/stress/atom (src/compute_centroid_stress_atom.cpp:131)

maybe related to this error: lammps/lammps#2481
