### ISSUE TITLE
Easy Install with conda lmp does not support deepmd pair style

### ISSUE THREAD

**Issue by drewbehr** [deepmodeling/deepmd-kit#1594]
### Bug summary

I am using the easy install version of the DeePMD-kit and I can successfully train and freeze a model, but when I use the generated lmp executable the pair-style deepmd is not supported. With the deepmd environment activated, using lmp -h shows pair styles available that do not include deepmd. Is there a way to fix this in the easy install or is the only way to run deepmd to install from source. 

### DeePMD-kit Version

v2.1.0

### TensorFlow Version

2.8.0

### How did you download the software?

conda

### Input Files, Running Commands, Error Log, etc.

From lammps output:

pair_style      deepmd water.pb
ERROR: Unrecognized pair style 'deepmd' (src/force.cpp:279)
Last command: pair_style        deepmd water.pb

### Steps to Reproduce

conda create -n deepmd deepmd-kit=*=*cpu libdeepmd=*=*cpu lammps-dp -c https://conda.deepmodeling.org

conda activate deepmd

lmp -h

**Comment by njzjz** [comment]
I cannot reproduce your error in a Google Colab environment - you can follow it step by step: https://gist.github.com/njzjz/2716399dda1de96e16f7e3e9c721df9e
