### ISSUE TITLE
The Descriptor for a given structure    

### ISSUE THREAD

**Issue by ZhanPengOu** [deepmodeling/deepmd-kit#1612]
### Summary

Hi,all
After the update of version`2.1.0`, I used module `eval_descriptor` to calculate the descriptor. However,The shape of the descriptor is not what I need

### Detailed Description

My data set has N frames, and each frame has M atoms, so I finally got an array like N * M * dim (dim refers to the high dimension after embedding).
But for some reasons, I need to get a high-dimensional vector describing a structure, in other words,  an array like N * dim, I don't know if there is such this vector during training,If so, could you tell me how to get this? I would be very grateful.
All the best.

**Comment by njzjz** [comment]
However, there are only atomic vectors which describe the environment of an atom.

**Comment by ZhanPengOu** [comment]
ok,thanks
