### ISSUE TITLE
deepkit can not train model for multiple components systems if database does not contain all elements in one frame

### ISSUE THREAD

**Issue by lizzybai** [deepmodeling/deepmd-kit#1617]
### Bug summary

LiTFSI  includes elements of  **"N", "S", "O", "C", "F", "Li",**
Water includes elements of **"O" "H"**
To train deep model of LiTFSI-water, here I tried two case:
1. Use initial databases :  1) LiTFSI    2)water.  The trained process terminated by error:"ValueError: Cannot feed value of shape (8,) for Tensor 'd_sea_t_natoms:0', which has shape '(9,)'"
2. Use initial databases: 1) mixture of LiTFSI+Water   2) LiTFSI    3)water.  The train process goes normal.

### DeePMD-kit Version

1.3.3

### TensorFlow Version

unknow

### How did you download the software?

conda

### Input Files, Running Commands, Error Log, etc.

[case1-input-failed.txt](https://github.com/deepmodeling/deepmd-kit/files/8397758/case1-input-failed.txt)
[case2-input-normal.txt](https://github.com/deepmodeling/deepmd-kit/files/8397761/case2-input-normal.txt)
[train-case1-failed.log](https://github.com/deepmodeling/deepmd-kit/files/8397762/train-case1-failed.log)
[train-case2-normal.log](https://github.com/deepmodeling/deepmd-kit/files/8397764/train-case2-normal.log)

Here, I attached the input file and trained log files.

### Steps to Reproduce

[LiTFSI-1.zip](https://github.com/deepmodeling/deepmd-kit/files/8397828/LiTFSI-1.zip)
[298K-mixture.zip](https://github.com/deepmodeling/deepmd-kit/files/8397834/298K-mixture.zip)
[Water-16.zip](https://github.com/deepmodeling/deepmd-kit/files/8397838/Water-16.zip)
Here I attacted the database for reproduce the error.

Thank you very much!

**Comment by wanghan-iapcm** [comment]
We may have bugs in mapping the types of atoms in early versions of deepmd-kit. Have you tried deepmd-kit v2.1.0?

**Comment by njzjz** [comment]
I think it has been fixed by #924 (released in v2.0.0).

**Comment by lizzybai** [comment]
> We may have bugs in mapping the types of atoms in early versions of deepmd-kit. Have you tried deepmd-kit v2.1.0?

Yes, maybe the I should try new version.
