### ISSUE TITLE
Sum of forces in the water dataset

### ISSUE THREAD

**Issue by FGMphys** [deepmodeling/deepmd-kit#1619]
### Summary

Hi, 
in the water dataset, provided on the github repository of DeepMDkit, I found that the sum of forces is non zero. The sum of forces should be zero since no external field is applied. Why is not?

Thanks for the help.

### DeePMD-kit Version

2.0

### TensorFlow Version

??

### Details

In the folder water/data/data_0/set.000 I just opened the forces file (force.npy) and then I computed the sum of forces along axis x y and z. Then  I plotted the results and I computed the mean of absolute value of the sum. I found the following plot. Here the sum of forces is about 0.08. It means that you saved the forces with a precision of 0.08 in your raw data? Is there something I am not considering?
![Schermata del 2022-04-04 15-00-52](https://user-images.githubusercontent.com/82268906/161549305-1a154f20-b081-4f29-977e-5ca5881b0c65.png)

**Comment by njzjz** [comment]
This is the numerical noise of VASP. Please take a look at https://www.vasp.at/forum/viewtopic.php?f=4&t=16851.
