### ISSUE TITLE
Error while running dp_ipi

### ISSUE THREAD

**Issue by xjhsafeguards** [deepmodeling/deepmd-kit#163]
I am using conda installed depend-kit v1.1.2.

While using ipi with dp_ipi, 
'dp_ipi water.json & ' gives this message and stop running:

Not found: Op type not registered 'Descrpt' in binary running on ###. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.

Can anyone help, thanks.

**Comment by njzjz** [comment]
This issue is confirmed. Something is broken while linking the deepmd_op library. We are working to solve it.

**Comment by njzjz** [comment]
You can update the conda package to the newest one. It should be solved.
