### ISSUE TITLE
Unsupported descriptors and How to get the input.json of different descriptors

### ISSUE THREAD

**Issue by flaminyu** [deepmodeling/deepmd-kit#1636]
### Summary

We wonder what descriptors are no longer supported, and we want to know how to get the input.json of different desicriptors

### DeePMD-kit Version

DeePMD-kit v2.0.3.dev65+gc6c1ce9.d20220303

### TensorFlow Version

tensorflow 2.7.0

### Python Version, CUDA Version, GCC Version, LAMMPS Version, etc

cuda 11.6
gcc 9.4.0
python 3.9.7

### Details

Some descriptors type in DeePMD-kit are no longer supported，such as ”se_a_ebd“，I wonder what other descriptors are not supported.  And how can I get the input.json of different descriptors.

**Comment by njzjz** [comment]
Why do you say it's no longer supported?
