### ISSUE TITLE
Can DP potentials be mixed with other potentials when used in LAMMPS?

### ISSUE THREAD

**Issue by lansekbaige** [deepmodeling/deepmd-kit#1646]
### Summary

I have a complex system which include water. I'm going to use DP potential to describe the effect of the water and ues empirical potential to describe the other effect in the system by LAMMPS.  I want to kown if DP potentials can be mixed  with other potentials when used in LAMMPS?

### DeePMD-kit Version

V.2.1.0

### TensorFlow Version

2.7.0

### Details

The LAMMPS can use several empirical potential to describe complex system's interaction. I want to know if the DP potential can be mixed  with other potentials when used in LAMMPS?
For example:
pair_style            hybrid   lj/cut   deepmd/...pb 
If this can be realize, how can I set the pair_coeff?

There has a example which use several potential to calculate the hybrid system. The details are as follows:
pair_style            hybrid  lj/cut  10  eam/fs  airebo 3.0
pair_coeff            * * eam/fs Al_mm.eam.fs Al NULL
pair_coeff             * * airebo CH.airebo NULL C
pair_coeff             1 2 lj/cut 0.023 2.852

**Comment by njzjz** [comment]
There is no limitation on the DP side.
