### ISSUE TITLE
How to run lammps with hybrid/overlay and combine LJ interaction with DP potential to describe different interaction in a complex system?

### ISSUE THREAD

**Issue by lansekbaige** [deepmodeling/deepmd-kit#1649]
### Summary

I successfully used the # pair_style      hybrid/overlay# founction when the system only have H2O.(I used deepmd water.pb and lj to describe the interaction of H2O )
 But I  failed to use this founction when the system include H2O and Au. (I used deepmd water.pb and lj to describe the interaction) 
I want to know when I used the # pair_style      hybrid/overlay# founction with deepmd, if the DP potential only can be used in the system which  only contains the elements in DP potential?
Is there any way can help me to achieve my goals?

### DeePMD-kit Version

2.1.0

### TensorFlow Version

2.7.0

### Python Version, CUDA Version, GCC Version, LAMMPS Version, etc

deepmd-kit/2.1.0-cpu-py3.9

### Details

 I have a complex system which include H2O and Au surbstrate . I'm going to use  LAMMPS's hybrid/overlay founction to realize my purpose( the DP potential was used to describe the interaction between O and H in water molecule, and the LJ interaction was used to describe the interaction between Au and O in water molecule).

The details of my in file for lammps are as fellows:
units           metal
boundary        p f f
atom_style      atomic
dimension       3
box             tilt large
read_data	./water.lmp
mass            1 15.999
mass            2 1.008
mass            3 197
pair_style      hybrid/overlay deepmd compress21.pb lj/cut 4
pair_coeff	* * deepmd compress21.pb 
pair_coeff      1 3 lj/cut 0.023 2.852
neighbor        2.0 bin
neigh_modify    every 1 delay 0 check yes
molecule        dimer water.data
region		bot	block INF INF INF INF 0 11			 
group		fbot	region	bot  
group		other	subtract	all	fbot
fix		1 fbot  setforce 0.0 0.0 0.0
velocity	other	create	100 39849 mom yes rot yes dist gaussian
timestep	0.001
compute         1 all pe/atom
fix             3 all nvt temp 100.0 100.0 0.1
region          sput  block 24 34 0 29.9 65 65
fix		4 other deposit 100 0 10000 12345 region sput near 1.2  mol dimer vz -5 -5
dump            strj2 all custom 100 all-test.lammpstrj id type x y z c_1
restart         100000 lammps.restart
thermo          100     
thermo_style    custom step atoms temp press vol pe ke epair etotal
thermo_modify lost ignore flush yes
run		1000000

And the slurm file is:

LAMMPS (29 Sep 2021 - Update 2)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:98)
  using 1 OpenMP thread(s) per MPI task
Loading plugin: deepmd pair style v2.0 by Han Wang
Loading plugin: compute deeptensor/atom v2.0 by Han Wang
Loading plugin: fix dplr v2.0 by Han Wang
Reading data file ...
  triclinic box = (0.0000000 0.0000000 0.0000000) to (69.211197 29.969200 70.000000) with tilt (0.0000000 0.0000000 0.0000000)
  1 by 1 by 1 MPI processor grid
  reading atoms ...
  1512 atoms
  read_data CPU = 0.008 seconds
Summary of lammps deepmd module ...
  >>> Info of deepmd-kit:
  installed to:       /THL7/software/deepmd-kit/2.1.0-cpu-py3.9
  source:             v2.1.0
  source branch:       HEAD
  source commit:      3e54fea7
  source commit at:   2022-03-07 11:41:41 +0800
  surpport model ver.:1.1 
  build float prec:   double
  build with tf inc:  /THL7/software/deepmd-kit/2.1.0-cpu-py3.9/include;/THL7/software/deepmd-kit/2.1.0-cpu-py3.9/include
  build with tf lib:  /THL7/software/deepmd-kit/2.1.0-cpu-py3.9/lib/libtensorflow_cc.so;/THL7/software/deepmd-kit/2.1.0-cpu-py3.9/lib/libtensorflow_framework.so
  set tf intra_op_parallelism_threads: 0
  set tf inter_op_parallelism_threads: 0
  >>> Info of lammps module:
  use deepmd-kit at:  /THL7/software/deepmd-kit/2.1.0-cpu-py3.92022-04-19 11:48:16.367479: I tensorflow/core/platform/cpu_feature_guard.cc:151] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-04-19 11:48:16.373272: I tensorflow/core/common_runtime/process_util.cc:146] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
  >>> Info of model(s):
  using   1 model(s): compress21.pb 
  rcut in model:      6
  ntypes in model:    2
WARNING: Interaction between types 0 and 3 is set with deepmd, but will be ignored.
 Deepmd model has only 2 types, it only computes the mulitbody interaction of types: 1-2. (/home/conda/feedstock_root/build_artifacts/libdeepmd_1646626617432/work/source/lmp/pair_deepmd.cpp:1029)
WARNING: Interaction between types 1 and 3 is set with deepmd, but will be ignored.
 Deepmd model has only 2 types, it only computes the mulitbody interaction of types: 1-2. (/home/conda/feedstock_root/build_artifacts/libdeepmd_1646626617432/work/source/lmp/pair_deepmd.cpp:1029)
WARNING: Interaction between types 2 and 3 is set with deepmd, but will be ignored.
 Deepmd model has only 2 types, it only computes the mulitbody interaction of types: 1-2. (/home/conda/feedstock_root/build_artifacts/libdeepmd_1646626617432/work/source/lmp/pair_deepmd.cpp:1029)
WARNING: Interaction between types 3 and 3 is set with deepmd, but will be ignored.
 Deepmd model has only 2 types, it only computes the mulitbody interaction of types: 1-2. (/home/conda/feedstock_root/build_artifacts/libdeepmd_1646626617432/work/source/lmp/pair_deepmd.cpp:1029)
Read molecule template dimer:
  1 molecules
  0 fragments
  3 atoms with max type 2
  0 bonds with max type 0
  0 angles with max type 0
  0 dihedrals with max type 0
  0 impropers with max type 0
1152 atoms in group fbot
360 atoms in group other

CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE

Your simulation uses code contributions which should be cited:
- USER-DEEPMD package:
The log file lists these citations in BibTeX format.

CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE

WARNING: Interaction between types 1 and 3 is set with deepmd, but will be ignored.
 Deepmd model has only 2 types, it only computes the mulitbody interaction of types: 1-2. (/home/conda/feedstock_root/build_artifacts/libdeepmd_1646626617432/work/source/lmp/pair_deepmd.cpp:1060)
WARNING: Interaction between types 2 and 3 is set with deepmd, but will be ignored.
 Deepmd model has only 2 types, it only computes the mulitbody interaction of types: 1-2. (/home/conda/feedstock_root/build_artifacts/libdeepmd_1646626617432/work/source/lmp/pair_deepmd.cpp:1060)
WARNING: Interaction between types 3 and 3 is set with deepmd, but will be ignored.
 Deepmd model has only 2 types, it only computes the mulitbody interaction of types: 1-2. (/home/conda/feedstock_root/build_artifacts/libdeepmd_1646626617432/work/source/lmp/pair_deepmd.cpp:1060)
Neighbor list info ...
  update every 1 steps, delay 0 steps, check yes
  max neighbors/atom: 2000, page size: 100000
  master list distance cutoff = 8
  ghost atom cutoff = 8
  binsize = 4, bins = 18 8 18
  3 neighbor lists, perpetual/occasional/extra = 3 0 0
  (1) pair deepmd, perpetual
      attributes: full, newton on
      pair build: full/bin/atomonly
      stencil: full/bin/3d
      bin: standard
  (2) pair lj/cut, perpetual, skip from (3)
      attributes: half, newton on
      pair build: skip
      stencil: none
      bin: none
  (3) neighbor class addition, perpetual, half/full from (1)
      attributes: half, newton on
      pair build: halffull/newton
      stencil: none
      bin: none
Setting up Verlet run ...
  Unit style    : metal
  Current step  : 0
  Time step     : 0.001
*** Error in `lmp': free(): invalid size: 0x00002b75700012c0 ***
/tmp/slurmd/job5600410/slurm_script: line 6: 10145 Segmentation fault      lmp -in in.water

**Comment by njzjz** [comment]
I failed to reproduce the error. The error may be caused somewhere else.

**Comment by lansekbaige** [comment]
Thanks to you reply. The error doesn't exist in pure water system, but only be exist in the Au+water hybrid system.  I also try the different model, like init model, transfer model, compress model, but the issue also exist. If you succefully run the Au+water system, would you like to provide the structure file for me？I want to learn from it .This problem has puzzled me for a long time. Thanks very much.

> I failed to reproduce the error in the water example. The error may be caused somewhere else.

**Comment by njzjz** [comment]
I just added an Au atom to the [example](https://github.com/deepmodeling/deepmd-kit/tree/v2.1.1/examples/water/lmp). There was no error.

Do you still have error when you only use the LJ interaction or the DP potential?

**Comment by lansekbaige** [comment]
Thanks to your reply. The error doesn't exist when I only use  the LJ interaction. Because I don't have the dp potential of Au-O-H, so I can't only use the DP potential to describe my system.  Would you like to provide the in.lammps file which you successfully to describe the Au-water hybrid system for me？I want to learn from it. Thank you very much.

> I just added an Au atom to the [example](https://github.com/deepmodeling/deepmd-kit/tree/v2.1.1/examples/water/lmp). There was no error.
> 
> Do you still have error when you only use the LJ interaction or the DP potential?
