### ISSUE TITLE
[Parameters] Is tabulation no longer supported after v2.x ?

### ISSUE THREAD

**Issue by DingChangjie** [deepmodeling/deepmd-kit#1661]
### Summary

Dear developers :
I'd like to try the "tabulation" of dp, as is explained in a tutorial here : https://zhuanlan.zhihu.com/p/349158172. Currently I'm using v2.0.3, I followed the tutorial but eventually get an error "undefined key `use_srtab` is not allowed in strict mode". Does this indicate that the tabulation function is no longer supported (officially) after v2.x ?
Thanks.
PS : The syntax used in the tutorial seems to be old version ,maybe 1.x

### Detailed Description

The error is : 
`  File "/data/cjding/deepmd_v2_0_3/lib/python3.9/site-packages/dargs/dargs.py", line 228, in traverse
    self.traverse_value(value, 
  File "/data/cjding/deepmd_v2_0_3/lib/python3.9/site-packages/dargs/dargs.py", line 241, in traverse_value
    self._traverse_sub(value,
  File "/data/cjding/deepmd_v2_0_3/lib/python3.9/site-packages/dargs/dargs.py", line 256, in _traverse_sub
    sub_hook(self, value, path)
  File "/data/cjding/deepmd_v2_0_3/lib/python3.9/site-packages/dargs/dargs.py", line 307, in _check_strict
    raise ArgumentKeyError(path,
dargs.dargs.ArgumentKeyError: [at location `model/descriptor`] undefined key `use_srtab` is not allowed in strict mode`

**Comment by njzjz** [comment]
> `[at location model/descriptor] undefined key use_srtab is not allowed in strict mode`

You put the key in the incorrect location.
The correct path is `model/use_srtab`.
