### ISSUE TITLE
[Feature Request] Implementation of Force-Consistent Free Energy for ASE Calculator

### ISSUE THREAD

**Issue by mkphuthi** [deepmodeling/deepmd-kit#1666]
### Summary

Is it possible to have the ASE calculator populate 'energy' and 'free_energy' in the results when calling calculator.get_potential_energy()?

### Detailed Description

This is pretty simple. The ASE base calculator class has two keys for energy. One called 'energy' and one called 'free_energy'.  The difference is that 'free_energy' should be necessarily consistent with forces for things like optimizers in DFT whereas 'energy' can be for example an extrapolated value that doesn't necessarily correspond directly to forces.

The implementation of ASE requires that if the energy from `calculator.get_potential_energy()` is force consistent (Like in DP), it populates both 'energy' and 'free_energy' if the energy. Right now for example, when calling `calc.get_numerical_stress(atoms)` using DP calculator gives:

`PropertyNotImplementedError: Force consistent/free energy ("free_energy") not provided by DP calculator`

Could this be added to the calculator? 

See here for a similar discussion for quippy: [(https://gitlab.com/ase/ase/-/issues/430)]

**Comment by njzjz** [comment]
Got it. It will be fixed by #1667.
