### ISSUE TITLE
[Feature Request] document supported version dependencies

### ISSUE THREAD

**Issue by hoba87** [deepmodeling/deepmd-kit#1670]
### Summary

A better documention of the supported/tested dependencies for cuda/tensorflow/lammps versions would fasten installations from source, like e.g.:

deepmdkit 2.0.3: lammps 29Sep2021, tensorflow 2.3.4, cuda 10.1/11.3
deepmdkit 2.1.0: lammps 17Feb2022, tensorflow 2.3.4, cuda 10.1/11.3
deepmdkit 2.1.1: lammps 24Mar2022, tensorflow ??, cuda 10.1/11.3

### Detailed Description

---

**Comment by njzjz** [comment]
Added in #1683. We support TF>=1.8, CUDA>=7, LAMMPS>=20201029.
