### ISSUE TITLE
Error When Compiling LAMMPS with USER-DEEPMD package

### ISSUE THREAD

**Issue by swome** [deepmodeling/deepmd-kit#1671]
### Bug summary

Hi, When I follow all the instructions in the manual to build the c++ interfaces of TF, c++ interfaces of KIT, it goes well.
However when I do the final compilation of LAMMPS it gives an error report.
![02c28e745b3da18e8de1bc84d2d8975](https://user-images.githubusercontent.com/66358358/165925793-3dfe71a2-9514-4ce9-b753-462c5e0e4be0.png)

It says "fix_ttm_mod" no such file or directory.

### DeePMD-kit Version

2.0.3

### TensorFlow Version

Latest up to 04/29/2022

### How did you download the software?

Built from source

### Input Files, Running Commands, Error Log, etc.

make mpi -j4

### Steps to Reproduce

Follow all the instructions given on the manual. Use the Built-in mode to compile LAMMPS. At the final completion of LAMMPS. The bug will show itself

### Further Information, Files, and Links

Jinzhe told me Just to switch off the "TTM" when building the USER-DEEPMD. It is very easy to fix.

**Comment by njzjz** [comment]
Fixed in #2055.
