### ISSUE TITLE
Temperature Dependent Deep Potential Molecular Dynamics

### ISSUE THREAD

**Issue by yunai2384** [deepmodeling/deepmd-kit#1674]
### Summary

Dear experts,
   I have tried to model the Temperature Dependent Deep Potential Molecular Dynamics, which has been mentioned in article [Warm dense matter simulation via electron temperature dependent deep potential molecular dynamics](https://aip.scitation.org/doi/10.1063/5.0023265). However, the feature seems not implemented, can you give me some suggestions where to start if the feature was not implemented.

### DeePMD-kit Version

v2.1.1

### TensorFlow Version

2.7.0

### Details

If the feature has not been implemented. How can I add this feature to the deepMD-kit, any help will be of great appreciate,

**Comment by AnguseZhang** [comment]
This has been implemented in DeePMD-kit. You can search `fparam` in the documents and refer to https://github.com/deepmodeling/deepmd-kit/tree/master/examples/fparam . In [Warm dense matter simulation via electron temperature dependent deep potential molecular dynamics](https://aip.scitation.org/doi/10.1063/5.0023265) , the electronic temperature is treated as a `fparam`.

**Comment by yunai2384** [comment]
Dear Dr. Zhang,
    Thank you very much, this helps me a lot.
Best regards,
Yongnian, Qi
