### ISSUE TITLE
RuntimeError: cudaGetDevice() failed. Status: initialization error

### ISSUE THREAD

**Issue by gdbhcxhmjk-z** [deepmodeling/deepmd-kit#1694]
### Summary

Previously, deepmd could work normally in the old environment. But when I try to run deepmd in new environment, it is unable to initialize.
[stdout.txt](https://github.com/deepmodeling/deepmd-kit/files/8650876/stdout.txt)
The new environment is composed of 4 V100 GPUs. And the cuda version is 10.1 while the cuda version of the old one is 11.2.
The deepmd is installed by anaconda without specifying the cuda version. (**conda create -n deepmd deepmd-kit=*=*gpu libdeepmd=*=*gpu lammps-dp  horovod -c https://conda.deepmodeling.com**)
The details of the new environment is followed
[nvidia-smi.txt](https://github.com/deepmodeling/deepmd-kit/files/8650881/nvidia-smi.txt)
Conda list of the deepmd environment is followed.
[conda-list.txt](https://github.com/deepmodeling/deepmd-kit/files/8650882/conda-list.txt)

### DeePMD-kit Version

2.0.3

### TensorFlow Version

2.5.0

### Python Version, CUDA Version, GCC Version, LAMMPS Version, etc

python  3.9.12 
GPU:cuda 10.1  
conda list: cudatoolkit  11.3.1 ; cudnn   8.2.1

### Details

When I submit the slurm script(showed as slurm.txt), the stdout.txt is produced.
[slurm.txt](https://github.com/deepmodeling/deepmd-kit/files/8650911/slurm.txt)
[nvidia-smi.txt](https://github.com/deepmodeling/deepmd-kit/files/8650913/nvidia-smi.txt)
[input.txt](https://github.com/deepmodeling/deepmd-kit/files/8650914/input.txt)
[stdout.txt](https://github.com/deepmodeling/deepmd-kit/files/8650916/stdout.txt)
[conda-list.txt](https://github.com/deepmodeling/deepmd-kit/files/8650917/conda-list.txt)

**Comment by AnguseZhang** [comment]
Try to allocate manually a GPU node and log on to the node by `salloc`. On the GPU node, execute `source /export/home/wenjiezhang/anaconda3/bin/activate && conda activate deepmd-gpu && dp train input.json`, and see whether it works. (Notice that do not add `module load cuda/10.1`, since in your conda environment there has been libraries for cuda11.)

**Comment by gdbhcxhmjk-z** [comment]
> Try to allocate manually a GPU node and log on to the node by `salloc`. On the GPU node, execute `source /export/home/wenjiezhang/anaconda3/bin/activate && conda activate deepmd-gpu && dp train input.json`, and see whether it works. (Notice that do not add `module load cuda/10.1`, since in your conda environment there has been libraries for cuda11.)

It doesn't work. The error information repeats again.

**Comment by AnguseZhang** [comment]
Your Driver Version is "418.39" (see nvida-smi.txt), which is too old for CUDA 11.2. 
I think there are two solutions:
1. Try to use https://github.com/deepmodeling/deepmd-kit/releases/download/v2.0.3/deepmd-kit-2.0.3-cuda10.1_gpu-Linux-x86_64.sh  or https://github.com/deepmodeling/deepmd-kit/releases/download/v2.1.1/deepmd-kit-2.1.1-cuda10.1_gpu-Linux-x86_64.sh to install. 
2. Contact the admin to upgrade the driver version.

**Comment by gdbhcxhmjk-z** [comment]
> 
https://github.com/deepmodeling/deepmd-kit/releases/download/v2.0.3/deepmd-kit-2.0.3-cuda10.1_gpu-Linux-x86_64.sh 
This version can work normally in the new environment. "RuntimeError: cudaGetDevice() failed" is caused by the incompatibility between the deepmd version and gpu driver. Thanks a lot!
