### ISSUE TITLE
[BUG] Have a trouble when I calculate MD(lammps) by using pbs to submit tasks  

### ISSUE THREAD

**Issue by baihuyu12** [deepmodeling/deepmd-kit#1718]
### Bug summary

I meet a trouble when I use graph.gh to calculate task by lammps.

I use **pbs** to submit my task on two local machines, one machine (hyper-thread) can  successfully work, but the other (no hyper-thread) can't. Two machine have the same hardware and  software settings. Once I submit the task, the other machine will be down. Only I delete the task, and the other machine can be opened again.

I don't know why?
![image](https://user-images.githubusercontent.com/57975158/169063175-ccd68c24-16fb-4d7c-8907-39b1eb8912c2.png)

And I also use 'export OMP_NUM_THREADS=50 && nohup mpirun /home/***/deepmd-kit/bin/lmp < in.data >output 2>&1 &' to submit task, only one thread can be used which is computationally inefficient.

How can I implement multi-threaded on the other machine(no hyper-thread)?

![image](https://user-images.githubusercontent.com/57975158/169063284-64689d5a-5f11-44ae-8ab9-8ea98c255ce3.png)

### DeePMD-kit Version

2.1.1

### TensorFlow Version

2.7.0

### How did you download the software?

Offline packages

### Input Files, Running Commands, Error Log, etc.

#!/bin/bash
#PBS -N In-12
#PBS -l nodes=node01:ppn=20
#PBS -l walltime=12000:00:00

cd $PBS_O_WORKDIR
NP=`cat $PBS_NODEFILE|wc -l`
mpirun -machinefile $PBS_NODEFILE -np $NP /home/software/deepmd/bin/lmp < in.data

### Steps to Reproduce

anything is ok, Only submit isn't ok.

**Comment by njzjz** [comment]
You did not limit the number of threads when you started multiple processes. These processes may compete for resources.
