### ISSUE TITLE
[BUG] failed to paint lcurve.out

### ISSUE THREAD

**Issue by 222lei** [deepmodeling/deepmd-kit#1747]
### Bug summary

i can't paint lcurve.out successfully,i used the code from this project

### DeePMD-kit Version

deepmd-kit-1.3.1-cuda10.1_gpu-Linux-x86_64

### TensorFlow Version

2.2.0

### How did you download the software?

Offline packages

### Input Files, Running Commands, Error Log, etc.

(base) [root@leilinux1 lcurve]# python
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import matplotlib.pyplot as plt
>>> 
>>> data = np.genfromtxt("lcurve.out", names=True)
>>> for name in data.dtype.names[1:-1]:
...     plt.plot(data['step'], data[name], label=name)
... plt.legend()
  File "<stdin>", line 3
    plt.legend()
    ^
SyntaxError: invalid syntax
>>> plt.xlabel('Step')
Text(0.5, 0, 'Step')
>>> plt.ylabel('Loss')
Text(0, 0.5, 'Loss')
>>> plt.xscale('symlog')
>>> plt.yscale('log')
>>> plt.grid()
>>> plt.show()

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/98208338/172434328-4d0d49ba-2f40-47e8-ad76-20424718ad53.png)

**Comment by njzjz** [comment]
You may copy the code into a file like `plot.py` and execute `python plot.py`...

**Comment by 222lei** [comment]
because i use the deepmd-kit with version 1.3.1,the lcurve.out is different.because of it ,i should change the code .thanks for your  directions!
 import numpy as np
import matplotlib.pyplot as plt

data = np.genfromtxt("lcurve.out", names=True)
for name in data.dtype.names[1:-1]:
    plt.plot(data['batch'], data[name], label=name)
plt.legend()
plt.xlabel('batch')
plt.ylabel('Loss')
plt.xscale('symlog')
plt.yscale('log')
plt.grid()
plt.show()
