### ISSUE TITLE
All electron calculation trained DPMD model induced larger potential energy in lammps

### ISSUE THREAD

**Issue by yunai2384** [deepmodeling/deepmd-kit#1813]
### Summary

Dear experts,
    I trained DPMD model by all electron AIMD in cp2k, and i got a  higher absolute potential energy values of thermo result in lammps:
            Step   Temp     KinEng           PotEng
DPMD   0       300        59.524297     -6104252.6
BKS      0       300        59.524297      -29252.67
I know the result was right as the energy is part of raw data to be trained. However, the thermal conductivity (**Kappa**) i calculated was 6 orders higher in magnitude, since the formula uses the potential information. Any suggestions would be appreciated, the information about energy output of **all electron** and **pseudopotential** (same xc function and cutoff) are listed in details:

### DeePMD-kit Version

v2.1.1

### TensorFlow Version

2.7.0

### Python Version, CUDA Version, GCC Version, LAMMPS Version, etc

The offline package was used: deepmd-kit-2.1.1-cpu-Linux-x86_64.sh

### Details

**All electron**:
  Overlap energy of the core charge distribution:               0.00000788681379
  Self energy of the core charge distribution:             -17374.76145282973812
  Core Hamiltonian energy:                                 -11153.50780054557981
  Hartree energy:                                            4907.46071688482516
  Exchange-correlation energy:                               -840.30675538052083
  Dispersion energy:                                           -0.56002247943643

  GAPW| Exc from hard and soft atomic rho1:                 -1482.88459367895030
  GAPW| local Eh = 1 center integrals:                      -2096.63562574158095

  Total energy:                                            -28041.19552588416991

 ENERGY| Total FORCE_EVAL ( QS ) energy [a.u.]:           -28041.195525884169911

**pseudopotential**:
  Overlap energy of the core charge distribution:               0.00000150683146
  Self energy of the core charge distribution:              -5971.86602151288207
  Core Hamiltonian energy:                                   1677.16537406201178
  Hartree energy:                                            2520.44334444094466
  Exchange-correlation energy:                               -527.95773554765651
  Dispersion energy:                                           -0.56002247943643

  Total energy:                                             -2302.77505953018635

 ENERGY| Total FORCE_EVAL ( QS ) energy [a.u.]:            -2302.775059530186354

**Comment by njzjz** [comment]
The potential energy is defined relative to that for a particular state. In your two potentials, the zero points are not the same. Absolute energy does not make sense in physics. Why does your equation rely on the absolute energy?

**Comment by yunai2384** [comment]
Thank you for your valuable suggestions, i will check my calculation precedure of thermal conductivity.
