### ISSUE TITLE
Documentation inconsistency in description of virial

### ISSUE THREAD

**Issue by hyhuang00** [deepmodeling/deepmd-kit#1823]
### Summary

The documentation [here](https://docs.deepmodeling.com/projects/deepmd/en/master/data/system.html) describes that the virial should be using the unit eV and the shape is `nframes * 3`. However, the description of virial suggests every frame should have 9 entries. Furthermore, if the virial here suggests "virial pressure", why is the unit in eV?

### DeePMD-kit Version

documentation problem

### TensorFlow Version

documentation problem

### Python Version, CUDA Version, GCC Version, LAMMPS Version, etc

Latest version of the documentation
### Details

documentation problem listed in summary

**Comment by njzjz** [comment]
The shape should be `nframes * 3` and the unit should be in eV. @wanghan-iapcm correct me if I'm wrong.

**Comment by wanghan-iapcm** [comment]
The shape of the virial tensor should be 9 = 3x3, the components are in the same order as the box tensor: XX XY XZ YX YY YZ ZX ZY ZZ. 
The virial is the potential part of the pressure times the volume, which gives the energy unit.
