### ISSUE TITLE
[BUG]the temperature is out of control and the configure become unphysical when running DP/MM in Gromacs

### ISSUE THREAD

**Issue by Cynthia0807-learn** [deepmodeling/deepmd-kit#1825]
### Bug summary

When I run DP/MM in Gromacs, the temperature of the system is out of control,and the configurations become strange and unphycial.Maybe something wrong with my topology file and gro file?
![energy](https://user-images.githubusercontent.com/81007099/178885742-c8f180d8-2142-4c95-9af4-c9cab22c180d.png)

### DeePMD-kit Version

2.0.2

### TensorFlow Version

2.5.0

### How did you download the software?

Offline packages

### Input Files, Running Commands, Error Log, etc.

[input.zip](https://github.com/deepmodeling/deepmd-kit/files/9107984/input.zip)
This is my input and output files. the file Graph.pb is too big to be uploaded.

### Steps to Reproduce

My train data is from umbrella sampling with classic force field.Initial structure to run DP/MM is from umbrella sampling

**Comment by Cynthia0807-learn** [comment]
@[Ericwang6](https://github.com/Ericwang6)

**Comment by njzjz** [comment]
I'll close this issue since it doesn't seem to be a bug in DeePMD-kit.
