### ISSUE TITLE
[BUG] Package conflicts when trying to install deepmd v2.1.4 & cuda 11.6 via conda

### ISSUE THREAD

**Issue by gdbhcxhmjk-z** [deepmodeling/deepmd-kit#1883]
### Bug summary

Online conda installation of deepmd gpu version (deepmd v2.1.4 & cuda 11.6) has many conflicts. 

**1. basic information of environment:** conda info

> active environment : base
    active env location : /export/home/wenjiezhang/anaconda3
            shell level : 1
       user config file : /export/home/wenjiezhang/.condarc
 populated config files : /export/home/wenjiezhang/.condarc
          conda version : 4.12.0
    conda-build version : 3.21.7
         python version : 3.8.12.final.0
       virtual packages : __linux=3.10.0=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /export/home/wenjiezhang/anaconda3  (writable)
      conda av data dir : /export/home/wenjiezhang/anaconda3/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /export/home/wenjiezhang/anaconda3/pkgs
                          /export/home/wenjiezhang/.conda/pkgs
       envs directories : /export/home/wenjiezhang/anaconda3/envs
                          /export/home/wenjiezhang/.conda/envs
               platform : linux-64
             user-agent : conda/4.12.0 requests/2.27.1 CPython/3.8.12 Linux/3.10.0-1160.76.1.el7.x86_64 centos/7.9.2009 glibc/2.17
                UID:GID : 1114:1002
             netrc file : None
           offline mode : False

**2. installation way** :`conda create -n deepmd deepmd-kit=*=*gpu libdeepmd=*=*gpu lammps cudatoolkit=11.6 horovod -c https://conda.deepmodeling.com -c defaults`
the same as mentioned in manaul. https://docs.deepmodeling.com/projects/deepmd/en/master/install/easy-install.html
But there are conflicts between packages:

> Found conflicts! Looking for incompatible packages.                                                                                                                                                                                  failed
UnsatisfiableError: The following specifications were found to be incompatible with each other:
The detailed information is packed into the following file.
[conflicts_log.txt](https://github.com/deepmodeling/deepmd-kit/files/9460996/conflicts_log.txt)

**3.overriding detection**: solution in #1362 ,adding the environment variables
`export `CONDA_OVERRIDE_CUDA=""`
`export CONDA_OVERRIDE_GLIBC=""`
Conflicts still come out. The errors are different to some extent but the online installation still doesn't work.

> The following specifications were found to be incompatible with your system:

  - deepmd-kit[build=*gpu] -> __glibc[version='>=2.17']
  - deepmd-kit[build=*gpu] -> cudatoolkit[version='>=11.6,<12'] -> __glibc[version='>=2.17,<3.0.a0']
  - deepmd-kit[build=*gpu] -> tensorflow=2.9[build=cuda*] -> __cuda
>Your installed version is: not available

**4.Some suggetions**
In most research groups, the computing cluster is composed of different nodes with different functions.  Most of the software installations, compilation works and task submissions are manipulated in the master node which is a pure CPU environment. GPU nodes are  only for specific computing tasks and don't connect to the Internet. So it's really inconvenient for installation when the environment detection is needed.  
I hope there will be a solution to this situation in the future version.

### DeePMD-kit Version

2.1.4

### TensorFlow Version

2.9

### How did you download the software?

conda

### Input Files, Running Commands, Error Log, etc.

1.Running Commands:`conda create -n deepmd deepmd-kit=*=*gpu libdeepmd=*=*gpu lammps cudatoolkit=11.6 horovod -c https://conda.deepmodeling.com -c defaults`

2.Environment variables:
`export CONDA_OVERRIDE_CUDA=""`
`export CONDA_OVERRIDE_GLIBC=""`

3.Conflicts before adding environment variables
[conflicts_log.txt](https://github.com/deepmodeling/deepmd-kit/files/9461222/conflicts_log.txt)

4.Conflicts after adding environement variables:
[error_log.txt](https://github.com/deepmodeling/deepmd-kit/files/9461238/error_log.txt)

### Steps to Reproduce

conda create -n deepmd deepmd-kit=*=*gpu libdeepmd=*=*gpu lammps cudatoolkit=11.6 horovod -c https://conda.deepmodeling.com -c defaults

**Comment by wanghan-iapcm** [comment]
@njzjz could you please take a look?

**Comment by njzjz** [comment]
According to [conda documentation](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-virtual.html#overriding-detected-packages), setting environmental variables to empty means no packages. Instead, they should be set to a version number.

**Comment by gdbhcxhmjk-z** [comment]
> 

In this case, should I set the environmental variables as follows in order to install deepmd v2.1.4 &cuda 11.6?
`export CONDA_OVERRIDE_CUDA="11.6"`
`export CONDA_OVERRIDE_GLIBC="2.17"`

**Comment by gdbhcxhmjk-z** [comment]
> 
It really works by setting environment variables to version numbers. Thanks a lot.
