### ISSUE TITLE
[BUG] LAMMPS installed with in DeePMD-kit 2.1.4 offline package cannot recognized pair style 'deepmd'

### ISSUE THREAD

**Issue by HuangJiameng** [deepmodeling/deepmd-kit#1903]
### Bug summary

LAMMPS installed with in DeePMD-kit 2.1.4 offline package cannot recognized pair style 'deepmd'

### DeePMD-kit Version

2.1.4

### TensorFlow Version

deepmd-kit-2.1.4-cpu-Linux-x86_64.sh

### How did you download the software?

Offline packages

### Input Files, Running Commands, Error Log, etc.

[Uploading test_dp2.1.4_lmp.tgz…]()

Error log:
```
(base) ➜ test_dp2.1.4_lmp lmp -i input.lammps -v restart 0  
LAMMPS (23 Jun 2022 - Update 1)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:98)
  using 1 OpenMP thread(s) per MPI task
Reading data file ...
  triclinic box = (0 0 0) to (10 10 10) with tilt (0 0 0)
  1 by 1 by 1 MPI processor grid
  reading atoms ...
  5 atoms
  read_data CPU = 0.003 seconds
Changing box ...
  triclinic box = (0 0 0) to (10 10 10) with tilt (0 0 0)
ERROR: Unrecognized pair style 'deepmd' (src/force.cpp:279)
Last command: pair_style      deepmd ../graph.001.pb ../graph.003.pb ../graph.000.pb ../graph.002.pb  out_freq ${THERMO_FREQ} out_file model_devi.out
```

### Steps to Reproduce

```Shell
wget https://github.com/deepmodeling/deepmd-kit/releases/download/v2.1.4/deepmd-kit-2.1.4-cpu-Linux-x86_64.sh
bash deepmd-kit-2.1.4-cpu-Linux-x86_64.sh -b -p /root/local/deepmd-kit-2.1.4-cpu 
export PATH="/root/local/deepmd-kit-2.1.4-cpu/bin/:$PATH"
cd test_dp2.1.4_lmp
lmp -i input.lammps -v restart 0
lmp -h
```

**Comment by HuangJiameng** [comment]
[test_dp2.1.4_lmp.tgz](https://github.com/deepmodeling/deepmd-kit/files/9533770/test_dp2.1.4_lmp.tgz)
If the link above does not work, the file is attached again here.

**Comment by wanghan-iapcm** [comment]
@njzjz could you please take a look? Thanks!

**Comment by HuangJiameng** [comment]
After activate environment with `conda activate /root/local/deepmd-kit-2.1.4-cpu`, it works.

**Comment by wanghan-iapcm** [comment]
We may write in the doc 
```
conda activate /root/local/deepmd-kit-xxx   
```
the path to the installation should be similar for offline packages.

**Comment by njzjz** [comment]
> We may write in the doc
> 
> ```
> conda activate /root/local/deepmd-kit-xxx   
> ```
> 
> the path to the installation should be similar for offline packages.

Already added in #1808.
