### ISSUE TITLE
Get USER-DEEPMD without building DeepMD-kit source code

### ISSUE THREAD

**Issue by zhenzey** [deepmodeling/deepmd-kit#1906]
### Summary

Can we get the source code folder USER-DEEPMD without building the source code and directly put it in the source folder of LAMMPS to enable pair style deepmd?

### DeePMD-kit Version

N/A

### TensorFlow Version

2.9/2.6

### Details

As above

**Comment by njzjz** [comment]
No, as `USER-DEEPMD` module is statically linked to DeePMD-kit.
