### ISSUE TITLE
gradient registry has no entry for: Gelu

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/deepmd-kit#1913]
LookupError: gradient registry has no entry for: Gelu-- when fiting net OR embbeding activation function  is set 'gelu'  meanwhile   it can be trained in GPU when fiting net AND embbeding activation function  is set 'tanh'

_Originally posted by @WhiteCrosstheRiver in https://github.com/deepmodeling/dpgen/discussions/941#discussioncomment-3626339_

Related code:
https://github.com/deepmodeling/deepmd-kit/blob/716cb5d84a384189b56543c023bc3e5f9561b54f/source/op/_gelu.py#L9-L18

**Comment by denghuilu** [comment]
#1918 should fix this issue.
