### ISSUE TITLE
[BUG] Sum of sys_probs not equal to 1.0

### ISSUE THREAD

**Issue by Johnsyisme** [deepmodeling/deepmd-kit#1917]
### Bug summary

Hi!
I try to set the sys_probs manually, but it doesn't work
the error:
![image](https://user-images.githubusercontent.com/88381657/190431411-d7c58b8c-9bef-4dd7-bffe-41e4927be0dc.png)

I found the source file deepmd/utils/data_system.py used
`np.sum(sys_probs)<=1`
But there are some difficulties in these float calculations like:
![image](https://user-images.githubusercontent.com/88381657/190431296-e2351c08-deef-4e13-a9cf-1bad730ed300.png)
the sum of these sys_probs cannot be the 1.0 exactly

### DeePMD-kit Version

2.1.3

### TensorFlow Version

2.9

### How did you download the software?

conda

### Input Files, Running Commands, Error Log, etc.

![image](https://user-images.githubusercontent.com/88381657/190432513-dd4d2bd4-0af8-4523-8aad-238faeb0517c.png)
[sys_probs.txt](https://github.com/deepmodeling/deepmd-kit/files/9576200/sys_probs.txt)

### Steps to Reproduce

Set the sys_probs manually with some floats like 0.01

**Comment by njzjz** [comment]
Reproduced, and changing `1` to `1.+1e-15` will resolve the issue.

**Comment by Johnsyisme** [comment]
Appreciate!
