### ISSUE TITLE
[BUG] definition of `cvatom` in `pair deepmd` differs from that in the LAMMPS

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/deepmd-kit#1935]
### Summary

Thanks for the report by @brucefan1983. `cvatom` in `pair deepmd` may have a wrong sign.

https://github.com/deepmodeling/deepmd-kit/blob/c9b46e443688b1d6e722cb9a8b27b5d03c319f44/source/lmp/pair_deepmd.cpp#L455-L463

### Detailed Description

Per [LAMMPS documentation](https://docs.lammps.org/compute_stress_atom.html),

> Note that as defined in the formula, per-atom stress is the negative of the per-atom pressure tensor.

**Comment by njzjz** [comment]
Hi @DavideTisi, could you take a look? Thanks!

**Comment by DavideTisi** [comment]
I will look at it in the next days.

**Comment by njzjz** [comment]
Hi @DavideTisi, what do you think here? If you don't oppose, I want to remove the minus sign to make it consistent with the definition in LAMMPS documentation and other LAMMPS styles.

**Comment by DavideTisi** [comment]
yes it is ok, I didn't remember this issue was still open
