### ISSUE TITLE
axis_rule of local_frame

### ISSUE THREAD

**Issue by Zhhaibing** [deepmodeling/deepmd-kit#1962]
Hi dper,
    I hope use the local_frame descriptor, but i do not understand and know how to set this part
![image](https://user-images.githubusercontent.com/40423083/193444430-7a22b611-6d95-40bf-83f0-c3e1211f4b59.png)
I look for help. It will be nice if there is a more accurate explanation and an example.

**Comment by njzjz** [comment]
@wanghan-iapcm: are there typos here?

**Comment by wanghan-iapcm** [comment]
> @wanghan-iapcm, are there typos here?

Yes, let me fix

**Comment by njzjz** [comment]
Fixed by #1963.
