### ISSUE TITLE
Latest deepmd-kit version needs Tensorflow 2.x?

### ISSUE THREAD

**Issue by rohskopf** [deepmodeling/deepmd-kit#199]
Whenever I do `pip install deepmd-kit`, and run the `dp -h` test, it fails if unless my Tensorflow version is 2.x. 

The error is:
`tensorflow.python.framework.errors_impl.NotFoundError: libtensorflow_framework.so.2: cannot open shared object file: No such file or directory`

So if you use Tensorflow version 1.x with the latest deepmd-kit, it won't work?

Just wondering if this is a bug or if this is intentional.

**Comment by njzjz** [comment]
We compiled the pypi package with the newest TensorFlow (2.1). You can compile deepmd-kit with any TensorFlow version, just using

pip install git+https://github.com/deep modeling/deepmd-kit

Thanks!

————————
Jinzhe Zeng
PhD student in Chemistry
Rutgers University

jinzhe.zeng@rutgers.edu
CV: https://njzjz.win/cv
