### ISSUE TITLE
[Feature Request] Porting to new GPU

### ISSUE THREAD

**Issue by yzamora-intel** [deepmodeling/deepmd-kit#2026]
### Summary

 We're hoping to get general information regarding porting DeePMD to a new platform (GPU) or if someone has ported to SYCL.

### Detailed Description

Hello,

We are trying to port DeePMD-kit to an Intel GPU. We're hoping to get general information regarding porting DeePMD to a new platform or if someone has ported to SYCL.

Thank you,

Yuliana

**Comment by njzjz** [comment]
As deepmd-kit is based on TensorFlow, TensorFlow should be first supported.

If TensorFlow has been supported, most OPs have run on a new GPU. Then, we have some custom OPs that are defined in [`source/op/`](https://github.com/deepmodeling/deepmd-kit/tree/devel/source/op) directory. The kernel, for example CUDA, is implemented in [`source/lib/src/cuda`](https://github.com/deepmodeling/deepmd-kit/tree/devel/source/lib/src/cuda).

**Comment by njzjz** [comment]
I am going to close the issue as it's unclear what we can do for this issue.
