### ISSUE TITLE
Cannot execute lmp with deepmd when build from source as described in doc

### ISSUE THREAD

**Issue by Angel-Jia** [deepmodeling/deepmd-kit#2048]
### Summary

I have installed deepmd and lammps in plugin mode following the instruction in
https://github.com/deepmodeling/deepmd-kit/blob/master/doc/install/install-from-source.md and
https://github.com/deepmodeling/deepmd-kit/blob/master/doc/install/install-lammps.md.
However I got this error when executor command `${deepmd_root}/bin/lmp -i in.lammps -v restart 0`:
ERROR: Unrecognized pair style 'deepmd' (src/force.cpp:279)

### DeePMD-kit Version

v2.1.5

### TensorFlow Version

2.9

### Details

The problem can be solved by:
```
cd ${deepmd_root}/lib
ln -s libdeepmd_lmp.so dpplugin.so
```
Then executor lmp:
```
LAMMPS_PLUGIN_PATH=${deepmd_root}/lib/  ${deepmd_root}/bin/lmp -i in.lammps -v restart 0
```
I'm not sure if this is my problem.

**Comment by Angel-Jia** [comment]
Another way to solve it:
```
export LD_LIBRARY_PATH="${deepmd_root}/lib/:$LD_LIBRARY_PATH"
LAMMPS_PLUGIN_PATH=${deepmd_root}/lib/deepmd_lmp /root/deepmd-kit/bin/lmp -i in.lammps -v restart 0
```

**Comment by njzjz** [comment]
> Another way to solve it:
> 
> ```
> export LD_LIBRARY_PATH="${deepmd_root}/lib/:$LD_LIBRARY_PATH"
> LAMMPS_PLUGIN_PATH=${deepmd_root}/lib/deepmd_lmp /root/deepmd-kit/bin/lmp -i in.lammps -v restart 0
> ```

The documentation is clear enough as shown below:

![image](https://user-images.githubusercontent.com/9496702/199729528-9e2cfa96-4ec6-42f7-acdf-109121c77218.png)

**Comment by Angel-Jia** [comment]
1. `$deepmd_root/lib` has to be added into `LD_LIBRARY_PATH` and I haven't found it in doc.
2. I suggest adding information about checking if the installation is successful at the end of the doc: https://github.com/deepmodeling/deepmd-kit/blob/master/doc/install/install-lammps.md
Or just adding the url of `lammps-command.md` at the end of the doc.

The command `${deepmd_root}/bin/lmp -h` is unable to indicate whether deepmd is installed successfully with lammps.
At that time I didn't realize that there is another doc which has those information.

**Comment by njzjz** [comment]
`LD_LIBRARY_PATH` is not required if you have set `-D LAMMPS_INSTALL_RPATH=ON`.

**Comment by Angel-Jia** [comment]
`-D LAMMPS_INSTALL_RPATH=ON` has been set in my case, however I cannot execute `lmp` unless `$deepmd_root/lib` is added into `LD_LIBRARY_PATH`.
Here is my directory tree:
```
.
├── deepmd-kit    # deepmd-kit2.1.5 source code
├── deepmd_lammps    # INSTALL_PREFIX of DeePMD-kit's C++ interface and LAMMPS
├── lammps-23Jun2022    # lammps source code
└── tf_cpp    # tensorflow's C++ interface
```
DeePMD-kit's C++ interface:
```
mkdir /root/deepmd-kit/source/build
cd /root/deepmd-kit/source/build
cmake -DTENSORFLOW_ROOT=/root/tf_cpp/ -DCMAKE_INSTALL_PREFIX=/root/deepmd_lammps/ -DLAMMPS_SOURCE_ROOT=/root/lammps-23Jun2022/ -DUSE_CUDA_TOOLKIT=TRUE ..
make -j12
make install
```

LAMMPS:
```
mkdir /root/lammps-23Jun2022/build
cd /root/lammps-23Jun2022/build
cmake -D PKG_MC=ON -D PKG_PLUGIN=ON -D PKG_KSPACE=ON -D LAMMPS_INSTALL_RPATH=ON -D BUILD_SHARED_LIBS=yes -D CMAKE_INSTALL_PREFIX=/root/deepmd_lammps/ -D CMAKE_INSTALL_LIBDIR=lib -D CMAKE_INSTALL_FULL_LIBDIR=/root/deepmd_lammps/lib ../cmake
make -j12
make install
```
Then execute command:
```
LAMMPS_PLUGIN_PATH=/root/deepmd_lammps/lib/deepmd_lmp /root/deepmd_lammps/bin/lmp -i in.lammps -v restart 0
```
I got this error:
ERROR: Unrecognized pair style 'deepmd' (src/force.cpp:279)

After executing `export LD_LIBRARY_PATH="/root/deepmd_lammps/lib:$LD_LIBRARY_PATH"`, lammps can be executed with the command above.
Did I miss something?

**Comment by njzjz** [comment]
You can check `RUNPATH` by `readelf -d liblammps.so`.

I think your TF is not in `RUNPATH`.

**Comment by Angel-Jia** [comment]
> You can check `RUNPATH` by `readelf -d liblammps.so`.
> 
> I think your TF is not in `RUNPATH`.

Yes, my `RUNPATH` is `/root/deepmd_lammps/lib:/usr/lib/x86_64-linux-gnu/openmpi/lib` and I cannot set `RUNPATH` in `.bashrc`.

I installed tensorflow C++ interface by running the script `$deepmd_source_dir/source/install/build_tf.py`

**Comment by Angel-Jia** [comment]
Now I have another problem: DeePMD model is running on cpu after executing command:
```
LAMMPS_PLUGIN_PATH=/root/deepmd_lammps/lib/deepmd_lmp /root/deepmd_lammps/bin/lmp -i in.lammps -v restart 0
```
Here is the output of lammps:
```
Summary of lammps deepmd module ...
  >>> Info of deepmd-kit:
  installed to:       /root/deepmd_lammps
  source:             v2.1.5
  source branch:       HEAD
  source commit:      6e3d4a6
  source commit at:   2022-09-23 16:10:28 +0800
  surpport model ver.:1.1
  build float prec:   double
  build variant:      cuda
  build with tf inc:  /root/tf_cpp/include;/root/tf_cpp/include
  build with tf lib:  /root/tf_cpp/lib/libtensorflow_cc.so;/root/tf_cpp/lib/libtensorflow_framework.so
  set tf intra_op_parallelism_threads: 538976288
  set tf inter_op_parallelism_threads: 538981920
  >>> Info of lammps module:
  use deepmd-kit at:  /root/deepmd_lammps
  source:             v2.1.5
  source branch:      HEAD
  source commit:      6e3d4a6
  source commit at:   2022-09-23 16:10:28 +0800
  build float prec:   double
  build with tf inc:  /root/tf_cpp/include;/root/tf_cpp/include
  build with tf lib:  /root/tf_cpp/lib/libtensorflow_cc.so;/root/tf_cpp/lib/libtensorflow_framework.so
```
I haven't found the reason yet. I am prety sure cuda11.3 is used when compiling DeePMD-kit's C++ interface and there is a `libdeepmd_op_cuda.so` in `/root/deepmd_lammps/lib`. My `LD_LIBRARY_PATH` is  `/usr/local/cuda/lib64:/usr/local/nvidia/lib:/usr/local/nvidia/lib64`.
In addition, `dp train input.json` is running on GPU.

Do you have any suggestions?

**Comment by njzjz** [comment]
Did you build TensorFlow against Cuda?

**Comment by njzjz** [comment]
> Yes, my `RUNPATH` is `/root/deepmd_lammps/lib:/usr/lib/x86_64-linux-gnu/openmpi/lib` and I cannot set `RUNPATH` in `.bashrc`.

`RUNPATH` can be changed by
```sh
patchelf --set-rpath '/path/to/some' liblammps.so
```

**Comment by Angel-Jia** [comment]
> Did you build TensorFlow against Cuda?

I think this is the reason. I ran the script `$deepmd_source_dir/source/install/build_tf.py` with only one argument `--prefix`.
Thanks for your help.
