### ISSUE TITLE
Conda install erro

### ISSUE THREAD

**Issue by kdpan** [deepmodeling/deepmd-kit#2068]
### Summary

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.deepmodeling.com/noarch/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(MaxRetryError('HTTPSConnectionPool(host=\'conda.deepmodeling.com\', port=443): Max retries exceeded with url: /noarch/repodata.json (Caused by SSLError(SSLError("bad handshake: Error([(\'SSL routines\', \'ssl3_get_server_certificate\', \'certificate verify failed\')])")))'))

### DeePMD-kit Version

=*=gpu

### TensorFlow Version

2.7

### Details

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.deepmodeling.com/noarch/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
SSLError(MaxRetryError('HTTPSConnectionPool(host=\'conda.deepmodeling.com\', port=443): Max retries exceeded with url: /noarch/repodata.json (Caused by SSLError(SSLError("bad handshake: Error([(\'SSL routines\', \'ssl3_get_server_certificate\', \'certificate verify failed\')])")))'))

**Comment by njzjz** [comment]
You can follow [conda documentation](https://docs.conda.io/projects/conda/en/latest/user-guide/configuration/disable-ssl-verification.html#disabling-ssl-verification) to disable SSL verification.
