### ISSUE TITLE
[BUG] TestInferDeepPotA.cpu_lmp_nlist_type_sel failed when requesting atomic energies and atomic virial

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/deepmd-kit#2105]
### Bug summary

At present, `TestInferDeepPotA.cpu_lmp_nlist_type_sel` passes. But when using the `compute` method that requests atomic energies and atomic virials, it throws `Segmentation fault`.

### DeePMD-kit Version

devel

### TensorFlow Version

2.9.0

### How did you download the software?

Built from source

### Input Files, Running Commands, Error Log, etc.

The current codes:
https://github.com/deepmodeling/deepmd-kit/blob/37c69bc545d9ef4eb25021eed90a1dab1dd431f0/source/api_cc/tests/test_deeppot_a.cc#L370

If we change it to 
```cpp
  std::vector<VALUETYPE> force_(nall*3, 0.0), virial(9, 0.0), atomic_energy(nall*3, 0.0), atomic_virial(nall*9, 0.0);
  dp.compute(ener, force_, virial, atomic_energy, atomic_virial, coord_cpy, atype_cpy, box, nall-nloc, inlist, 0);
```

We will get
```
4074706 Segmentation fault      (core dumped)
```

This means this API has a potential bug.

### Steps to Reproduce

After changing that codes, run `source/install/test_cc.sh` or `source/install/test_cc_local.sh`.

**Comment by wanghan-iapcm** [comment]
I cannot reproduce the bug, or at least the Seg fault should not happen at `dp.compute`. Could you please provide your test_deeppot_a.cc?

**Comment by njzjz** [comment]
https://github.com/deepmodeling/deepmd-kit/commit/b831685e9429beb1594b23db29611a3ed1fcf70e

I can reproduce the segmentation fault on the GitHub: https://github.com/njzjz/deepmd-kit/commit/b831685e9429beb1594b23db29611a3ed1fcf70e/checks?check_suite_id=9399836409

**Comment by njzjz** [comment]
c1e4a3702a30e1ee8905c897d9a3075c1352babf

Reproduced on the GitHub Actions:
https://github.com/njzjz/deepmd-kit/commit/c1e4a3702a30e1ee8905c897d9a3075c1352babf/checks?check_suite_id=9399906381

**Comment by wanghan-iapcm** [comment]
The failure is expected. One has to fold back the ghost atoms to local atoms like

https://github.com/njzjz/deepmd-kit/blob/c1e4a3702a30e1ee8905c897d9a3075c1352babf/source/api_cc/tests/test_deeppot_a.cc#L287-L293

**Comment by njzjz** [comment]
I can't get it, as in this test, `atomic_energy` and `atomic_virial` are never read. The segmentation fault can only happen within `dp.compute`.
