### ISSUE TITLE
'sel' adjustment support error

### ISSUE THREAD

**Issue by michaelmacisaac** [deepmodeling/deepmd-kit#2118]
### Bug summary

Good morning,

I recently completed a grid search for optimal NN params and trained a model using initially only temperature data (model_1). Following completion of model_1 training, I froze the model, adjusted the input script to now only include shear data (i.e. changed training data directory), and began training a new model (model_2) with the same input json params as model_1 with the exception of the previously mentioned change in training data. When doing this I got an error: 
"Adjusting sel is only supported when 'set_davg_zero' is true!"

I am wondering why this error arises as 'set_davg_zero' should be set to true when 'atom_ener' in the fitting net is used, but I have the 'atom_ener' parameter set to defaults i.e. not in the input json file. 

See below for running command, error log, and input json.

### DeePMD-kit Version

v2.1.5

### TensorFlow Version

2.9.0

### How did you download the software?

conda

### Input Files, Running Commands, Error Log, etc.

**INPUT FILE:**
{
    "model": {
        "type_map": [
            "Si",
            "C"
        ],
        "type_embedding": {
            "neuron": [
                20,
                20,
                20
            ],
            "activation_function": "relu",
            "trainable": true,
            "seed": 1
        },
        "descriptor": {
            "type": "se_e2_a",
            "sel": "auto:1.5",
            "rcut": 6.0,
            "rcut_smth": 5.5,
            "neuron": [
                20,
                40,
                80
            ],
            "axis_neuron": 16,
            "activation_function": "relu",
            "trainable": true,
            "seed": 1
        },
        "fitting_net": {
            "type": "ener",
            "neuron": [
                160,
                160,
                160
            ],
            "activation_function": "relu",
            "trainable": true,
            "seed": 1
        }
    },
    "learning_rate": {
        "type": "exp",
        "start_lr": 0.001,
        "stop_lr": 3.51e-08,
        "decay_steps": 500
    },
    "loss": {
        "type": "ener",
        "start_pref_e": 0.001,
        "limit_pref_e": 1,
        "start_pref_f": 10,
        "limit_pref_f": 10
    },
    "training": {
        "training_data": {
            "systems": "/blue/subhash/michaelmacisaac/SiC/SiC_potential/data/volumetricstraindata/trainingdata"
        },
        "numb_steps": 100000,
        "seed": 1,
        "disp_file": "lcurve.out",
        "disp_freq": 100,
        "save_freq": 1000,
        "save_ckpt": "model_ckpt",
        "disp_training": true,
        "time_training": true,
        "profiling": true,
        "profiling_file": "profile",
        "tensorboard": true,
        "tensorboard_log_dir": "tensorboard_log_dir",
        "tensorboard_freq": 500
    }
}

*RUNNING COMMANDS:**

#!/bin/bash
#SBATCH --job-name=model_003
#SBATCH --mail-type=ALL
#SBATCH --mail-user=michaelmacisaac@ufl.edu
#SBATCH --output j_%j_model_003.out
#SBATCH --error j_%j_model_003.err
#SBATCH --account=spearot
#SBATCH --qos=spearot
#SBATCH --partition=gpu
#SBATCH --gres=gpu:2
#SBATCH --ntasks=1
#SBATCH --mem=16gb
#SBATCH --time=5-0:00:00

cd $SLURM_SUBMIT_DIR
pwd;
echo 'GPU Job started - '$(pwd)
date;
nvidia-smi

export PATH=/blue/subhash/michaelmacisaac/SiC/envs/deepmd/bin:$PATH
dp train input.json --init-frz-model /blue/subhash/michaelmacisaac/SiC/SiC_potential/models/model_002/graph.pb
echo 'Done.'
date;

**ERROR LOG:**

WARNING:tensorflow:From /blue/subhash/michaelmacisaac/SiC/envs/deepmd/lib/python3.10/site-packages/tensorflow/python/compat/v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:root:To get the best performance, it is recommended to adjust the number of threads by setting the environment variables OMP_NUM_THREADS, TF_INTRA_OP_PARALLELISM_THREADS, and TF_INTER_OP_PARALLELISM_THREADS.
DEEPMD INFO    Calculate neighbor statistics... (add --skip-neighbor-stat to skip this step)
DEEPMD INFO    training data with min nbor dist: 1.890051368991065
DEEPMD INFO    training data with max nbor size: [44 44]
DEEPMD INFO     _____               _____   __  __  _____           _     _  _   
DEEPMD INFO    |  __ \             |  __ \ |  \/  ||  __ \         | |   (_)| |  
DEEPMD INFO    | |  | |  ___   ___ | |__) || \  / || |  | | ______ | | __ _ | |_ 
DEEPMD INFO    | |  | | / _ \ / _ \|  ___/ | |\/| || |  | ||______|| |/ /| || __|
DEEPMD INFO    | |__| ||  __/|  __/| |     | |  | || |__| |        |   < | || |_ 
DEEPMD INFO    |_____/  \___| \___||_|     |_|  |_||_____/         |_|\_\|_| \__|
DEEPMD INFO    Please read and cite:
DEEPMD INFO    Wang, Zhang, Han and E, Comput.Phys.Comm. 228, 178-184 (2018)
DEEPMD INFO    installed to:         /home/conda/feedstock_root/build_artifacts/deepmd-kit_1663923590539/work/_skbuild/linux-x86_64-3.10/cmake-install
DEEPMD INFO    source :              v2.1.5
DEEPMD INFO    source brach:         HEAD
DEEPMD INFO    source commit:        6e3d4a62
DEEPMD INFO    source commit at:     2022-09-23 16:10:28 +0800
DEEPMD INFO    build float prec:     double
DEEPMD INFO    build variant:        cuda
DEEPMD INFO    build with tf inc:    /blue/subhash/michaelmacisaac/SiC/envs/deepmd/lib/python3.10/site-packages/tensorflow/include;/blue/subhash/michaelmacisaac/SiC/envs/deepmd/include
DEEPMD INFO    build with tf lib:    
DEEPMD INFO    ---Summary of the training---------------------------------------
DEEPMD INFO    running on:           c46a-s25
DEEPMD INFO    computing device:     gpu:0
DEEPMD INFO    CUDA_VISIBLE_DEVICES: 4,5
DEEPMD INFO    Count of visible GPU: 2
DEEPMD INFO    num_intra_threads:    0
DEEPMD INFO    num_inter_threads:    0
DEEPMD INFO    -----------------------------------------------------------------
DEEPMD INFO    ---Summary of DataSystem: training     -----------------------------------------------
DEEPMD INFO    found 1 system(s):
DEEPMD INFO                                        system  natoms  bch_sz   n_bch   prob  pbc
DEEPMD INFO    -- lumetricstraindata/trainingdata/Si32C32      64       1      40  1.000    T
DEEPMD INFO    --------------------------------------------------------------------------------------
DEEPMD INFO    training without frame parameter
Traceback (most recent call last):
  File "/blue/subhash/michaelmacisaac/SiC/envs/deepmd/bin/dp", line 10, in <module>
    sys.exit(main())
  File "/blue/subhash/michaelmacisaac/SiC/envs/deepmd/lib/python3.10/site-packages/deepmd/entrypoints/main.py", line 562, in main
    train_dp(**dict_args)
  File "/blue/subhash/michaelmacisaac/SiC/envs/deepmd/lib/python3.10/site-packages/deepmd/entrypoints/train.py", line 107, in train
    _do_work(jdata, run_opt, is_compress)
  File "/blue/subhash/michaelmacisaac/SiC/envs/deepmd/lib/python3.10/site-packages/deepmd/entrypoints/train.py", line 163, in _do_work
    model.build(train_data, stop_batch)
  File "/blue/subhash/michaelmacisaac/SiC/envs/deepmd/lib/python3.10/site-packages/deepmd/train/trainer.py", line 329, in build
    self._init_from_frz_model()
  File "/blue/subhash/michaelmacisaac/SiC/envs/deepmd/lib/python3.10/site-packages/deepmd/train/trainer.py", line 744, in _init_from_frz_model
    self.model.init_variables(graph, graph_def, model_type=self.model_type)
  File "/blue/subhash/michaelmacisaac/SiC/envs/deepmd/lib/python3.10/site-packages/deepmd/model/ener.py", line 318, in init_variables
    self.descrpt.init_variables(graph, graph_def, suffix=suffix)
  File "/blue/subhash/michaelmacisaac/SiC/envs/deepmd/lib/python3.10/site-packages/deepmd/descriptor/se_a.py", line 901, in init_variables
    raise RuntimeError("Adjusting sel is only supported when `set_davg_zero` is true!")
RuntimeError: Adjusting sel is only supported when `set_davg_zero` is true!

### Steps to Reproduce

Use the running commands shown in previous cell with appropriate input json and frozen model (provided below).

[graph.pb.zip](https://github.com/deepmodeling/deepmd-kit/files/10058081/graph.pb.zip)

### Further Information, Files, and Links

[graph.pb.zip](https://github.com/deepmodeling/deepmd-kit/files/10058086/graph.pb.zip)

**Comment by njzjz** [comment]
When you use `auto` as `sel`, the value of `sel` depends on the data, so it changed after you changed the data.
You can keep `sel` constant.
