### ISSUE TITLE
Cannot successfully call GPU on hpc

### ISSUE THREAD

**Issue by SimonkingCat** [deepmodeling/deepmd-kit#2169]
### Summary

Cannot successfully call GPU on hpc
`
WARNING:deepmd.train.run_options:Switch to serial execution due to lack of horovod module.
`
running information
`
DEEPMD INFO    ---Summary of the training---------------------------------------
DEEPMD INFO    running on:           gpu05
DEEPMD INFO    computing device:     cpu:0
DEEPMD INFO    CUDA_VISIBLE_DEVICES: 0,1,2,3,4,5,6,7
DEEPMD INFO    Count of visible GPU: 0
DEEPMD INFO    num_intra_threads:    0
DEEPMD INFO    num_inter_threads:    0
DEEPMD INFO    -----------------------------------------------------------------
`

### DeePMD-kit Version

2.1.5

### TensorFlow Version

2.9.0

### Details

[train.log](https://github.com/deepmodeling/deepmd-kit/files/10177884/train.log)

**Comment by njzjz** [comment]
> DEEPMD INFO    build variant:        cpu

The log clearly shows that it is the CPU version.
