### ISSUE TITLE
[BUG] dp test  *e_peratom.out 

### ISSUE THREAD

**Issue by Manyi-Yang** [deepmodeling/deepmd-kit#2201]
### Bug summary

Here I would like to do `dp test`  for multi-systems simultaneously using the following command:
 `dp test -s $multi-systems -m graph.pb -d dptest`

 The generated  _dptest.e_peratom.out_  file only include the information for the latest subsystem, rather than for all tested systems. 

### DeePMD-kit Version

DeePMD-kit v2.2.0b1.dev0+g89d0d23.d20221223

### TensorFlow Version

2.6.0

### How did you download the software?

Built from source

### Input Files, Running Commands, Error Log, etc.

Running Command: 
`dp test -s $multi-systems -m graph.pb -d dptest`

### Steps to Reproduce

`dp test -s $multi-systems -m graph.pb -d dptest`

**Comment by njzjz** [comment]
Fixed in #2220
