### ISSUE TITLE
run C++ inference example infer_water, got ALREADY_EXISTS: Op with name Gelu error

### ISSUE THREAD

**Issue by yiqichenshallwetalk** [deepmodeling/deepmd-kit#2223]
### Bug summary

The DeepMD C++ inferace was built successfully following the instructions on https://docs.deepmodeling.com/projects/deepmd/en/master/install/install-from-source.html.

However, when tested with the inference example: https://docs.deepmodeling.com/projects/deepmd/en/master/inference/cxx.html, an error was raised:
2023-01-06 18:43:03.150927: F tensorflow/core/framework/op.cc:215] Non-OK-status: RegisterAlreadyLocked(deferred_[i]) status: ALREADY_EXISTS: Op with name Gelu
Aborted (core dumped)

It seems like there are conflicts between the custom Gelu and TF's default Gelu.

### DeePMD-kit Version

v2.2.0b1.dev0+g89d0d23.d20230106

### TensorFlow Version

2.8.0

### How did you download the software?

Built from source

### Input Files, Running Commands, Error Log, etc.

compile infer_water.cpp successfully using:
gcc infer_water.cpp -L $deepmd_root/lib -L $tensorflow_root/lib -I $deepmd_root/include -Wl,--no-as-needed -ldeepmd_cc -lstdc++ -ltensorflow_cc -Wl,-rpath=$deepmd_root/lib -Wl,-rpath=$tensorflow_root/lib -o infer_water

However, runing ./infer_water generated a TF error:
F tensorflow/core/framework/op.cc:215] Non-OK-status: RegisterAlreadyLocked(deferred_[i]) status: ALREADY_EXISTS: Op with name Gelu
Aborted (core dumped)

### Steps to Reproduce

1. Install the tensorflow and deepmd C++ inferface. 
2. Compile infer_water.cpp using gcc.
3. Run the compiled program.

**Comment by yiqichenshallwetalk** [comment]
Yes. I was using a Rocm enhanced version of TF, which has a Gelu OP.

**Comment by cugbls** [comment]
I have the same problem, Deepmd + ROCm ver. Tensorflow . How can I solve this problem ?

**Comment by yiqichenshallwetalk** [comment]
Skipping the custom Gelu op works for me. Do not include _gelu_multi_device.cc_ in source/op/CMakeLists and it should work.

**Comment by cugbls** [comment]
> Skipping the custom Gelu op works for me. Do not include _gelu_multi_device.cc_ in source/op/CMakeLists and it should work.

Thanks a lot ! It works !

But after solve this , I have a new problem when running Lammps , there is a error  :
Not found: No attr named 'dtype' in NodeDef:
         [[{{node filter_type_0/Cast/x}}]]
         [[filter_type_0/Cast/x]]
ERROR: DeePMD-kit Error: TensorFlow Error: Not found: No attr named 'dtype' in NodeDef:
         [[{node filter_type_0/Cast/x}]]
         [[filter_type_0/Cast/x]] (../pair_deepmd.cpp:933)
Last command: pair_style      deepmd Sn.pb

Maybe something still wrong.
BTW, thank you so much !
