### ISSUE TITLE
[BUG] There are many useless log messages(INFO:tensorflow:10400) in train.log

### ISSUE THREAD

**Issue by dingzhaohan** [deepmodeling/deepmd-kit#2238]
### Bug summary

There are many useless log messages(INFO:tensorflow:10400) in train.log

### DeePMD-kit Version

2.1.5

### TensorFlow Version

2.9

### How did you download the software?

Offline packages

### Input Files, Running Commands, Error Log, etc.

INFO:tensorflow:9000
DEEPMD INFO 9000
INFO:tensorflow:/home/input_lbg-157-5264508/003/model.ckpt-36000.meta
DEEPMD INFO /home/input_lbg-157-5264508/003/model.ckpt-36000.meta
INFO:tensorflow:10400
DEEPMD INFO 10400
DEEPMD INFO saved checkpoint model.ckpt
DEEPMD INFO batch 37000 training time 15.89 s, testing time 0.01 s
INFO:tensorflow:/home/input_lbg-157-5264508/003/model.ckpt-37000.data-00000-of-00001
DEEPMD INFO /home/input_lbg-157-5264508/003/model.ckpt-37000.data-00000-of-00001
INFO:tensorflow:9000

### Steps to Reproduce

using 2.1.5-cuda11.6 offline installer and water/se_e2_a example in github repo

**Comment by wanghan-iapcm** [comment]
@njzjz do you have any hint?

**Comment by njzjz** [comment]
The logging messages in other modules are forwarded to deepmd and the logging level is set to `INFO` by default.

https://github.com/deepmodeling/deepmd-kit/blob/89d0d2339b22954f07765202f50e34eb87ec4080/deepmd/loggers/loggers.py#L194-L200

https://github.com/deepmodeling/deepmd-kit/blob/89d0d2339b22954f07765202f50e34eb87ec4080/deepmd/loggers/loggers.py#L211-L225

Why do we need to forward messages from other modules?

**Comment by njzjz** [comment]
I believe the correct thing is to change line 195 to `logging.getLogger(name="deepmd")` and remove line 199-200.

**Comment by wanghan-iapcm** [comment]
I do not think so..
