### ISSUE TITLE
[Feature Request] Changing the default value of `type_one_side` to `True`

### ISSUE THREAD

**Issue by wanghan-iapcm** [deepmodeling/deepmd-kit#2265]
### Summary

Changing the default value of `type_one_side` to `True` will enhance the performance on multi component systems. 

### Detailed Description

Now the default value of `type_one_side` is `False`, with which the number of embedding networks goes as square of number of atom types in the system. Setting it to `True` will reduce the number to the number of atom types. In almost all systems this will not lead to significant loss of accuracy. Thus `False` is the recommended value.

**Comment by njzjz** [comment]
Are there any test results? Also, this is a **breaking** change. The alternative way is to throw a warning for this information.

**Comment by njzjz** [comment]
> Changing the default value of `type_one_side` to `True` will enhance the performance on multi component systems.

I also notice that performance is not improved on CPUs.

**Comment by wanghan-iapcm** [comment]
> > Changing the default value of `type_one_side` to `True` will enhance the performance on multi component systems.
> 
> I also notice that performance is not improved on CPUs.

How many types do you have in your test system?

**Comment by njzjz** [comment]
I have a 7-type system. The CPU have a different parallel strategy compared to the GPU, so the performance is not significantly improved (only slightly).

**Comment by njzjz** [comment]
I think a better way is to set this parameter in the examples to `true`. However, we may need to do some tests first.
