### ISSUE TITLE
[Feature Request] Modify dplr source code to support the newest LAMMPS 

### ISSUE THREAD

**Issue by Yi-FanLi** [deepmodeling/deepmd-kit#2275]
### Summary

Currently, compiling deepmd-kit with the newest LAMMPS (commit 554257 in LAMMPS's develop branch) fails. The error message is as follows:

[  6%] Building CXX object CMakeFiles/lammps.dir/scratch/gpfs/yifanl/Softwares/lammps-dev/lammps/src/DEEPMD/pppm_dplr.cpp.o
/scratch/gpfs/yifanl/Softwares/lammps-dev/lammps/src/DEEPMD/pppm_dplr.cpp:10:10: fatal error: gridcomm.h: No such file or directory
 #include "gridcomm.h"
          ^~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/lammps.dir/build.make:5774: CMakeFiles/lammps.dir/scratch/gpfs/yifanl/Softwares/lammps-dev/lammps/src/DEEPMD/pppm_dplr.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:172: CMakeFiles/lammps.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

This error stems from this commit of LAMMPS:
https://github.com/lammps/lammps/commit/72b0a2dfdf86936029dc7f7c935401c37e1d0ee1
which was committed on Dec 19, 2022. In this commit, LAMMPS's gridcomm.h file is renamed into grid3d.h. The GridComm class is deprecated, and a new class called Grid3d is used instead. Therefore, DeePMD-kit should support the changes accordingly.

### Detailed Description

I suggest to add support for Grid3d in pppm_dplr.h and pppm_dplr.cpp, like what is done for src/KSPACE/pppm.h and src/KSPACE/pppm.cpp. However, how to support both old and new versions is not clear yet. Using macro with "if" based on LAMMPS_VERSION_NUMBER may not work, since LAMMPS's commit 72b0a2 did not change its version number.

**Comment by njzjz** [comment]
> Using macro with "if" based on LAMMPS_VERSION_NUMBER may not work, since LAMMPS's commit 72b0a2 did not change its version number.

LAMMPS version number is updated in every stable and patch release. If we only support the release version of LAMMPS, this should not be a problem.
