### ISSUE TITLE
[BUG] Run MD with LAMMPS has a temperature instability problem on the AMD ROCM platform

### ISSUE THREAD

**Issue by LLfbforever** [deepmodeling/deepmd-kit#2303]
### Bug summary

When executing the calculation example, the temperature is unstable when LAMMPS runs the force field trained by deepmd

### DeePMD-kit Version

master branch

### TensorFlow Version

tensorflow2.7.0

### How did you download the software?

Offline packages

### Input Files, Running Commands, Error Log, etc.

in file to add the command line：
plugin load libdeepmd_lmp.so

The output result of lammps operation:
 the temperature value is unstable. When temp=2000k, more than 10,000 temp values will appear during the operation.

### Steps to Reproduce

1. install deepmd-kit
2. install lammps
3. run
4. Draw a graph of temperature change

**Comment by LLfbforever** [comment]
by finding bugs:
Through debugging, locate the calculation process of the TabulateFusionSeAGrad operator in deepmd-kit. After modifying the number of iterations of the second for loop of kernel: tabulate_fusion_se_a_grad_fifth_order_polynomial in the /deepmd-kit-master/source/lib/src/rocm/tabulate.hip.cu file.
Namely: 
         (1) The for loop should start from warp_idx→nnei
         (2) Change int ii = 0 in the for loop to int ii = warp_idx, and all ii+warp_idx in the for loop are changed to ii
Running the study again, the temperature reached a steady state.

**Comment by njzjz** [comment]
Fixed in #2357.
