### ISSUE TITLE
I wonder can we set different rcut with different atom type groups? 

### ISSUE THREAD

**Issue by Yufan121** [deepmodeling/deepmd-kit#2321]
### Summary

I wonder can we set different rcut with different atom type groups? 

### DeePMD-kit Version

2.1.5

### TensorFlow Version

2.11.0

### Details

I wonder can we set different rcut with different atom type groups?

**Comment by njzjz** [comment]
Hi there is an example in the documentation:
https://docs.deepmodeling.com/projects/deepmd/en/v2.2.0.b0/model/dprc.html#training-the-dprc-model

**Comment by Yufan121** [comment]
> Hi there is an example in the documentation:
> https://docs.deepmodeling.com/projects/deepmd/en/v2.2.0.b0/model/dprc.html#training-the-dprc-model

Thanks you! Let me give it a try
