### ISSUE TITLE
PLUMED error when run the lamps-dp

### ISSUE THREAD

**Issue by lwen9** [deepmodeling/deepmd-kit#2399]
### Summary

PLUMED error occurred when run the lammps-dp

### DeePMD-kit Version

2.1.5

### TensorFlow Version

2.9.0

### Details

Hi,
when I run a lammps-dp with plumed, there is a error reported:
"+++ Loading the PLUMED kernel runtime +++
+++ PLUMED_KERNEL="/export/home/liuwen/miniconda3/envs/deepmd/lib/libplumedKernel.so" +++
/export/home/xx/miniconda3/envs/deepmd/bin/lmp: line 11:  3943 Aborted                 /export/home/xx/miniconda3/envs/deepmd/bin/_lmp "$@"
 the keyword in input file relevant to plumed is
 "fix            dpgen_plm all plumed plumedfile plumed-1_2.dat outfile output.plumed"
How could I solve this problem? Could anyone give a help? I would be very appreciated!
Best regards

**Comment by njzjz** [comment]
The detailed error message might be in `lammps.log` or `plumed.log` or `output.plumed`. Could you try to find it?

**Comment by lwen9** [comment]
> The detailed error message might be in `lammps.log` or `plumed.log` or `output.plumed`. Could you try to find it?

Thanks very much for your reply. It's the error from my input file of plumed.

**Comment by XMax92** [comment]
Hello lwen9,
I also met the same issue, could you please let me know how you fix it?
Best reagrds

**Comment by lwen9** [comment]
> Hello lwen9,
> I also met the same issue, could you please let me know how you fix it?
> Best reagrds

It may be some error in your input file, you can see the output file (lammps.log or plumed.log or output  as answered above), it offer the specific questions.
