### ISSUE TITLE
LAMMPS_SOURCE_ROOT argument in setup.py

### ISSUE THREAD

**Issue by yiqichenshallwetalk** [deepmodeling/deepmd-kit#2432]
### Summary

I noticed several recent changes in sutup.py file. Now it is possible to build lmp and ipi plugins via pip install, which is much easier than the C++ build. However, it only contains the LAMMPS_VERSION argument. Without LAMMPS_SOURCE_ROOT, we are not able to build lmp plugin on existing lammps source. Are there any plans to add that in setup.py in the future?

### Detailed Description

Add LAMMPS_SOURCE_ROOT argument in setup.py to build lammps plugin on existing lammps source.

**Comment by njzjz** [comment]
Indeed, one can use `CMAKE_ARGS` environment variables to pass any CMake argument.
