### ISSUE TITLE
Trouble with downloading offline package

### ISSUE THREAD

**Issue by lindafei01** [deepmodeling/deepmd-kit#2445]
### Bug summary

I have tried for multiple times to download[deepmd-kit-2.2.1-cuda10.2_gpu-Linux-x86_64.sh](https://github.com/deepmodeling/deepmd-kit/releases/download/v2.2.1/deepmd-kit-2.2.1-cuda10.2_gpu-Linux-x86_64.sh).
I am getting the failure message from the browser: Download Needs Authorization ('失败，需要获得授权'）

### DeePMD-kit Version

/

### TensorFlow Version

/

### How did you download the software?

Offline packages

### Input Files, Running Commands, Error Log, etc.

/

### Steps to Reproduce

/

### Further Information, Files, and Links

/

**Comment by njzjz** [comment]
I felt it is just a network issue.
