### ISSUE TITLE
Installation from conda-forge provides lammps without deepmd pairstyle

### ISSUE THREAD

**Issue by martincramerpedersen** [deepmodeling/deepmd-kit#2451]
### Bug summary

As per the installation instructions, I am attempting to install deepmd-kit alongside lammps on my arm64 Mac M1 using e.g. the command:

`conda create -n deepmd deepmd-kit=*=*cpu libdeepmd=*=*cpu lammps -c https://conda.deepmodeling.com -c defaults`

However, there are no arm64 packages available from this channel. As I understand, I am to use the conda-forge installation option for these; i.e.:

`conda create -n deepmd deepmd-kit lammps -c conda-forge`

While this does indeed run, this command does - I believe - install the stock version of Lammps from the lammps package and not a version of Lammps with this Lammps deepmd pairstyle included (i.e. not lammps-dp).

Any advice on how to install the correct, modified version of Lammps would be much appreciated.

### DeePMD-kit Version

2.2.1

### TensorFlow Version

2.9

### How did you download the software?

conda

### Input Files, Running Commands, Error Log, etc.

conda create -n deepmd deepmd-kit lammps -c conda-forge

### Steps to Reproduce

As above

**Comment by njzjz** [comment]
Hi, for both channels, the deepmd pair style works in the plugin mode. The LAMMPS library in both channels does not contain the deepmd pair style.

For more information, see LAMMPS documentation

https://docs.lammps.org/plugin.html

**Comment by martincramerpedersen** [comment]
Thank you for clarifying - and for the quick reply. Though I am a bit puzzled; on my Ubuntu workstation, installing the packages via the deepmodeling channel does indeed provide a version of Lammps that does not need the plugin activated to utilize the pairstyle.

Can I ask for your advice on how to enable the plugin (on Mac)? Simply adding:
`plugin load libdeepmd_lmp.so`
to the Lammps input file yields an error running Lammps (explaining that the file cannot be found). Seeing as this was installed by conda, I have attempted to set LAMMPS_PLUGIN_PATH to pathtoanaconda/anaconda3/envs/deepmd/lib/ or pathtoanaconda/anaconda3/envs/deepmd/lib/deepmd_lmp but neither of these help.

**Comment by njzjz** [comment]
What version of LAMMPS did you install? (see `conda list`)

I guess the problem is that the LAMMPS version is not properly pinned.

**Comment by martincramerpedersen** [comment]
Thank you very much for your efforts.

Installing the current version from conda-forge on arm64 MacOS - i.e.:
`conda create -n deepmd deepmd-kit lammps -c conda-forge`
gives me the following version:
`conda-forge/osx-arm64::lammps-2023.03.28-py310h69f0182_mpich_0 None`

This version appears no different than the one in conda-forge when I wrote the original post; it neither has the deepmd pairstyle nor is it able to import the plugin. 

For comparison, the version installed on my Ubuntu workstation (from the deepmodeling channel) is:
`lammps                    20220623.1           h9954876_1    deepmodeling`

Using this version, I can run the non-plugin water example in /examples/water/lmp (with an appropriate .pb file).

**Comment by njzjz** [comment]
The plugin was built against 2022.06.23, so it is not compatible with 2023.03.28.

**Comment by njzjz** [comment]
I just realized that `LAMMPS_PLUGIN_PATH` was incorrectly configured for the conda-forge packages, so one has to manually call `plugin load`.

I am going to fix it in https://github.com/conda-forge/deepmd-kit-feedstock/pull/63.
