### ISSUE TITLE
[Parameters] rcut

### ISSUE THREAD

**Issue by liu-stewart** [deepmodeling/deepmd-kit#2468]
### Summary

当我在使用dpgen训练的时候出了一些问题，经检查问题出自于rcut参数的设定，程序要求给定float类型的参数而我给了int类型，train过程中止，我觉得这是极其不合理的行为。

### Detailed Description

并且在使用dpgen的时候，对于这一错误的提示很不明显，需要去remote目录下进入某一文件夹查看train.log才能发现，我认为这会极大的影响用户体验，希望可以加入对int的支持（比如将其自动转换为float），或者给出更明显的错误提示。

**Comment by y1xiaoc** [comment]
new dargs package should solve this. Rely on @njzjz to give a new release.

Another related issue is maybe dpgen or dflow should forward the error message of its failed task?

**Comment by njzjz** [comment]
Fixed in deepmodeling/dargs@829e19b475aabb78af765b62ff822a8b247d4333 and I've released darg v0.3.5.

> Another related issue is maybe dpgen or dflow should forward the error message of its failed task?

@felix5572 @zjgemi any ideas?

**Comment by njzjz** [comment]
> Another related issue is maybe dpgen or dflow should forward the error message of its failed task?

I post the rest issue in https://github.com/deepmodeling/dpdispatcher/issues/333. This issue is closed.

**Comment by njzjz** [comment]
Forwarding the error message of the failed task has been implemented in https://github.com/deepmodeling/dpdispatcher/issues/333 and released in dpdispatcher v0.6.0.
