### ISSUE TITLE
ZBL not available when I am using hybrid descriptor

### ISSUE THREAD

**Issue by swome** [deepmodeling/deepmd-kit#2490]
### Summary

Not implemented Error

### DeePMD-kit Version

2.1.5

### TensorFlow Version

2.9.0

### Details

When using this input script:
    "model": {
        "use_srtab": "zbl_file",
        "smin_alpha": 0.1,
        "sw_rmin": 1.0,
        "sw_rmax": 1.2,
        "type_map": [
            "Na"
        ],

        "descriptor" :{
            "type":     "hybrid",
            "list": [
        {
            "type":             "se_a",
            "sel":              [200],
            "rcut_smth":        2.00,
            "rcut":             6.00,
            "neuron":           [25, 50, 100],
            "resnet_dt":        false,
            "axis_neuron":      16,
            "seed": 659551769
        }, {
            "type":             "se_at",
            "sel":              [45],
            "rcut_smth":        0.50,
            "rcut":             4.00,
            "neuron":           [4, 8, 16],
            "resnet_dt":        false,
            "seed": 659551769
        }
                ]
        },

        "fitting_net": {
            "neuron": [
                240,
                240,
                240
            ],
            "resnet_dt": true,
            "_comment": " that's all",
            "seed": 742487852
        },
        "_comment": " that's all"
    },

    "learning_rate": {
        "type": "exp",
        "start_lr": 0.001,
        "decay_steps": 80000
    },

    "loss": {
        "start_pref_e": 0.2,
        "limit_pref_e": 1,
        "start_pref_f": 1000,
        "limit_pref_f": 1,
        "start_pref_v": 0.2,
        "limit_pref_v": 1
    },

    "training": {
        "numb_steps": 16000000,
        "disp_file": "lcurve.out",
        "disp_freq": 2000,
        "numb_test": 4,
        "save_freq": 2000,
        "save_ckpt": "model.ckpt",
        "disp_training": true,
        "time_training": true,
        "profiling": false,
        "profiling_file": "timeline.json",
        "_comment": "that's all",
        "training_data": {
            "systems": "./init/",
            "batch_size": "auto"
        },
        "seed": 801755202
    }
}

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
Traceback (most recent call last):
  File "/opt/deepmd-kit-2.1.5/bin/dp", line 10, in <module>
    sys.exit(main())
  File "/opt/deepmd-kit-2.1.5/lib/python3.10/site-packages/deepmd/entrypoints/main.py", line 562, in main
    train_dp(**dict_args)
  File "/opt/deepmd-kit-2.1.5/lib/python3.10/site-packages/deepmd/entrypoints/train.py", line 107, in train
    _do_work(jdata, run_opt, is_compress)
  File "/opt/deepmd-kit-2.1.5/lib/python3.10/site-packages/deepmd/entrypoints/train.py", line 163, in _do_work
    model.build(train_data, stop_batch)
  File "/opt/deepmd-kit-2.1.5/lib/python3.10/site-packages/deepmd/train/trainer.py", line 352, in build
    self._build_network(data, suffix)
  File "/opt/deepmd-kit-2.1.5/lib/python3.10/site-packages/deepmd/train/trainer.py", line 376, in _build_network
    = self.model.build (self.place_holders['coord'],
  File "/opt/deepmd-kit-2.1.5/lib/python3.10/site-packages/deepmd/model/ener.py", line 203, in build
    nlist, rij, sel_a, sel_r = self.descrpt.get_nlist()
  File "/opt/deepmd-kit-2.1.5/lib/python3.10/site-packages/deepmd/descriptor/descriptor.py", line 141, in get_nlist
    raise NotImplementedError
NotImplementedError

Problems solved if I do not involve ZBL during the training

**Comment by njzjz** [comment]
See #2286
