### ISSUE TITLE
The task should have reported OOM from the beginning, but the task has not been terminated as usual

### ISSUE THREAD

**Issue by XuFanffei** [deepmodeling/deepmd-kit#2516]
### Bug summary

The task should have reported OOM from the beginning, but the task has not been terminated as usual

### DeePMD-kit Version

deepmd-kit:2.1.5

### TensorFlow Version

2.9.0

### How did you download the software?

docker

### Input Files, Running Commands, Error Log, etc.

input file:
https://dpcloudserver.oss-cn-shenzhen.aliyuncs.com/dpcloudserver/indicate/f4aaf05aed8d11ed8f67e9dd2e60bc82/f4aaf05aed8d11ed8f67e9dd2e60bc82.zip

running command:mpirun -n 8 lmp -i [lammps.in](http://lammps.in/) -v restart 1 && touch tag_1

### Steps to Reproduce

Submit tasks on Bohrium use image deepmd-kit:2.1.5-cuda11.6 ，platform paratera，machine c80 m304 8 * NVIDIA V100

**Comment by njzjz** [comment]
Could you provide `lammps.log`?
