### ISSUE TITLE
[BUG]  DeePMD-kit’s C++ interface build error

### ISSUE THREAD

**Issue by Ternity** [deepmodeling/deepmd-kit#2522]
### Bug summary

When I build DeepMD-kit‘s C++ interface by cmake, maybe there are something wrong with tf_version.cpp

  /home/yuqinghan/Systemtools/gcc-7.3.1/bin/gcc
  CMakeFiles/cmTC_574ec.dir/tf_version.cpp.o -o cmTC_574ec

  CMakeFiles/cmTC_574ec.dir/tf_version.cpp.o: In function `main':

  tf_version.cpp:(.text+0x15): undefined reference to `std::cout'

  tf_version.cpp:(.text+0x1a): undefined reference to
  `std::basic_ostream<char, std::char_traits<char> >& std::operator<<
  <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char>
  \>&, char const*)'

  CMakeFiles/cmTC_574ec.dir/tf_version.cpp.o: In function
  `__static_initialization_and_destruction_0(int, int)':

  tf_version.cpp:(.text+0x48): undefined reference to
  `std::ios_base::Init::Init()'

  tf_version.cpp:(.text+0x57): undefined reference to
  `std::ios_base::Init::~Init()'

  collect2: error: ld returned 1 exit status

  gmake[1]: *** [cmTC_574ec] Error 1

### DeePMD-kit Version

v2.2.2.dev0+g3ac8c4c.d20230408

### TensorFlow Version

libtensorflow_cc ==2.5.0==gpu_cuda10.1_0

### How did you download the software?

Built from source

### Input Files, Running Commands, Error Log, etc.

My environment:
I install tensorflow_cc by conda:
``` (lammps)$ conda install libtensorflow_cc=2.5.0=gpu_cuda10.1_0 -c https://conda.deepmodeling.com```
My system is Cent OS 7, the system GNU version is 6.1.0
Considering tensorflow specific requirements for compiler versions, I install gcc 7.3.0 for userself.
Then add related path to `PATH` and `LD_LIBRARY_PATH`:
```
(lammps)$ export PATH="/home/yuqinghan/Systemtools/gcc-7.3.1/bin:$PATH"
(lammps)$ export LD_LIBRARY_PATH="/home/yuqinghan/Systemtools/gcc-7.3.1/lib:$LD_LIBRARY_PATH"
(lammps)$ export LD_LIBRARY_PATH="/home/yuqinghan/Systemtools/gcc-7.3.1/lib64:$LD_LIBRARY_PATH"
```
After that, I specify the following path:
```
(lammps)$ export tensorflow_root=/home/yuqinghan/anaconda3/envs/lammps
(lammps)$ export deepmd_source_dir=/home/yuqinghan/Software/DeePMD-kit
(lammps)$ export deepmd_root=/home/yuqinghan/Software/DeePMD-kit/deepmd_root
(lammps)$ export lammps_source_code=/home/yuqinghan/Software/Setup/LAMMPS-setup/lammps
```

### Steps to Reproduce

Then,  I:
```
(lammps)$ cd $deepmd_source_dir
(lammps)$ mkdir build
(lammps)$ cd build
(lammps)$ cmake -DLAMMPS_SOURCE_ROOT=$lammps_source_code -DTENSORFLOW_ROOT=$tensorflow_root
-DCMAKE_INSTALL_PREFIX=$deepmd_root -DUSE_CUDA_TOOLKIT=TRUE
-DCMAKE_CXX_COMPILER=/home/yuqinghan/Systemtools/gcc-7.3.1/bin/gcc
-DCMAKE_C_COMPILER=/home/yuqinghan/Systemtools/gcc-7.3.1/bin/gcc ../
```

The erroe log is:
-- Supported model version: 1.1
-- Found CUDA in /home/yuqinghan/Systemtools/NVIDIA/CUDA/v10.1.2, build nv GPU support
-- Will not build AMD GPU support
-- Enabled cpp interface build, looking for tensorflow_cc and tensorflow_framework
CMake Warning (dev) at cmake/Findtensorflow.cmake:217 (file):
  You have used file(GET_RUNTIME_DEPENDENCIES) in project mode.  This is
  probably not what you intended to do.  Instead, please consider using it in
  an install(CODE) or install(SCRIPT) command.  For example:
\
    install(CODE [[
      file(GET_RUNTIME_DEPENDENCIES
        # ...
        )
      ]])
\
Call Stack (most recent call first):
  CMakeLists.txt:134 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at cmake/Findtensorflow.cmake:280 (message):
  Failed to compile:

   Change Dir: /home/yuqinghan/Software/DeePMD-kit/source/build/tf_version/CMakeFiles/CMakeTmp

  Run Build Command(s):/usr/bin/gmake cmTC_574ec/fast && /usr/bin/gmake -f
  CMakeFiles/cmTC_574ec.dir/build.make CMakeFiles/cmTC_574ec.dir/build

  gmake[1]: Entering directory
  `/home/yuqinghan/Software/DeePMD-kit/source/build/tf_version/CMakeFiles/CMakeTmp'

  Building CXX object CMakeFiles/cmTC_574ec.dir/tf_version.cpp.o

  /home/yuqinghan/Systemtools/gcc-7.3.1/bin/gcc
  -I/home/yuqinghan/anaconda3/envs/lammps/include -o
  CMakeFiles/cmTC_574ec.dir/tf_version.cpp.o -c
  /home/yuqinghan/Software/DeePMD-kit/source/cmake/tf_version.cpp

  Linking CXX executable cmTC_574ec

  /home/yuqinghan/anaconda3/envs/lammps/lib/python3.8/site-packages/cmake/data/bin/cmake
  -E cmake_link_script CMakeFiles/cmTC_574ec.dir/link.txt --verbose=1

  /home/yuqinghan/Systemtools/gcc-7.3.1/bin/gcc
  CMakeFiles/cmTC_574ec.dir/tf_version.cpp.o -o cmTC_574ec

  CMakeFiles/cmTC_574ec.dir/tf_version.cpp.o: In function `main':

  tf_version.cpp:(.text+0x15): undefined reference to `std::cout'

  tf_version.cpp:(.text+0x1a): undefined reference to
  `std::basic_ostream<char, std::char_traits<char> >& std::operator<<
  <std::char_traits<char> >(std::basic_ostream<char, std::char_traits<char>
  \>&, char const*)'

  CMakeFiles/cmTC_574ec.dir/tf_version.cpp.o: In function
  `__static_initialization_and_destruction_0(int, int)':

  tf_version.cpp:(.text+0x48): undefined reference to
  `std::ios_base::Init::Init()'

  tf_version.cpp:(.text+0x57): undefined reference to
  `std::ios_base::Init::~Init()'

  collect2: error: ld returned 1 exit status

  gmake[1]: *** [cmTC_574ec] Error 1

  gmake[1]: Leaving directory
  `/home/yuqinghan/Software/DeePMD-kit/source/build/tf_version/CMakeFiles/CMakeTmp'

  gmake: *** [cmTC_574ec/fast] Error 2

Call Stack (most recent call first):
  CMakeLists.txt:134 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/yuqinghan/Software/DeePMD-kit/source/build/CMakeFiles/CMakeOutput.log"

### Further Information, Files, and Links

The CMakeOutput.log are as follow:
[CMakeOutput.log](https://github.com/deepmodeling/deepmd-kit/files/11452034/CMakeOutput.log)

**Comment by njzjz** [comment]
Please check whether your gcc compiler has the correct configurations for the included path of the standard libraries.

**Comment by Ternity** [comment]
Thank you very much for your reply. This is the returned content after executing the command you provided:

```(lammps) user@/path/to/deepmd_source_dir $ echo | gcc -xc++ -E -v -```
Using built-in specs.
COLLECT_GCC=gcc
Target: x86_64-pc-linux-gnu
Configured with: ../configure --prefix=/home/yuqinghan/Systemtools/gcc-7.3.0 --enable-checking=release --enable-languages=c,c++ --disable-multilib
Thread model: posix
gcc version 7.3.0 (GCC)
COLLECT_GCC_OPTIONS='-E' '-v' '-mtune=generic' '-march=x86-64'
 /home/yuqinghan/Systemtools/gcc-7.3.0/libexec/gcc/x86_64-pc-linux-gnu/7.3.0/cc1plus -E -quiet -v -D_GNU_SOURCE - -mtune=generic -march=x86-64
ignoring nonexistent directory "/home/yuqinghan/Systemtools/gcc-7.3.0/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../x86_64-pc-linux-gnu/include"
#include "..." search starts here:
#include <...> search starts here:
 /opt/intel/compilers_and_libraries_2019.1.144/linux/mkl/include
 /home/yuqinghan/Systemtools/gcc-7.3.0/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../include/c++/7.3.0
 /home/yuqinghan/Systemtools/gcc-7.3.0/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../include/c++/7.3.0/x86_64-pc-linux-gnu
 /home/yuqinghan/Systemtools/gcc-7.3.0/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../include/c++/7.3.0/backward
 /home/yuqinghan/Systemtools/gcc-7.3.0/lib/gcc/x86_64-pc-linux-gnu/7.3.0/include
 /usr/local/include
 /home/yuqinghan/Systemtools/gcc-7.3.0/include
 /home/yuqinghan/Systemtools/gcc-7.3.0/lib/gcc/x86_64-pc-linux-gnu/7.3.0/include-fixed
 /usr/include
End of search list.
\# 1 "\<stdin\>"
\# 1 "\<built-in\>"
\# 1 "\<command-line\>"
\# 1 "/usr/include/stdc-predef.h" 1 3 4
\# 1 "\<command-line\>" 2
\# 1 "\<stdin\>"
COMPILER_PATH=
/home/yuqinghan/Systemtools/gcc-7.3.0/libexec/gcc/x86_64-pc-linux-gnu/7.3.0/:
/home/yuqinghan/Systemtools/gcc-7.3.0/libexec/gcc/x86_64-pc-linux-gnu/7.3.0/:
/home/yuqinghan/Systemtools/gcc-7.3.0/libexec/gcc/x86_64-pc-linux-gnu/:
/home/yuqinghan/Systemtools/gcc-7.3.0/lib/gcc/x86_64-pc-linux-gnu/7.3.0/:
/home/yuqinghan/Systemtools/gcc-7.3.0/lib/gcc/x86_64-pc-linux-gnu/
LIBRARY_PATH=/home/yuqinghan/Systemtools/gcc-7.3.0/lib/gcc/x86_64-pc-linux-gnu/7.3.0/:
/home/yuqinghan/Systemtools/gcc-7.3.0/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../../lib64/:
/lib/../lib64/:
/usr/lib/../lib64/:
/opt/intel/compilers_and_libraries_2019.1.144/linux/mpi/intel64/libfabric/lib/:
/opt/intel/compilers_and_libraries_2019.1.144/linux/tbb/lib/intel64_lin/gcc4.7/:
/opt/intel/compilers_and_libraries_2019.1.144/linux/compiler/lib/intel64_lin/:
/opt/intel/compilers_and_libraries_2019.1.144/linux/mkl/lib/intel64_lin/:
/home/yuqinghan/Systemtools/gcc-7.3.0/lib/gcc/x86_64-pc-linux-gnu/7.3.0/../../../:
/lib/:
/usr/lib/
COLLECT_GCC_OPTIONS='-E' '-v' '-mtune=generic' '-march=x86-64'

**Comment by Ternity** [comment]
Hi，@njzjz! After add 
```DCMAKE_C_COMPILER=/home/yuqinghan/Systemtools/gcc-7.3.1/bin/gcc -DCMAKE_CXX_FLAGS=-L/home/yuqinghan/Systemtools/gcc-7.3.1/lib64 -DCMAKE_EXE_LINKER_FLAGS=-lstdc++```
to cmake command, compilation successfully passed.
Thank you again!
