### ISSUE TITLE
How to run the lammps gpu with the installed Deepmd lammps version.

### ISSUE THREAD

**Issue by Jeremy1189** [deepmodeling/deepmd-kit#2528]
### Summary

Issue origin:  I prepared well the potential model (NiFe.pd) and use it to calculate the vacancy energy barrier with this model. I use the Lammps NEB module to obtain the vacancy energy barrier and it works well under the deepmd-cpu version, which is installed by [ conda create -n deepmd deepmd-kit=*=*cpu libdeepmd=*=*cpu lammps -c https://conda.deepmodeling.com -c defaults]. But the neb module only allows me to use one-image one -processor( eg: though I have 128 core, I have to run it by  mpirun -n 11 lmp -p 11x1 -in inp4.neb > out4), which leads to a very slow speed (8 to 10 hours for obtain a barrier). Thus, I think the lmp gpu-version may have a better speed. 

Issue: After I install the gpu-deemd well by [conda create -n deepmd deepmd-kit=*=*gpu libdeepmd=*=*gpu lammps cudatoolkit=11.6 horovod -c https://conda.deepmodeling.com -c defaults], and change to run as a gpu pattern, but  I find the default install lammps gives a error  as follows:
(deepmd) [jingtchen6@hpclogin02 deepmd]$ mpirun -n 11 -ppn 1 lmp -sk gpu -pk gpu 1 11x1 inp4.neb
ERROR: Invalid command-line argument (src/lammps.cpp:439)

Could anyone help me to solve this problem, or give me some suggestions to accelerate the process for calculating the energy barrier with the DP interatomic potential?

### DeePMD-kit Version

2.1.1

### TensorFlow Version

11.6

### Details

Issue origin:  I prepared well the potential model (NiFe.pd) and use it to calculate the vacancy energy barrier with this model. I use the Lammps NEB module to obtain the vacancy energy barrier and it works well under the deepmd-cpu version, which is installed by [ conda create -n deepmd deepmd-kit=*=*cpu libdeepmd=*=*cpu lammps -c https://conda.deepmodeling.com -c defaults]. But the neb module only allows me to use one-image one -processor( eg: though I have 128 core, I have to run it by  mpirun -n 11 lmp -p 11x1 -in inp4.neb > out4), which leads to a very slow speed (8 to 10 hours for obtain a barrier). Thus, I think the lmp gpu-version may have a better speed. 
Issue: After I install the gpu-deemd well by [conda create -n deepmd deepmd-kit=*=*gpu libdeepmd=*=*gpu lammps cudatoolkit=11.6 horovod -c https://conda.deepmodeling.com -c defaults], and change to run as a gpu pattern, but  I find the default install lammps gives a error  as follows:
(deepmd) [jingtchen6@hpclogin02 deepmd]$ mpirun -n 11 -ppn 1 lmp -sk gpu -pk gpu 1 11x1 inp4.neb
ERROR: Invalid command-line argument (src/lammps.cpp:439)

Could anyone help me to solve this problem, or give me some suggestions to accelerate the process for calculating the energy barrier with the DP interatomic potential?

**Comment by wanghan-iapcm** [comment]
Lammps tells you that the command line argument is invalid. This is not the issue of deepmd-kit.

**Comment by Jeremy1189** [comment]
Dear Dr. Wang, 
Thanks for your reply.
Since the lammps is integrated into the current deepmd-kit, I don't know whether the deepmd-kit's lammps have enabled the GPU package? (I can run this command well by EAM potential with  only lammps GPU pattern )

Jeremy XU
City University of Hong Kong

**Comment by gxm11** [comment]
I think jeremy1189 used the wrong command-line argument '-sk', it should be '-sf'. But I still get the error like:
![image](https://github.com/deepmodeling/deepmd-kit/assets/32235594/8d784f33-4612-4ac2-86d9-c8eab1c6cc66)
Is the lammps in deepmd-kit use the GPU to calculate or not?
