### ISSUE TITLE
Long range electrostatic, charge fitting

### ISSUE THREAD

**Issue by martino95** [deepmodeling/deepmd-kit#255]
Hello

I'm working on a model of nucleotides in water using deepmd. Since the system has many charged atoms I think long range electrostatic effects could play a crucial role. I read some articles presenting NN models with long range electrostatic included using a second NN to predict atomic charges. Playing around with your code I found some classes (DipoleChargeModifier, EwaldRecp, DeepDipole) that seem to be here to do this job. When I saw this lines of code in DeepPot.py:
``` Python
            e, f, v = self.eval_inner(coords, cells, atom_types, fparam = fparam, aparam = aparam, atomic = atomic)
            if self.modifier_type is not None:
                me, mf, mv = self.dm.eval(coords, cells, atom_types)
                e += me.reshape(e.shape)
                f += mf.reshape(f.shape)
                v += mv.reshape(v.shape)
            return e, f, v
```
I thought, wow, everything I need is already implemented.
So the question is: am I right? Or those are just pieces of code not intended to be used and left for future development?
If not how can I train a network to predict charges? What's the input data format? What keywords are needed in the .json model file?

Thank you very much

Kindly

Riccardo

**Comment by amcadmus** [comment]
Dear Riccardo,

You are right, we are actively working on including the long-range electrostatics into the deepmd approach. 

The code is not stable at the moment. We will inform you as soon as the it is ready for productive run.

Best regards,
Han
