### ISSUE TITLE
Will connecting ZBL affect DP's description of equilibrium states

### ISSUE THREAD

**Issue by XuFanffei** [deepmodeling/deepmd-kit#2647]
### Summary

I compared the DP potential of connected ZBL and unconnected ZBL, and found that the energy changes with distance. It was found that the connection of ZBL would change the DP's description of the equilibrium state. What is the method to make ZBL only effective at short distances without affecting the description of the equilibrium state？

### DeePMD-kit Version

2.1.5

### TensorFlow Version

null

### Details

I have seen  ​https://github.com/deepmodeling/deepmd-kit/discussions/1932 and it seems to be the input.json parameter required to connect to ZBL, but I would like to know if connecting to ZBL will affect DP's description of the equilibrium state.
When I connected ZBL, it was possible that I trained ZBL-Tab with other input configurations, which in turn affected the overall energy weight,Is there a way to only add ZBL-Tab in the last step?

**Comment by njzjz** [comment]
> What is the method to make ZBL only effective at short distances without affecting the description of the equilibrium state？

I don't understand why you ask this question. In #1932, `sw_rmax` is set to 0.68, which is obviously a short distance.

**Comment by taol1** [comment]
> > What is the method to make ZBL only effective at short distances without affecting the description of the equilibrium state？
> 
> I don't understand why you ask this question. In #1932, `sw_rmax` is set to 0.68, which is obviously a short distance.

Thank you for your reply

In my input.json, 'sw_rmax' is set to 1.2. 

However, I statically calculated the change in the energy of the two atoms with distance and found that DP without zbl and DP with zbl have different results.
![E-d](https://github.com/deepmodeling/deepmd-kit/assets/127073312/80f0ce51-70a6-496e-bd67-fe1d5e4189ed)

**Comment by wanghan-iapcm** [comment]
please provide the input script of your training, and describe how did you generate the training dataset.

**Comment by taol1** [comment]
![image](https://github.com/deepmodeling/deepmd-kit/assets/127073312/aed8e2d3-75f6-4ff9-aa1a-442850894644)
This is the ZBL-related parameter in my input script.

I removed 19  0,19  1,19  2 from record.dpgen (iter.000019 is the latest iter not connected to zbl), and used the input.json script with the zbl parameter added, using the instruction: nohup dpgen run input.json machine.json

**Comment by wanghan-iapcm** [comment]
from the description it is not clear to me how the configurations are explored in dpgen

**Comment by taol1** [comment]
> from the description it is not clear to me how the configurations are explored in dpgen

Thank you for you reply!

If I add a new set of configurations and add zbl related parameters in input.json, and finish the whole process of 01.model_devi,02.fp,00.train, can I connect ZBL-Tab?

**Comment by njzjz** [comment]
I think #2670 has fixed this issue (or at least #2670 will make the potential to be very strange). Feel free to reopen this issue if the problem still exists.
