### ISSUE TITLE
[BUG] Strange behavior when set `training`/`systems` in input.json

### ISSUE THREAD

**Issue by iProzd** [deepmodeling/deepmd-kit#2656]
### Bug summary

See [#1268](https://github.com/deepmodeling/dpgen/issues/1268) in dpgen.

The user provided the `input.json` in a strange format.
It has both `training`/`systems` and `training`/`training_data`/`systems`, the former is empty. Whatever the latter is, it will unexpectedly choose the empty `training`/`systems`. 

To reproduce the bug, just add `systems`: [] in  `training` scope in example/water/se_e2_a/input.json.

### DeePMD-kit Version

2.2.2

### TensorFlow Version

2.6.0

### How did you download the software?

Offline packages

### Input Files, Running Commands, Error Log, etc.

See above.

### Steps to Reproduce

See above.

**Comment by njzjz** [comment]
`training/systems` is the v1 key. It is an undefined behavior to have v1 and v2 parameters at the same time.
