### ISSUE TITLE
Floating point exception

### ISSUE THREAD

**Issue by JTaozhang** [deepmodeling/deepmd-kit#2668]
### Bug summary

when I use the lammp module of deepmd-kit to do NVT simulation, It always report the out-of-memory bug. The strcuture and input setting files was produced by dpgen during the step3(make_model_devi). However, If I use other structure file, the lammps module can work normally. what is the problem?

### DeePMD-kit Version

deePMD-kit v2.2.2

### TensorFlow Version

tensorflow 2.9.0

### How did you download the software?

Offline packages

### Input Files, Running Commands, Error Log, etc.

**error file1:**
 >>> Info of model(s):
  using   4 model(s): ../graph.000.pb ../graph.001.pb ../graph.003.pb ../graph.002.pb 
  rcut in model:      7
  ntypes in model:    1

CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE

Your simulation uses code contributions which should be cited:
- USER-DEEPMD package:
The log file lists these citations in BibTeX format.

CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE-CITE

Generated 0 of 0 mixed pair_coeff terms from geometric mixing rule
Neighbor list info ...
  update every 1 steps, delay 10 steps, check yes
  max neighbors/atom: 2000, page size: 100000
  master list distance cutoff = 8
  ghost atom cutoff = 8
  binsize = 4, bins = 3 2 7
  1 neighbor lists, perpetual/occasional/extra = 1 0 0
  (1) pair deepmd, perpetual
      attributes: full, newton on
      pair build: full/bin/atomonly
      stencil: full/bin/3d
      bin: standard
Setting up Verlet run ...
  Unit style    : metal
  Current step  : 0
  Time step     : 0.001

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 0 PID 37292 RUNNING AT node235
=   KILLED BY SIGNAL: 9 (Killed)
===================================================================================

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   RANK 1 PID 37293 RUNNING AT node235
=   KILLED BY SIGNAL: 9 (Killed)
===================================================================================

error file2:
DeePMD-kit WARNING: Environmental variable TF_INTRA_OP_PARALLELISM_THREADS is not set. Tune TF_INTRA_OP_PARALLELISM_THREADS for the best performance. See https://deepmd.rtfd.io/parallelism/ for more information.
This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.1 SSE4.2 AVX AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:354] MLIR V1 optimization pass is not enabled
/share/home/zhangtao/anaconda3/envs/deepmd2/bin/lmp: line 11: 37357 Floating point exception/share/home/zhangtao/anaconda3/envs/deepmd2/bin/_lmp "$@"

### Steps to Reproduce

here is the reproduce files, if you could give me some advice, I would greatly appreciate your kind help.

链接：https://pan.baidu.com/s/1Tmo_LMHBGfX-PgFpgJbdvw 
提取码：1230

**Comment by JTaozhang** [comment]
I would like to revise the installation path, I installed the software through conda, not offline.

**Comment by njzjz** [comment]
If you can use GDB to print stack traces, that will be helpful to us. See https://stackoverflow.com/a/2792735/9567349

**Comment by JTaozhang** [comment]
I will test it later, but for now, I don't know whether this code can run on lammps version 2023.06.23-updata4, because I notice your lammps version is that. it also seems that update4 is more stable.

**Comment by njzjz** [comment]
I just added update4 to the conda channel.

**Comment by JTaozhang** [comment]
Hi, I use command "conda create -n deepmd deepmd-kit=*=*gpu libdeepmd=*=*gpu lammps cudatoolkit=11.6 horovod -c https://conda.deepmodeling.com -c defaults"  I didn't see the update4 version in the list. Neither I see it in the cpu version.
![image](https://github.com/deepmodeling/deepmd-kit/assets/125844761/f4d3bc25-00ad-4503-853d-b20b27545a64)

Could you tell me how to install the update4?

**Comment by njzjz** [comment]
Thanks for reminding me. The old build failed, and I rebuilt it.

**Comment by JTaozhang** [comment]
Sorry, I still built the update 1 version directly through command"conda create -n deepmd deepmd-kit=*=gpu libdeepmd==*gpu lammps cudatoolkit=11.6 horovod -c https://conda.deepmodeling.com/ -c defaults", Could you check it again?

**Comment by njzjz** [comment]
Thanks. I fix the issue, and use a new Google Colab environment to confirm the LAMMPS version is `update4`: https://nbviewer.org/gist/njzjz/7e162754c922d65ea16ef3320843c241

**Comment by njzjz** [comment]
I sucessfully reproduce the error when the MPI rank is 2.

There is no error when the MPI rank is 1.
