### ISSUE TITLE
[BUG]  Can't use models from AIS Square

### ISSUE THREAD

**Issue by rschireman** [deepmodeling/deepmd-kit#2718]
### Bug summary

After attempting to use the H2O-DPLR-model in the ASE and LAMMPS (w/ ASE interface), I receive the following error:

`
RuntimeError: model in graph (version 0.0) is incompatible with the model (version 1.1) supported by the current code.See https://deepmd.rtfd.io/compatability/ for details.`

### DeePMD-kit Version

DeePMD-kit v2.2.3.dev1+g61703566

### TensorFlow Version

2.13.0

### How did you download the software?

Built from source

### Input Files, Running Commands, Error Log, etc.

ASE input:

```
from ase import Atoms
from deepmd.calculator import DP

water = Atoms(
    "H2O",
    positions=[(0.7601, 1.9270, 1), (1.9575, 1, 1), (1.0, 1.0, 1.0)],
    cell=[100, 100, 100],
    calculator=DP(model="H2O-SCAN0-model.pb"),
)
print(water.get_potential_energy())
print(water.get_forces())
```

LAMMPS ASE input:
```

from ase.calculators.lammpsrun import LAMMPS
from ase import Atoms
water = Atoms(
    "H2O",
    positions=[(0.7601, 1.9270, 1), (1.9575, 1, 1), (1.0, 1.0, 1.0)],
    cell=[100, 100, 100],
)

parameters = {'pair_style': 'deepmd H2O-DPLR-model.pb',
             'pair_coeff':   '* * O H'}                   
files = ['H2O-DPLR-model.pb']
lammps = LAMMPS(parameters=parameters, files=files, keep_tmp_files=True, tmp_dir='./debug')
water.calc = lammps
print(water.get_potential_energy())
```

### Steps to Reproduce

Link to model: https://www.aissquare.com/models/detail?pageType=models&name=H2O-DPLR-model

**Comment by njzjz** [comment]
For AIS Square issue, please report to https://github.com/deepmodeling/AIS-Square
