### ISSUE TITLE
Unable to successfully install version 2.2.3 via conda

### ISSUE THREAD

**Issue by morethankk** [deepmodeling/deepmd-kit#2733]
### Summary

I tried to install DeepMD-kit by specifeid the DeePMD-kit version 2.2.3 using
`conda create -n deepmd deepmd-kit=2.2.3=*gpu libdeepmd=2.2.3=*gpu lammps cudatoolkit=11.6 -c https://conda.deepmodeling.org`

But the return: 

**PackagesNotFoundError: The following packages are not available from current channels:**

  - deepmd-kit==2.2.3[build=*gpu]
  - libdeepmd==2.2.3[build=*gpu]

Current channels:

  - https://conda.deepmodeling.org/linux-64
  - https://conda.deepmodeling.org/noarch
  - file:///opt/intel/oneapi/conda_channel/linux-64
  - file:///opt/intel/oneapi/conda_channel/noarch
  - https://conda.anaconda.org/intel/linux-64
  - https://conda.anaconda.org/intel/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

However, I actually found the Package at https://anaconda.org. 

### DeePMD-kit Version

2.2.3

### TensorFlow Version

/

### Details

/

**Comment by wanghan-iapcm** [comment]
The conda package will be released next week.

**Comment by morethankk** [comment]
Thanks a lot!

**Comment by njzjz** [comment]
I just returned from a vacation and will update by the end of this week.

**Comment by njzjz** [comment]
Released.

**Comment by morethankk** [comment]
Appreciate！
