### ISSUE TITLE
A error: Assign requires shapes of both tensors to match. lhs shape= [3,664] rhs shape= [3,656]

### ISSUE THREAD

**Issue by linkuixin** [deepmodeling/deepmd-kit#2735]
We've trained our model using a small set of data, and now we want to continue the training after introducing some new data. However, the `dp train --restart` and `dp train --init-model` commands are working just fine when using the original data, but fails when we introduce the new data.

Our traceback error makes it look like the network is trying to change when we introduce the new data:
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [1,720] rhs shape= [1,704]
```
One key difference between datasets is the temperature that simulations were ran at -- but would this lead to new network architectures? If so, is there a way to fix our architecture to prevent this error?

_Originally posted by @jacksund in https://github.com/deepmodeling/deepmd-kit/discussions/1242_

**Comment by linkuixin** [comment]
I'm having this problem, how did  solve it?
I also set sel to auto. if I set sel manually, this error will not happen.

**Comment by wanghan-iapcm** [comment]
As @jacksund has pointed out, you need to use exactly the same sel as your original training. If you used `auto`, please check the actual sel number in the log and write it in the input script used by the new training

BTW. Use a different data set does not make much sense for the `--restart` mode.

**Comment by scott-materials** [comment]
Thanks -- will be interested to know answer.

**Comment by wanghan-iapcm** [comment]
> We were trying to add newly acquired data to our set and then using `--restart` to continue the model training from where we left off. Is that not a normal way to train on a data set that is constantly growing?

when `--restart` is used, the learning rate and training step is set to the value where the old training stopped.  If the old training stopped at a relatively late stage, the learning rate would decay to a small value, and training with new data from such a small learning rate would not be effective. What you want is actually `--init-model`, by which the model parameter is initialized from an old model, and the training procedure is started from the `start_lr` you set in the input script. Note that in this case you may want to use a smaller start learning rate (e.g. 1e-4) to avoid forgetting from the old model.

**Comment by njzjz** [comment]
I find one can do this easily:

```
dp train input.json
dp train out.json --init-model model.ckpt
``

where `out.json` is produced by `dp train` and contains the actual `sel` used by the previous training.
