### ISSUE TITLE
ERROR: Unrecognized pair style 'deepmd' (src/force.cpp:271)

### ISSUE THREAD

**Issue by caolz** [deepmodeling/deepmd-kit#2739]
### Bug summary

lmp -in in.dp
LAMMPS (2 Aug 2023)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (src/comm.cpp:98)
  using 1 OpenMP thread(s) per MPI task
Open of file /home/ustb-clz/software/deepmd-gpu/lib/deepmd_lmp/dpplugin.so failed: /home/ustb-clz/software/deepmd-gpu/lib/deepmd_lmp/dpplugin.so: undefined symbol: MPI_Bcast
Loaded 0 plugins from /home/ustb-clz/software/deepmd-gpu/lib/deepmd_lmp

The 'box' command has been removed and will be ignored

Reading data file ...
  triclinic box = (0 0 0) to (23.504033 20.35509 19.190963) with tilt (11.752017 11.752017 6.7850299)
WARNING: Triclinic box skew is large. LAMMPS will run inefficiently. (src/domain.cpp:220)
  1 by 1 by 1 MPI processor grid
  reading atoms ...
  243 atoms
  read_data CPU = 0.001 seconds
ERROR: Unrecognized pair style 'deepmd' (src/force.cpp:271)
Last command: pair_style     deepmd graph.pb

lmp -h
~/deepmd-gpu/bin/lmp: line 11: 313091 Segmentation fault      (core dumped) ~/deepmd-gpu/bin/_lmp "$@"

### DeePMD-kit Version

2.2.3

### TensorFlow Version

\

### How did you download the software?

Others (write below)

### Input Files, Running Commands, Error Log, etc.

I installed the CPU and GPU versions using conda, and installed the GPU version offline. Ran into the same problem.

### Steps to Reproduce

\

**Comment by njzjz** [comment]
It should be fixed now: https://nbviewer.org/gist/njzjz/97d9440bb77b25c15579d350b4eefa11
