### ISSUE TITLE
Going through difficulties on DeePMDKIT and LAMMPS installation

### ISSUE THREAD

**Issue by jaejae9804** [deepmodeling/deepmd-kit#2745]
### Bug summary

I've installed DeepMDKIT cpu version and also installed LAMMPS built-in mode according to the installation documentations. During doing so, Ive installed virtual enviroment with tensorflow(2.4 ver.) and python (3.8 ver.). After doing all that, the compilation of LAMMPS and DeepMDKIT was done and Ive got this execution file named "lmp_cmse_deepmd". So, I can run MD with LAMMPS using DeepMD made potentials by running "lmp_cmse_deepmd -i input.script". But, Ive encountered errors which I cannot fix. The error is as follows.

(tf24) mesiya9804@1gbmaster:~/1$lmp_cmse_deepmd -i in.meam

LAMMPS (2 Aug 2023)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (../comm.cpp:98)
using 1 OpenMP thread(s) per MPI task
Reading data file ...
orthogonal box = (0 0 0) to (100 100 100)
1 by 1 by 1 MPI processor grid
reading atoms ...
74978 atoms
read_data CPU = 0.330 seconds
DeePMD-kit WARNING: Environmental variable TF_INTRA_OP_PARALLELISM_THREADS is not set. Tune TF_INTRA_OP_PARALLELISM_THREADS for the best performance. See https://deepmd.rtfd.io/parallelism/ for more information.
DeePMD-kit WARNING: Environmental variable TF_INTER_OP_PARALLELISM_THREADS is not set. Tune TF_INTER_OP_PARALLELISM_THREADS for the best performance. See https://deepmd.rtfd.io/parallelism/ for more information.
DeePMD-kit WARNING: Environmental variable OMP_NUM_THREADS is not set. Tune OMP_NUM_THREADS for the best performance. See https://deepmd.rtfd.io/parallelism/ for more information.
Summary of lammps deepmd module ...

Info of deepmd-kit:
installed to:
source: v2.2.2-85-g53a1078
source branch: master
source commit: 53a1078
source commit at: 2023-08-08 11:52:54 +0800
surpport model ver.:1.1
build variant: cpu
build with tf inc: /home/mesiya9804/anaconda3/envs/tf24/lib/python3.8/site-packages/tensorflow/include;/home/mesiya9804/anaconda3/envs/tf24/lib/python3.8/site-packages/tensorflow/include
build with tf lib: /home/mesiya9804/anaconda3/envs/tf24/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
set tf intra_op_parallelism_threads: 0
set tf inter_op_parallelism_threads: 0
Info of lammps module:
use deepmd-kit at:
source: v2.2.2-85-g53a1078
source branch: master
source commit: 53a1078
source commit at: 2023-08-08 11:52:54 +0800
build float prec: double
build with tf inc: /home/mesiya9804/anaconda3/envs/tf24/lib/python3.8/site-packages/tensorflow/include;/home/mesiya9804/anaconda3/envs/tf24/lib/python3.8/site-packages/tensorflow/include
build with tf lib: /home/mesiya9804/anaconda3/envs/tf24/lib/python3.8/site-packages/tensorflow/libtensorflow_cc.so.2
DeePMD-kit WARNING: Environmental variable TF_INTRA_OP_PARALLELISM_THREADS is not set. Tune TF_INTRA_OP_PARALLELISM_THREADS for the best performance. See https://deepmd.rtfd.io/parallelism/ for more information.
DeePMD-kit WARNING: Environmental variable TF_INTER_OP_PARALLELISM_THREADS is not set. Tune TF_INTER_OP_PARALLELISM_THREADS for the best performance. See https://deepmd.rtfd.io/parallelism/ for more information.
DeePMD-kit WARNING: Environmental variable OMP_NUM_THREADS is not set. Tune OMP_NUM_THREADS for the best performance. See https://deepmd.rtfd.io/parallelism/ for more information.
2023-08-15 22:36:02.558450: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations: AVX512F
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-15 22:36:02.601489: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:196] None of the MLIR optimization passes are enabled (registered 0 passes)
Segmentation fault (core dumped)

Ive tried reading the https://deepmd.rtfd.io/parallelism/ docs to dianose the problem, but it seems that the parallelism of the job is not what causes the problem. Should the version of the tensorflow be of a problem? Any help will be greatly appreciated.

### DeePMD-kit Version

DeePMD-kit v2.2.3.dev85+g53a1078

### TensorFlow Version

2.4

### How did you download the software?

Built from source

### Input Files, Running Commands, Error Log, etc.

LAMMPS (2 Aug 2023)
OMP_NUM_THREADS environment is not set. Defaulting to 1 thread. (../comm.cpp:98)
using 1 OpenMP thread(s) per MPI task
Reading data file ...
orthogonal box = (0 0 0) to (100 100 100)
1 by 1 by 1 MPI processor grid
reading atoms ...
74978 atoms
read_data CPU = 0.330 seconds
DeePMD-kit WARNING: Environmental variable TF_INTRA_OP_PARALLELISM_THREADS is not set. Tune TF_INTRA_OP_PARALLELISM_THREADS for the best performance. See https://deepmd.rtfd.io/parallelism/ for more information.
DeePMD-kit WARNING: Environmental variable TF_INTER_OP_PARALLELISM_THREADS is not set. Tune TF_INTER_OP_PARALLELISM_THREADS for the best performance. See https://deepmd.rtfd.io/parallelism/ for more information.
DeePMD-kit WARNING: Environmental variable OMP_NUM_THREADS is not set. Tune OMP_NUM_THREADS for the best performance. See https://deepmd.rtfd.io/parallelism/ for more information.
Summary of lammps deepmd module ...

Info of deepmd-kit:
installed to:
source: v2.2.2-85-g53a1078
source branch: master
source commit: 53a1078
source commit at: 2023-08-08 11:52:54 +0800
surpport model ver.:1.1
build variant: cpu
build with tf inc: /home/mesiya9804/anaconda3/envs/tf24/lib/python3.8/site-packages/tensorflow/include;/home/mesiya9804/anaconda3/envs/tf24/lib/python3.8/site-packages/tensorflow/include
build with tf lib: /home/mesiya9804/anaconda3/envs/tf24/lib/python3.8/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
set tf intra_op_parallelism_threads: 0
set tf inter_op_parallelism_threads: 0
Info of lammps module:
use deepmd-kit at:
source: v2.2.2-85-g53a1078
source branch: master
source commit: 53a1078
source commit at: 2023-08-08 11:52:54 +0800
build float prec: double
build with tf inc: /home/mesiya9804/anaconda3/envs/tf24/lib/python3.8/site-packages/tensorflow/include;/home/mesiya9804/anaconda3/envs/tf24/lib/python3.8/site-packages/tensorflow/include
build with tf lib: /home/mesiya9804/anaconda3/envs/tf24/lib/python3.8/site-packages/tensorflow/libtensorflow_cc.so.2
DeePMD-kit WARNING: Environmental variable TF_INTRA_OP_PARALLELISM_THREADS is not set. Tune TF_INTRA_OP_PARALLELISM_THREADS for the best performance. See https://deepmd.rtfd.io/parallelism/ for more information.
DeePMD-kit WARNING: Environmental variable TF_INTER_OP_PARALLELISM_THREADS is not set. Tune TF_INTER_OP_PARALLELISM_THREADS for the best performance. See https://deepmd.rtfd.io/parallelism/ for more information.
DeePMD-kit WARNING: Environmental variable OMP_NUM_THREADS is not set. Tune OMP_NUM_THREADS for the best performance. See https://deepmd.rtfd.io/parallelism/ for more information.
2023-08-15 22:36:02.558450: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations: AVX512F
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-08-15 22:36:02.601489: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:196] None of the MLIR optimization passes are enabled (registered 0 passes)
Segmentation fault (core dumped)

### Steps to Reproduce

have none yet..

**Comment by njzjz** [comment]
It will be helpful if you provide an example for reproducing.

**Comment by njzjz** [comment]
Close, as no more information is given to reproduce the issue.
