### ISSUE TITLE
Why is the ckpt.meta file not generated during the train process using deepmd?

### ISSUE THREAD

**Issue by XuFanffei** [deepmodeling/deepmd-kit#2761]
### Summary

The training process uses the official image of the Bohrium platform，there should be no errors during model training.

### DeePMD-kit Version

Deepmd-kit:2.2.1-cuda.11.6

### TensorFlow Version

2.9.0

### Details

The training process uses the official image of the Bohrium platform，there should be no errors during model training.

**Comment by wanghan-iapcm** [comment]
please post your input script and command so others can reproduce the issue

**Comment by lzcun** [comment]
[machine.txt](https://github.com/deepmodeling/deepmd-kit/files/12471507/machine.txt)
[run_param.txt](https://github.com/deepmodeling/deepmd-kit/files/12471513/run_param.txt)
aboves are scripts of my job, and the input command is:
`nohup dpgen run run_param.json machine.json > job.out 2>&1 &`

**Comment by wanghan-iapcm** [comment]
from the provided input script I do not see the problem.
Could you please restore the training environment and try to reproduce the issue?

**Comment by lzcun** [comment]
Actually, all the jobs I have down in this  training environment, don't have ckpt.meta files.

**Comment by njzjz** [comment]
@lzcun you leaked passwords in the attached file. I removed that file and please reset the password for security.

**Comment by njzjz** [comment]
I'll close the issue since it cannot be reproduced.
