### ISSUE TITLE
Compress a model

### ISSUE THREAD

**Issue by keke-Song** [deepmodeling/deepmd-kit#2762]
### Summary

Both my embedding network and fitting network use a single layer:    descriptor[50]  ,fitting_net[100], When we compress the model, there will be this error：dargs.dargs.ArgumentKeyError: [at location `model`] undefined key `srtab_add_bias` is not allowed in strict mode.

### Detailed Description

DEEPMD INFO    training data with min nbor dist: 0.5542080596937582
DEEPMD INFO    training data with max nbor size: [143 305]
DEEPMD INFO     _____               _____   __  __  _____           _     _  _   
DEEPMD INFO    |  __ \             |  __ \ |  \/  ||  __ \         | |   (_)| |  
DEEPMD INFO    | |  | |  ___   ___ | |__) || \  / || |  | | ______ | | __ _ | |_ 
DEEPMD INFO    | |  | | / _ \ / _ \|  ___/ | |\/| || |  | ||______|| |/ /| || __|
DEEPMD INFO    | |__| ||  __/|  __/| |     | |  | || |__| |        |   < | || |_ 
DEEPMD INFO    |_____/  \___| \___||_|     |_|  |_||_____/         |_|\_\|_| \__|
DEEPMD INFO    Please read and cite:
DEEPMD INFO    Wang, Zhang, Han and E, Comput.Phys.Comm. 228, 178-184 (2018)
DEEPMD INFO    Zeng et al, J. Chem. Phys., 159, 054801 (2023)
DEEPMD INFO    See https://deepmd.rtfd.io/credits/ for details.
DEEPMD INFO    installed to:         /home/conda/feedstock_root/build_artifacts/deepmd-kit_1691718166888/work/_skbuild/linux-x86_64-3.10/cmake-install
DEEPMD INFO    source :              v2.2.3
DEEPMD INFO    source brach:         HEAD
DEEPMD INFO    source commit:        53a1078c
DEEPMD INFO    source commit at:     2023-08-08 11:52:54 +0800
DEEPMD INFO    build float prec:     double
DEEPMD INFO    build variant:        cuda
DEEPMD INFO    build with tf inc:    /fs1/home/ustbyjsu/app/dpmd-2.2.3/lib/python3.10/site-packages/tensorflow/include/;/fs1/home/ustbyjsu/app/dpmd-2.2.3/include
DEEPMD INFO    build with tf lib:    
DEEPMD INFO    ---Summary of the training---------------------------------------
DEEPMD INFO    running on:           gsn1
DEEPMD INFO    computing device:     gpu:0
DEEPMD INFO    CUDA_VISIBLE_DEVICES: 0
DEEPMD INFO    Count of visible GPU: 1
DEEPMD INFO    num_intra_threads:    0
DEEPMD INFO    num_inter_threads:    0
DEEPMD INFO    -----------------------------------------------------------------
DEEPMD INFO    ---Summary of DataSystem: training     -----------------------------------------------
DEEPMD INFO    found 237 system(s):

**Comment by keke-Song** [comment]
solved

**Comment by keke-Song** [comment]
Even with a 3-layer neural network, there will be this error

**Comment by njzjz** [comment]
Could you paste the entire output?

**Comment by keke-Song** [comment]
Maybe the path is written wrong
