### ISSUE TITLE
Cannot install phonolammps on dplmp

### ISSUE THREAD

**Issue by XuFanffei** [deepmodeling/deepmd-kit#2765]
### Summary

I have referred to the following tutorial
https://zhuanlan.zhihu.com/p/509763344

### DeePMD-kit Version

null

### TensorFlow Version

null

### Details

It should be that dp lmp has not been modularized by Python

**Comment by smismyname** [comment]
DeePMD-kit Version  V2.1.1
Python Version 3.10.11

**Comment by smismyname** [comment]
![image](https://github.com/deepmodeling/deepmd-kit/assets/62820385/1bdef424-9273-4512-a981-eb46849ced27)

**Comment by njzjz** [comment]
How did you install the LAMMPS?

**Comment by smismyname** [comment]
I didn't install others LAMMPS,the LAMMPS is dp' s lmp.

**Comment by smismyname** [comment]
![image](https://github.com/deepmodeling/deepmd-kit/assets/62820385/e1c13a94-dbf7-48d4-89ad-1b28d0479342)

**Comment by njzjz** [comment]
Please use a newer version. I don't think v2.1.1 is compatible with LAMMPS 2 Aug 2023.

**Comment by smismyname** [comment]
ok，thanks，I'll try it.

**Comment by njzjz** [comment]
Feel free to reopen if the problem still exists. Thank you.
