### ISSUE TITLE
TypeError: expected str, bytes or os.Pathlike object, not NoneType

### ISSUE THREAD

**Issue by XuFanffei** [deepmodeling/deepmd-kit#2767]
### Summary

I want to use the “dp train init-model.json --init-model [model.ckpt.index”](url) instruction to improve my model, but this error occurred：
TypeError: expected str, bytes or os.Pathlike object, not NoneType
[init-model.json.zip](https://github.com/deepmodeling/deepmd-kit/files/12462207/init-model.json.zip)

### DeePMD-kit Version

deepmd-kit-2.1.5

### TensorFlow Version

2.9.0

### Details

[err.zip](https://github.com/deepmodeling/deepmd-kit/files/12462498/err.zip)

**Comment by njzjz** [comment]
The correct argument is `--init-model model.ckpt`.

**Comment by taol1** [comment]
> The correct argument is `--init-model model.ckpt`.

Thank you for your reply!

I use this directive: dp train --init-model model.ckpt.index init-model.json, and still report: TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by njzjz** [comment]
The checkpoint should be `model.ckpt` instead of `model.ckpt.index`.

**Comment by taol1** [comment]
> The checkpoint should be `model.ckpt` instead of `model.ckpt.index`.

![image](https://github.com/deepmodeling/deepmd-kit/assets/127073312/0d74d5ee-f671-476e-bd0d-7ee466125ce0)

My 00.train/000/ directory is constructed as shown in the figure,  no model.ckpt file.
