### ISSUE TITLE
Encountered this issue while running DP on GPU nodes: When there is only one task (each task calls one GPU card), the training duration is approximately 1.47s/100 steps When there are two independent tasks at the same time (each calling one GPU card), the training duration for each task is 2.54s/100 steps

### ISSUE THREAD

**Issue by XuFanffei** [deepmodeling/deepmd-kit#2786]
### Bug summary

Encountered this issue while running DP on GPU nodes:
When there is only one task (each task calls one GPU card), the training duration is approximately 1.47s/100 steps
When there are two independent tasks at the same time (each calling one GPU card), the training duration for each task is 2.54s/100 steps
According to the document settings on the official website：
export OMP_NUM_THREADS=1
export TF_INTRA_OP_PARALLELISM_THREADS=1
export TF_INTER_OP_PARALLELISM_THREADS=1
The test files have exceeded the upload limit. If you need these files, you can contact me

### DeePMD-kit Version

deepmd-kit:2.2.3-cuda11.6

### TensorFlow Version

2.5.0

### How did you download the software?

Offline packages

### Input Files, Running Commands, Error Log, etc.

The test files have exceeded the upload limit. If you need these files, you can contact me

### Steps to Reproduce

 have been having this issue before, so I wonder if there are any other parameters. Deepmd kit's 11.2 (which should be this) is about the efficiency of parallel training, which includes these parameter settings. I think running multiple tasks at the same time may also require settings, so refer to the settings. But as a result, it's the same whether it's set or not

**Comment by DingChangjie** [comment]
It is very likely that you've faced the same problem as I did. Please refer to this discussion: https://github.com/deepmodeling/deepmd-kit/discussions/2004. Basically, this problem is related to your running environment, thus some environment varaibles should be set properly.

**Comment by FenixQian** [comment]
Thanks for your reply! Indeed, the weirdest thing I found was that I submitted the jobs using the **SLURM** management system, which was set to use only 1 GPU card and 1 CPU core per job. So in theory, the issue that each job takes up more than one CPU cores shouldn't happen.
Besides, I tried to set the environment variable `export KMP_AFFINITY=scatter` just now, but the issue remained. The commands `top` and `nvidia-smi` were used to see CPU and GPU loading during training respectively. When only one job was running, one GPU card usage was about 55% and one CPU core usage was about 133%. However, when two jobs were running, not only each GPU card usage decreased to 33%, but also each CPU core usage decreased to 71%.

**Comment by DingChangjie** [comment]
> Thanks for your reply! I tried to set the environment variable `export KMP_AFFINITY=scatter` just now, but the issue remained. The commands `top` and `nvidia-smi` were used to see CPU and GPU loading during training respectively. When only one job was running, one GPU card usage was about 55% and one CPU core usage was about 133%. However, when two independent jobs were running, not only each GPU card usage decreased to 33%, but also each CPU core usage decreased to 71%. Each job was set to use only 1 GPU card and 1 CPU core by **SLURM** system. Indeed, the weirdest thing I found was that, the jobs were submitted by **SLURM** system, which was set to use only 1 GPU card and 1 CPU core per job. So in theory, the issue that each job takes up more than one CPU cores shouldn't happen.

It is indeed weird. In theory SLURM system should be able to assign CPU and GPU resources properly... My method is only a workaround on a single machine or node (like a workstation)
PS: you can also force the threads be bounded to CPU cores by something like `export KMP_AFFINITY="explicit,proclist=[0]`

**Comment by njzjz** [comment]
Slurm does have an affinity plugin and configuration. See https://slurm.schedmd.com/mc_support.html. Please check whether it has been configured correctly or consult your cluster administrator.

**Comment by njzjz** [comment]
Feel free to reopen if the problem still exists. Thank you.
