### ISSUE TITLE
new compiler error after open kspace and kokkos: Force has no member named 'bounds'

### ISSUE THREAD

**Issue by leiwang1989** [deepmodeling/deepmd-kit#287]
../pair_nnp.cpp: In member function ‘virtual void LAMMPS_NS::PairNNP::coeff(int, char**)’:
../pair_nnp.cpp:819:12: error: ‘class LAMMPS_NS::Force’ has no member named ‘bounds’
     force->bounds(FLERR,arg[0],atom->ntypes,ilo,ihi);
            ^
../pair_nnp.cpp:820:12: error: ‘class LAMMPS_NS::Force’ has no member named ‘bounds’
     force->bounds(FLERR,arg[1],atom->ntypes,jlo,jhi);

**Comment by njzjz** [comment]
We have noticed that the latest LAMMPS changed some APIs. We are investigating this issue.
Please downgrade LAMMPS to 3Mar2020.

**Comment by leiwang1989** [comment]
I see, thanks.

**Comment by leiwang1989** [comment]
Previous Lammps works. I never used DP potential before, but it seems very slow compared to EAM?  openmp seems work but not MPI.

**Comment by njzjz** [comment]
> Previous Lammps works. I never used DP potential before, but it seems very slow compared to EAM? openmp seems work but not MPI.

For training, only openmp works; for MD simulations, both MPI and openmp are avaiable.
