### ISSUE TITLE
The following error occurs when I use the dp compress command. By upgrading the numpy library operation, it still reported an error. Ask for help

### ISSUE THREAD

**Issue by 12jscvb** [deepmodeling/deepmd-kit#2962]
![2023-10-30 (9)](https://github.com/deepmodeling/dpgen/assets/145745956/4017da12-67dd-4583-982a-ce295d112a1d)

**Comment by njzjz** [comment]
The compatibility with NumPy 1.26 has been added in #2853. (released in v2.2.5)

**Comment by 12jscvb** [comment]
> The compatibility with NumPy 1.26 has been added in #2853. (released in v2.2.5)

Thank you for your help. I have succeeded in solving the problem
