### ISSUE TITLE
ERROR: Could not build wheels for deepmd-kit, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by zhourunyu** [deepmodeling/deepmd-kit#2977]
### Bug summary

Error occurs when using "pip install ." to install the DeepMD-kit under the directory of source code

### DeePMD-kit Version

N/A

### TensorFlow Version

2.12.0

### How did you download the software?

Built from source

### Input Files, Running Commands, Error Log, etc.

N/A

### Steps to Reproduce

Following the tutorial here: https://docs.deepmodeling.com/projects/deepmd/en/master/install/install-from-source.html. The error arises when I try to install DeepMD-kit

### Further Information, Files, and Links

All error messages：
(tf) (myenv) [gao@node116 deepmd-kit]$ pip install -i https://pypi.tuna.tsinghua.edu.cn/simple/ .
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/
Processing /home/gao/software/deepmd-kit/deepmd-kit
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy in /home/gao/myenv/lib/python3.9/site-packages (from deepmd-kit==2.2.8.dev0+g839f4fe.d20231106) (1.23.5)
Requirement already satisfied: scipy in /home/gao/myenv/lib/python3.9/site-packages (from deepmd-kit==2.2.8.dev0+g839f4fe.d20231106) (1.11.3)
Collecting pyyaml (from deepmd-kit==2.2.8.dev0+g839f4fe.d20231106)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/7d/39/472f2554a0f1e825bd7c5afc11c817cd7a2f3657460f7159f691fbb37c51/PyYAML-6.0.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (738 kB)
Collecting dargs>=0.4.1 (from deepmd-kit==2.2.8.dev0+g839f4fe.d20231106)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/41/75/9fced67e5f2ef47df23df1a7f456403e47c90464ac11fb890198a726ba6f/dargs-0.4.3-py3-none-any.whl (18 kB)
Collecting python-hostlist>=1.21 (from deepmd-kit==2.2.8.dev0+g839f4fe.d20231106)
  Using cached python_hostlist-1.23.0-py3-none-any.whl
Requirement already satisfied: h5py in /home/gao/myenv/lib/python3.9/site-packages (from deepmd-kit==2.2.8.dev0+g839f4fe.d20231106) (3.10.0)
Collecting wcmatch (from deepmd-kit==2.2.8.dev0+g839f4fe.d20231106)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/6d/45/563267247f0b6f7c0f8028ab92bf1664da26179a630f863933033d74ab75/wcmatch-8.5-py3-none-any.whl (39 kB)
Requirement already satisfied: packaging in /home/gao/myenv/lib/python3.9/site-packages (from deepmd-kit==2.2.8.dev0+g839f4fe.d20231106) (23.2)
Collecting typeguard>=4 (from dargs>=0.4.1->deepmd-kit==2.2.8.dev0+g839f4fe.d20231106)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/18/01/5fc45558268ced46d86292763477996a3cdd505567cd590a688e8cdc386e/typeguard-4.1.5-py3-none-any.whl (34 kB)
Collecting bracex>=2.1.1 (from wcmatch->deepmd-kit==2.2.8.dev0+g839f4fe.d20231106)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/2b/f5/8f99837b32e2badc189382774dbe6227fa01e1e928a7eff857fdc89d8a75/bracex-2.4-py3-none-any.whl (11 kB)
Requirement already satisfied: importlib-metadata>=3.6 in /home/gao/myenv/lib/python3.9/site-packages (from typeguard>=4->dargs>=0.4.1->deepmd-kit==2.2.8.dev0+g839f4fe.d20231106) (6.8.0)
Requirement already satisfied: typing-extensions>=4.7.0 in /home/gao/myenv/lib/python3.9/site-packages (from typeguard>=4->dargs>=0.4.1->deepmd-kit==2.2.8.dev0+g839f4fe.d20231106) (4.8.0)
Requirement already satisfied: zipp>=0.5 in /home/gao/myenv/lib/python3.9/site-packages (from importlib-metadata>=3.6->typeguard>=4->dargs>=0.4.1->deepmd-kit==2.2.8.dev0+g839f4fe.d20231106) (3.17.0)
Building wheels for collected packages: deepmd-kit
  Building wheel for deepmd-kit (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for deepmd-kit (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [133 lines of output]
      WARNING setuptools_scm.git git too old -> timestamp is '%cI'
      *** scikit-build-core 0.5.1 using CMake 3.17.5 (wheel)
      *** Configuring CMake...
      2023-11-06 03:20:03,745 - scikit_build_core - WARNING - libdir/ldlibrary: /home/gao/software/Anaconda/ANACONDA2022/envs/tf/lib/libpython3.9.a is not a real file!
      2023-11-06 03:20:03,745 - scikit_build_core - WARNING - Can't find a Python library, got libdir=/home/gao/software/Anaconda/ANACONDA2022/envs/tf/lib, ldlibrary=libpython3.9.a, multiarch=x86_64-linux-gnu, masd=None
      loading initial cache file build/py37-none-manylinux_2_17_x86_64/CMakeInit.txt
      -- Supported model version: 1.1
      -- Will not build nv GPU support
      -- Will not build AMD GPU support
      -- Disabled cpp interface build, looking for tensorflow_framework
      CMake Warning (dev) at cmake/Findtensorflow.cmake:234 (file):
        You have used file(GET_RUNTIME_DEPENDENCIES) in project mode.  This is
        probably not what you intended to do.  Instead, please consider using it in
        an install(CODE) or install(SCRIPT) command.  For example:
      
          install(CODE [[
            file(GET_RUNTIME_DEPENDENCIES
              # ...
              )
            ]])
      Call Stack (most recent call first):
        CMakeLists.txt:147 (find_package)
      This warning is for project developers.  Use -Wno-dev to suppress it.
      
      -- Found TensorFlow: /home/gao/myenv/lib/python3.9/site-packages/tensorflow/include;/home/gao/myenv/lib/python3.9/site-packages/tensorflow/include, , /home/gao/myenv/lib/python3.9/site-packages/tensorflow/libtensorflow_framework.so.2  in /home/gao/myenv/lib/python3.9/site-packages/tensorflow;/home/gao/myenv/lib/python3.9/site-packages/tensorflow/../tensorflow_core (found version "2.12.0")
      CMake Warning at cmake/Findtensorflow.cmake:374 (message):
        Output with _GLIBCXX_USE_CXX11_ABI=0:Change Dir:
        /home/gao/software/deepmd-kit/deepmd-kit/build/py37-none-manylinux_2_17_x86_64/tf_cxx_abi0/CMakeFiles/CMakeTmp
      
      
      
      
        Run Build
        Command(s):/tmp/pip-build-env-s8r1epgt/normal/lib/python3.9/site-packages/ninja/data/bin/ninja
        cmTC_ffb82 && [1/2] Building CXX object
        CMakeFiles/cmTC_ffb82.dir/test_cxx_abi.cpp.o
      
        [2/2] Linking CXX executable cmTC_ffb82
      
        FAILED: cmTC_ffb82
      
        : && /opt/rh/devtoolset-9/root/usr/bin/c++
        CMakeFiles/cmTC_ffb82.dir/test_cxx_abi.cpp.o -o cmTC_ffb82
        -Wl,-rpath,/home/gao/myenv/lib/python3.9/site-packages/tensorflow
        /home/gao/myenv/lib/python3.9/site-packages/tensorflow/libtensorflow_framework.so.2
        && :
      
        /opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld:
        CMakeFiles/cmTC_ffb82.dir/test_cxx_abi.cpp.o: in function `main':
      
        test_cxx_abi.cpp:(.text+0x3e): undefined reference to
        `tsl::strings::StrCat(tsl::strings::AlphaNum const&, tsl::strings::AlphaNum
        const&)'
      
        /opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld:
        CMakeFiles/cmTC_ffb82.dir/test_cxx_abi.cpp.o: in function `std::string*
        tsl::internal::MakeCheckOpString<long, int>(long const&, int const&, char
        const*)':
      
      
        test_cxx_abi.cpp:(.text._ZN3tsl8internal17MakeCheckOpStringIliEEPSsRKT_RKT0_PKc[_ZN3tsl8internal17MakeCheckOpStringIliEEPSsRKT_RKT0_PKc]+0x6c):
        undefined reference to `tsl::internal::CheckOpMessageBuilder::NewString()'
      
        collect2: error: ld returned 1 exit status
      
        ninja: build stopped: subcommand failed.
      
      
      
      Call Stack (most recent call first):
        CMakeLists.txt:147 (find_package)
      
      
      CMake Warning at cmake/Findtensorflow.cmake:376 (message):
        Output with _GLIBCXX_USE_CXX11_ABI=1:Change Dir:
        /home/gao/software/deepmd-kit/deepmd-kit/build/py37-none-manylinux_2_17_x86_64/tf_cxx_abi1/CMakeFiles/CMakeTmp
      
      
      
      
        Run Build
        Command(s):/tmp/pip-build-env-s8r1epgt/normal/lib/python3.9/site-packages/ninja/data/bin/ninja
        cmTC_9f97c && [1/2] Building CXX object
        CMakeFiles/cmTC_9f97c.dir/test_cxx_abi.cpp.o
      
        [2/2] Linking CXX executable cmTC_9f97c
      
        FAILED: cmTC_9f97c
      
        : && /opt/rh/devtoolset-9/root/usr/bin/c++
        CMakeFiles/cmTC_9f97c.dir/test_cxx_abi.cpp.o -o cmTC_9f97c
        -Wl,-rpath,/home/gao/myenv/lib/python3.9/site-packages/tensorflow
        /home/gao/myenv/lib/python3.9/site-packages/tensorflow/libtensorflow_framework.so.2
        && :
      
        /opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld:
        CMakeFiles/cmTC_9f97c.dir/test_cxx_abi.cpp.o: in function `main':
      
        test_cxx_abi.cpp:(.text+0x3e): undefined reference to
        `tsl::strings::StrCat(tsl::strings::AlphaNum const&, tsl::strings::AlphaNum
        const&)'
      
        /opt/rh/devtoolset-9/root/usr/libexec/gcc/x86_64-redhat-linux/9/ld:
        CMakeFiles/cmTC_9f97c.dir/test_cxx_abi.cpp.o: in function `std::string*
        tsl::internal::MakeCheckOpString<long, int>(long const&, int const&, char
        const*)':
      
      
        test_cxx_abi.cpp:(.text._ZN3tsl8internal17MakeCheckOpStringIliEEPSsRKT_RKT0_PKc[_ZN3tsl8internal17MakeCheckOpStringIliEEPSsRKT_RKT0_PKc]+0x6c):
        undefined reference to `tsl::internal::CheckOpMessageBuilder::NewString()'
      
        collect2: error: ld returned 1 exit status
      
        ninja: build stopped: subcommand failed.
      
      
      
      Call Stack (most recent call first):
        CMakeLists.txt:147 (find_package)
      
      
      CMake Error at cmake/Findtensorflow.cmake:378 (message):
        Both _GLIBCXX_USE_CXX11_ABI=0 and 1 do not work.  The reason may be that
        your C++ compiler (e.g.  Red Hat Developer Toolset) does not support the
        custom cxx11 abi flag.  Please check the above outputs.
      Call Stack (most recent call first):
        CMakeLists.txt:147 (find_package)
      
      
      -- Configuring incomplete, errors occurred!
      See also "/home/gao/software/deepmd-kit/deepmd-kit/build/py37-none-manylinux_2_17_x86_64/CMakeFiles/CMakeOutput.log".
      
      *** CMake configuration failed
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for deepmd-kit
Failed to build deepmd-kit
ERROR: Could not build wheels for deepmd-kit, which is required to install pyproject.toml-based projects

**Comment by njzjz** [comment]
See #2023.

xref: https://github.com/tensorflow/tensorflow/issues/5179
