### ISSUE TITLE
Request for input interface suitable for databases with inconstant atom number.

### ISSUE THREAD

**Issue by permissionx** [deepmodeling/deepmd-kit#300]
Seems present interface doesn't  allow the atom number change in the input .raw files. Is it possible to modify the input rule for the situations that atom number varies between frames?

**Comment by njzjz** [comment]
This rule is for performance. You can divided your data into different directory (i.e. different systems). `systems` parameter can be a list.
An example here: https://doi.org/10.6084/m9.figshare.12973055

**Comment by permissionx** [comment]
Appreciate that.
