### ISSUE TITLE
Request for specification of the the element sequence as well as the unit of the virial matrix.

### ISSUE THREAD

**Issue by permissionx** [deepmodeling/deepmd-kit#301]
Some people used to set the virial matrix element sequence as {xx yy zz xy xz yz ...}, and others prefer {xx xy xz yx yy yz ...}. Users may not be sure which order you used in this kit.
Likewise, the units of the **A^3*bar** or the **eV**  for virial quantify are both in common use, for which I think the unit need to be give out clearly.

**Comment by njzjz** [comment]
Resolved by #468.
