### ISSUE TITLE
calculate the thermal conductivity

### ISSUE THREAD

**Issue by Suyoung999999999** [deepmodeling/deepmd-kit#3012]
### Summary

Hello, I use the training potential provided in the literature to repeat the results （R. Li et al. / Materials Today Physics 12 (2020) 100181）. The training potential in the literature is an old version, and I converted it with dp convert auto, but I did not get the results in the literature. Did I lose some potential function information during the conversion?
[Uploading potential-convert.zip…]()

### DeePMD-kit Version

2.2.2

### TensorFlow Version

2.2.2

### Details

I used EMD+Deepmd method to calculate the thermal conductivity of single crystal Si structure. Although the number of independent simulations reached dozens of times, the current results were far from the theoretical value. For this reason, I think it is possible that the potential function has a problem in the conversion process, but do not rule out the problem of the IN file (less likely). Hereby, consult professionals, hope to be able to get guidance, thank you!
[potential-convert.zip](https://github.com/deepmodeling/deepmd-kit/files/13484890/potential-convert.zip)

**Comment by njzjz** [comment]
It's likely due to #1935 - the previous definition of per-atom stress is incorrect. We've fixed it, but this is a breaking change.

**Comment by njzjz** [comment]
We've discussed.

The result in the literature is wrong due to #1093.
The result from v2.2.2 is also wrong due to #1935.
