### ISSUE TITLE
Some problems encountered in using GPU to accelerate lammps

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/deepmd-kit#3034]
### Discussed in https://github.com/deepmodeling/deepmd-kit/discussions/3033

<div type='discussions-op-text'>

<sup>Originally posted by **SEU-NiuWenLong** December  2, 2023</sup>
I have two GPU cards, and when I use GPU acceleration, lammps always breaks off after running for a while and reports an error.
Possible remote error message: ESC[31m==> /home/gcniu/workspace/deepmd/23-32/run/temp/81c427e9fd55ff100029be97075854c91642ee29/task.002.000055/model_devi
.log <==
ibdeepmd_1697184996481/work/source/lib/src/gpu/prod_env_mat.cu: 625, in file /home/conda/feedstock_root/build_artifacts/libdeepmd_1697184996481/work/sour
ce/op/custom_op.cc:18
         [[{{node ProdEnvMatA}}]]
         [[o_energy/_31]]
  (1) INTERNAL: Operation received an exception: DeePMD-kit Error: CUDA Runtime library throws an error: an illegal memory access was encountered, in file /home/conda/feedstock_root/build_artifacts/libdeepmd_1697184996481/work/source/lib/src/gpu/prod_env_mat.cu: 625, in file /home/conda/feedstock_root/build_artifacts/libdeepmd_1697184996481/work/source/op/custom_op.cc:18
         [[{{node ProdEnvMatA}}]]
0 successful operations.
0 derived errors ignored. (/home/conda/feedstock_root/build_artifacts/libdeepmd_1697184996481/work/source/lmp/pair_deepmd.cpp:634)
Last command: run             ${NSTEPS} upto
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1
:
system msg for write_line failure : Bad file descriptor
ESC[0m
This is my machine.json file:
        "model_devi": [
                { 
                  "command": "lmp",
                  "machine": {
                   "context_type": "local",
                        "batch_type": "Slurm",
                        "local_root": "./",
                        "remote_root": "/home/gcniu/workspace/deepmd/23-32/run/temp"
                  },
                  "resources": {
                        "number_node": 1,
                        "cpu_per_node": 16,
                        "gpu_per_node": 2,
                        "queue_name": "GPU",
                        "strategy":{"if_cuda_multi_devices":true},
                        "custom_flags" : [
                        "#SBATCH -J gcniu",
                        "#SBATCH -n 16",
                        "#SBATCH -o %j.log",
                        "#SBATCH -e %j.log"
                        ],
                        "group_size": 1000,
                        "_source_list": ["/home/gcniu/workspace/deepmd/23-32/run/envs.sh"]
                  }
                }
        ]
     Is there something wrong with my parameter file configuration? Or is it something else?</div>

**Comment by Yi-FanLi** [comment]
I can reproduce the error. Following is the error message I see:

129000 3.124644e+02 -5.989470e+04 -5.987923e+04 3.670433e+03 1.043236e+00
129500 2.893116e+02 -5.989537e+04 -5.988105e+04 3.498218e+03 1.094594e+00
INTERNAL: 2 root error(s) found.
  (0) INTERNAL: Operation received an exception: DeePMD-kit Error: CUDA Runtime library throws an error: an illegal memory access was encountered, in file /scratch/gpfs/yifanl/Softwares/deepmd-kit-dev/deepmd-kit/source/lib/src/gpu/prod_env_mat.cu: 267, in file /scratch/gpfs/yifanl/Softwares/deepmd-kit-dev/deepmd-kit/source/op/custom_op.cc:18
         [[{{node ProdEnvMatA}}]]
         [[o_atom_energy/_31]]
  (1) INTERNAL: Operation received an exception: DeePMD-kit Error: CUDA Runtime library throws an error: an illegal memory access was encountered, in file /scratch/gpfs/yifanl/Softwares/deepmd-kit-dev/deepmd-kit/source/lib/src/gpu/prod_env_mat.cu: 267, in file /scratch/gpfs/yifanl/Softwares/deepmd-kit-dev/deepmd-kit/source/op/custom_op.cc:18
         [[{{node ProdEnvMatA}}]]
0 successful operations.
0 derived errors ignored.
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 0 in communicator MPI_COMM_WORLD
with errorcode 1.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
[warn] Epoll MOD(1) on fd 8 failed.  Old events were 6; read change was 0 (none); write change was 2 (del): Bad file descriptor
[warn] Epoll MOD(4) on fd 8 failed.  Old events were 6; read change was 2 (del); write change was 0 (none): Bad file descriptor

**Comment by Yi-FanLi** [comment]
I am encountering this bug again today:

389000 2.942137e+02 -2.395761e+05 -2.395178e+05 1.504009e+04 1.018380e+00
ERROR on proc 0: DeePMD-kit Error: TensorFlow Error: INTERNAL: 2 root error(s) found.
  (0) INTERNAL: Operation received an exception: DeePMD-kit Error: CUDA Runtime library throws an error: an illegal memory access was encountered, in file /scratch/gpfs/yifanl/Softwares/deepmd-kit-dev/deepmd-kit-2.2.7/source/lib/src/gpu/prod_env_mat.cu: 275, in file /scratch/gpfs/yifanl/Softwares/deepmd-kit-dev/deepmd-kit-2.2.7/source/op/custom_op.cc:18
         [[{{node ProdEnvMatA}}]]
         [[o_force/_37]]
  (1) INTERNAL: Operation received an exception: DeePMD-kit Error: CUDA Runtime library throws an error: an illegal memory access was encountered, in file /scratch/gpfs/yifanl/Softwares/deepmd-kit-dev/deepmd-kit-2.2.7/source/lib/src/gpu/prod_env_mat.cu: 275, in file /scratch/gpfs/yifanl/Softwares/deepmd-kit-dev/deepmd-kit-2.2.7/source/op/custom_op.cc:18
         [[{{node ProdEnvMatA}}]]
0 successful operations.
0 derived errors ignored. (/scratch/gpfs/yifanl/Softwares/deepmd-kit-dev/deepmd-kit-2.2.7/source/lmp/pair_deepmd.cpp:586)
Last command: run 2000000

I am using the 2.2.7 release version.

**Comment by njzjz** [comment]
Fixed by #3157.
