### ISSUE TITLE
dp freeze and dp compress: warning

### ISSUE THREAD

**Issue by Suyoung999999999** [deepmodeling/deepmd-kit#3039]
### Summary

The following warning is displayed when I use the dp freeze and dp compress commands to extract potential functions. Would you like to ask me the solution and whether this has any impact on the use of the generated potential functions?
![6e78a5df5bbde51f69b6b2146082cc2](https://github.com/deepmodeling/deepmd-kit/assets/140064615/689c1faa-b1b9-47f7-abb0-3d19307b1931)
![c05a6eafdcadc8808b74745d558e947](https://github.com/deepmodeling/deepmd-kit/assets/140064615/27ef330c-4429-4fea-8836-41afe04743d9)

### DeePMD-kit Version

2.2.7

### TensorFlow Version

2.9.0

### Details

Is the potential function thus generated consistent with no-warning accuracy?

**Comment by njzjz** [comment]
Reopen. There is a way to filter the warning messages.
