### ISSUE TITLE
[BUG] easy Install with pip lmp does not support deepmd pair style

### ISSUE THREAD

**Issue by Cheng-JW** [deepmodeling/deepmd-kit#3069]
### Bug summary

LAMMPS installed with DeePMD-kit 2.2.7 package cannot recognized pair style 'deepmd'

### DeePMD-kit Version

2.2.7

### TensorFlow Version

2.15.0

### How did you download the software?

pip

### Input Files, Running Commands, Error Log, etc.

mpirun -n 4 lmp -in input.lammps
LAMMPS (2 Aug 2023 - Update 1)
ERROR: Unrecognized pair style 'deepmd' (src/src/force.cpp:271)

### Steps to Reproduce

conda version: 4.12.0
conda create -n deepmd python=3.11
pip install deepmd-kit[gpu,cu11,lmp,ipi]

**Comment by njzjz** [comment]
The latest pip wheel was built against TF 2.14. If you found TF 2.15 was installed, perhaps the GLIBC requirement of the wheel was not met, and a wheel was rebuilt (which did not enable the lammps module).

**Comment by Cheng-JW** [comment]
> The latest pip wheel was built against TF 2.14. If you found TF 2.15 was installed, perhaps the GLIBC requirement of the wheel was not met, and pip rebuilt a wheel (which did not enable the lammps module).

Thanks for your answers. I checked that while pip install, the version is deepmd_kit-2.2.7-py37-none-manylinux_2_17_x86_64.whl and tensorflow==2.15.0 is required by deepmd-kit[cu11,gpu,ipi,lmp] (tensorflow-2.15.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata). Is it a newer version for pip wheel or this is the pip-rebuilt wheel?

**Comment by njzjz** [comment]
The pypi wheels are shown on pypi.org:

![image](https://github.com/deepmodeling/deepmd-kit/assets/9496702/7ad6518f-60e6-47fe-9937-0f6b4b9b45af)

which are different from yours. It looks like you only have GLIBC 2.17, and the pypi wheels require GLIBC 2.28.

**Comment by Cheng-JW** [comment]
> The pypi wheels are shown on pypi.org:
> 
> ![image](https://private-user-images.githubusercontent.com/9496702/291391051-7ad6518f-60e6-47fe-9937-0f6b4b9b45af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyOTc0NDcsIm5iZiI6MTcwMzI5NzE0NywicGF0aCI6Ii85NDk2NzAyLzI5MTM5MTA1MS03YWQ2NTE4Zi02MGU2LTQ3ZmUtOTkzNy0wZjZiNGI5YjQ1YWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjNUMDIwNTQ3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MGQyY2MyZjYzODIwODliNzYyZGIwZGIyNjRjZmI0NDIxNTUzZDdkZDU4NmRjZjRmYjA0ODc3NjhlMzFiOWNiYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.w-PKZ_3Z39pyauClNzKt8t5y2l5I7h3L4o9yC2I6OJ0)
> 
> which are different from yours. It looks like you only have GLIBC 2.17, and the pypi wheels require GLIBC 2.28.

That is clear for me. But how can I install deepmd with GLIBC 2.17? I've tried conda install and pip install and both failed. Do I need to build from source?
