### ISSUE TITLE
[Feature Request] _Integrate Grimme DFTD-3 or DFTD-4 into DeepMD-kit

### ISSUE THREAD

**Issue by Epikurz** [deepmodeling/deepmd-kit#3099]
### Summary

I would like to propose an enhancement for future versions of DeepMD-Kit. It would be highly beneficial if the software could integrate Grimme-D3 or D4 corrections directly into the potential energy functions trained with the PBE functional. This integration would eliminate the need to train potentials with van der Waals forces explicitly included.

From a theoretical standpoint, potentials without van der Waals forces could potentially utilize a smaller Rcut, offering computational advantages. I believe this enhancement would greatly improve the versatility and efficiency of DeepMD-Kit, particularly for users interested in training potentials using the PBE functional with van der Waals corrections.

### Detailed Description

Current versions allow for the simultaneous use of DeepMD-kit and DFTD3 as calculators through ASE to achieve certain functionalities. However, when running LAMMPS, there is currently no straightforward method to perform D3 corrections concurrently with MD simulations. I would like to propose the capability to easily incorporate van der Waals force corrections when using LAMMPS for DeepPotential simulations. I believe this approach would be more convenient and accurate than training potential functions using DFT data pre-corrected with D3 corrections.

**Comment by njzjz** [comment]
I notice a recent work did the similar things: https://doing.org/10.1088/1361-648X/ad1278 The cutoff radius was added for simulations, but it's unclear whether there was a switch function.

I personally think it should be implemented into LAMMPS.

For the DeePMD-kit, the fastest way might be reimplementing the pairwise tabulate. So, the DeePMD-kit does not need to know the details about external potentials.
