### ISSUE TITLE
[BUG] LAMMPS error: "Unrecognized pair style 'deepmd'" when installing deepmd-kit via CPU version of offline packages

### ISSUE THREAD

**Issue by rashidrafeek** [deepmodeling/deepmd-kit#3105]
### Bug summary

When installing the CPU version of offline packages for the current version of DeepMD-kit (v2.2.7), the lammps executables installed does not recognize `deepmd` pair style. 

I have also installed the GPU version of the same version of DeepMD-kit and this issue does not occur there.

### DeePMD-kit Version

DeePMD-kit v2.2.7

### TensorFlow Version

2.14.0

### How did you download the software?

Offline packages

### Input Files, Running Commands, Error Log, etc.

Following is a snippet of the output produced for the command: `lmp_serial -in in.lammps`:
```
LAMMPS (2 Aug 2023)
Reading data file ...
  triclinic box = (0 0 0) to (23.704 23.704 23.704) with tilt (0 0 0)
  1 by 1 by 1 MPI processor grid
  reading atoms ...
  768 atoms
  read_data CPU = 0.005 seconds
ERROR: Unrecognized pair style 'deepmd' (src/force.cpp:271)
Last command: pair_style	deepmd ../model.pb
```
The same occurs for the mpi executable `lmp_mpi` also.

### Steps to Reproduce

- Download CPU version of offline package version v2.2.7 with  this [link](https://github.com/deepmodeling/deepmd-kit/releases/download/v2.2.7/deepmd-kit-2.2.7-cpu-Linux-x86_64.sh).
- Install using `bash deepmd-kit-2.2.7-cpu-Linux-x86_64.sh`
- Activate the environment using conda
- Run `lmp_serial -in in.lammps` using any input file `in.lammps`.

**Comment by njzjz** [comment]
It's never expected for `lmp_serial` to work. See https://github.com/deepmodeling/deepmd-kit/discussions/1025#discussioncomment-7202939. I am working on https://github.com/conda-forge/lammps-feedstock/pull/172 to remove it.

I do not find problems when using `lmp_mpi`, though. See https://gist.github.com/njzjz/800a27410b44569748851c0b36835d23. Please check if you have anything different.

**Comment by rashidrafeek** [comment]
The only difference is that I am installing at a different path. Would that be an issue?

But as I understood that deepmd pair style is loaded as a plugin, I did the following and it started working:
```
export LAMMPS_PLUGIN_PATH=/path/to/deepmd-kit/lib/deepmd_lmp
```

Is the default installation path of `/root/deepmd-kit` hard-coded by any chance? Anyway the above workaround solves my issue. Thanks for the reply.

**Comment by njzjz** [comment]
The latest installer was updated on Nov 27, 2023. Did you download it before that time? There were some issues in an old version.

Could you show the output of `conda list`?

**Comment by rashidrafeek** [comment]
I am attaching the output of `conda list` for your reference.
[conda_list.txt](https://github.com/deepmodeling/deepmd-kit/files/13828393/conda_list.txt)
I have installed some extra packages using pip in the same environment. Would that be an issue?

I don't remember when I installed deepmd-kit, but there is a chance it was before that date. I will install again now and check if this occurs now.

**Comment by njzjz** [comment]
I see. It should have been fixed by https://github.com/conda-forge/deepmd-kit-feedstock/pull/63. Just update deepmd-kit from cpu_py311h5e042cb_2 to cpu_py311h5e042cb_3
