### ISSUE TITLE
[Feature request] Roadmap for PyTorch backend

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/deepmd-kit#3122]
### Summary

This issue is a roadmap to migrate the PyTorch (PT) backend from the temporary repository to here.

### Detailed Description

- [x] #2982 
- [ ] #2103 
- [x] #3118 
- [x] #3119 
- [x] #3120
- [x] #3121
- [x] Migrate existing codes

**Comment by iProzd** [comment]
Use project https://github.com/orgs/deepmodeling/projects/19 to track.
