### ISSUE TITLE
[BUG] _calculate dynamical_matrix and segmentation fault. 

### ISSUE THREAD

**Issue by MushroomYa** [deepmodeling/deepmd-kit#3126]
### Bug summary

I use DP model to run dynamical_matrix, and it shows "/opt/deepmd-kit-2.1.5/bin/lmp: line 11:    24 Segmentation fault      /opt/deepmd-kit-2.1.5/bin/_lmp "$@"" . The similar script can work when using EAM potential. 

### DeePMD-kit Version

deepmd-kit-2.1.5

### TensorFlow Version

not found

### How did you download the software?

Built from source

### Input Files, Running Commands, Error Log, etc.

units           metal
boundary        p p p
atom_style      atomic
atom_modify     map array sort 0 0.0

read_data relaxed_npt_Al.data

mass 1 6.941
mass 2 26.981539

pair_style	deepmd graph-compress-1014.pb
pair_coeff	* *  

neighbor    2 bin

dynamical_matrix all regular 1.0e-6 file Dyn.form binary no 

### Steps to Reproduce

Just run.

**Comment by njzjz** [comment]
What I got from the latest version is

```
ERROR: 6-element atomic virial is not supported. Use compute centroid/stress/atom command for 9-element atomic virial. (/home/conda/feedstock_root/build_artifacts/deepmd-kit_1701131171981/work/source/lmp/pair_deepmd.cpp:470)
Last command: dynamical_matrix all regular 1.0e-6 file Dyn.form binary no
```

If `dynamical_matrix` requests a 6-element atom virial, it will be incorrect, per #1093.

**Comment by MushroomYa** [comment]
Thanks for your response. I use the latest verision and reproduce the similar error. So I can't use DP model to produce dynamical_matrix? 

---------------- 

----------原邮件信息----------
发件人："Jinzhe Zeng" ***@***.***>
收件人："deepmodeling/deepmd-kit" ***@***.***>
抄送人："MushroomYa" ***@***.***>, "Author" ***@***.***>
主题：Re: [deepmodeling/deepmd-kit] [BUG] _calculate dynamical_matrix andsegmentation fault. (Issue #3126)
发送时间：2024-01-11 05:22:35

 What I got from the latest version is

```
ERROR: 6-element atomic virial is not supported. Use compute centroid/stress/atom command for 9-element atomic virial. (/home/conda/feedstock_root/build_artifacts/deepmd-kit_1701131171981/work/source/lmp/pair_deepmd.cpp:470)
Last command: dynamical_matrix all regular 1.0e-6 file Dyn.form binary no
```

If `dynamical_matrix` requests a 6-element atom virial, it will be incorrect, per #1093.

**Comment by njzjz** [comment]
It might be a bug that evflag is not initialized correctly.

**Comment by njzjz** [comment]
#3133 should fix the error.
