### ISSUE TITLE
[BUG]Error during 'pip install .' when Installing DeepMD from Source Code

### ISSUE THREAD

**Issue by Miller10101010** [deepmodeling/deepmd-kit#3146]
### Bug summary

Installing DeepMD on ROCm: First creating a virtual environment with conda, then installing tensorflow-rocm with pip. Encounter an error during "pip install ."

### DeePMD-kit Version

uninstall

### TensorFlow Version

tensorflow-rocm              2.14.0.600

### How did you download the software?

Built from source

### Input Files, Running Commands, Error Log, etc.

![image](https://github.com/deepmodeling/deepmd-kit/assets/155539163/d80f177c-1c9d-4bb4-999d-e788c8727c35)
![image](https://github.com/deepmodeling/deepmd-kit/assets/155539163/510f6ee7-0fd4-42c6-bd2b-f973c2b811a8)
![image](https://github.com/deepmodeling/deepmd-kit/assets/155539163/10a7d828-6b46-4810-b5e8-98238abac446)
![image](https://github.com/deepmodeling/deepmd-kit/assets/155539163/25e50db3-e4a0-4a2e-b386-650559347e79)

### Steps to Reproduce

![image](https://github.com/deepmodeling/deepmd-kit/assets/155539163/806c1da1-4e72-4c12-be57-329c6d9c81fa)
This is the environment variable setup before running 'pip install .'

**Comment by njzjz** [comment]
Where did you install the ROCm CMake modules?

**Comment by Miller10101010** [comment]
ROCm is installed in /opt/rocm/lib/cmake/hip, but the error above says it cannot find /opt/rocm/lib/cmake/hip-lang/hip-lang-config.cmake. This file is located in /public/software/compiler/dtk-23.10/lib/cmake/hip-lang. I copied hip-lang over, but the error persists (see Figure 1), and the error.log file is as follows (see Figure 2). Later, I changed the environment variables to what is shown in Figure 3, and now it complains about not finding /opt/rocm/hip/lib/libgalaxvhip.so.5.2.23453.269-23afd42c (see Figure 4)
![d5a50dd2773e918b97938e5e0a6dc83](https://github.com/deepmodeling/deepmd-kit/assets/155539163/78ae3902-6d6f-4903-9695-7b61627eb413)
![d98b958dad0c8c13670265fa831de87](https://github.com/deepmodeling/deepmd-kit/assets/155539163/93fc7cf7-4882-4ba5-869c-89982ab8677f)
![5231c8634ae8f2c287dc5cb0e1c39c6](https://github.com/deepmodeling/deepmd-kit/assets/155539163/3fb40a40-8273-47fa-b473-d3ee970ab2dd)
![acd0503942fdd8086492c5468f2f7ec](https://github.com/deepmodeling/deepmd-kit/assets/155539163/bc1a9127-85d6-4f3c-8368-8eb4412ab98b)

**Comment by Miller10101010** [comment]
The above issue has been resolved. Now, the problem is that the 'hsa-runtime64Config.cmake' file cannot be found.
![1705384685075](https://github.com/deepmodeling/deepmd-kit/assets/155539163/690156be-b874-42e7-be48-e7bc99eb1d39)

**Comment by Miller10101010** [comment]
I found the has-runtime64Config.cmake. I solved this probelm by export environment variables(see fig1),but unfortunately I got the other problem(see fig2 ) Any hint?
![image](https://github.com/deepmodeling/deepmd-kit/assets/155539163/00460bad-e484-4129-bf63-938426daf551)

![image](https://github.com/deepmodeling/deepmd-kit/assets/155539163/70d16544-a31a-4f69-bc14-68c2a6ff12e6)

**Comment by njzjz** [comment]
What is the detailed error message thrown by GCC?

**Comment by njzjz** [comment]
Close, as no more information is given to reproduce the issue.
