### ISSUE TITLE
[BUG] _Strange problems when running MD with a DPA-1 model_

### ISSUE THREAD

**Issue by dfz05** [deepmodeling/deepmd-kit#3150]
### Bug summary

I trained a DPA-1 model based on deepmd-kit-2.2.7.
When I use it to do NPT MD simulations, I usually meet the error "ERROR: Non-numeric pressure - simulation unstable (src/fix_nh.cpp:1049)".

If I change the NPT  to NVT, all the forces and velocities change to "nan" at a sudden step. 

![w1G7UWYhEl](https://github.com/deepmodeling/deepmd-kit/assets/24411753/32edfa8d-cef1-48c3-8862-fb608dac8739)

### DeePMD-kit Version

2.2.7

### TensorFlow Version

2.9.0

### How did you download the software?

Others (write below)

### Input Files, Running Commands, Error Log, etc.

[potential.zip](https://github.com/deepmodeling/deepmd-kit/files/13951964/potential.zip)

### Steps to Reproduce

lmp -in in.lammps

**Comment by njzjz** [comment]
Fixed by https://github.com/deepmodeling/deepmd-kit/pull/3157.
