### ISSUE TITLE
DeepMD installation error

### ISSUE THREAD

**Issue by Matheus-Novoa** [deepmodeling/deepmd-kit#324]
A tried to install deepmd using conda, but i got this error: 

conda install deepmd-kit=*=*cpu lammps-dp=*=*cpu -c deepmodeling                      Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

**PackagesNotFoundError: The following packages are not available from current channels:**

  - lammps-dp[build=*cpu]
  - deepmd-kit[build=*cpu]

Current channels:

  - https://conda.anaconda.org/deepmodeling/win-64
  - https://conda.anaconda.org/deepmodeling/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by njzjz** [comment]
We did not add support for Windows. See #305 for the suggestion.

**Comment by xn-huang** [comment]
I installed specified version of deepmd in Ubantu, but also got the error..

----------------
PackagesNotFoundError: The following packages are not available from current channels:

  - deepmd-kit==1.2[build=*cpu]
  - lammps-dp==1.2[build=*cpu]

Current channels:

  - https://conda.anaconda.org/deepmodeling/linux-64
  - https://conda.anaconda.org/deepmodeling/noarch
  - https://repo.anaconda.com/pkgs/main/linux-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/linux-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://conda.anaconda.org/conda-forge/linux-64
  - https://conda.anaconda.org/conda-forge/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
---------------
What should I do to fix it ..? Thank you.

**Comment by njzjz** [comment]
We have removed old versions on https://conda.anaconda.org/deepmodeling. You may try newer version like `1.2.4` instead of `1.2`, or use our archiving channel https://conda.deepmodeling.org instead of https://conda.anaconda.org/deepmodeling.

**Comment by xn-huang** [comment]
Thank you for your help. The channel (https://conda.deepmodeling.org) works. 
Another question is :
I found that the computing speed of the cpu version using lammps and machine learning potential is slow. Can the computing speed be improved by using a GPU version? Thank you.

**Comment by njzjz** [comment]
> Can the computing speed be improved by using a GPU version?

Of course, if you have a GPU.

**Comment by xn-huang** [comment]
> > Can the computing speed be improved by using a GPU version?
> 
> Of course, if you have a GPU.

Thank you for your reply.
Yes. The lammps-GPU version works, too. But it seems need a lot of memory. I found the error as follows:
------------
I tensorflow/stream_executor/cuda/cuda_driver.cc:775] failed to allocate 3.38G (3629691648 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
------------
And when I use the lammps-cpu version, when the number of atoms is large, there are a memory problem, too. The atom number is 86400. The memory is 31GB.
Do you have any suggestion for the problem? Thank you.
