### ISSUE TITLE
[BUG] Model deviation calculation output nan occasionally in model_devi.out

### ISSUE THREAD

**Issue by robinzyb** [deepmodeling/deepmd-kit#3242]
### Bug summary

![Screenshot 2024-02-06 at 15 51 16](https://github.com/deepmodeling/deepmd-kit/assets/38876805/dd31ac53-931b-4ff5-b950-ea8e687bc536)

### DeePMD-kit Version

2.2.7

### TensorFlow Version

2.9.0

### How did you download the software?

conda

### Input Files, Running Commands, Error Log, etc.

https://drive.google.com/drive/folders/1GzDIUjdFfn7APTuSepa_ONugUoBkk4an?usp=drive_link
potentials and inputs for the model deviation calculation as well as the results.

### Steps to Reproduce

run the model deviation calculation in google drive.

**Comment by njzjz** [comment]
@robinzyb Please confirm whether the problem has been fixed by #3157.

**Comment by robinzyb** [comment]
yes. no nan appears on the model_devi.out when using version 2.2.9
