### ISSUE TITLE
[Feature Request] dpmodel and pt fitting should export several methods

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/deepmd-kit#3273]
### Summary

Fitting should add methods to get fparam, aparam, and sel_types.

### Detailed Description

Add these methods so the model can get it.

https://github.com/deepmodeling/deepmd-kit/blob/612bedc5da89b468b0c9531c310d2d9671d8b0f5/deepmd/dpmodel/model/dp_atomic_model.py#L147-L162

**Comment by wanghan-iapcm** [comment]
The methods in the linear_atomic_models should be rethink.

**Comment by anyangml** [comment]
added in this PR https://github.com/deepmodeling/deepmd-kit/pull/3266/

**Comment by njzjz** [comment]
> The methods in the linear_atomic_models should be rethink.

This will be tracked in #3502 instead.
