### ISSUE TITLE
[Feature Request] pt: statistics of the fitting net is not covered by UTs

### ISSUE THREAD

**Issue by wanghan-iapcm** [deepmodeling/deepmd-kit#3278]
### Summary

In the torch implementation, the behavior of the fitting stats are not tested. 

### Detailed Description

The behavior  `compute_output_stats` and `init_fitting_stat` of the torch fitting networks (see below) are not covered by unit testes. Especially the behavior when the dimension of the variables are larger than 1. 

https://github.com/deepmodeling/deepmd-kit/blob/aae48508e002d194446d71260fdab7622c83b88e/deepmd/pt/model/task/ener.py#L213-L230

**Comment by njzjz** [comment]
It seems that `init_fitting_stat` has been removed from the energy fitting (but it is still in BaseFitting). `compute_output_stats` is tested by `source/tests/pt/test_stat.py`.
