### ISSUE TITLE
[BUG] deepmd v3.0.0.a0 could not freeze

### ISSUE THREAD

**Issue by scott-5** [deepmodeling/deepmd-kit#3406]
### Bug summary

Deepmd v3.0.0a0 can train normally but cannot freeze the model.

### DeePMD-kit Version

v3.0.0.a0

### TensorFlow Version

2.14.0

### How did you download the software?

Offline packages

### Input Files, Running Commands, Error Log, etc.

Input Files: as example/water/dpa2/input_torch.json except type_map and dataset
Commands: dp --pt freeze
[err.log](https://github.com/deepmodeling/deepmd-kit/files/14478774/err.log)

### Steps to Reproduce

example/water/dpa2/input_torch.json slightly has been modified at type_map and training_data/system, then dp --pt train input_torch.json && dp --pt freeze

**Comment by njzjz** [comment]
I've triggered a new installer.
