### ISSUE TITLE
[Feature Request] Update the energy bias after the final step of training

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/deepmd-kit#3408]
### Summary

Add an option to update the energy bias after the final step of training.

### Detailed Description

Sometimes, the predicted energy is shifted compared to the reference energy, such as #2935. I think it might be because the energy loss is too small (the force loss cannot train the energy bias). However, we have an easy way to improve it: do `update_energy_bias` after the final step of the training. It just changes the energy bias and will not break other things. We already have the code for `update_energy_bias`, so we can add an option to call it.
(in theory, it is equivalent to `--finetune` with 0 steps, but a user won't come up with it.)

**Comment by wanghan-iapcm** [comment]
I agree. we can provide the feature after @iProzd refactorizes and merges the update_energy_bias with the current output stat code.
