### ISSUE TITLE
Fail in finetuning of pre-train model in DPA2 of DeePMD-kit v3

### ISSUE THREAD

**Issue by h757062840** [deepmodeling/deepmd-kit#3412]
### Bug summary

Using the 'examples/water/dpa2/input_torch.json' as input file, and using the model 'DPA2_18head_1m/model.pt' as pre-train model. Then excute "dp --pt train input_torch.json --finetune ./model.pt ". While it fail and the report show like this 
![Snipaste_2024-03-05_09-30-55](https://github.com/deepmodeling/deepmd-kit/assets/135682831/d006db07-4144-4336-80ba-975247205d4f)
How can i fix thi problem and finetuning succesfully?

### DeePMD-kit Version

DeePMD-kit v3.0.0a0

### TensorFlow Version

PyTorch v2.0.0.post200-gc263bd43e8e

### How did you download the software?

Offline packages

### Input Files, Running Commands, Error Log, etc.

[erro.zip](https://github.com/deepmodeling/deepmd-kit/files/14489174/erro.zip)

### Steps to Reproduce

None

**Comment by wanghan-iapcm** [comment]
yes it is expected.  The model is only compatible with the code released on https://doi.org/10.5281/zenodo.10428497

We will release deepmd-kit v3 compatible pretrained model asap. @iProzd  FYI
