### ISSUE TITLE
[BUG] Finetuned model has wrong type_map

### ISSUE THREAD

**Issue by iProzd** [deepmodeling/deepmd-kit#3455]
### Bug summary

When doing finetuing, the user-defined `type_map` (e.g. ['H', 'O']) will be covered by the `type_map` in the pretrained model (e.g. the whole periodic table) , which is confusing for users.

### DeePMD-kit Version

3.0.0a

### TensorFlow Version

2.6.0

### How did you download the software?

Built from source

### Input Files, Running Commands, Error Log, etc.

See above.

### Steps to Reproduce

See above.

**Comment by njzjz** [comment]
Idea: the easiest way is to add a virtual `Model`, "adapt type map model", which just adapts the input `atom_type` from the outer model `type_map` to the inner model `type_map` and forwards everything else like #3450.

**Comment by iProzd** [comment]
> Idea: the easiest way is to add a virtual `Model`, "adapt type map model", which just adapts the input `atom_type` from the outer model `type_map` to the inner model `type_map` and forwards everything else like #3450.
I see, but this will cause the model to be wrapped repeatedly each time it is fine-tuned, as discussed with @wanghan-iapcm and @anyangml.

**Comment by njzjz** [comment]
>  repeatedly each time it is fine-tuned

Indeed, I don't understand why it needs to change the type map each time it is fine-tuned...

**Comment by anyangml** [comment]
> > repeatedly each time it is fine-tuned
> 
> Indeed, I don't understand why it needs to change the type map each time it is fine-tuned...

For the LinearModel, let's say we have two pre-trained models: model A with ["H", "O", "Na"], model B with ["H", "O", "K"]. Now if we want to finetune a LinearModel with this, the new type map becomes ["H", "O"].

**Comment by njzjz** [comment]
> > > repeatedly each time it is fine-tuned
> 
> > 
> 
> > Indeed, I don't understand why it needs to change the type map each time it is fine-tuned...
> 
> 
> 
> For the LinearModel, let's say we have two pre-trained models: model A with ["H", "O", "Na"], model B with ["H", "O", "K"]. Now if we want to finetune a LinearModel with this, the new type map becomes ["H", "O"].

This is not correct. The type map should be the union of two models.

**Comment by anyangml** [comment]
> > > > repeatedly each time it is fine-tuned
> > 
> > 
> > > 
> > 
> > 
> > > Indeed, I don't understand why it needs to change the type map each time it is fine-tuned...
> > 
> > 
> > For the LinearModel, let's say we have two pre-trained models: model A with ["H", "O", "Na"], model B with ["H", "O", "K"]. Now if we want to finetune a LinearModel with this, the new type map becomes ["H", "O"].
> 
> This is not correct. The type map should be the union of two models.

I think the combined model should only handle the common types. Suppose the new type map is the union of the two, there will be unseen types for each individual models.

**Comment by njzjz** [comment]
> > > > > repeatedly each time it is fine-tuned
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > Indeed, I don't understand why it needs to change the type map each time it is fine-tuned...
> 
> > > 
> 
> > > 
> 
> > > For the LinearModel, let's say we have two pre-trained models: model A with ["H", "O", "Na"], model B with ["H", "O", "K"]. Now if we want to finetune a LinearModel with this, the new type map becomes ["H", "O"].
> 
> > 
> 
> > This is not correct. The type map should be the union of two models.
> 
> 
> 
> I think the combined model should only handle the common types. Suppose the new type map is the union of the two, there will be unseen types for each individual models.

A model doesn't need to evaluate all types. A typical example is DPLR. Pairwise potentials may also be aimed at several certain types.

**Comment by wanghan-iapcm** [comment]
> > repeatedly each time it is fine-tuned
> 
> Indeed, I don't understand why it needs to change the type map each time it is fine-tuned...

because the user may provide new type_map that is not consistent with the model type_map
