### ISSUE TITLE
[BUG] _Replace With Suitable Title_

### ISSUE THREAD

**Issue by wangyi01** [deepmodeling/deepmd-kit#3457]
### Bug summary

deepmd-kit v2.2.9 cuda120版本的.sh.0访问不了，其他的都可以访问

### DeePMD-kit Version

deepmd-kit v2.2.9

### TensorFlow Version

deepmd-kit v2.2.9

### How did you download the software?

Built from source

### Input Files, Running Commands, Error Log, etc.

deepmd-kit v2.2.9 cuda120版本的.sh.0访问不了，其他的都可以访问

### Steps to Reproduce

deepmd-kit v2.2.9 cuda120版本的.sh.0访问不了，其他的都可以访问

**Comment by njzjz** [comment]
See #740.

**Comment by njzjz** [comment]
Duplicate of #740
