### ISSUE TITLE
dpmodel/pt: Random methods without explicit seeds should be forbidden

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/deepmd-kit#3467]
For new backends, random methods without explicit seeds should be forbidden, as they create unreproduced behavior.

## dpmodel

https://github.com/deepmodeling/deepmd-kit/blob/d61b152af72143cac3be114786eaaf2789ee6f10/deepmd/dpmodel/utils/network.py#L173-L174

## pt
https://github.com/deepmodeling/deepmd-kit/blob/d61b152af72143cac3be114786eaaf2789ee6f10/deepmd/pt/model/network/network.py#L72-L73

https://github.com/deepmodeling/deepmd-kit/blob/d61b152af72143cac3be114786eaaf2789ee6f10/deepmd/pt/optimizer/KFWrapper.py#L138

The following normal methods need to be provided with a [torch Generator](https://pytorch.org/docs/stable/generated/torch.Generator.html):

https://github.com/deepmodeling/deepmd-kit/blob/d61b152af72143cac3be114786eaaf2789ee6f10/deepmd/pt/model/network/mlp.py#L68
https://github.com/deepmodeling/deepmd-kit/blob/d61b152af72143cac3be114786eaaf2789ee6f10/deepmd/pt/model/network/mlp.py#L73
https://github.com/deepmodeling/deepmd-kit/blob/d61b152af72143cac3be114786eaaf2789ee6f10/deepmd/pt/model/network/mlp.py#L78
https://github.com/deepmodeling/deepmd-kit/blob/d61b152af72143cac3be114786eaaf2789ee6f10/deepmd/pt/model/network/network.py#L141
https://github.com/deepmodeling/deepmd-kit/blob/d61b152af72143cac3be114786eaaf2789ee6f10/deepmd/pt/model/network/network.py#L143
https://github.com/deepmodeling/deepmd-kit/blob/d61b152af72143cac3be114786eaaf2789ee6f10/deepmd/pt/model/network/network.py#L146
https://github.com/deepmodeling/deepmd-kit/blob/d61b152af72143cac3be114786eaaf2789ee6f10/deepmd/pt/model/network/network.py#L307
https://github.com/deepmodeling/deepmd-kit/blob/d61b152af72143cac3be114786eaaf2789ee6f10/deepmd/pt/model/network/network.py#L310
https://github.com/deepmodeling/deepmd-kit/blob/d61b152af72143cac3be114786eaaf2789ee6f10/deepmd/pt/model/network/network.py#L315
https://github.com/deepmodeling/deepmd-kit/blob/d61b152af72143cac3be114786eaaf2789ee6f10/deepmd/pt/model/network/network.py#L370
https://github.com/deepmodeling/deepmd-kit/blob/d61b152af72143cac3be114786eaaf2789ee6f10/deepmd/pt/model/network/network.py#L383
https://github.com/deepmodeling/deepmd-kit/blob/d61b152af72143cac3be114786eaaf2789ee6f10/deepmd/pt/model/network/network.py#L430
https://github.com/deepmodeling/deepmd-kit/blob/d61b152af72143cac3be114786eaaf2789ee6f10/deepmd/pt/model/task/atten_lcc.py#L25

I also noticed in some modules, `torch.manual_seed` is called to change the global seed after the network initlization. I don't see the meaning of them.

**Comment by wanghan-iapcm** [comment]
i do no think it is a issue at least in the UTs, as they do not rely on the reproducibility of the random numbers.
