### ISSUE TITLE
any c_api for model deviation compute without nlist?

### ISSUE THREAD

**Issue by robinzyb** [deepmodeling/deepmd-kit#3641]
### Summary

nope

### DeePMD-kit Version

xxx

### TensorFlow Version

xx

### Details

I would like to add model devi in cp2k while the nlist is required in 
https://github.com/deepmodeling/deepmd-kit/blob/b875ea8f6661b6e1567537ead7e2b4a8b14ea113/source/api_c/src/c_api.cc#L1065-L1081
How do I bypass the Nlist input?

**Comment by njzjz** [comment]
I remember no one has written it, including the C++ API.
