### ISSUE TITLE
ModuleNotFoundError: No module named 'deepmd.lib'

### ISSUE THREAD

**Issue by zhaowenlon** [deepmodeling/deepmd-kit#3664]
### Bug summary

import dpdata

training_systems = dpdata.LabeledSystem("/deepmd-kit-master/examples/water/data/data_3", fmt = "deepmd/npy")  
# print(training_systems["energies"])
predict = training_systems.predict("/deepmd-kit-master/examples/water/se_e2_a/graph-compress.pb")  

### DeePMD-kit Version

deepmd-kit              2.2.10

### Backend and its version

TensorFlow v2.16

### How did you download the software?

Offline packages

### Input Files, Running Commands, Error Log, etc.

import deepmd.lib
ModuleNotFoundError: No module named 'deepmd.lib'

### Steps to Reproduce

import dpdata

training_systems = dpdata.LabeledSystem("/deepmd-kit-master/examples/water/data/data_3", fmt = "deepmd/npy")  
# print(training_systems["energies"])
predict = training_systems.predict("/deepmd-kit-master/examples/water/se_e2_a/graph-compress.pb")

**Comment by njzjz** [comment]
Could you prove the entire traceback?



> ### DeePMD-kit Version
> 
> deepmd-kit 2.2.10
> ### Backend and its version
> 
> TensorFlow v2.16
> ### How did you download the software?
> 
> Offline packages

The offline package for v2.2.10 doesn't contain TensorFlow v2.16. Could you recheck the above information?

**Comment by zhaowenlon** [comment]
in deepmd/env.py,line 31,import deepmd.lib
ModuleNotFoundError: No module named 'deepmd.lib'

**Comment by zhaowenlon** [comment]
not find lib in deepmd file

**Comment by njzjz** [comment]
Did you install it? It seems you just run the source code, which won't work

**Comment by njzjz** [comment]
I close this issue as there is no active task for developers.

**Comment by lizhen62017** [comment]
Hi Jinzhe, 

I am learning QM/MM book-ending these days, and just encountered the same error. Here is the full call stack.( BTW the "step2.py" file is the same code block in the "quick start CH4" tutorial where JSON file is to be printed.)
```
Traceback (most recent call last):
  File "/mnt/isilon/w_ccls/merzklab/Zhen/deepmd-kit/step2.py", line 1, in <module>
    from deepmd.utils.argcheck import gen_args
  File "/mnt/isilon/w_ccls/merzklab/Zhen/deepmd-kit/deepmd/__init__.py", line 11, in <module>
    import deepmd.utils.network as network
  File "/mnt/isilon/w_ccls/merzklab/Zhen/deepmd-kit/deepmd/utils/__init__.py", line 9, in <module>
    from .learning_rate import (
  File "/mnt/isilon/w_ccls/merzklab/Zhen/deepmd-kit/deepmd/utils/learning_rate.py", line 8, in <module>
    from deepmd.env import (
  File "/mnt/isilon/w_ccls/merzklab/Zhen/deepmd-kit/deepmd/env.py", line 30, in <module>
    import deepmd.lib
ModuleNotFoundError: No module named 'deepmd.lib'
```
Also my deepmd-kit version is 2.2.12.dev2+g440bb821 and I am using tensorflow-cpu 2.17.0. Thanks for any help!

**Comment by njzjz** [comment]
@lizhen62017 [The first entry in the Python module search path is the directory that contains the input script](https://docs.python.org/3/library/sys_path_init.html). Thus, if you install the module into other directories, you should avoid putting the script in this directory.

**Comment by lizhen62017** [comment]
Hi Jinzhe, 

Thanks for the reply. I moved the python script out of the current directory to the parent directory (../) but got another error as below: Appreciate any insights!
```
Traceback (most recent call last):
  File "/mnt/isilon/w_ccls/merzklab/Zhen/step2.py", line 1, in <module>
    from deepmd.utils.argcheck import gen_args
  File "/mnt/isilon/w_ccls/merzklab/Zhen/deepmd-kit/lib/python3.10/site-packages/deepmd/__init__.py", line 11, in <module>
    import deepmd.utils.network as network
  File "/mnt/isilon/w_ccls/merzklab/Zhen/deepmd-kit/lib/python3.10/site-packages/deepmd/utils/__init__.py", line 9, in <module>
    from .learning_rate import (
  File "/mnt/isilon/w_ccls/merzklab/Zhen/deepmd-kit/lib/python3.10/site-packages/deepmd/utils/learning_rate.py", line 8, in <module>
    from deepmd.env import (
  File "/mnt/isilon/w_ccls/merzklab/Zhen/deepmd-kit/lib/python3.10/site-packages/deepmd/env.py", line 72, in <module>
    dlopen_library("nvidia.cusparse.lib", "libcusparse.so*")
  File "/mnt/isilon/w_ccls/merzklab/Zhen/deepmd-kit/lib/python3.10/site-packages/deepmd/env.py", line 61, in dlopen_library
    ctypes.CDLL(str(libs[0].absolute()))
  File "/cm/shared/apps/python/gpu/3.10.6/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /mnt/isilon/w_ccls/merzklab/Zhen/deepmd-kit/lib/python3.10/site-packages/nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkComplete_12_3, version libnvJitLink.so.12
```

**Comment by lizhen62017** [comment]
> Hi Jinzhe,
> 
> Thanks for the reply. I moved the python script out of the current directory to the parent directory (../) but got another error as below: Appreciate any insights!
> 
> ```
> Traceback (most recent call last):
>   File "/mnt/isilon/w_ccls/merzklab/Zhen/step2.py", line 1, in <module>
>     from deepmd.utils.argcheck import gen_args
>   File "/mnt/isilon/w_ccls/merzklab/Zhen/deepmd-kit/lib/python3.10/site-packages/deepmd/__init__.py", line 11, in <module>
>     import deepmd.utils.network as network
>   File "/mnt/isilon/w_ccls/merzklab/Zhen/deepmd-kit/lib/python3.10/site-packages/deepmd/utils/__init__.py", line 9, in <module>
>     from .learning_rate import (
>   File "/mnt/isilon/w_ccls/merzklab/Zhen/deepmd-kit/lib/python3.10/site-packages/deepmd/utils/learning_rate.py", line 8, in <module>
>     from deepmd.env import (
>   File "/mnt/isilon/w_ccls/merzklab/Zhen/deepmd-kit/lib/python3.10/site-packages/deepmd/env.py", line 72, in <module>
>     dlopen_library("nvidia.cusparse.lib", "libcusparse.so*")
>   File "/mnt/isilon/w_ccls/merzklab/Zhen/deepmd-kit/lib/python3.10/site-packages/deepmd/env.py", line 61, in dlopen_library
>     ctypes.CDLL(str(libs[0].absolute()))
>   File "/cm/shared/apps/python/gpu/3.10.6/lib/python3.10/ctypes/__init__.py", line 374, in __init__
>     self._handle = _dlopen(self._name, mode)
> OSError: /mnt/isilon/w_ccls/merzklab/Zhen/deepmd-kit/lib/python3.10/site-packages/nvidia/cusparse/lib/libcusparse.so.12: undefined symbol: __nvJitLinkComplete_12_3, version libnvJitLink.so.12
> ```
> 
> This is probably my deepmd installation error, since the same error occurs during "dp test". Should I re-install again? I pretty much followed the "install from source code" step by step but maybe I made some mistakes.

@njzjz Update: After resinstalling tensor flow CPU and deepmd-kit carefully. Step 2 finally runs but instead of printing out the JSON file, it gives the output as below: Does this make sense? Thank you! 
```
2024-10-30 19:25:38.534603: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING:tensorflow:From /mnt/isilon/w_ccls/merzklab/Zhen/tensorflow_venv/lib/python3.10/site-packages/tensorflow/python/compat/v2_compat.py:98: disable_resource_variables (from tensorflow.python.ops.resource_variables_toggle) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:root:To get the best performance, it is recommended to adjust the number of threads by setting the environment variables OMP_NUM_THREADS, TF_INTRA_OP_PARALLELISM_THREADS, and TF_INTER_OP_PARALLELISM_THREADS. See https://deepmd.rtfd.io/parallelism/ for more information.
<IPython.core.display.HTML object>
```

**Comment by njzjz** [comment]
> Step 2 finally runs but instead of printing out the JSON file, it gives the output as below: Does this make sense? 

Do you run the script inside a notebook?

Note: the discussion is out of topic. You may start a new discussion instead.
