### ISSUE TITLE
Does deepmd-kit support `atom_style full` when running lammps?

### ISSUE THREAD

**Issue by luowh35** [deepmodeling/deepmd-kit#3673]
### Summary

I want to add an electric field in molecular dynamics and need to use charge information. Can deepmd support the `full` atom_style of atomic configuration? And ensure that the prediction of energy will not be affected by charge information, which is only used to feel the electric field force given by the external electric field.

### DeePMD-kit Version

deepmd --master

### Backend and its version

TensorFlow v2.12.0.

### Details

I want to add an electric field in molecular dynamics and need to use charge information. Can deepmd support the `full` atom_style of atomic configuration? And ensure that the prediction of energy will not be affected by charge information, which is only used to feel the electric field force given by the external electric field.

**Comment by njzjz** [comment]
`atom_style full` has been in the unit test

https://github.com/deepmodeling/deepmd-kit/blob/f8a0b3128e51ee523515cce26e520dde09a973f9/source/lmp/tests/test_dplr.py#L300

**Comment by luowh35** [comment]
> `atom_style full` has been in the unit test
> 
> https://github.com/deepmodeling/deepmd-kit/blob/f8a0b3128e51ee523515cce26e520dde09a973f9/source/lmp/tests/test_dplr.py#L300

Thank you. I noticed that this is used in dplr. If I want to use standard dp, can it be used?

**Comment by njzjz** [comment]
This tests the energy of the standard dp

https://github.com/deepmodeling/deepmd-kit/blob/f8a0b3128e51ee523515cce26e520dde09a973f9/source/lmp/tests/test_dplr.py#L342-L352
