### ISSUE TITLE
LAMMPS fix dplr issue

### ISSUE THREAD

**Issue by cesaremalosso** [deepmodeling/deepmd-kit#3679]
### Summary

`ERROR: find a bonded pair that is not on the same processor, something should not happen (../fix_dplr.cpp:345)` when restart from a previous simulation run.

### DeePMD-kit Version

2.2.3

### Backend and its version

2.13.0

### Details

Hi,

I'm encountering the following error:
`ERROR: find a bonded pair that is not on the same processor, something should not happen (../fix_dplr.cpp:345)`

when I try to restart a LAMMPS run from the previous ended one. I'm using a DPLR model and I'm running it just with 1 MPI process (`mpirun -np 1`) for the LAMMPS `lmp_mpi`. I attach the input file for LAMMPS as well as the two restart file from the previous run

[files.zip](https://github.com/deepmodeling/deepmd-kit/files/15009961/files.zip)

**Comment by cesaremalosso** [comment]
Hi, has this issue been fixed?

**Comment by Yi-FanLi** [comment]
> Hi, has this issue been fixed?

Hi @cesaremalosso, I am sorry that I was so overwhelmed in the past few weeks. In the recent days I have more time. I am working on this issue. Thanks for your patience.

**Comment by cesaremalosso** [comment]
Thank you very much! I have another related question. It seems that the `kspace_style pppm/dplr`, which is used to account for the long-range interactions, is quite slow in LAMMPS, significantly slowing down the MD simulation. Do you think it would be beneficial to implement OpenMP thread parallelization to speed this up? Perhaps using GPUs for both the short-range NNP and the Wannier NN, while using CPU processes for the particle-particle particle-mesh solver?

**Comment by njzjz** [comment]
> Perhaps using GPUs for both the short-range NNP and the Wannier NN, while using CPU processes for the particle-particle particle-mesh solver

This is the current implementation. `pppm/dplr` is based on `pppm` and the pppm solver is implemented in LAMMPS.

I know `pppm` has some variants, such as `pppm/gpu`, `pppm/omp`, `pppm/intel`, but they need to be tested.

Could you raise a separate issue?

**Comment by cesaremalosso** [comment]
Hi @njzjz , I raise a separate issue here: [#4078](https://github.com/deepmodeling/deepmd-kit/issues/4078)

**Comment by Yi-FanLi** [comment]
> Thank you very much @Yi-FanLi ! I have another related question. It seems that the `kspace_style pppm/dplr`, which is used to account for the long-range interactions, is quite slow in LAMMPS, significantly slowing down the MD simulation. Do you think it would be beneficial to implement OpenMP thread parallelization to speed this up? Perhaps using GPUs for both the short-range NNP and the Wannier NN, while using CPU processes for the particle-particle particle-mesh solver?

Hi @cesaremalosso, I am replying to you in #4078 : )
