### ISSUE TITLE
Cannot install deepmd-kit=2.2.8 with conda

### ISSUE THREAD

**Issue by Manyi-Yang** [deepmodeling/deepmd-kit#3697]
### Bug summary

Failed in installing deepmd-kit=2.2.8 with conda

### DeePMD-kit Version

2.2.8

### Backend and its version

deepmd-kit=2.2.8

### How did you download the software?

conda

### Input Files, Running Commands, Error Log, etc.

 conda install deepmd-kit=2.2.8=*gpu libdeepmd=2.2.8=*gpu lammps cudatoolkit=11.6 horovod -c https://conda.deepmodeling.com -c defaults

> horovod -c https://conda.deepmodeling.com -c defaults
Channels:
 - https://conda.deepmodeling.com
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: failed

LibMambaUnsatisfiableError: Encountered problems while solving:
  - package libdeepmd-2.2.8-1_cuda11.6_gpu requires mpich >=4.1.1,<5.0a0, but none of the providers can be installed

Could not solve for environment specs
The following packages are incompatible
├─ cudatoolkit 11.6**  is requested and can be installed;
├─ horovod is installable with the potential options
│  ├─ horovod 0.22.1 would require
│  │  └─ cudatoolkit >=10.1.243,<10.2.0a0* , which conflicts with any installable versions previously reported;
│  ├─ horovod 0.22.1 would require
│  │  └─ tensorflow-base 2.5.0.* mkl*, which requires
│  │     └─ abseil-cpp >=20200923.3,<20200923.4.0a0 , which can be installed;
│  ├─ horovod 0.22.1 would require
│  │  └─ cudatoolkit >=11.3.1,<11.4.0a0* , which conflicts with any installable versions previously reported;
│  ├─ horovod [0.23.0|0.24.1] would require
│  │  └─ cudatoolkit 10.1|10.1.* , which conflicts with any installable versions previously reported;
│  ├─ horovod [0.23.0|0.24.1] would require
│  │  └─ tensorflow 2.7.* cpu*, which requires
│  │     └─ abseil-cpp >=20210324.2,<20210324.3.0a0 , which can be installed;
│  ├─ horovod [0.23.0|0.24.1] would require
│  │  └─ tensorflow 2.7.* cuda* with the potential options
│  │     ├─ tensorflow 2.7.0, which can be installed (as previously explained);
│  │     └─ tensorflow 2.7.0 would require
│  │        └─ cudatoolkit 10.1|10.1.* , which conflicts with any installable versions previously reported;
│  ├─ horovod [0.24.3|0.25.0|0.27.0] would require
│  │  └─ mpich >=3.3.2,<3.4.0a0 , which can be installed;
│  └─ horovod [0.24.3|0.25.0|0.27.0] would require
│     └─ cudatoolkit 10.2|10.2.* , which conflicts with any installable versions previously reported;
├─ lammps is installable with the potential options
│  ├─ lammps 20230802.1 would require
│  │  └─ mpich >=3.3.2,<3.4.0a0 , which can be installed;
│  ├─ lammps [20220623.0|20220623.1|20220623.4|20230802.0], which can be installed;
│  └─ lammps 20230802.1 would require
│     └─ mpich >=4.1.1,<5.0a0 , which conflicts with any installable versions previously reported;
└─ libdeepmd 2.2.8 *gpu is not installable because there are no viable options
   ├─ libdeepmd 2.2.8 would require
   │  ├─ lammps 20230802.1 , which conflicts with any installable versions previously reported;
   │  ├─ libtensorflow_cc 2.9.* cuda* but there are no viable options
   │  │  ├─ libtensorflow_cc 2.9.0 would require
   │  │  │  └─ abseil-cpp >=20211102.0,<20211102.1.0a0 , which conflicts with any installable versions previously reported;
   │  │  └─ libtensorflow_cc 2.9.0 would require
   │  │     └─ cudatoolkit 10.2|10.2.* , which conflicts with any installable versions previously reported;
   │  └─ mpich >=4.1.1,<5.0a0 , which conflicts with any installable versions previously reported;
   └─ libdeepmd 2.2.8 would require
      └─ cudatoolkit 10.2|10.2.* , which conflicts with any installable versions previously reported.

### Steps to Reproduce

conda create -n deepmd-kit
conda activate deepmd-kit
 conda install deepmd-kit=2.2.8=*gpu libdeepmd=2.2.8=*gpu lammps cudatoolkit=11.6 horovod -c https://conda.deepmodeling.com -c defaults

**Comment by njzjz** [comment]
It should be fixed. The new package is deployed.
