### ISSUE TITLE
the number of atomic species in the training set does not match the species in the trained model

### ISSUE THREAD

**Issue by wangyi01** [deepmodeling/deepmd-kit#3708]
### Summary

I wrote a script following this example, but encountered a problem where the number of atomic species in the training set does not match the species in the trained model."

### This example
https://github.com/deepmodeling/deepmd-kit/blob/master/doc/train/finetuning.md

**Comment by wangyi01** [comment]
![wecom-temp-138509-42dec86cd1008464da0b5ed33d96e912](https://github.com/deepmodeling/deepmd-kit/assets/163240721/892218fc-05cf-4703-902c-83c607acbd05)

**Comment by wangyi01** [comment]
[train-2.json](https://github.com/deepmodeling/deepmd-kit/files/15093227/train-2.json)

**Comment by iProzd** [comment]
I've tried v2.2.1(the same image reported) and v2.2.7, using the same model OC_10M.pb to finetune on the examples/water/se_atten/input.json, and they both work well. 

And I also tried simply change the type_map to ['H', 'O'] and training data in [train-2.json](https://github.com/deepmodeling/deepmd-kit/files/15093227/train-2.json) attached here, to doing finetune as well, they aslo work well. 

Please check the data and maybe try to first directly finetune using examples/water/se_atten/input.json with command `dp train input.json --finetune OC_10M.pb`. If it still raises error, please attach a more reproducable data and input file.
