### ISSUE TITLE
[BUG] _Mismatch between header and data in `lcurve.out`

### ISSUE THREAD

**Issue by thangckt** [deepmodeling/deepmd-kit#3765]
### Bug summary

It is seemly that `nan` values are not printed in `lcurve.out`
My `lcurve.out` like this
```
#  step      rmse_val    rmse_trn    rmse_e_val  rmse_e_trn    rmse_f_val  rmse_f_trn         lr
# If there is no available reference data, rmse_*_{val,trn} will print nan
      0      8.14e+00      2.00e-01      2.57e-01    1.0e-03
   1000      3.23e-01      1.84e-03      1.59e-01    3.2e-06
```

### DeePMD-kit Version

v3.0.0a1.dev146+g6c715d14

### Backend and its version

Pytorch 2.3.0

### How did you download the software?

Offline packages

### Input Files, Running Commands, Error Log, etc.

.

### Steps to Reproduce

.

**Comment by njzjz** [comment]
The header is wrong when there's no validation data.
