### ISSUE TITLE
[BUG] Consistent test for DPA2 only reaches around 1e-10 atol between pt & dp

### ISSUE THREAD

**Issue by iProzd** [deepmodeling/deepmd-kit#3786]
### Bug summary

Consistent test for DPA2 only reaches around 1e-10 atol between pt & dp.
Located in `repformer_update_g1_has_attn` but still needs figuring out.

### DeePMD-kit Version

3.0.0a

### Backend and its version

 PyTorch v2.1.2

### How did you download the software?

Offline packages

### Input Files, Running Commands, Error Log, etc.

See above.

### Steps to Reproduce

See above.

### Further Information, Files, and Links

See above.

**Comment by njzjz** [comment]
Do we want to resolve the issue or close it?

**Comment by iProzd** [comment]
We should close it, since it's a numerical error which has been discussed.
