### ISSUE TITLE
An error occurred while using the init-model tool to add a new dataset for model training

### ISSUE THREAD

**Issue by 676954172** [deepmodeling/deepmd-kit#3795]
### Summary

When I use the init-model tool to add a new dataset for model training, I encountered the following error: "There was a problem executing the operation 'save/Assign 3'. The root cause of the error is an attempt to assign a tensor of shape [4, 928] to a tensor of shape [4, 464], but the shapes of these two tensors do not match.

In TensorFlow, when you try to use tf.assign or when saving and restoring a model, the tensor being assigned (lhs, left-hand side) and the tensor being assigned from (rhs, right-hand side) must have the same shape."

In my new input file, apart from the dataset, I haven't modified any other parameters. Why am I unable to train the model?

### DeePMD-kit Version

DeePMD-kit v2.2.7

### Backend and its version

tensorflow v2.9.0

### Python Version, CUDA Version, GCC Version, LAMMPS Version, etc

cuda

### Details

When I use the init-model tool to add a new dataset for model training, I encountered the following error: "There was a problem executing the operation 'save/Assign 3'. The root cause of the error is an attempt to assign a tensor of shape [4, 928] to a tensor of shape [4, 464], but the shapes of these two tensors do not match.

In TensorFlow, when you try to use tf.assign or when saving and restoring a model, the tensor being assigned (lhs, left-hand side) and the tensor being assigned from (rhs, right-hand side) must have the same shape."

In my new input file, apart from the dataset, I haven't modified any other parameters. Why am I unable to train the model?

**Comment by njzjz** [comment]
Did you meet the same situation as #2735?

**Comment by njzjz** [comment]
I close this issue as there is no active task for developers.
