### ISSUE TITLE
cudatoolkit 11.0 doesn't support compute_86

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/deepmd-kit#384]
https://github.com/deepmodeling/deepmd-kit/blob/b3b2662e1276409e269df41f5dabef612e308c14/source/op/cuda/CMakeLists.txt#L32

compute_86 is only supported in cudatoolkit >= 11.1

related PRs: #353, #354

**Comment by amcadmus** [comment]
can be closed if #390 solves this issue @njzjz
