### ISSUE TITLE
The phonon spectrums calculated using the cpu version and gpu version are different？

### ISSUE THREAD

**Issue by wanghaopku** [deepmodeling/deepmd-kit#386]
The cpu or gpu version is installed using the conda ：
conda install deepmd-kit=*=*cpu lammps-dp=*=*cpu -c deepmodeling or
 conda install deepmd-kit=*=*gpu lammps-dp=*=*gpu -c deepmodeling，
 then I installed the lammp-dp python interface by using  : conda install -c deepmodeling pylammps-dp；
 then installed the phonolammps using ：pip install phonolammps
 
 However，the calculated phonon spectrums are very different！It seems the CPU Version give the correct result，while the GPU version is not.
 
attached is files used for calculations.

I wondered whether i did mistakes in my calculations? or it's a bug?
[DP.zip](https://github.com/deepmodeling/deepmd-kit/files/6059682/DP.zip)

**Comment by amcadmus** [comment]
Which version of the DeePMD-kit did you use?

**Comment by wanghaopku** [comment]
the lammps output showes  it's  v1.3.0-4-g4002aa5,   but the “conda list” showes it's  1.3.1

**Comment by amcadmus** [comment]
Thanks we will fix it asap

**Comment by amcadmus** [comment]
> 
> 
> the lammps output showes it's v1.3.0-4-g4002aa5, but the “conda list” showes it's 1.3.1

@njzjz do you have any idea of the inconsistency?

**Comment by njzjz** [comment]
> > the lammps output showes it's v1.3.0-4-g4002aa5, but the “conda list” showes it's 1.3.1
> 
> @njzjz do you have any idea of the inconsistency?

Because we made the package before `git tag`.

**Comment by njzjz** [comment]
I am not sure, but it may have been fixed by #334.

**Comment by amcadmus** [comment]
> 
> 
> I am not sure, but it may have been fixed by #334.

The same idea. 

> 
> 
> > > the lammps output showes it's v1.3.0-4-g4002aa5, but the “conda list” showes it's 1.3.1
> > 
> > 
> > @njzjz do you have any idea of the inconsistency?
> 
> Because we made the package before `git tag`.

I see. we should firstly release then make the package.

**Comment by amcadmus** [comment]
@wanghaopku  Please try v1.3.2 and tell us if the new release fixes the reported bug
https://github.com/deepmodeling/deepmd-kit/releases/tag/v1.3.2

**Comment by wanghaopku** [comment]
i try  the V1.3.2 version, now the gpu result is correct as well as the cpu version！Thanks a lot！
