### ISSUE TITLE
Only the last set.xxxx of a LabeledSytem is tested in 'dp test'

### ISSUE THREAD

**Issue by Carrotkingdom** [deepmodeling/deepmd-kit#3860]
### Bug summary

When I do  
```shell
dp test -m model.ckpt.pt -s data
``` 
only the last of ``` set.000 set.001 set.002 set.003....``` is used during the test, when it contains more than one set.

### DeePMD-kit Version

3.0.0

### Backend and its version

PT ver:                v2.3.0+cu121-g97ff6cfd9c8

### How did you download the software?

pip

### Input Files, Running Commands, Error Log, etc.

dp test -m model.ckpt.pt -s data

### Steps to Reproduce

1. prepare a dataset that contains a large System (more than 2000 frames with the same chemical composition).
2. dump it to deepmd/npy/mix format using dpdata
3. RUN: dp test -m model.ckpt.pt -s data
4. you'll find only the last set is used

**Comment by njzjz** [comment]
This is the designed behavior, which has never changed since 7 years ago. See #2063.
However, we may discuss whether to change the behavior in v3. cc @wanghan-iapcm @iProzd

**Comment by njzjz** [comment]
Btw, finetune also uses the last set.
