### ISSUE TITLE
coord.xyz and deepmd-kit for MacOS

### ISSUE THREAD

**Issue by dingye18** [deepmodeling/deepmd-kit#39]
Can you provide the an example of coord.xyz for ipi example? Such as water model as you used in paper.
Besides, deepmd-kit does not support running on macos, aren't they? 
I checked the code on `Model.py` and `CMakeLists`, you just load the `*.so` for op_library, but on MacOS, it will build a `*.dylib` files but `.so` files.
Will you provide a version of deepmd-kit on MacOS for test only?

**Comment by njzjz** [comment]
MacOS has been supported by #95.
