### ISSUE TITLE
[BUG] Zero thermal conductivity results when using DPA-2 model in 2024Q1 branch

### ISSUE THREAD

**Issue by iProzd** [deepmodeling/deepmd-kit#3904]
### Bug summary

When using DPA-2 model in 2024Q1 branch trained with virial switched on, the lammps results will give thermal conductivity around zero.

The training is in multitask-finetune mode, but I think it's the same doing single-task from scratch. Training data(example)/input and input for lammps are in attached files:
[tc-test.zip](https://github.com/user-attachments/files/15973472/tc-test.zip)

The thermal conductivity calculation script:
[cal.zip](https://github.com/user-attachments/files/15973485/cal.zip)

The thermal conductivity results is:
![img_v3_02c6_bfdc7e2c-1685-40ca-9bba-c5d1d17c740g](https://github.com/deepmodeling/deepmd-kit/assets/50307526/25398c2c-dace-4973-b096-ec088d83450d)

### DeePMD-kit Version

2024Q1

### Backend and its version

 PyTorch v2.1.2

### How did you download the software?

Built from source

### Input Files, Running Commands, Error Log, etc.

See above.

### Steps to Reproduce

See above.

**Comment by njzjz** [comment]
Is the 2024Q1 branch still maintained? If not we can close this issue.
