### ISSUE TITLE
[BUG] lmp: error while loading shared libraries: libpnetcdf.so.4: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by leeeru1987** [deepmodeling/deepmd-kit#3923]
### Bug summary

when I installed the offline package deepmdkit v2.2.10 (rebuild on 2024.6.8), and run the lmp -h, I got the error
lmp: error while loading shared libraries: libpnetcdf.so.4: cannot open shared object file: No such file or directory

### DeePMD-kit Version

v2.2.10

### Backend and its version

TensorFlow v2.15.0

### How did you download the software?

Offline packages

### Input Files, Running Commands, Error Log, etc.

lmp -h

### Steps to Reproduce

1, install the off-line package 2.2.10
2, lmp -h
lmp: error while loading shared libraries: libpnetcdf.so.4: cannot open shared object file: No such file or directory

**Comment by njzjz** [comment]
I submitted https://github.com/conda-forge/lammps-feedstock/issues/199 to the upstream repository, but it's fine to pin the libpnetcdf version in the offline package as a workaround.

**Comment by njzjz** [comment]
The offline package has been rebuilt. The issue of the LAMMPS package itself can be tracked in https://github.com/conda-forge/lammps-feedstock/issues/199, as it is not related to DeePMD-kit codes.

**Comment by chazeon** [comment]
@njzjz The deepmd-kit feedstock currently depends on the Aug2023 version of LAMMPS, which has this issue. Currently one need to downgrade libpnetcdf to libpnetcdf=1.12. Maybe upgrade the LAMMPS dependencies version in the deepmd-kit feedstock or pin the libpnetcdf inside deepmd-kit feedstock?

**Comment by njzjz** [comment]
> @njzjz The deepmd-kit feedstock currently depends on the Aug2023 version of LAMMPS, which has this issue. Currently one need to downgrade libpnetcdf to libpnetcdf=1.12. Maybe upgrade the LAMMPS dependencies version in the deepmd-kit feedstock or pin the libpnetcdf inside deepmd-kit feedstock?

DeePMD-kit doesn't directly depend on libpnetcdf. Instead, LAMMPS should be patched as requested in https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/787.

**Comment by chazeon** [comment]
> > @njzjz The deepmd-kit feedstock currently depends on the Aug2023 version of LAMMPS, which has this issue. Currently one need to downgrade libpnetcdf to libpnetcdf=1.12. Maybe upgrade the LAMMPS dependencies version in the deepmd-kit feedstock or pin the libpnetcdf inside deepmd-kit feedstock?
> 
> DeePMD-kit doesn't directly depend on libpnetcdf. Instead, LAMMPS should be patched as requested in [conda-forge/conda-forge-repodata-patches-feedstock#787](https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/787).

OK. That makes sense. Hope those old LAMMPS versions get patched soon.
