### ISSUE TITLE
[Feature Request] append to existing lcurve for restart training

### ISSUE THREAD

**Issue by anyangml** [deepmodeling/deepmd-kit#4039]
### Summary

Currently, when restart a training, the `lcurve.out` file will be overwritten. Maybe it's more natural to keep adding to the existing file, so that we can keep the entire training history in a single file.

### Detailed Description

When a training crashes, and I would like to restart it from the latest ckpt, I have to move the ckpt and input file into a separate folder to prevent log files from being overwritten. This creates more complexity for downstream workflows such as training history visualization. If there is no technical issue, I believe adding to the existing log file is a more desirable behavior than overwriting it.

**Comment by njzjz** [comment]
> Currently, when restart a training, the `lcurve.out` file will be overwritten.

I don't reproduce it using the water example. Do you have any specific configuration (e.g. multi-task)?

**Comment by anyangml** [comment]
Interesting, this happens to me for both single-task and multi-task. Maybe it's something associated with the cloud server, Ali-Pai, I will look into that.

**Comment by njzjz** [comment]
Are you sure the latest code is used?

**Comment by anyangml** [comment]
I see, I didn't notice this is already available.
