### ISSUE TITLE
[BUG] Numpy version causing errors.

### ISSUE THREAD

**Issue by aersilang** [deepmodeling/deepmd-kit#4050]
### Bug summary

When I was using the dptest feature, the following error occurred:  A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.1 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.
......
TypeError: Unable to convert function return value to a Python type! The signature was
        () -> handle
When I downgraded the NumPy version, the following error occurred: WARNING: Error parsing requirements for numpy: [Errno 2] No such file or directory: '/opt/deepmd-kit-2.1.5/lib/python3.10/site-packages/numpy-2.0.1.dist-info/METADATA'
Installing collected packages: numpy
  Attempting uninstall: numpy
    WARNING: No metadata found in /opt/deepmd-kit-2.1.5/lib/python3.10/site-packages
    Found existing installation: numpy 2.0.1
    WARNING: No metadata found in /opt/deepmd-kit-2.1.5/lib/python3.10/site-packages
    WARNING: No metadata found in /opt/deepmd-kit-2.1.5/lib/python3.10/site-packages
    WARNING: No metadata found in /opt/deepmd-kit-2.1.5/lib/python3.10/site-packages
    WARNING: No metadata found in /opt/deepmd-kit-2.1.5/lib/python3.10/site-packages
    WARNING: No metadata found in /opt/deepmd-kit-2.1.5/lib/python3.10/site-packages
ERROR: Cannot uninstall numpy 2.0.1, RECORD file not found. You might be able to recover from this via: 'pip install --force-reinstall --no-deps numpy==2.0.1'.
Other potentially useful files have been placed in the attachment. Please let me know if further information is needed.

### DeePMD-kit Version

 deepmd-kit:2.1.5-cuda11.6

### Backend and its version

Tensorflow v2.9.0

### How did you download the software?

Offline packages

### Input Files, Running Commands, Error Log, etc.

when first time I want to use dptest , I got
[firsttimedptest.txt](https://github.com/user-attachments/files/16511149/firsttimedptest.txt)
then I try to downrage numpy ,I got:
[numpy.txt](https://github.com/user-attachments/files/16511191/numpy.txt)

### Steps to Reproduce

When you check the version number of TensorFlow using the this version of DeepMDKit, you are likely to encounter this problem.
the my use one is 
deepmd-kit:2.1.5-cuda11.6

**Comment by njzjz** [comment]
How did you do the installation? v2.1.5 was released two years ago and numpy v2.0.1 was released just two weeks ago. It's impossible that numpy v2.0.1 is inside of the offline packages of v2.1.5.

**Comment by aersilang** [comment]
I apologize for my naive question. I must tell you that v2.1.5 is the recommended configuration when choosing an image. After I switched the image, there was no 'graph.pb' file in iter000000 (the first iteration). Using the 'frozen_model.pb' file from the 000 folder does not allow me to perform dptest and it reports an error: 

 W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
WARNING:tensorflow:From /opt/mamba/lib/python3.10/site-packages/tensorflow/python/compat/v2_compat.py:98: disable_resource_variables (from tensorflow.python.ops.resource_variables_toggle) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
[2024-08-11 00:46:04,444] DEEPMD WARNING To get the best performance, it is recommended to adjust the number of threads by setting the environment variables OMP_NUM_THREADS, DP_INTRA_OP_PARALLELISM_THREADS, and DP_INTER_OP_PARALLELISM_THREADS. See https://deepmd.rtfd.io/parallelism/ for more information.
Traceback (most recent call last):
  File "/opt/mamba/bin/dp", line 8, in <module>
    sys.exit(main())
  File "/opt/mamba/lib/python3.10/site-packages/deepmd/main.py", line 807, in main
    deepmd_main(args)
  File "/opt/mamba/lib/python3.10/site-packages/deepmd/entrypoints/main.py", line 64, in main
    test(**dict_args)
  File "/opt/mamba/lib/python3.10/site-packages/deepmd/entrypoints/test.py", line 130, in test
    dp = DeepEval(model, head=head)
  File "/opt/mamba/lib/python3.10/site-packages/deepmd/infer/deep_eval.py", line 307, in __new__
    deep_eval = DeepEvalBackend(
  File "/opt/mamba/lib/python3.10/site-packages/deepmd/tf/infer/deep_eval.py", line 103, in __init__
    self.graph = self._load_graph(
  File "/opt/mamba/lib/python3.10/site-packages/deepmd/tf/infer/deep_eval.py", line 365, in _load_graph
    graph_def.ParseFromString(f.read())
google.protobuf.message.DecodeError: Error parsing message.

 Is this normal?

**Comment by njzjz** [comment]
Do you have an example file?

**Comment by njzjz** [comment]
I close this issue as there is no active task for developers.
