### ISSUE TITLE
[BUG] When using the GROMACS plugin with pytorch on the backend, a "free(): invalid pointer" error is reported

### ISSUE THREAD

**Issue by duqi-hnu** [deepmodeling/deepmd-kit#4077]
### Bug summary

The platform is ARM64.
When using the GROMACS plugin with pytorch on the backend, a "free(): invalid pointer" error is reported.
The specific error information is as follows:
--------------------------------------
Init deepmd plugin from: input.json
Setting lambda: 1
Setting pbc: 1
Number of atoms: 768
Begin Init Model: graph.pth
load model from: graph.pth to cpu 
free(): invalid pointer
Aborted
--------------------------------------

### DeePMD-kit Version

DeePMD-kit v3.0.0b3

### Backend and its version

Pytorch 2.1.0

### How did you download the software?

Offline packages

### Input Files, Running Commands, Error Log, etc.

input.json
--------------
{
  "graph_file": "graph.pth",
  "type_file": "type.raw",
  "index_file": "index.raw",
  "lambda": 1.0
}
-----------------

Running Commands
-----------------
export OMP_NUM_THREADS=2
export GMX_DEEPMD_INPUT_JSON=input.json
gmx_mpi grompp -f md.mdp -c water.gro -p water.top -o md.tpr -maxwarn 3
gmx_mpi mdrun -deffnm md
------------------

Log
------------------
No protocol specified
               :-) GROMACS - gmx mdrun, 2020.2-dev-UNCHECKED (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar      Christian Blau   Viacheslav Bolnykh     Kevin Boyd    
 Aldert van Buuren   Rudi van Drunen     Anton Feenstra       Alan Gray     
  Gerrit Groenhof     Anca Hamuraru    Vincent Hindriksen  M. Eric Irrgang  
  Aleksei Iupinov   Christoph Junghans     Joe Jordan     Dimitrios Karkoulis
    Peter Kasson        Jiri Kraus      Carsten Kutzner      Per Larsson    
  Justin A. Lemkul    Viveca Lindahl    Magnus Lundborg     Erik Marklund   
    Pascal Merz     Pieter Meulenhoff    Teemu Murtola       Szilard Pall   
    Sander Pronk      Roland Schulz      Michael Shirts    Alexey Shvetsov  
   Alfons Sijbers     Peter Tieleman      Jon Vincent      Teemu Virolainen 
 Christian Wennberg    Maarten Wolf      Artem Zhmurov   
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spoel

Copyright (c) 1991-2000, University of Groningen, The Netherlands.
Copyright (c) 2001-2019, The GROMACS development team at
Uppsala University, Stockholm University and
the Royal Institute of Technology, Sweden.
check out http://www.gromacs.org for more information.

GROMACS is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License
as published by the Free Software Foundation; either version 2.1
of the License, or (at your option) any later version.

GROMACS:      gmx mdrun, version 2020.2-dev-UNCHECKED
Executable:   /home/duqi/pytorch/gromacs-2020.2-deepmd/bin//gmx_mpi
Data prefix:  /home/duqi/pytorch/gromacs-2020.2-deepmd
Working dir:  /home/duqi/pytorch/deepmd-kit-3.0.0b3/examples/water/gmx-0
Command line:
  gmx_mpi mdrun -deffnm md

Back Off! I just backed up md.log to ./#md.log.5#
No protocol specified
Reading file md.tpr, VERSION 2020.2-dev-UNCHECKED (single precision)
Changing nstlist from 10 to 100, rlist from 0.8 to 0.8

Using 1 MPI process
Using 2 OpenMP threads 

NOTE: The number of threads is not equal to the number of (logical) cores
      and the -pin option is set to auto: will not pin threads to cores.
      This can lead to significant performance degradation.
      Consider using -pin on (and -pinoffset in case you run multiple jobs).

WARNING: There are no atom pairs for dispersion correction
Init deepmd plugin from: input.json
Setting lambda: 1
Setting pbc: 1
Number of atoms: 768
Begin Init Model: graph.pth
load model from: graph.pth to cpu 
free(): invalid pointer
Aborted
------------------

### Steps to Reproduce

Step 1: Train the model
-----------------------
cd deepmd-kit-3.0.0b3/examples/water/se_e2_a
dp --pt train input.json
-----------------------
Step 2: Execute
-----------------------
cd ../gmx
export OMP_NUM_THREADS=2
export GMX_DEEPMD_INPUT_JSON=input.json
gmx_mpi grompp -f md.mdp -c water.gro -p water.top -o md.tpr -maxwarn 3
gmx_mpi mdrun -deffnm md
-----------------------

**Comment by njzjz** [comment]
Could you use gdb to debug which line throws this error?

**Comment by duqi-hnu** [comment]
After investigation, this is an error caused by the system environment configuration.
