### ISSUE TITLE
Error installing lammps from USER-DEEPMD

### ISSUE THREAD

**Issue by mayankaditya** [deepmodeling/deepmd-kit#4086]
### Summary

Hi, I am trying to install the lammps with USER-DEEPMD. I followed the procedure as described in the webpage. However I am getting the following error:
/home/mayank/SOFTWARE/lammps/bin/../lib/gcc/x86_64-conda-linux-gnu/11.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/mayank/SOFTWARE/lammps/lib/libdeepmd_c.so: undefined reference to `memcpy@GLIBC_2.14'

Please advise.

Thanks,
Mayank

### DeePMD-kit Version

2.2.11

### Backend and its version

TensorFlow v2.15.0

### Details

Hi, I am trying to install the lammps with USER-DEEPMD. I followed the procedure as described in the webpage. However I am getting the following error:
/home/mayank/SOFTWARE/lammps/bin/../lib/gcc/x86_64-conda-linux-gnu/11.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/mayank/SOFTWARE/lammps/lib/libdeepmd_c.so: undefined reference to `memcpy@GLIBC_2.14'

Please advise.

Thanks,
Mayank

**Comment by njzjz** [comment]
> /home/mayank/SOFTWARE/lammps/bin/../lib/gcc/x86_64-conda-linux-gnu/11.4.0/../../../../x86_64-conda-linux-gnu/bin/ld: /home/mayank/SOFTWARE/lammps/lib/libdeepmd_c.so: undefined reference to `memcpy@GLIBC_2.14'

It looks to me like you compiled `libdeepmd_c.so` with a higher GLIBC version and then used `ld` with a lower GLIBC version.

**Comment by njzjz** [comment]
I close this issue as there is no active task for developers.
