### ISSUE TITLE
How to using a FP64 model with FP32 precision

### ISSUE THREAD

**Issue by MoseyQAQ** [deepmodeling/deepmd-kit#4102]
### Summary

Dear developers,

I have a model that was trained with the default FP64 precision. How can I use this model to predict forces, energies, or run MD simulations with LAMMPS using FP32 precision? I tried setting the environment variable <kbd>export DP_INTERFACE_PREC=low</kbd> when running LAMMPS, but it doesn't seem to work.

Do I need to retrain the model with FP32 precision?

### DeePMD-kit Version

2.2.7

### Backend and its version

TensorFlow v2.9.0

### Python Version, CUDA Version, GCC Version, LAMMPS Version, etc

I use an offline installation package, running on Linux.

### Details

Runscript:
```Bash
source /shared_apps/deepmd-kit/2.2.7/bin/activate /shared_apps/deepmd-kit/2.2.7

nvidia-smi dmon -s pucvmt -o T -f nvsmi.log &

export DP_INTERFACE_PREC=low
mpirun -np 1 lmp_mpi -i input.lammps

killall nvidia-smi
```

**Comment by njzjz** [comment]
The precision of the model is stored in the model and cannot be changed after the model is frozen.
