### ISSUE TITLE
DPA-1-OC2M mapping issue

### ISSUE THREAD

**Issue by ZLI-afk** [deepmodeling/deepmd-kit#4107]
### Summary

When I try to run energy minimization of **HCP Ti** by `LAMMPS` via [DPA-1_OC2M](https://www.aissquare.com/models/detail?pageType=models&name=DPA_1_OC2M&id=62), I found different prediction result with two different mapping scheme. I wonder which one is correct. (the alphabetic FULL mapping list is adopted according to `input.json` from https://www.aissquare.com/datasets/detail?pageType=datasets&name=Open_Catalyst_2020(OC20_Dataset))

- FULL list mapping:
[relax_task_full_list.tar.gz](https://github.com/user-attachments/files/16902649/relax_task_full_list.tar.gz)

- Single element mapping:
[relax_task_single.tar.gz](https://github.com/user-attachments/files/16902651/relax_task_single.tar.gz)

### DeePMD-kit Version

v2.1.5

### Backend and its version

commit: 6e3d4a62

### Python Version, CUDA Version, GCC Version, LAMMPS Version, etc

"image_name": "registry.dp.tech/dptech/prod-11045/phonolammps-dpmd:2.1.5"

### Details

As described in the summary section

**Comment by njzjz** [comment]
Assigning the type map via `pair_coeff` (#2267) was added in v2.2.0.
