### ISSUE TITLE
[Feature Request] Support `eval_descriptor` for PT `DeepEval`

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/deepmd-kit#4112]
### Summary

Support `eval_descriptor` for PT `DeepEval`.

### Detailed Description

The abstract method is here:

https://github.com/deepmodeling/deepmd-kit/blob/d2b624304dc9a5273c3c023914c0ff4304e3225d/deepmd/infer/deep_eval.py#L172-L222

However, how to do it for PT needs to be clarified. PT descriptor has a different `forward` method.

**Comment by Chengqian-Zhang** [comment]
I implemented this function some time ago by copying all the `forward` related code before descriptor to `eval_descriptor`, but I think this implementation is rather redundant.

**Comment by njzjz** [comment]
```
    def fail(self, *args, **kwargs):
>       raise RuntimeError(name + " is not supported on ScriptModules")
E       RuntimeError: register_forward_hook is not supported on ScriptModules

../../anaconda3/lib/python3.10/site-packages/torch/jit/_script.py:981: RuntimeError
```
