### ISSUE TITLE
Undefined key "modifier" is not allowed in strict model for running DPLR model

### ISSUE THREAD

**Issue by tingguangli** [deepmodeling/deepmd-kit#4128]
### Summary

Undefined key "modifier" is not allowed in strict model for running DPLR model

### DeePMD-kit Version

DeePMD-kit v2.2.9

### Backend and its version

did not print

### Details

Hi All,

I have an issue (Undefined key "modifier" is not allowed in the strict model ) when I used the DPLR model to capture the long-range order behavior:
Here is a part of my input.json file:
 "descriptor" :{
            "type":             "se_e2_a",
            "sel":              "auto",
            "rcut_smth":        1.5,
            "rcut":             9.0,
            "neuron":           [20, 40, 60],
            "resnet_dt":        false,
            "axis_neuron":      16,
            "seed":             1,
            "_comment":         " that's all"
        },
        "fitting_net" : {
            "type":             "dipole",
            "dipole_type":      [0],
            "neuron":           [120, 120, 120],
            "resnet_dt":        true,
            "seed":             1,
            "_comment":         " that's all"
        },
        "_comment":     " that's all"
    },
  "loss" :{
        "type":         "tensor",
        "pref":          0.0,
        "pref_atomic":   1.0
    },
     "modifier": {
            "type":             "dipole_charge",
            "model_name":       "dw.pb",
            "model_charge_map": [-8],
            "sys_charge_map":   [6, 1],
            "ewald_h":          1.00,
            "ewald_beta":       0.40
	},

Also, I saw in the introduction of the DPLR manual that besides the input files for the traditional training model, there are also other input files like atomic_dipole.npy that are required for training, does DeePMD have a tutorial for how to get those files for specific systems? (So far I only have the input.json and post-processed files by dpdata after VASP calculation.) 

Thanks a lot!

**Comment by njzjz** [comment]
Your `modifier` is out of the `model` scope. It should be within the `model` scope.

**Comment by tingguangli** [comment]
Hi Jingzhe,

Thanks for your reply! Can you be more specific for what do you mean by my modifier is out of the model scope?

Thanks a lot!

Best Regards,
Tingguang

**Comment by njzjz** [comment]
It looks to me your file is something like this:
```json
{
  "model": {
    "descriptor": {},
    "fitting_net": {}
  },
  "loss": {},
  "modifier": {}
}
```

**Comment by tingguangli** [comment]
Hi Jingzhe,

Thanks for your suggestion! After I changed "modifier" into the model scale, it has the following error:
tensorflow.python.framework.errors_impl.NotFoundError: dw.pb; No such file or directory

I think it is due to the lack of the dw.pb file. 

Do you have any idea that how to get the required input files introduced in DPLR manual page:https://docs.deepmodeling.com/projects/deepmd/en/r2/model/dplr.html

Thanks a lot!
Tingguang

**Comment by tingguangli** [comment]
An additional comment to this that when I commented out the modifier the training model running normally, but I believe the modifier is required for DPLR model training as it stated in the DPLR mannual

**Comment by njzjz** [comment]
Could you watch this tutorial: https://www.youtube.com/watch?v=j6SuMXjaXuo

**Comment by tingguangli** [comment]
That's very helpful! Thanks a lot!

**Comment by njzjz** [comment]
I close this issue as there is no active task for developers.
