### ISSUE TITLE
[Feature Request] Uncertainty metric

### ISSUE THREAD

**Issue by akwarii** [deepmodeling/deepmd-kit#4164]
### Summary

Add an uncertainty / extrapolation metric to dp descriptors

### Detailed Description

As I'm not too familiar with the new DPA architectures this idea was mostly based on the original DP-SE descriptors but from my understanding it should be applicable to other (all ?) DP descriptors such as the DPA ones. 

Currently, there is no existing way to know if a potential is giving bad results. Of course, unphysical results are easy to find just by looking at the results but during complex events, such as phase transformation or dislocation motion, it is currenly not possible to know if one potential is behaving correctly. To address this problem, an uncertainty / extrapolation metric  could enhance interpretability. In my (maybe wrong) opinion the MaxVol algorithm used by both ACE and MTP frameworks can be directly applied to the descriptor matrix.

**Comment by wanghan-iapcm** [comment]
The dp has [the model deviation](https://docs.deepmodeling.com/projects/deepmd/en/r2/test/model-deviation.html#calculate-model-deviation) for measuring the prediction uncertianty.

**Comment by akwarii** [comment]
Isn't this feature available only during the active learning loop ?

**Comment by wanghan-iapcm** [comment]
Usually 4 models are enough for estimate the uncertainty.

**Comment by akwarii** [comment]
Yes, and my point is that it's impossible to do so during a simulations and get this feedback on the fly

**Comment by wanghan-iapcm** [comment]
You can with lammps, https://docs.deepmodeling.com/projects/deepmd/en/r2/third-party/lammps-command.html#pair-style-deepmd
```
pair_style deepmd graph_0.pb graph_1.pb graph_2.pb out_file md.out out_freq 10 
```
model deviation is calculated every 10 time steps. Note the dynamics of the system is always driven by the first model, thus the overhead of the model deviation is marginal and can be made even smaller by increasing `out_freq`

**Comment by wanghan-iapcm** [comment]
You can with lammps, https://docs.deepmodeling.com/projects/deepmd/en/r2/third-party/lammps-command.html#pair-style-deepmd
```
pair_style deepmd graph_0.pb graph_1.pb graph_2.pb out_file md.out out_freq 10 
```
model deviation is calculated every 10 time steps. Note the dynamics of the system is always driven by the first model, thus the overhead of the model deviation is marginal and can be made even smaller by increasing `out_freq`

**Comment by njzjz** [comment]
I close this issue as there is no active task for developers.
