### ISSUE TITLE
Compilation error in LAMMPS package USER-DEEPMD

### ISSUE THREAD

**Issue by luizfcpe** [deepmodeling/deepmd-kit#4174]
### Summary

I am compiling LAMMPS with the USER-DEEPMD package following the same steps I have used dozens of times on different machines. First I clone deepmd-kit from github, install with pip and make the USER-DEEPMD lammps package. Moving on to lammps/src I include the package and try to make. The error message indicates a series of undefined references in deepmd.hpp such as `DP_NewNlist', `DP_NlistCheckOK', `DP_DeleteChar' and others.

### DeePMD-kit Version

v2.2.12.dev2+g440bb821 installed from source: wget from github+pip

### Backend and its version

tensorflow 2.17.0 

### Python Version, CUDA Version, GCC Version, LAMMPS Version, etc

Python 3.10.14, no CUDA, gcc version 11.4.0, LAMMPS 27 Jun 2024

### Details

Code compiles without errors if package USER-DEEPMD is not included, but gives undefined references in deepmd.hpp if it is included.

mpicxx -g -O3 -std=c++11 main.o -L/Users/pereira/deepmd-kit/source/build/deepMD/lib  -L/Users/pereira/deepmd-kit/source/build/deepMD/lib   -L/home/boi/luiz-pereira/miniforge3/lib/python3.10/site-packages/tensorflow -L/home/boi/luiz-pereira/Programs/deepmd-kit/source/build/deepMD/lib     -L. -llammps_mpi      -ldl  -o ../lmp_mpi
/usr/bin/ld: ./liblammps_mpi.a(compute_deeptensor_atom.o): in function `deepmd::hpp::InputNlist::InputNlist(int, int*, int*, int**)':
/home/boi/luiz-pereira/Programs/deepmd-kit/source/build/deepMD/include/deepmd/deepmd.hpp:572: undefined reference to `DP_NewNlist'
/usr/bin/ld: /home/boi/luiz-pereira/Programs/deepmd-kit/source/build/deepMD/include/deepmd/deepmd.hpp:573: undefined reference to `DP_NlistCheckOK'
/usr/bin/ld: /home/boi/luiz-pereira/Programs/deepmd-kit/source/build/deepMD/include/deepmd/deepmd.hpp:573: undefined reference to `DP_DeleteChar'
/usr/bin/ld: /home/boi/luiz-pereira/Programs/deepmd-kit/source/build/deepMD/include/deepmd/deepmd.hpp:573: undefined reference to `DP_DeleteChar'
/usr/bin/ld: ./liblammps_mpi.a(compute_deeptensor_atom.o): in function `void _DP_DeepTensorComputeNList<double>(DP_DeepTensor*, int, double const*, int const*, double const*, int, DP_Nlist const*, double*, double*, double*, double**, double*, int*)':
/home/boi/luiz-pereira/Programs/deepmd-kit/source/build/deepMD/include/deepmd/deepmd.hpp:466: undefined reference to `DP_DeepTensorComputeNList'
/usr/bin/ld: ./liblammps_mpi.a(compute_deeptensor_atom.o): in function `void deepmd::hpp::DeepTensor::compute<double>(std::vector<double, std::allocator<double> >&, std::vector<double, std::allocator<double> >&, std::vector<double, std::allocator<double> >&, std::vector<double, std::allocator<double> >&, std::vector<double, std::allocator<double> >&, std::vector<double, std::allocator<double> > const&, std::vector<int, std::allocator<int> > const&, std::vector<double, std::allocator<double> > const&, int, deepmd::hpp::InputNlist const&)':
/home/boi/luiz-pereira/Programs/deepmd-kit/source/build/deepMD/include/deepmd/deepmd.hpp:2098: undefined reference to `DP_DeepTensorCheckOK'
/usr/bin/ld: /home/boi/luiz-pereira/Programs/deepmd-kit/source/build/deepMD/include/deepmd/deepmd.hpp:2098: undefined reference to `DP_DeleteChar'
/usr/bin/ld: /home/boi/luiz-pereira/Programs/deepmd-kit/source/build/deepMD/include/deepmd/deepmd.hpp:2098: undefined reference to `DP_DeleteChar'
/usr/bin/ld: ./liblammps_mpi.a(compute_deeptensor_atom.o): in function `deepmd::hpp::InputNlist::~InputNlist()':
/home/boi/luiz-pereira/Programs/deepmd-kit/source/build/deepMD/include/deepmd/deepmd.hpp:575: undefined reference to `DP_DeleteNlist'
/usr/bin/ld: ./liblammps_mpi.a(compute_deeptensor_atom.o): in function `deepmd::hpp::DeepTensor::sel_types() const':
/home/boi/luiz-pereira/Programs/deepmd-kit/source/build/deepMD/include/deepmd/deepmd.hpp:2130: undefined reference to `DP_DeepTensorGetSelTypes'
/usr/bin/ld: ./liblammps_mpi.a(compute_deeptensor_atom.o): in function `deepmd::hpp::DeepTensor::output_dim() const':
/home/boi/luiz-pereira/Programs/deepmd-kit/source/build/deepMD/include/deepmd/deepmd.hpp:2126: undefined reference to `DP_DeepTensorGetOutputDim'
/usr/bin/ld: ./liblammps_mpi.a(compute_deeptensor_atom.o): in function `deepmd::hpp::DeepTensor::init(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, int const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':

**Comment by luizfcpe** [comment]
Sorry, just noticed a mistake on my compilation files.

**Comment by njzjz** [comment]
The error happened because the linked library (`-ldeepmd_c`) is not listed in the command. Could you post your `USER-DEEPMD/Install.sh` and `Makefile.package` files?

**Comment by luizfcpe** [comment]
That was indeed the problem. Adding -ldeepmd_c and adjusting the remaining of Makefile.package solved the issue. This was caused by me trying to re-use files from a previous compilation in a different system. Apologies, and thank you for the quick reply.
