### ISSUE TITLE
Not running using mpirun -np $SLURMN_TASKS

### ISSUE THREAD

**Issue by umang4002** [deepmodeling/deepmd-kit#4215]
### Bug summary

Error while 

### DeePMD-kit Version

DeePMD-kit v2.2.10

### Backend and its version

TensorFlow v2.15.0

### How did you download the software?

conda

### Input Files, Running Commands, Error Log, etc.

Error whille parellelization (CPU)

### Steps to Reproduce

Shown below

### Further Information, Files, and Links

error is 
![Image](https://github.com/user-attachments/assets/d284c66d-2e16-42be-b932-603a0d94a24b)
I am using the following bash script 
![Image](https://github.com/user-attachments/assets/a5e64262-8468-43ac-adcc-7d1134b48767)

**Comment by njzjz** [comment]
It seems that you should use `mpirun -np $SLURM_NNODES` if you want to run one processor on each node. By the way, it's unclear to me why you set the number of threads larger than the number of cores...
