### ISSUE TITLE
How to train hundreds of systems of different convalent moleculars together?

### ISSUE THREAD

**Issue by zhoufy20** [deepmodeling/deepmd-kit#4232]
Hello, developers of Deepmd-kit,

I am new to Deepmd-kit and wandering how to train the deepmd model for hundreds systems about convalent moleculars. Because the document is mainly on a specific system, such as Gas-Phase. I am curious about its application to multiple convalent moleculars.

I add discussions in https://github.com/deepmodeling/deepmd-kit/discussions/4231 too.

**Comment by zhoufy20** [comment]
I have several ideas, Thanks! But how about the performance in hundreds convalent moleculars?

**Comment by njzjz** [comment]
Do you have any specific issues? In general, there is no difference between training one system and two systems.

**Comment by njzjz** [comment]
If not, I'll close the issue.
