### ISSUE TITLE
[BUG] Wrong dptest results except for energy head

### ISSUE THREAD

**Issue by Chengqian-Zhang** [deepmodeling/deepmd-kit#4249]
### Bug summary

I find property dptest's results to be very different from the learning curve. And I have found the reason. This is a general bug for all heads except for energy head.
In `/deepmd/entrypoints/test.py`  line 127 `tmap = dp.get_type_map() if isinstance(dp, DeepPot) else None`. If we use `DeepProperty` or `DeepPolar` or `DeepDOS`..... `tmap` is None. So  `type_map` is not modified again according to `type_map` in `input.json`. So `atype` is wrong in the model forward process. The model prediction value is wrong.

### DeePMD-kit Version

All versions

### Backend and its version

pytorch

### How did you download the software?

Offline packages

### Input Files, Running Commands, Error Log, etc.

See above.

### Steps to Reproduce

See above.

### Further Information, Files, and Links

See above.

**Comment by njzjz** [comment]
It seems that in the `r2` branch, `get_type_map()` is only available in `DeepPot`. After we refactor `DeepEval` in v3, this should not be a problem anymore.
