### ISSUE TITLE
issue in using dplr with hybrid/scaled pair_style

### ISSUE THREAD

**Issue by fengwangxmu** [deepmodeling/deepmd-kit#4273]
When using dplr with hybrid/scaled pair_style to combining two dplr models, fix_dplr can not be used to define all dplr models.
input:

```
pair_style hybrid/scaled &
           v_LAMBDA_i deepmd ini.pb &
           v_LAMBDA_f deepmd fin.pb

pair_coeff *  * deepmd 1
pair_coeff *  * deepmd 2


fix   0 all dplr model ini.pb type_associate 1 4 bond_type 1
fix_modify  0 virial yes
fix   1 all dplr model ini.pb type_associate 1 5 bond_type 1
fix_modify  1 virial yes
```

log.lammps:
```
ERROR: pair_style deepmd should be set before this fix
 (/home/conda/feedstock_root/build_artifacts/deepmd-kit_1707091051406/work/source/lmp/fix_dplr.cpp:144)
Last command: fix   0 all dplr model ini.pb type_associate 1 4 bond_type 1

```

**Comment by njzjz** [comment]
I've read the related LAMMPS code. It seems when there are more than one deepmd pairs match, and no index is assigned, no pair is returned.

https://github.com/lammps/lammps/blob/6d0e633edf0b6fd27f97d06e01480089eebcd8d0/src/force.cpp#L288-L310

I am not sure whether it is okay to set index to 1 or an argument for index should be passed in this case.

**Comment by fengwangxmu** [comment]
Thank you very much for adding this new feature into the fix_dplr. I am testing this new feature.
Furthermore, I wander if the the corresponding potential energy for ini.pb and fin.pb can be scaled by the hybrid/scale method with this new feature?

**Comment by njzjz** [comment]
> I wander if the the corresponding potential energy for ini.pb and fin.pb can be scaled by the hybrid/scale method with this new feature?

It looks unrelated. If you found bugs, please open a new issue.

**Comment by fengwangxmu** [comment]
keys.push_back("pair_deepmd_index") should be added in the fix_dplr.cpp to activate the new parameter "pair_deepmd_index"

**Comment by njzjz** [comment]
> keys.push_back("pair_deepmd_index") should be added in the fix_dplr.cpp to activate the new parameter "pair_deepmd_index"

Thank you for reporting the bug. Did it work after it is added?

**Comment by fengwangxmu** [comment]
it works. Thank you for your help



---- Replied Message ----
| From | Jinzhe ***@***.***> |
| Date | 11/05/2024 15:35 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [deepmodeling/deepmd-kit] issue in using dplr with hybrid/scaled pair_style (Issue #4273) |

keys.push_back("pair_deepmd_index") should be added in the fix_dplr.cpp to activate the new parameter "pair_deepmd_index"

Thank you for reporting the bug. Did it work after it is added?
