### ISSUE TITLE
ValueError: Cannot feed value of shape (5,) for Tensor d_sea_t_natoms:0, which has shape (6,)

### ISSUE THREAD

**Issue by sysu23110** [deepmodeling/deepmd-kit#4306]
### Summary

When DPGEN was training the model, he reported this mismatch. I changed the writing of sel descriptor to a smaller size, but he still reported this, 1 ValueError: Cannot feed value of shape (5,) for Tensor d_sea_t_natom, How do we solve this

### DeePMD-kit Version

 "deepmd_version": "3.0.0b3",

### Backend and its version

 "deepmd_version": "3.0.0b3",

### Details

When DPGEN was training the model, he reported this mismatch. I changed the writing of sel descriptor to a smaller size, but he still reported this, 1 ValueError: Cannot feed value of shape (5,) for Tensor d_sea_t_natom, How do we solve this

**Comment by njzjz** [comment]
See #1399.

**Comment by sysu23110** [comment]
[param.json](https://github.com/user-attachments/files/17628191/param.json)
After I modified sel, I still reported the same error.
