### ISSUE TITLE
[BUG] DP-GEN workflow fails with unrecognized mpirun options when using init-model/restart features

### ISSUE THREAD

**Issue by chenggoj** [deepmodeling/deepmd-kit#4359]
### Bug summary

When attempting to restart a DP-GEN workflow with pre-trained models or from a previous interrupted job, the following error occurs:
```
--------------------------------------------------------------------------
An unrecognized option was included on the mpirun command line:

  Option: --init-model

Please use the "mpirun --help" command to obtain a list of all
supported options.
--------------------------------------------------------------------------
```

param.json settings:
```
"training_iter0_model_path":[
    "/expanse/projects/qstore/mia344/cjiang1/NNPs-traing-DeepMD-kit/DP-GEN/run/training_iter0_model/000",
    "..."
],
"training_init_model": true
```
Similar error occurs with --restart option when trying to resume interrupted workflows.

The command in machine.json:

`"command": "CUDA_VISIBLE_DEVICES=0,1,2,3 mpirun dp"`

### DeePMD-kit Version

DeePMD-kit v3.0.0b4

### Backend and its version

TensorFlow v2.15.0

### How did you download the software?

conda

### Input Files, Running Commands, Error Log, etc.

When attempting to restart a DP-GEN workflow with pre-trained models or from a previous interrupted job, the following error occurs:
```
--------------------------------------------------------------------------
An unrecognized option was included on the mpirun command line:

  Option: --init-model

Please use the "mpirun --help" command to obtain a list of all
supported options.
--------------------------------------------------------------------------
```

### Steps to Reproduce

param.json settings:
```
"training_iter0_model_path":[
    "/expanse/projects/qstore/mia344/cjiang1/NNPs-traing-DeepMD-kit/DP-GEN/run/training_iter0_model/000",
    "..."
],
"training_init_model": true
```
Similar error occurs with --restart option when trying to resume interrupted workflows.

The command in machine.json:

`"command": "CUDA_VISIBLE_DEVICES=0,1,2,3 mpirun dp"`

**Comment by njzjz** [comment]
xref: https://github.com/open-mpi/ompi/issues/11402

It's not related to deepmd-kit.
