### ISSUE TITLE
When training my own methane data, it went wrong and displayed "Floating point exception (core dumped). 

### ISSUE THREAD

**Issue by Gengxin-LIU** [deepmodeling/deepmd-kit#445]
We are training a set of data which is a methane molecule system. But it always went wrong when we began to train the data. DeepMD-kit only told us that "Floating point exception (core dumped)", without any further instructions. Could you please tell us some possible mistakes we might make?

**Comment by AnguseZhang** [comment]
1. Please provide the version of your DeePMD-kit version.
2. Please provide the dataset and input file to reproduce the problem.

**Comment by Gengxin-LIU** [comment]
Thanks for your attention. I found I made a stupid mistake.

**Comment by AnguseZhang** [comment]
Glad to see your problem is solved. You're also welcomed to share your experience in case that others make the same mistake.

**Comment by ml1234567854** [comment]
> Thanks for your attention. I found I made a stupid mistake.

Could you tell me what mistake you had made? I am receiving the same error now and would appreciate it.
