### ISSUE TITLE
data stating takes too long

### ISSUE THREAD

**Issue by cjxxjc729** [deepmodeling/deepmd-kit#4454]
Hello everyone, I encountered an issue during training where the process gets stuck at 
DEEPMD INFO data stating... (this step may take long time) 
for an extended period(it took 6 hours on GPU). My training system involves a total of 20,000 data points. Does anyone have suggestions for speeding up this step? Thank you.

**Comment by njzjz** [comment]
Do you use the latest version?

**Comment by cjxxjc729** [comment]
No, I am using  v2.2.9. Has this issue been resolved in the newer version?

**Comment by njzjz** [comment]
Yes, please see #3272

**Comment by cjxxjc729** [comment]
thank you. that is really cool
