### ISSUE TITLE
Encounter program crash when using the deepmdkit and dpgen

### ISSUE THREAD

**Issue by zhanghuang103031** [deepmodeling/deepmd-kit#4462]
### Summary

I encounter the error "*** Error in `/home/haichao/anaconda3/envs/deepmd=2.2.9/bin/_lmp': double free or corruption (!prev): 0x0000558eea839e40 ***" when run the "dpgen autotest relaxation.json machin.json" 
Also, sometimes, I encounter same error when run the dpgen run param.json machine.json

### DeePMD-kit Version

deepmkit version: 2.2.9  dpgen version: 0.12.1

### Backend and its version

Tensorflow versin: 2.9.0

### Python Version, CUDA Version, GCC Version, LAMMPS Version, etc

System: Centos 7
cuda version: 11.2 
GPU: 3060 12G 
CPU: Intel(R) Xeon(R) Platinum 8383C CPU @ 2.70GHz
python 3.10.13
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/local/libexec/gcc/x86_64-pc-linux-gnu/7.3.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../configure --enable-checking=release --enable-languages=c,c++ --disable-multilib
Thread model: posix
gcc version 7.3.0 (GCC)

### Details

When dpgen run param.json machine.json, two or three model would be trained succesfully, but the error would happened and print "double free or corruption (!prev): 0x0000558eea839e40 ***” and all the work are submmited by order rather than the script
when run dpgen autotest relaxation.json machine.json, the terminal print:"cannot find upload file /home/hh/Documents/train/dpgen/in.lammps，"
but if I copy the in.lammps to the file, the "home/h/anaconda3/envs/deepmd=2.2.9/bin/_lmp': double free or corruption (!prev): 0x00005596e27fce40 ***" would happen.
Also there are error of compress model.![Image](https://github.com/user-attachments/assets/6ca03a58-f6bf-44ad-bb5e-0aee5037c55d).
![Image](https://github.com/user-attachments/assets/31d11bc4-47ef-4dca-8317-151d4806c264)

All the error happens after training model succesfully by dpgen for some time

I don't know if this problem are caused by the deepmdkit or other software
Thanks so much for your generous help.

**Comment by njzjz** [comment]
The backtrace shows it is from your MPI library, so I suggest removing it and trying again.

**Comment by zhanghuang103031** [comment]
Thanks a lot, the problem is solved.
