### ISSUE TITLE
The Pip-installed newest deepmd-kit (1.3.3)  requires libtensorflow_framework.so.2

### ISSUE THREAD

**Issue by permissionx** [deepmodeling/deepmd-kit#447]
The recommended tensorflow-1.14.0 seems not provide  libtensorflow_framework.so.2, but libtensorflow_framework.so.1.
`dp -h `
returns 

> tensorflow.python.framework.errors_impl.NotFoundError: libtensorflow_framework.so.2: cannot open shared object file: No such file or directory

**Comment by njzjz** [comment]
This is the expected behavior. We recommend to use the latest tensorflow. You can also build yourself by using `pip install deepmd-kit --no-binary deepmd-kit`.

**Comment by njzjz** [comment]
See also #406.

**Comment by permissionx** [comment]
Sorry but I just noticed the C++ interface recommended tensorflow 1.14.0, which is said to should be the same with python interface tensorflow.

**Comment by njzjz** [comment]
> Sorry but I just noticed the C++ interface recommended tensorflow 1.14.0, which is said to should be the same with python interface tensorflow.

This is out-of-date. We have updated the document in #328, but it hasn’t been merged into `master` branch.
