### ISSUE TITLE
The se_a descriptor cannot utilize all cores when trained on the cpu

### ISSUE THREAD

**Issue by gengxingze** [deepmodeling/deepmd-kit#4474]
### Summary

When training the dp_sea model on a 64core cpu-only node, the cpu utilization is only about 1800%. How to set it up to further increase the cpu utilization?

### DeePMD-kit Version

2.2.10

### Backend and its version

v2

### Python Version, CUDA Version, GCC Version, LAMMPS Version, etc

python=3.10.13

### Details

   PID   USER       PR  NI    VIRT    RES    SHR S     %CPU %MEM     TIME+ COMMAND                                    
34016 gengxz    20   0   16.1g 636216 102264 S  1779  0.2   1268:54 python 

![Image](https://github.com/user-attachments/assets/1f7bb463-a73c-4620-b2a7-a4c44db943eb)

**Comment by njzjz** [comment]
> the cpu utilization is only about 180%.

Isn't it 1800%?

**Comment by njzjz** [comment]
In the `top` program, you can type 1 to see how much each process is utilized.

How do you set the threads?

**Comment by gengxingze** [comment]
> In the `top` program, you can type 1 to see how much each process is utilized.
> 
> How do you set the threads?
#!/bin/bash
#SBATCH --job-name=deepmd           
#SBATCH --partition=cpu
#SBATCH --output=job.%j.out      
#SBATCH --error=job.%j.err        
#SBATCH --nodes=1                   
#SBATCH --ntasks-per-node=64

begin=`date +%s`
echo "======== Job starts at `date +'%Y-%m-%d %T'` ======== "

module load mkl mpi compiler
conda activate deepmd

dp train input.json
echo "======== Job ends   at `date +'%Y-%m-%d %T'` ======== "
final=`date +%s`
total=$(($final-$begin))
day=$((total/86400))
hour=$((total%86400/3600))
minute=$((total%3600/60))
second=$((total%60))
echo totaltime: $day days, ${hour}:${minute}:${second} | tee -a out

![Image](https://github.com/user-attachments/assets/b3378674-afa2-4377-a879-a0b9ef2477e2)

**Comment by njzjz** [comment]
From the `top` I can see that all cores have been used.
