### ISSUE TITLE
Train result analysis

### ISSUE THREAD

**Issue by LLfbforever** [deepmodeling/deepmd-kit#4494]
### Summary

Hello, when I train a model, the multi-card wall time is longer than the single-card wall time. Why is this? How do I view the training results?
![Image](https://github.com/user-attachments/assets/2262532b-0df1-4b0d-a83c-0372c849370c)

### DeePMD-kit Version

v2.2.11,v3.0

### Backend and its version

tf 2.15

### Details

Hello, when I train a model, the multi-card wall time is longer than the single-card wall time. Why is this? How do I view the training results?

![Image](https://github.com/user-attachments/assets/abaf83ec-67c6-4d74-9b1e-999faca3c494)

**Comment by njzjz** [comment]
It looks to me that the title should be "seconds every 100 batches".

**Comment by njzjz** [comment]
> It looks to me that the title should be "seconds every 100 batches".

Documentation has been updated.
