### ISSUE TITLE
[BUG] zero result of test_descrpt_smooth

### ISSUE THREAD

**Issue by JiabinYang** [deepmodeling/deepmd-kit#500]
**Summary**

In gpu mode, I tried `test_descrpt_smooth` and it will failed like this
![image](https://user-images.githubusercontent.com/22361972/114307552-b7c83500-9b12-11eb-871f-27c4dff14aa7.png)

but in cpu mode it works well.
**Steps to Reproduce**

**Further Information, Files, and Links**

**Comment by amcadmus** [comment]
Know the reason: The GPU impl of `prod_force_grad` and `prod_virial_grad` were not submitted to branch `api`
