### ISSUE TITLE
[BUG]libop_abi.so undefined symbol

### ISSUE THREAD

**Issue by jxxiaoshaoye** [deepmodeling/deepmd-kit#557]
Hi guys, I cloned the latest version of deepmd-kit, master branch and devel branch. 
My TF environment is tensorflow-gpu 2.4.1 ( pip source ), with python3.6 , gcc/g++ 7.3.1 , cuda10.1
When I 'pip install .' , it would deliver the error message of "libop_abi.so : undefined symbol: _ZN10tensorflow8OpKernel11TraceStringEPNS_15OpKernelContextEb "
![image](https://user-images.githubusercontent.com/53417696/115808686-6fb3e700-a41d-11eb-8c56-ccd597a200a2.png)

**Comment by njzjz** [comment]
I cannot repeat the error on a new environment of Google Colaboratory. https://gist.github.com/b9b7c5c3b002e3e1b6e853c5b0e7317b

**Comment by njzjz** [comment]
Can you post the output of `tensorflow.version.COMPILER_VERSION` and `tensorflow.version.GIT_VERSION`?

**Comment by jxxiaoshaoye** [comment]
Hi,  my TF version is tensorflow-gpu 2.4.1, I think you didn't use the gpu version in the link you replied

**Comment by AnguseZhang** [comment]
>>> tensorflow.version.COMPILER_VERSION
'7.3.1 20180303'
>>> tensorflow.version.GIT_VERSION
'v2.4.0-49-g85c8b2a817f'

**Comment by njzjz** [comment]
It can not be reproduced on `tensorflow-gpu` as well. Note that `tensorflow` is also the GPU version.

**Comment by njzjz** [comment]
I notice https://github.com/tensorflow/text/issues/385 reported a same error, but their tensorflow is from docker source and not pip.

**Comment by AnguseZhang** [comment]
How to fix this problem : first install tensorflow and then install deepmd-kit.

**Comment by hyhuang00** [comment]
I tried to solution above but the problem persists:
tensorflow.python.framework.errors_impl.NotFoundError:~/.local/lib/python3.7/site-packages/deepmd/libop_abi.so: undefined symbol: _ZN10tensorflow11GetNodeAttrERKNS_9AttrSliceEN4absl14lts_2020_02_2511string_viewEPSt6vectorIiSaIiEE

**Comment by njzjz** [comment]
> I tried to solution above but the problem persists:
> 
> tensorflow.python.framework.errors_impl.NotFoundError:~/.local/lib/python3.7/site-packages/deepmd/libop_abi.so: undefined symbol: _ZN10tensorflow11GetNodeAttrERKNS_9AttrSliceEN4absl14lts_2020_02_2511string_viewEPSt6vectorIiSaIiEE

Please provide more information such as how you install it. If it's a new problem, you can open a new issue.

**Comment by njzjz** [comment]
In #797, I'm going to throw a message if this error happen.
