### ISSUE TITLE
[BUG] Lammps compilation fails when using low-precision mode USER-DEEPMD

### ISSUE THREAD

**Issue by BaozCWJ** [deepmodeling/deepmd-kit#563]
**Summary**

The low-precision mode deepmd module cannot be compiled by LAMMPS

**Deepmd-kit version, installation way, input file, running commands, error log, etc.**

vserion: 2.0.0 devel branch
installation way: C++ interface
key commands: 
`cmake -DUSE_CUDA_TOOLKIT=true -DTENSORFLOW_ROOT=$tensorflow_root -DCMAKE_INSTALL_PREFIX=$deepmd_root -DFLOAT_PREC=low ..
`
After the compilation of low-precision deepmd,  there's an error when compile lammps.

**Steps to Reproduce**

Following the step after the above cmake command from [https://deepmd.readthedocs.io/en/master/install.html#install-the-c-interface](url), then the error will occur at the last step of **Install LAMMPS’s DeePMD-kit module**

**Further Information, Files, and Links**
<img width="970" alt="Screen Shot 2021-04-24 at 14 51 29" src="https://user-images.githubusercontent.com/37867949/115950537-66ef0e00-a50e-11eb-80b7-05a423744a9b.png">

**Comment by njzjz** [comment]
So why did I build conda packages successfully? 😂
Build log: https://dev.azure.com/deepmd-kit-recipes/dfe7535b-bc98-4288-9a49-be8914966e7a/_apis/build/builds/401/logs/63

**Comment by amcadmus** [comment]
If you change the precision of deepmd-kit package, the lammps module should be replace by doing the following in the lammps src dir
```
make no-user-deepmd
rm -fr USER-DEEPMD
cp -r /path/to/new/USER-DEEPMD .
make yes-user-deepmd
```

**Comment by BaozCWJ** [comment]
> If you change the precision of deepmd-kit package, the lammps module should be replace by doing the following in the lammps src dir
> 
> ```
> make no-user-deepmd
> rm -fr USER-DEEPMD
> cp -r /path/to/new/USER-DEEPMD .
> make yes-user-deepmd
> ```

I tried these steps and  `make clean-all`, but it makes no difference.

**Comment by amcadmus** [comment]
Same as @njzjz I cannot reproduce this issue.

**Comment by njzjz** [comment]
@BaozCWJ you may post `Makefile.package` to let us see the compiling arguments.

**Comment by BaozCWJ** [comment]
> @BaozCWJ you may post `Makefile.package` to let us see the compiling arguments.

Maybe the compilation environment has changed, I cannot reproduce this error today,  but I think the key is whether to specify C++11 to compile lammps.

**Comment by njzjz** [comment]
In #600, I added LAMMPS cmake builds to CI, and no error was raised there.

**Comment by njzjz** [comment]
Did you use C++ 8 or 9?

**Comment by BaozCWJ** [comment]
Denghui and I still cannot reproduce this bug, maybe it had been fixed or something else.
@amcadmus This issue can be closed now

> Did you use C++ 8 or 9?

**Comment by sigbjobo** [comment]
On a similar note, I am also trying to use the low precision, and followed the suggestions, with some success (deepmd2.1.3). I get far but get the following error right before the LAMMPS MD loop:
2022-08-02 19:09:37.313538: F tensorflow/core/framework/tensor.cc:718] Check failed: dtype() == expected_dtype (2 vs. 1) float expected, got double
Is this due to:
1. That I trained with a different precision (double precision)
2. How I compiled tensorflow
see  [output.txt](https://github.com/deepmodeling/deepmd-kit/files/9246878/output.txt) for more details. Please note that high precision works, but is very slow for the A40 GPU.

**Comment by wanghan-iapcm** [comment]
@njzjz any hint?
