### ISSUE TITLE
Model compression error: descriptor type must be se_a!

### ISSUE THREAD

**Issue by zhangyongsdu** [deepmodeling/deepmd-kit#575]
model trainned with se_e2_a type can not be compressed with the dp  compress command for the latest devel version deepmp-kit.

**Comment by amcadmus** [comment]
Thanks for reporting we will fix it soon

**Comment by denghuilu** [comment]
#586 should fix this problem

**Comment by denghuilu** [comment]
#586 should fix this problem

**Comment by amcadmus** [comment]
#586 merged. close
