### ISSUE TITLE
plumed cannot work

### ISSUE THREAD

**Issue by JunboLu** [deepmodeling/deepmd-kit#583]
Hi,
  I try to use lammps compiled through offline package to run metadynamics. I add plumed fix line in lammps input file:
  fix 1 all plumed plumdedfile plumed.dat plumedout plumed.log
  But there is a error occured:
  ERROR: Incompatible API version for PLUMED in fix plumed. Only Plumed 2.4.x, 2.5.x, and 2.6.x are tested and supported.
  I use offline package: deepmd-kit-1.3.2-cpu-Linux-x86_64.sh.How could I solve this problem? Could anyone give a help? I would be very appreciated!
  With my best regards,
  Junbo

**Comment by njzjz** [comment]
Duplicated of https://github.com/deepmd-kit-recipes/lammps-dp-feedstock/issues/25. This bug has been resolved in [v1.3.3 packages](https://github.com/deepmodeling/deepmd-kit/releases/tag/v1.3.3). You may use the latest package.
