### ISSUE TITLE
An error occurred after installation

### ISSUE THREAD

**Issue by MrLonelyZC88** [deepmodeling/deepmd-kit#591]
An error occurred after installation.

when i run dp to test whether DeepMD is fully installed, some warnings and error occurred. like below:
=====================
WARNING:tensorflow:From /work/admin/.anaconda3/lib/python3.8/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:root:Environment variable KMP_BLOCKTIME is empty. Use the default value 0
WARNING:root:Environment variable KMP_AFFINITY is empty. Use the default value granularity=fine,verbose,compact,1,0
usage: dp [-h] {transform,train,freeze,test,doc-train-input} ...

DeePMD-kit: A deep learning package for many-body potential energy representation and molecular dynamics

optional arguments:
  -h, --help            show this help message and exit

Valid subcommands:
  {transform,train,freeze,test,doc-train-input}
    transform           pass parameters to another model
    train               train a model
    freeze              freeze the model
    test                test the model
    doc-train-input     print the documentation (in rst format) of input training parameters.
Traceback (most recent call last):
  File "/work/admin/.anaconda3/bin/dp", line 10, in <module>
    sys.exit(main())
  File "/work/admin/.anaconda3/lib/python3.8/site-packages/deepmd/main.py", line 85, in main
    raise RuntimeError('unknown command ' + args.command)
TypeError: can only concatenate str (not "NoneType") to str
=====================

I'm looking forward to anyone's help.

**Comment by AnguseZhang** [comment]
You can ignore these warnings. 
You can use "dp test -h" and see how this subcommand can be used.
