### ISSUE TITLE
Citations missing

### ISSUE THREAD

**Issue by vwcruzeiro** [deepmodeling/deepmd-kit#605]
Hello! I noticed that the citations are missing on this page: https://github.com/deepmodeling/deepmd-kit/blob/master/doc/use-deepmd-kit.md#train-a-model . The page has "[2]" and "[3]", but not the actual papers to which it refers. Upon searching, I believe these refer to https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.120.143001 and https://papers.nips.cc/paper/2018/hash/e2ad76f2326fbc6b56a45a56c59fafdb-Abstract.html (or https://arxiv.org/abs/1805.09003 ), is this correct? Thank you!

**Comment by njzjz** [comment]
I find this issue has been resolved by #513 in the `devel` branch, so I'll close it. It will be merged to `master` before v2.0.0 releases.

**Comment by vwcruzeiro** [comment]
Thank you!
