### ISSUE TITLE
Silicon file in Database missing the type.raw file contents

### ISSUE THREAD

**Issue by Mskater** [deepmodeling/deepmd-kit#671]
Hello,
I simply tried to download the Si.zip file from the database.
After extracting, I clicked on the type.raw file and it said:  
"Photo source file missing"
Ubuntu 18.04
Thanks very much for advice.

**Comment by njzjz** [comment]
What's the database you download from?

**Comment by njzjz** [comment]
Which program did you use to open it? It's only text files, so it's recommended to use `vim` or just `cat` in the command line.

**Comment by Mskater** [comment]
Got it, thanks.
