### ISSUE TITLE
Automatically configure the ROCM environment

### ISSUE THREAD

**Issue by GaleSeLee** [deepmodeling/deepmd-kit#690]
**Summary**

Automatically configure the ROCM environment

**Detailed Description**

ROCM is a similar CUDA launched by AMD. In order to check the DeepMD-Kit and subsequent work compiled process on ROCM in a pure CPU environment(github). Need to implement automatic configuration of the ROCM environment similar to the current CUDA. The compiled ROCM must include basic ROCM, hip, hipcub, rocprim for DeepMD-kit. 

**Further Information, Files, and Links**
install ROCM tutorial: https://rocmdocs.amd.com/

We have the configured ROCM  located /opt/rocm in Kun Shan computing center. 
/opt/rocm directory screenshot
![image](https://user-images.githubusercontent.com/47965866/120373182-9fbea600-c34a-11eb-93aa-6f99fd0c09da.png)

Some useful links
https://github.com/aieater/rocm_pytorch_informations
https://blog.csdn.net/znsoft/article/details/109143399

**Comment by njzjz** [comment]
Fixed by #2012.
