### ISSUE TITLE
[BUG] PBC inference very slow in v2.0

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/deepmd-kit#713]
**Summary**

Using PBC to predict my system is very slow in both v2.0.0.b0 and v2.0.0.b1, for both Python and C++. Non-PBC works well. The model converted from v1.3.3 or frozen in v2.0.0.b1 have the same behavior below.

| the version of DP program | PBC | non-PBC |
| -- | -- | -- |
v1.3.3 | Fast | Fast |
v2.0.0.b1 | Very slow | Fast |

**Deepmd-kit version, installation way, input file, running commands, error log, etc.**

v2.0.0.b1 conda GPU cuda10.1

**Steps to Reproduce**

```py
import dpdata
s1=dpdata.System("input", fmt="deepmd/raw")
s1p=s1.predict("g2.pb")
```

dpdata is https://github.com/deepmodeling/dpdata/pull/162

Model input is as the same as #658.

**Further Information, Files, and Links**

**Comment by amcadmus** [comment]
How large is the PBC system?

**Comment by njzjz** [comment]
> How large is the PBC system?

Here is my system: [input.zip](https://github.com/deepmodeling/deepmd-kit/files/6622511/input.zip)

My model:
- v2.0 version: [g2.zip](https://github.com/deepmodeling/deepmd-kit/files/6622524/g2.zip)
- v1.3 version: [g2o.zip](https://github.com/deepmodeling/deepmd-kit/files/6622526/g2o.zip)

**Comment by amcadmus** [comment]
> > How large is the PBC system?
> 
> Here is my system: [input.zip](https://github.com/deepmodeling/deepmd-kit/files/6622511/input.zip)
> 
> My model:
> 
> * v2.0 version: [g2.zip](https://github.com/deepmodeling/deepmd-kit/files/6622524/g2.zip)
> * v1.3 version: [g2o.zip](https://github.com/deepmodeling/deepmd-kit/files/6622526/g2o.zip)

I find nothing in the zip.

**Comment by njzjz** [comment]
[input.zip](https://github.com/deepmodeling/deepmd-kit/files/6635245/input.zip)

**Comment by iProzd** [comment]
There’s a collapsed data point in the input coords which contains a very large number:
> s1.data["coords"][0][274]
 array([1.88329067e+01, **_1.10405912e+17_**, 1.80823460e+01])

The v2.0 takes a _while_ function to normalize the coord by cutting down 1 box-scale in one loop, so it stucked (cpu and gpu). 
(In v1.x, it only cut down 1 box-scale once, which is not expected but passed.)

I can figure out the simple solution to replace the _while_  function from:
>while(ri[dd] >= 1.) ri[dd] -= 1.;
while(ri[dd] <  0.) ri[dd] += 1.;

to:
>ri[dd]=ri[dd]-(long long int)ri[dd];
if (ri[dd] <  0.) ri[dd] += 1.;

Or we add an **_assert_** to exit when it encounters a very large number.

**Comment by njzjz** [comment]
I just realized that I missed a dot when I copy the numbers!

**Comment by njzjz** [comment]
> Or we add an assert to exit when it encounters a very large number.
I agree. Or throw a warning to screen. Usually the input is incorrect.

**Comment by njzjz** [comment]
> I can figure out the simple solution to replace the _while_ function from:
> 
> > while(ri[dd] >= 1.) ri[dd] -= 1.;
> > while(ri[dd] <  0.) ri[dd] += 1.;
> 
> to:
> 
> > ri[dd]=ri[dd]-(long long int)ri[dd];
> > if (ri[dd] <  0.) ri[dd] += 1.;
> 

Although my input is incorrect, but for the current program, why not use something like
```cpp
ri[dd] = fmod(ri[dd], 1.)
```
See https://www.cplusplus.com/reference/cmath/fmod/

**Comment by iProzd** [comment]
> Although my input is incorrect, but for the current program, why not use something like
> 
> ```c++
> ri[dd] = fmod(ri[dd], 1.);
> if (ri[dd] < 0.) ri[dd] += 1.;
> ```
> 
> See https://www.cplusplus.com/reference/cmath/fmod/
> https://developer.download.nvidia.com/cg/fmod.html

We used to assume the coords in box-scale should be very small(around 1-2 or less), so the **_while_** style should be enough. But this issue reminds us to set something like you said **_fmod_** incase of unexpected numbers.
