### ISSUE TITLE
[Feature Request] Save the range of embedding matrix input in the DP model 

### ISSUE THREAD

**Issue by amcadmus** [deepmodeling/deepmd-kit#728]
**Summary**

Currently the model compression still need the training dataset to compute the range of the embedding matrix input, and to determine the range of tabulation. Saving the range of the embedding matrix input in the DP model will remove this dependency, so the user can still compress the model in the case that the original training data is not available.

**Comment by njzjz** [comment]
We may raise RuntimeError if sel is enough during the training, if users use their settings, since the model will be bad. We may add a --force option if users insist on using the bad sel.
