### ISSUE TITLE
[BUG]lmp MD very slow with offline installer compared with compiled myself

### ISSUE THREAD

**Issue by felix5572** [deepmodeling/deepmd-kit#730]
**Summary**

The `lmp` command in the offline installer seems to be very slow compared with the lammps compiled manually.
We have try to test the speed of lammps of water model (compressed and not compressed) on aliyun GPU-V100

lammps NPT simulation 10000 steps. unit: timesteps/second

| which lammps | speed of compressed model  | speed of not compressed mode|
| :-----| ----: | :----: |
| deepmd-kit-2.0.0.b1-cuda10.1_gpu-Linux-x86_64.sh | 9.825 | 12.485 |
| deepmd-kit-2.0.0.b1-cuda11.0_gpu-Linux-x86_64.sh| 9.694 |  12.422 |
|lammps by @denghuilu , cuda11.0 tf2.4 | 165.754 | 23.405 |

Ubuntu 18.04 aliyun GPU-V100 single node.

lammps-dp compiled manually and lammps in offline installer mentioned above.
lammps input: a trivial NPT simulaiton script `pair_style      deepmd graph.pb`

case1: download offline installer and run lmp command.
case2: compile tensorflow 2.4 from source (as well as libtensorflow_cc) lammps dp and compile lammps_mpi
case3: download offline installer and use this env (this means use the libtensorflow_cc.so libtensorflow_framework.so in the installer when linking) to compile deepmd-kit and lammps .

**Further Information, Files, and Links**

2,0 model and compress version , lammps in.lammps , conf.lmp
https://deepmd-kit.oss-cn-beijing.aliyuncs.com/water_wanghan_models.tar.gz

**Comment by felix5572** [comment]
@njzjz  attach files

**Comment by njzjz** [comment]
CMake can't detect CUDA automatically in `v2.0.0.b1`. (I think you are using `b1` instead of `b0`?) This bug should be imported by #656.
cc @pkulzy your changes to `CMakeLists.txt` breaks the detection of cudatoolkit.
https://github.com/deepmodeling/deepmd-kit/blob/ab7621e80302aeacbe67ae2767589dc66f840259/source/CMakeLists.txt#L59-L66

**Comment by pkulzy** [comment]
What does automatically mean? The logic of now is if you want to use CUDA, thus you should use -DUSE_CUDA_TOOLIKIT=TRUE

**Comment by pkulzy** [comment]
As more and more devices are supported, i think we should not implicitly help find the GPU

**Comment by njzjz** [comment]
This is a breaking change and should be explained in the release note, as users may follow the old installation steps.

**Comment by njzjz** [comment]
I am going to fix the offline installer and conda packages in next version.

**Comment by njzjz** [comment]
Fixed in the new version.
