### ISSUE TITLE
[BUG] 2.0.0.b0-cuda11.1 : Installation failed

### ISSUE THREAD

**Issue by yzx1999** [deepmodeling/deepmd-kit#740]
**Summary**
when I tried to install deepmd-kit-2.0.0.b0-cuda11.1, I downloaded deepmd-kit-2.0.0.b0-cuda11.1_gpu-Linux-x86_64.sh.0 and deepmd-kit-2.0.0.b0-cuda11.1_gpu-Linux-x86_64.sh.1 and upload them to my server. 
Then I bash sh.0 , following error appears: **concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
[34605] Failed to execute script entry_point**
It seems that Conda installation failed, Is something wrong with my installation?

**Comment by yzx1999** [comment]
I tried the installation on gpu RTX3080 with cuda11.1

**Comment by njzjz** [comment]
Merge into one file with
```sh
cat deepmd-kit-2.0.0.b0-cuda11.1_gpu-Linux-x86_64.sh.0 deepmd-kit-2.0.0.b0-cuda11.1_gpu-Linux-x86_64.sh.1 > deepmd-kit-2.0.0.b0-cuda11.1_gpu-Linux-x86_64.sh
```
