### ISSUE TITLE
installation issue 

### ISSUE THREAD

**Issue by mike-zz** [deepmodeling/deepmd-kit#750]
Dear developers, 

I tried 

`conda install deepmd-kit=*=*cpu lammps-dp=*=*cpu -c deepmodeling`

but got this error 

`conda: No match`

Could you please help me?

Thanks!
Mike

**Comment by njzjz** [comment]
Have you installed [conda](https://github.com/conda/conda)?

**Comment by mike-zz** [comment]
Yes, I have.

**Comment by njzjz** [comment]
Do you mean you can't find `conda` or others? Please post the full error message.

**Comment by mike-zz** [comment]
I meant I have installed `conda`. It works (for other things). It just doesn't for 
`conda install deepmd-kit=*=*cpu lammps-dp=*=*cpu -c deepmodeling`
The full error message is 
`conda: No match.`

**Comment by njzjz** [comment]
Can you try `conda create -n deepmd deepmd-kit=*=*cpu lammps-dp=*=*cpu -c deepmodeling` to create a new environment? Recently anaconda upgrade their packages to CentOS 7, which may cause inconsistent with old packages.

**Comment by GavinStevensHoboken** [comment]
I also met this problem, $ conda create -n deepmd deepmd-kit=*=*cpu lammps-dp=*=*cpu -c deepmodeling
zsh: no matches found: deepmd-kit=*=*cpu
(base)

**Comment by GavinStevensHoboken** [comment]
Is this project compatible with macOS terminal?

**Comment by shoehangxh** [comment]
> Is this project compatible with macOS terminal?

have u solved this problem, i also came across this issue.

**Comment by GavinStevensHoboken** [comment]
> > Is this project compatible with macOS terminal?
> 
> have u solved this problem yet ?, i also came across this issue.

Not yet, I gave up this project and turn into another one.

**Comment by njzjz** [comment]
DeePMD-kit is currently available on the [conda-forge](https://conda-forge.org/) channel, which contains macOS builds. For more information, see [the documentation](https://docs.deepmodeling.com/projects/deepmd/en/v2.2.0.b0/install/easy-install.html#conda-forge-channel) or the related [conda-forge repository](https://github.com/conda-forge/deepmd-kit-feedstock/).
