### ISSUE TITLE
Wiki page needs update

### ISSUE THREAD

**Issue by amcadmus** [deepmodeling/deepmd-kit#753]
**Summary**

It looks that the wiki page is not up-to-the date. Some update on the doc is not synced to the wiki. 

Do we really need the wiki pages, most of which are the same as the doc?

**Comment by tuoping** [comment]
I don't think we need it.

**Comment by njzjz** [comment]
I've removed duplicated pages. After the rest pages are processed, I'll close it.

**Comment by njzjz** [comment]
I've closed wiki and also projects, since they are unused now.
