### ISSUE TITLE
[Feature Request] add `-O2` or `-O3` optimize flag

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/deepmd-kit#756]
**Summary**

Currently CMake files don't contain a `-O2` or `-O3` optimize flag (I am not sure which is better). Maybe we should add it when compiling for production.

**Detailed Description**

**Further Information, Files, and Links**

**Comment by amcadmus** [comment]
By default the `CMAKE_BUILD_TYPE` is `release`, by default -O3 is included in `CMAKE_BUILD_TYPE_RELEASE`, see the [link](https://stackoverflow.com/questions/24767450/using-cmake-how-do-you-determine-the-default-compiler-flags-per-build-type)

**Comment by njzjz** [comment]
Got it.
