### ISSUE TITLE
[BUG] Installation issue

### ISSUE THREAD

**Issue by xfanak** [deepmodeling/deepmd-kit#796]
Dear dp developers, 

I'm trying to install the python interface of deepmd-kit only. I noted that someone had the similar issue: https://github.com/deepmodeling/deepmd-kit/issues/557, and I thought it could be the tensorflow's bug. But I couldn't solve it even if I tried the solutions given here: https://github.com/tensorflow/text/issues/385

I created an empty conda environment first, and set the python version to be 3.8. 
Then, I installed tensorflow-cpu (2.5.0) and deepmd-kit 1.3.3 using pip command: pip install tensorflow-cpu/deepmd-kit . 
But the dp can not run properly:
![image](https://user-images.githubusercontent.com/41663661/123426811-6fd78b00-d5f6-11eb-882d-d2f02935d6fb.png)

The problem was solved when I switched to deepmd-kit 1.3.4 using 
'pip install git+https://github.com/deepmodeling/deepmd-kit', instead of simply 'pip install deepmd-kit'. 
Update the deepmd-kit wheel may prevent similar problems in the future. 

Thanks.

**Comment by njzjz** [comment]
This wheel was built against TensorFlow 2.4, so you will se incompatibility when you are using TensorFlow 2.5.
Pypi does not allow updating files so we cannot help.

**Comment by njzjz** [comment]
I am considering to add a message before loading library, so one can know what happened and what to do.

**Comment by xfanak** [comment]
Thanks for the comments. I did more tests, dp1.3.3 is compatible with tf 2.4 only, but dp 1.3.4 works fine with tf 2.3, 2.4, and 2.5.

**Comment by njzjz** [comment]
When you `pip install git+https://github.com/deepmodeling/deepmd-kit`, you are actually building from the source but not the wheel. So the ABI will be consistent with the runtime. You can get the same result if you executing `pip install deepmd-kit --no-binary deepmd-kit`.
