### ISSUE TITLE
[BUG] _Process killed when running lammps by using deepmd-kit-2.0.0.beta0 model on GPU and DCU_

### ISSUE THREAD

**Issue by Carrotkingdom** [deepmodeling/deepmd-kit#824]
**I am running a DP model with deepmd-kit-2.0.0.beta0 version, both original and compressed, on GPU and DCU. In all cases the process is killed after several steps, depending on the number of threads and environment.**

**Here are the model type, machine type, the number of threads and the corresponding step number before the process died.**

![image](https://user-images.githubusercontent.com/86839379/124285415-79c23680-db80-11eb-9df2-380c107a33f3.png)

**The lammps input file and the submit files on GPU and DCU are attached below.**

[MgZn.zip](https://github.com/deepmodeling/deepmd-kit/files/6754941/MgZn.zip)

**Comment by pkulzy** [comment]
Will this problem occur when running on the CUDA platform?

**Comment by denghuilu** [comment]
Have you tested these models on a single GPU or DCU?

**Comment by pkulzy** [comment]
> Have you tested these models on a single GPU or DCU environment?

about 12300 on DCU

**Comment by amcadmus** [comment]
I would suggest trying the latest commit on `devel`

**Comment by denghuilu** [comment]
I will try it. > I would suggest trying the latest commit on `devel`

**Comment by Carrotkingdom** [comment]
> Have you tested these models on a single GPU or DCU environment?

Same results on a single GPU. On CPU the process is normal and won't be killed.

**Comment by denghuilu** [comment]
The latest GPU code has been tested on ehpc and there is no problem. Please close this   @amcadmus.

**Comment by Carrotkingdom** [comment]
The latest DCU code on NSCC-ZZ is tested successfully @amcadmus .
