### ISSUE TITLE
IndexError when trying to test Silicon graph.pb 

### ISSUE THREAD

**Issue by Mskater** [deepmodeling/deepmd-kit#829]
Hello again,
Thanks for all previous help.
DeePMD-kit version 1.3.3  TF version 2.2, Ubuntu 18.04.

This time I got a graph.pb to test and ran the command
dp test -m graph.pb -s ~/Si/ -n 30
Also tried:    dp test -m graph.pb -s ~/set.009/ -n 30     Which is correct?
I am in the Si directory with all the sets.  (set.000   to set.009)

This error came up.  (Last line before error thrown.)
File "~/miniconda3/lib/python3.8/site-packages/deepmd/test.py", line 77, in weighted_average
    nitems = len(err_coll[0])
IndexError: list index out of range

**Comment by njzjz** [comment]
`-s data/` where `data/` is as same as `data` key in your `train.json` file. `-s ~/set.009/` is wrong and it should be the parent directory.

**Comment by Mskater** [comment]
OK, thanks, I tried again, here is the output error again.  And why is it trying to test set.006 instead of set.009?   I am in the Si folder.

~/Si$ dp test -m graph.pb -s ../Si/ -n 30
WARNING:tensorflow:From ~/miniconda3/lib/python3.8/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
WARNING:root:Environment variable KMP_BLOCKTIME is empty. Use the default value 0
WARNING:root:Environment variable KMP_AFFINITY is empty. Use the default value granularity=fine,verbose,compact,1,0
2021-07-06 10:49:00.139024: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2021-07-06 10:49:00.160160: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2699905000 Hz
2021-07-06 10:49:00.160546: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x555f6ae48010 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2021-07-06 10:49:00.160563: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2021-07-06 10:49:00.160628: I tensorflow/core/common_runtime/process_util.cc:147] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
# ---------------output of dp test--------------- 
# testing system : ../Si/
OMP: Info #155: KMP_AFFINITY: Initial OS proc set respected: 0-11
OMP: Info #216: KMP_AFFINITY: decoding x2APIC ids.
OMP: Info #157: KMP_AFFINITY: 12 available OS procs
OMP: Info #158: KMP_AFFINITY: Uniform topology
OMP: Info #287: KMP_AFFINITY: topology layer "LL cache" is equivalent to "socket".
OMP: Info #287: KMP_AFFINITY: topology layer "L3 cache" is equivalent to "socket".
OMP: Info #287: KMP_AFFINITY: topology layer "L2 cache" is equivalent to "core".
OMP: Info #287: KMP_AFFINITY: topology layer "L1 cache" is equivalent to "core".
OMP: Info #192: KMP_AFFINITY: 1 socket x 6 cores/socket x 2 threads/core (6 total cores)
OMP: Info #218: KMP_AFFINITY: OS proc to physical thread map:
OMP: Info #172: KMP_AFFINITY: OS proc 0 maps to socket 0 core 0 thread 0 
OMP: Info #172: KMP_AFFINITY: OS proc 6 maps to socket 0 core 0 thread 1 
OMP: Info #172: KMP_AFFINITY: OS proc 1 maps to socket 0 core 1 thread 0 
OMP: Info #172: KMP_AFFINITY: OS proc 7 maps to socket 0 core 1 thread 1 
OMP: Info #172: KMP_AFFINITY: OS proc 2 maps to socket 0 core 2 thread 0 
OMP: Info #172: KMP_AFFINITY: OS proc 8 maps to socket 0 core 2 thread 1 
OMP: Info #172: KMP_AFFINITY: OS proc 3 maps to socket 0 core 3 thread 0 
OMP: Info #172: KMP_AFFINITY: OS proc 9 maps to socket 0 core 3 thread 1 
OMP: Info #172: KMP_AFFINITY: OS proc 4 maps to socket 0 core 4 thread 0 
OMP: Info #172: KMP_AFFINITY: OS proc 10 maps to socket 0 core 4 thread 1 
OMP: Info #172: KMP_AFFINITY: OS proc 5 maps to socket 0 core 5 thread 0 
OMP: Info #172: KMP_AFFINITY: OS proc 11 maps to socket 0 core 5 thread 1 
OMP: Info #254: KMP_AFFINITY: pid 6327 tid 6358 thread 1 bound to OS proc set 1
OMP: Info #254: KMP_AFFINITY: pid 6327 tid 6363 thread 2 bound to OS proc set 2
OMP: Info #254: KMP_AFFINITY: pid 6327 tid 6364 thread 3 bound to OS proc set 3
OMP: Info #254: KMP_AFFINITY: pid 6327 tid 6365 thread 4 bound to OS proc set 4
OMP: Info #254: KMP_AFFINITY: pid 6327 tid 6367 thread 6 bound to OS proc set 6
OMP: Info #254: KMP_AFFINITY: pid 6327 tid 6366 thread 5 bound to OS proc set 5
OMP: Info #254: KMP_AFFINITY: pid 6327 tid 6359 thread 7 bound to OS proc set 7
OMP: Info #254: KMP_AFFINITY: pid 6327 tid 6368 thread 8 bound to OS proc set 8
OMP: Info #254: KMP_AFFINITY: pid 6327 tid 6369 thread 9 bound to OS proc set 9
OMP: Info #254: KMP_AFFINITY: pid 6327 tid 6370 thread 10 bound to OS proc set 10
OMP: Info #254: KMP_AFFINITY: pid 6327 tid 6372 thread 12 bound to OS proc set 0
OMP: Info #254: KMP_AFFINITY: pid 6327 tid 6371 thread 11 bound to OS proc set 11
# number of test data : 30 
Energy L2err        : 8.373643e-02 eV
Energy L2err/Natoms : 1.938343e-04 eV
Force  L2err        : 3.495767e-02 eV/A
Virial L2err        : 9.105787e+02 eV
Virial L2err/Natoms : 2.107821e+00 eV
# ----------------------------------------------- 
# ---------------output of dp test--------------- 
# testing system : ../Si/set.006
Traceback (most recent call last):
  File "~/miniconda3/bin/dp", line 10, in <module>
    sys.exit(main())
  File "~/miniconda3/lib/python3.8/site-packages/deepmd/main.py", line 72, in main
    test(args)
  File "~/miniconda3/lib/python3.8/site-packages/deepmd/test.py", line 40, in test
    err, siz = test_ener(dp, args, append_detail = (cc!=0))
  File "~/miniconda3/lib/python3.8/site-packages/deepmd/test.py", line 103, in test_ener
    data = DeepmdData(args.system, args.set_prefix, shuffle_test = args.shuffle_test, type_map = dp.get_type_map())
  File "~/miniconda3/lib/python3.8/site-packages/deepmd/Data.py", line 37, in __init__
    self.test_dir = self.dirs[-1]
IndexError: list index out of range

**Comment by njzjz** [comment]
In v1.3.3, there's no way to use `dp test` to test `set.006` instead of `set.009`...

**Comment by Mskater** [comment]
But that is what it is trying to do.  I did not choose it.

**Comment by njzjz** [comment]
Do you have `type.raw` in `set.006`? This is not correct.

**Comment by Mskater** [comment]
Thanks!  That was the mistake. It runs testing now.
