### ISSUE TITLE
AssertionError: only support weight matrix and bias matrix at the tabulation op!

### ISSUE THREAD

**Issue by SongkKKK** [deepmodeling/deepmd-kit#850]
**Summary**

I use "dp compress" to compress a model and it goes wrong. How can I adress this problem?
**Deepmd-kit Version, Python Version, Tensorflow Version, GCC Version and Cuda Version.**

**Details**
![image](https://user-images.githubusercontent.com/38750504/125605020-91407122-ca7b-4af4-8c79-5fa31d8e250a.png)

**Comment by denghuilu** [comment]
@SongkKKK Could you give the frozen_modle.pb as well as the trainging data and script? So we can check the details of the problem.

**Comment by njzjz** [comment]
@denghuilu #1525 shows that compress a v1.2 model will raise this error.
