### ISSUE TITLE
[BUG] Error "Failed to execute script entry_point" when installing deepmd-kit-2.0.0.b3

### ISSUE THREAD

**Issue by Ericwang6** [deepmodeling/deepmd-kit#876]
**Summary**

An error occurs when installing deepmd-kit version deepmd-kit-2.0.0.b3 from off-line package with cuda10.1

![image](https://user-images.githubusercontent.com/63655850/126493369-38e4fffb-0016-4912-92dd-13d4625878c9.png)

**Comment by njzjz** [comment]
See conda/conda#10143. Do you have enough storage or memory?

**Comment by dingzhaohan** [comment]
Hi~I meet anathor problem when execute deepmd-kit**.sh.0 script.
[/root/deepmd-kit] >>> /opt/software/deepmd-kit/2.0.0.b3-cuda11.0
PREFIX=/opt/software/deepmd-kit/2.0.0.b3-cuda11.0
WARNING: md5sum mismatch of tar archive
expected: 1dd98d2721c502086fb760bf5bb582b7
     got: 308e78e46f63e584d4f5b0fefbec34a5  -
Unpacking payload ...
Traceback (most recent call last):
  File "entry_point.py", line 76, in <module>
  File "tarfile.py", line 2026, in extractall
  File "tarfile.py", line 2067, in extract
  File "tarfile.py", line 2139, in _extract_member
  File "tarfile.py", line 2188, in makefile
  File "tarfile.py", line 249, in copyfileobj
tarfile.ReadError: unexpected end of data
[28821] Failed to execute script entry_point

**Comment by njzjz** [comment]
> Hi~I meet anathor problem when execute deepmd-kit**.sh.0 script.
> [/root/deepmd-kit] >>> /opt/software/deepmd-kit/2.0.0.b3-cuda11.0
> PREFIX=/opt/software/deepmd-kit/2.0.0.b3-cuda11.0
> WARNING: md5sum mismatch of tar archive
> expected: 1dd98d2721c502086fb760bf5bb582b7
> got: 308e78e46f63e584d4f5b0fefbec34a5 -
> Unpacking payload ...
> Traceback (most recent call last):
> File "entry_point.py", line 76, in
> File "tarfile.py", line 2026, in extractall
> File "tarfile.py", line 2067, in extract
> File "tarfile.py", line 2139, in _extract_member
> File "tarfile.py", line 2188, in makefile
> File "tarfile.py", line 249, in copyfileobj
> tarfile.ReadError: unexpected end of data
> [28821] Failed to execute script entry_point

See #740.
