### ISSUE TITLE
[BUG] numerical regression of deepmd::copy_coord_gpu() from CUDA 10.1 to CUDA 11.2

### ISSUE THREAD

**Issue by jim19930609** [deepmodeling/deepmd-kit#878]
**Summary**

deepmd::copy_coord_gpu() behaves correctly with CUDA 10.1, but performs no copy with CUDA 11.2. 

**Steps to Reproduce**
CUDA Environment: 
![image](https://user-images.githubusercontent.com/22334008/126630304-4f8b9189-f693-4148-8b69-de6ff1a363fc.png)

Python Version: 3.7
Tensorflow Version: tensorflow-gpu==1.15.0

This issue was originally detected on Paddle branch.
1. git checkout paddle
2. python setup.py install
3. cd deepmd && python load_paddle_op.py install
4. cd ../source/tests/ && python test_pd_prod_env_mat_a.py
5. Run paddle unit test which calls "deepmd::copy_coord_gpu()" internally:

![image](https://user-images.githubusercontent.com/22334008/126630798-7aa6958e-1bb9-494e-9224-94e7824f55bc.png)

The outputs are all zero.

**Some more Diagnoses**
We printed out the variable value before and after calling "deepmd::copy_coord_gpu()". Note that variable named "coord_cpy" is expected to be copied:

![image](https://user-images.githubusercontent.com/22334008/126631302-6d563ede-15b9-4a84-925d-26b740dc1c9d.png)

The following image shows the logged outputs (left: correct behaviour on CUDA 10.1; right: does no copy on CUDA 11.2)

![image](https://user-images.githubusercontent.com/22334008/126631551-84495946-b10e-4c39-872c-8578f88300e0.png)

We also made sure all other inputs to "deepmd::copy_coord_gpu()" are the same across CUDA 10.1 and CUDA 11.2 to localize the problem.

![image](https://user-images.githubusercontent.com/22334008/126631585-316045c6-a5e9-4e6a-ab16-2230c5350ce3.png)

**Comment by njzjz** [comment]
I didn't reproduce it on the devel branch.

**Comment by denghuilu** [comment]
I didn't reproduce the problem on the devel branch with the CUDA-11.2 environment. All tests have passed in the CUDA-11.2 environment.

**Comment by njzjz** [comment]
Close as it cannot be reproduced. Feel free to reopen it if more details are provided.
