### ISSUE TITLE
Type map issue in DeepmdData

### ISSUE THREAD

**Issue by jxxiaoshaoye** [deepmodeling/deepmd-kit#920]
**type map may be wrong in __init__ of Deepmddata**

In the __init__ function of Deepmddata class, it read type.raw and cast it from local type map (which is read from a system's type_map.raw) to the global type map which is defined in the input.json file. The code is below:
![image](https://user-images.githubusercontent.com/53417696/128164377-b35119c1-24e6-4808-a5f6-aa7b54189c78.png)

However, for example, in the Al Cu Mg alloy case, the global type map is [Mg, Al, Cu]. If a system only have one elements Al,  and the local type_map.raw is [Al]. After process of __init__, self.type_map would be [Mg], which is incorrect logically.

my deepmd-kit version is v2.0.0.b3, and I print out the type map before and after __init__ cast to identify want I'm trying to say.
![image](https://user-images.githubusercontent.com/53417696/128165126-2d6b7f2f-55e0-4176-b470-04c5327c0b17.png)

**Comment by amcadmus** [comment]
Could you plz provide the minimal dataset and input script that reproduces the issue?

**Comment by njzjz** [comment]
If I remember correctly, the type map in all systems should be the same...

**Comment by jxxiaoshaoye** [comment]
[issue_920.zip](https://github.com/deepmodeling/deepmd-kit/files/6935817/issue_920.zip)
It's the same now in a single case, but I mean it should be extend further when we deal with more cases
