### ISSUE TITLE
[Feature Request] rebuild library dependencies

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/deepmd-kit#926]
**Summary**

The present library dependency is strange.

**Detailed Description**

Currently the library dependency is as follows (using `ldd` to see):

![image](https://user-images.githubusercontent.com/9496702/128432398-2eeebe34-fdca-4b25-ad91-b98420fb8c98.png)

It's a bit strange. Although it can work, we should make it more logical:

![image](https://user-images.githubusercontent.com/9496702/128433263-1010a73b-d469-48c7-95ba-40194afba14d.png)

**Comment by amcadmus** [comment]
You are right. Could you please update the CMake files accordingly? Thanks!
