### ISSUE TITLE
Compiling Lammps to use the deep potential

### ISSUE THREAD

**Issue by tfcao888666** [deepmodeling/deepmd-kit#944]
Dear all, 
I want to get USER-DEEPMD to compile lammps, so that I could use this lammps to cancluate the phonon spectra. 
I have tried to use the USER-DEEPMD  that was got with conda installation,
but it does not work. The error is "/work2/04587/tfcao/stampede2/miniconda3/include/tensorflow/core/framework/resource_handle.pb.h(584): error #140: too many arguments in function call
    device_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaNoVirtual());
                         ^

compilation aborted for ../fix_dplr.cpp (code 4)
make[2]: *** [fix_dplr.o] Error 4
make[2]: Leaving directory `/work2/04587/tfcao/stampede2/lammps/lammps-29Oct20/src/Obj_shared_mpi'
make[1]: *** [mpi] Error 2
make[1]: Leaving directory `/work2/04587/tfcao/stampede2/lammps/lammps-29Oct20/src'
make: *** [mpi] Error 2"
I also try to use python interface to install deepkit to get USER-DEEPMD, but I always encounter the error "ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pymatgen 2022.0.8 requires numpy>=1.20.1, but you have numpy 1.19.5 which is incompatible.
pymatgen 2022.0.8 requires scipy>=1.5.0, but you have scipy 1.2.0 which is incompatible.
 "
I appreciate all your help!
Best regards!

**Comment by njzjz** [comment]
As I mentioned in #642, this kind of errors is likely to be caused by incorrect headers. You can decompress the `libtensorflow_cc` archieve (stored in `pkgs` directory) and override the original one.

I don't think python interface have USER_DEEPMD.
