### ISSUE TITLE
[BUG] The table in document atom type embedding is broken.

### ISSUE THREAD

**Issue by shishaochen** [deepmodeling/deepmd-kit#953]
**Summary**

The table in document `atom type embedding` is broken.

**Deepmd-kit version, installation way, input file, running commands, error log, etc.**

[devel branch @ 3c2a2b](https://github.com/deepmodeling/deepmd-kit/commit/3c2a2bdd64a5a2d3eca611e6afd872302ae7d5e6)

Build docs and preview. A possible link is: https://explore-deepmd.njzjz.win/en/latest/development/type-embedding.html

![image](https://user-images.githubusercontent.com/17514649/129158742-8958f11b-f8e8-478c-a510-b652d04604ab.png)

**Comment by jxxiaoshaoye** [comment]
fixed in pr #967
