### ISSUE TITLE
Cherry-pick commits from `master`

### ISSUE THREAD

**Issue by njzjz** [deepmodeling/deepmd-kit#960]
It's hard to merge `devel` with `master` since the difference is too large. So I suggest cherry-pick and force-push instead.

PRs since v1.3.0 are as follows. We needs to check if a PR has been patched to `devel` or is out-dated.

- [x] #312 (out-dated)
- [x] #327 (out-dated)
- [x] #334 
- [x] #338 (#964)
- [x] #354 (out-dated)
- [x] #390 (out-dated)
- [x] #392 (#391)
- [x] #407 
- [x] #424 
- [x] #446 (out-dated, but needs to pay attention)
- [x] #492 (#961)
- [x] #535 (#963)
- [x] #536 (#962)
- [x] #564 (#965)
- [x] #620 (#621)
- [x] #641 (#640)
- [x] #664 (#492)
- [x] #676 (out-dated)
- [x] #932 (#933)
- [x] #934 (#933)
- [x] #936 (outdated)

**Comment by njzjz** [comment]
@denghuilu Can you make sure we can ignore #334, #407, and #424?

**Comment by denghuilu** [comment]
These three PRs can be safely ignored. #334 was out-dated, and #407,#427 were cherry-picked from devel branch.
