### ISSUE TITLE
[BUG] wrong model produced by deepmd-kit 2.0.0b4 when selecting activation function 'gelu' and runing on GPU

### ISSUE THREAD

**Issue by liangadam** [deepmodeling/deepmd-kit#987]
**Summary**

In a SE_A descriptor's example, when we choose the activation function of the descriptor in input.json to be 'gelu' and train it on GPU, and then use this model.pb to run lammps, we will obtain a constant temperature，which is obviously wrong.
I have triedto replace op_module.gelu with tensorflow.nn.gelu in common.py, and then it would produce a resonable model, so the bug is probably in source/lib/src/cuda/gelu.cu.
**Deepmd-kit version, installation way, input file, running commands, error log, etc.**

version: v2.0.0-beta.4 (devel branch)
installation way: build python interface(tensorflow) and pip install deepmd-kit in a conda environment.
input file: example/water/se_e2_a/input.json ,and specify the activation function of descriptor is gelu.
running command: dp train input.json, dp freeze -o model.pb, mpirun -n 1 lmp -i in.lammps
error log: 
Step PotEng KinEng TotEng Temp Press Volume 
       0   -29943.591    8.1472669   -29935.444          330    4515.2079    1927.3176 
     100    -29943.46    8.1472669   -29935.313          330    4515.2079    1927.3176 
     200   -29943.435    8.1472669   -29935.288          330    4515.2079    1927.3176 
     300   -29943.591    8.1472669   -29935.444          330    4515.2079    1927.3176 
     400   -29942.928    8.1472669   -29934.781          330    4515.2079    1927.3176 
     500   -29943.562    8.1472669   -29935.415          330    4515.2079    1927.3176 
     600    -29943.28    8.1472669   -29935.132          330    4515.2079    1927.3176 
     700   -29943.591    8.1472669   -29935.444          330    4515.2079    1927.3176 
     800   -29943.547    8.1472669     -29935.4          330    4515.2079    1927.3176 
     900   -29943.435    8.1472669   -29935.288          330    4515.2079    1927.3176 
    1000    -29943.85    8.1472669   -29935.703          330    4515.2079    1927.3176 
Loop time of 3.82837 on 1 procs for 1000 steps with 192 atoms
detail: run it on GPU, without command 'export DP_VARIANT=cuda' before compile deepmd-kit

platform: Lebesgue base image

**Steps to Reproduce**

In example/water/se_e2_a open input.json ,and specify the activation function of descriptor is gelu, then run 'dp train input.json' on GPU. After freeze the model.pb, copy it in ../lmp and modify in.lammps, then run 'mpirun -n 1 lmp -i in.lammps'.
**Further Information, Files, and Links**

**Comment by njzjz** [comment]
The function in `gelu.cc` is the approximate version, so if you want to see if they are the same, you need to use `lambda x: tf.nn.gelu(x, approximate=True)` instead of `tf.nn.gelu`.

**Comment by amcadmus** [comment]
Can you reproduce the bug on CPU?

**Comment by njzjz** [comment]
If there is no `DP_VARIANT=cuda`, gelu will only run on CPUs.

**Comment by denghuilu** [comment]
I have tested the gelu activation function in local gpu workstation and it works well.

**Comment by njzjz** [comment]
I cannot reproduce it as well, and also, the velocity is not directly provided by the model. Do you change the constant of fix nvt?

**Comment by liangadam** [comment]
Sorry，I find it works well now. Maybe it's caused by some wrong code I have added in that time. Now everything is OK and the issue can bu closed.
