### ISSUE TITLE
[BUG] problems with fitting Dipole/Polarizability

### ISSUE THREAD

**Issue by singlebook** [deepmodeling/deepmd-kit#989]
Q1   It is said in the tutorial that the "type" of loss for fitting Dipole/Polarizability should be "tensor", like this:

```
"loss" : {
  "type": "tensor",
  "pref": 1.0,
  "pref_atomic": 1.0,
  "_comment": "that's all"
},
```
But DeePMD-kit-1.3.1 always reported "KeyError: 'tensor' ". Everything is fine after I delete "type": "tensor" in the loss section.

Q2  It seems that raw_to_set.sh does not have any command to convert atomic_dipole.raw to dipole.npy.

**Comment by amcadmus** [comment]
Please use v2.0
